### ISSUE TITLE
Quarkus Swagger UI behind an Ingress Controller

### ISSUE THREAD

**Issue by sirAlexander** [quarkusio/quarkus#10112]
I'm having a similar Issue as described here. @gsmet as you are tagged in that post, has this been fixed yet? if not any ETA, thanks.

https://gitmemory.com/issue/quarkusio/quarkus/4200/535037694

**Comment by phillip-kruger** [comment]
Hi @sirAlexander - please explain the issue. Do you not get to the swagger ui page at all ? Or do you get there but it's not rendering properly ? Or do you get there, and it's rendering but the REST calls are not working ?

Thanks

**Comment by sirAlexander** [comment]
@phillip-kruger I do not get the swagger-ui page at all

**Comment by phillip-kruger** [comment]
Ok, that is somewhere in the swagger UI extension then. I'll have a look as soon as I get a chance. You are also welcome to see if you can pin point the issue there (and even better, do a PR with the fix ;))

**Comment by phillip-kruger** [comment]
@sirAlexander can you please share your application.properties?

**Comment by sirAlexander** [comment]
the only swagger related stuff I have in the properties is:
`# Swagger properties
quarkus.swagger-ui.always-include=true
`
Then as described in the original issue above (https://gitmemory.com/issue/quarkusio/quarkus/4200/535037694) 
...part of my ingress config has something similar to

`
"path": "/test-service(/|$)(.*)"
`

**Comment by sirAlexanderT** [comment]
@phillip-kruger looked at this again and I can get to the swagger-ui ok, but the REST calls aren't working

**Comment by phillip-kruger** [comment]
That changes things. So For OpenAPI to create a valid schema doc, would need to know all the valid servers that will be used. Do you have a `@Server` annotation that contains the proxy server ? Or you can use MP Config (see https://download.eclipse.org/microprofile/microprofile-open-api-1.0/microprofile-openapi-spec.html#_core_configurations) to add these servers.

Let me know. Thanks :)

**Comment by phillip-kruger** [comment]
Hi @sirAlexanderT - Any comment ? Is the `@server` working for you ?

**Comment by sirAlexander** [comment]
@phillip-kruger I fixed the issue by getting rid of the ingress re-write rule for now and setting 'quarkust.http.root-path=/test-service'

**Comment by phillip-kruger** [comment]
Ok. Still not sure if we can close this though. Seems like you bypassed the problem ? 

Are you setting the @server annotation at all ?

**Comment by thebe14** [comment]
This is not working. Bypassing the problem is not an option for me. The only option for me is to drop the Swagger-UI in production, as I cannot get my public URL http://hostname/api/query that gets rewritten to http://container/query by an ingress controller/Nginx reverse proxy to work at all. I can hack it to get the Swagger-UI to show, but trying out requests does not work.

**Comment by phillip-kruger** [comment]
W.r.t Swagger UI, depending on your case you might have to:

- Set the swagger endpoint with [quarkus.swagger-ui.path](https://quarkus.io/guides/openapi-swaggerui#quarkus-swaggerui_quarkus.swagger-ui.path)
- Set the endpoint for your operations with [quarkus.smallrye-openapi.servers](https://quarkus.io/guides/openapi-swaggerui#quarkus-smallrye-openapi_quarkus.smallrye-openapi.servers)
- If the above are on two different host, configure [CORS](https://quarkus.io/guides/openapi-swaggerui#cross-origin-resource-sharing) to allow swagger ui to call out to openapi operations

**Comment by thebe14** [comment]
No cigar. In my Quarkus project (the API) I have these settings:

``` yaml
quarkus:
  swagger-ui:
    always-include: true
    path: /swagger-ui
    urls:
      default: /api/slm/openapi
      local: /openapi
    urls-primary-name: default
  smallrye-openapi:
    path: /openapi
```

Then on deployment, I set this environment variable in the container that runs the API:

```
MP_OPENAPI_SERVERS=https://${SERVICE_DOMAIN}/api/slm
```

This fixes 2 of the 3 problems:
- The Swagger-UI page gets populated OK, by selecting "default" or "local" from the top-right dropdown, which is defaulting to the correct value when deployed in the wild - I can live with the minor inconvenience when testing to switch to the local path for loading the OpenAPI spec
- Execution from the Swagger-UI page works (thanks to the server specification)
- But the Swagger-UI page does not load, when requesting `https://<domain>/api/slm` I get redirected to `https://<domain>/swagger-ui`. I thought it was working but the page was coming from the cache. I have a yellow validation error at the bottom of the Swagger-UI coming from the cache, with this message:

``` json
{"schemaValidationMessages":[{"level":"error","message":"Can't read from file https://<domain>/api/slm/openapi"}]}
```

**Comment by thebe14** [comment]
**Update**: 
If I request `https://<domain>/api/slm/swagger-ui/index.html` then the Swagger-UI works fine. 
If I try to navigate to `https://<domain>/api/slm/swagger-ui/` then I get redirected to `https://<domain>/swagger-ui`. So there is still a bug in Swagger-UI.
