### ISSUE TITLE
Hibernate ORM Panache for Testing

### ISSUE THREAD

**Issue by danielpetisme** [quarkusio/quarkus#1367]
When I try to use the Panache operations in Test methods I have an unexpected behavior. So far, I didn't figured out how to fix it.

Reproducers:
I've forked the quarkus-quickstarts and simply invoked the `count()` method`
https://github.com/danielpetisme/quarkus-quickstarts/blob/reproducer/hibernate-orm-panache-resteasy/src/test/java/FruitsEndpointTest.java#L15

The test fails with `javax.enterprise.context.ContextNotActiveException`

Another configuration (with h2 this time)
https://github.com/danielpetisme/jhipster-sample-app-quarkus/tree/reproducer

Again I invoke the `count()` method
https://github.com/danielpetisme/jhipster-sample-app-quarkus/blob/reproducer/src/test/java/io/github/jhipster/sample/web/rest/BankAccountResourceTest.java#L50

Again the test fail
with
```
java.lang.IllegalStateException: This method is normally automatically overridden in subclasses: did you forget to annotated your entity with @Entity?
        at io.github.jhipster.sample.web.rest.BankAccountResourceTest.createBankAccount(BankAccountResourceTest.java:50)
```
The entity is properly annotated
https://github.com/danielpetisme/jhipster-sample-app-quarkus/blob/reproducer/src/main/java/io/github/jhipster/sample/domain/BankAccount.java

I hope the explanations are clear enough. To be frank, at this point I don't know if the 2 behaviors are related...

**Comment by FroMage** [comment]
Fixed. This should work now, but only for tests running on the JVM.

**Comment by danielpetisme** [comment]
Hello,

Sorry to raise up a close ticket...
I test the updated quickstart and indeed it works. But I still have the same error with
https://github.com/danielpetisme/jhipster-sample-app-quarkus
simply launch `./mvnw test`

```
2019-07-31 20:46:11.594 INFO  2947 --- [           main] io.quarkus                    : Quarkus 0.20.0 started in 1.845s. Listening on: http://[::]:8081
2019-07-31 20:46:11.594 INFO  2947 --- [           main] io.quarkus                    : Installed features: [agroal, cdi, hibernate-orm, hibernate-validator, jdbc-h2, mailer, narayana-jta, resteasy, resteasy-jsonb, scheduler, smallrye-metrics, smallrye-openapi, swagger-ui, vertx]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 8.226 s <<< FAILURE! - in io.github.jhipster.sample.web.rest.BankAccountResourceTest
[ERROR] createBankAccount  Time elapsed: 0.028 s  <<< ERROR!
java.lang.IllegalStateException: This method is normally automatically overridden in subclasses: did you forget to annotate your entity with @Entity?
        at io.github.jhipster.sample.web.rest.BankAccountResourceTest.createBankAccount(BankAccountResourceTest.java:56)

2019-07-31 20:46:11.684 INFO  2947 --- [           main] io.quarkus                    : Quarkus stopped in 0.051s
```
and yes the class is annotated
https://github.com/danielpetisme/jhipster-sample-app-quarkus/blob/master/src/main/java/io/github/jhipster/sample/domain/BankAccount.java#L18

How can I help you to troubleshoot?
Do you want me to create another issue or we continue to work on this one?

**Comment by gsmet** [comment]
Hi @danielpetisme 

Yes, please create another issue.

**Comment by danielpetisme** [comment]
Done #3395 3395
