### ISSUE TITLE
Duplicate JAXB artifacts

### ISSUE THREAD

**Issue by Sanne** [quarkusio/quarkus#1394]
When building Quarkus, specifically while wathing module `quarkus-integration-test-main` one can see this warning being logged:

    Duplicate entry javax/xml/bind/util/Messages.properties entry from javax.xml.bind:jaxb-api::jar:2.3.1(provided) will be ignored. Existing file was provided by org.jboss.spec.javax.xml.bind:jboss-jaxb-api_2.3_spec::jar:1.0.1.Final(compile)

So looks like we're bringing in both `javax.xml.bind:jaxb-api` and `org.jboss.spec.javax.xml.bind:jboss-jaxb-api_2.3_spec`.

Incidentally, 2.3.2 was released but the GAV of JAXB changed once again :(
 - https://wiki.eclipse.org/New_Maven_Coordinates

**Comment by Dufgui** [comment]
I take a look at old issue, as I can see it's still the case:
```
[INFO] org.acme:getting-started:jar:1.0-SNAPSHOT
[INFO] +- io.quarkus:quarkus-resteasy:jar:999-SNAPSHOT:compile
[INFO] |  +- io.quarkus:quarkus-undertow:jar:999-SNAPSHOT:compile
[INFO] |  \- io.quarkus:quarkus-resteasy-server-common:jar:999-SNAPSHOT:compile
[INFO] |     +- io.quarkus:quarkus-resteasy-common:jar:999-SNAPSHOT:compile
[INFO] |     |  +- org.jboss.resteasy:resteasy-core:jar:4.2.0.Final:compile
[INFO] |     |  |  +- org.jboss.spec.javax.ws.rs:jboss-jaxrs-api_2.1_spec:jar:1.0.2.Final:compile
[INFO] |     |  |  +- org.jboss.spec.javax.xml.bind:jboss-jaxb-api_2.3_spec:jar:1.0.1.Final:compile
[INFO] |     |  |  +- org.jboss.resteasy:resteasy-core-spi:jar:4.2.0.Final:compile
[INFO] |     |  |  \- org.reactivestreams:reactive-streams:jar:1.0.2:compile
[INFO] |     |  +- org.jboss.resteasy:resteasy-context-propagation:jar:4.2.0.Final:compile
[INFO] |     |  |  \- io.smallrye:smallrye-context-propagation:jar:1.0.7:compile
[INFO] |     |  |     \- io.smallrye:smallrye-context-propagation-api:jar:1.0.7:compile
[INFO] |     |  \- com.sun.activation:jakarta.activation:jar:1.2.1:compile
[INFO] |     +- javax.validation:validation-api:jar:2.0.1.Final:compile
[INFO] |     \- io.quarkus:quarkus-jaxb:jar:999-SNAPSHOT:compile
[INFO] \- io.rest-assured:rest-assured:jar:3.3.0:test
[INFO]    +- io.rest-assured:json-path:jar:3.3.0:test
[INFO]    \- io.rest-assured:xml-path:jar:3.3.0:test
[INFO]       +- org.apache.commons:commons-lang3:jar:3.8.1:test
[INFO]       +- javax.xml.bind:jaxb-api:jar:2.3.1:compile
[INFO]       \- org.apache.sling:org.apache.sling.javax.activation:jar:0.1.0:test
```

Which one do you want to keep . jakarta.xml.bind-api (jaxb-api) or jboss-jaxb-api ?

**Comment by gsmet** [comment]
This has been fixed by the big Jakarta move.

**Comment by Sanne** [comment]
Re-opening: It wasn't fixed, like you just explained to me on the mailing list you decided to not go for the Jakarta artifacts.

We're having:

- javax.xml.bind:jaxb-api - brought by rest-assured
- org.jboss.spec.javax.xml.bind:jboss-jaxb-api_2.3_spec - most Quarkus components - especially Resteasy

The good news is that rest-assured is mostly a test component - but it's expected to be used for testing by end users too so it's not a non-issue.

**Comment by gsmet** [comment]
Well, the only thing we can do here is wait for REST Assured to move to Jakarta.

We can keep it open if you prefer but there's nothing we can do on our side.

**Comment by Sanne** [comment]
https://github.com/rest-assured/rest-assured/pull/1228 ;-)

**Comment by rsvoboda** [comment]
I tried to update rest-assured to 4.2.0 with @Sanne's fix but I receive `Found Banned Dependency: jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.2`

https://github.com/quarkusio/quarkus/blob/master/build-parent/pom.xml#L222

Jakarta APIs still on hold ?

**Comment by gsmet** [comment]
I already merged the upgrade here: https://github.com/quarkusio/quarkus/pull/6704 .

The situation is a bit more complex than that because RESTEasy is using repackaged Jakarta artifacts for JAXB and JAX-RS APIs (the usual JBoss ones). For now, we decided to use that ones to avoid complexity for the users, at least until RESTEasy migrates to vanilla Jakarta artifacts.

**Comment by gastaldi** [comment]
Is this still an issue or can be closed?
