### ISSUE TITLE
MQTT client re-connection issue

### ISSUE THREAD

**Issue by mpcbass** [quarkusio/quarkus#14220]
I'm working on a project involving Mosquitto and Quarkus hosted by two different machines.
Apparently, whenever occurs a connection loss between the two, 
Quarkus is not able to reconnect to the broker.

From what I can understand, a connection loss leads a to two different outcomes depending on what quarkus has been doing
during the network failure.

SCENARIO 1
connection drops just before quarkus tries to send an outgoing message.
To reproduce this scenario:
-1- have mosquitto running on your localhost:1883 or on docker
-2- run https://github.com/mpcbass/quarkus-mqtt-connection-loss.git
-3- after quarkus is up and running emulate a connection loss [turn off the docker image, or block the on the firewall, or similar]
------> it will happen that MqttClient tries to send the message but it just freezes.
-4- restore the broker
------> nothing will happen even if you send explicitly set the _mp.messaging.connector.smallrye-mqtt.reconnect-attempts_
NOTE. restEasy it's still running

SENARIO 2 
connection drops while quarkus is waiting to receive a message.
To reproduce this scenario:
-1- have mosquitto running
-2- comment out the @outgoing example and comment in the @incoming
-3- after quarkus is up and running emulate a connection loss
------>MqttClient freezes and log loops on "Unmanaged exception" [even if you manage something, the problem is to tell the container to try to restore the connections]
-4- restore the broker
------> nothing will happen
NOTE. restEasy it's still running

I'm using Azul 11.0.9
but I have the same behaviour with graal on docker

**Comment by mpcbass** [comment]
A lot of time has been passed since this issue on vert.x
but it's still seems relevant

https://github.com/vert-x3/vertx-mqtt/issues/66

**Comment by masini** [comment]
In my opinion the MqttSink wait passively for a reconnection (MqttSink.java:54)

```
                            vertx.setPeriodic(100, id -> {
                                if (client.isConnected()) {
                                    vertx.cancelTimer(id);
                                    connected.set(true);
                                    future.complete(msg);
                                }
                            });

```
but the Vertx's MqttClientImpl is unable to reconnect. the cause is the yet cited bug #66, but I would like to understand from the SmallRye team if I can do something to workaround this behaviour until is fixed from Vert.x teams.

**Comment by masini** [comment]
I would like to add that from the discussion in:

https://github.com/vert-x3/vertx-mqtt/issues/66

is clear that NetClient only reconnect if a TCP error occurs.

If for some reason the MQTT broker fail and restart, nothing is done and the MQTTClient is unable to understand the difference.

Also the SmallRye documentation is not good at explaining that "reconnect-attempts" --> "Set the max reconnect attempts" is only related to the TCP protocol and not to the MQTT Broker.

I think we need a way to workaround this, may be a callback or something inside the MqttSink that create a new MqttClient.

**Comment by mpcbass** [comment]
Thanks for the analysis

Please tell me if I can help in some way. 
I'm more than happy to do.

I honestly tried but I don't know the project that well to be sure I'm tweaking the right part.

**Comment by Davide-Di-Do** [comment]
Hi @mpcbass I've created a pull request to your repo where there is a possibile solution of auto-reconnect

**Comment by mpcbass** [comment]
Hi Davide 
I'm very thankful for your try, I see what you tried to achieve.
I'd already came up with something similar, but that's not a viable way for me.

It seems people around use this kind of software just in cloud environments,
so that they are able to healthcheck and eventually restart the docker image.
That's maybe why nobody is annoyed by this issue.

Unfortunally I have to install my piece of software on the bare metal so the eventual healthchecks
are quite annoying to code on the shell.

It's way better to find something to fix into smallrye or vert.x directly.
I hope I will be able to find a solution sooner possible.

**Comment by CurtisBaldwinson** [comment]
+1 to this issue. @mpcbass in our project we decided to remove the smallrye library entirely because the connection can't be relied on. However we've had success with the Quarkus camel paho extension. We were able to get it to reconnect after disconnects and you may have similar success because it actually respects the reconnection parameters specified.

For anyone interested in the reasoning: even on cloud servers, the MQTT connection at least briefly wavers time to time. I can reliably startup a Quarkus app and confirm the connection is gone by the next day and see the same result every day. This makes the Smallrye MQTT connector unable to be considered for anything other than short term processing. I wish I had any idea how to contribute a fix or even where to start looking at solving this :(

**Comment by masini** [comment]
Hi @CurtisBaldwinson I have a PR with automatic reconnection:

https://github.com/smallrye/smallrye-reactive-messaging/pull/1081#issuecomment-792743422

**Comment by cescoffier** [comment]
The next version of the MQTT connector supports reconnect. It should be released tomorrow.

CC @ctron

**Comment by gsmet** [comment]
My understanding is that this should be fixed given we upgraded to a new version of the connector.

**Comment by amoscatelli** [comment]
Just to clarify this, this is fixed by adding this extension : 

https://github.com/quarkiverse/quarkus-hivemq-client

This will make ReactiveMessaging MQTT use the HiveMQ MQTT Client instead of the Vert.x one.
Without this I am still reproducing the issue.

**Comment by nirue** [comment]
> 2025-07-03 11:34:09,301 INFO  [io.sma.rea.mes.mqt.ses.imp.MqttClientSessionImpl] (vert.x-eventloop-thread-0) Connection closed: <unknown>                                                                    
2025-07-03 11:34:10,320 INFO  [io.ver.mqt.imp.MqttClientImpl] (vert.x-eventloop-thread-0) Connection with x.x.x.x:1883 established successfully 

I am still getting a lot of disconnects with Quarkus 3.24.2. The only solution is the hint above and replace ReactiveMessaging MQTT with the HiveMQ MQTT Client.
