### ISSUE TITLE
Quarkus 1.11 incompatibility with the upcoming GraalVM CE 20.3.3

### ISSUE THREAD

**Issue by zakkak** [quarkusio/quarkus#18722]
### Describe the bug

The upcoming GraalVM CE 20.3.3 release is going to return a different version string for `--version`.

The new string will look like this:
```
GraalVM 20.3.3-dev Java 11 (Java Version 11.0.11+8-jvmci-21.2-b01)
```

while it used to be:
```
GraalVM Version 20.3.2 (Java Version 11.0.11+8-jvmci-20.3-b15)
```

as a result the following pattern matching will fail
https://github.com/quarkusio/quarkus/blob/632e940a2535aa31f7c18221c8aa511d0950aa49/core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java#L758-L759

resulting in the following error being printed:
```
Error:  [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Unable to get GraalVM version from the native-image binary.
```
Note that despite the error the image build will not fail and a native executable will be generated since we don't exit the image building phase in that case
https://github.com/quarkusio/quarkus/blob/632e940a2535aa31f7c18221c8aa511d0950aa49/core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java#L116-L120

(we should probably make this a warning, or force a failure)

### GraalVM version

20.3.3-dev

### Quarkus version or git rev

1.11.7.Final

**Comment by zakkak** [comment]
To avoid this issue Mandrel 20.3.3 is going to use the same version string as it did in 20.3.2 (see https://github.com/graalvm/mandrel/pull/269).

**Comment by gsmet** [comment]
So should we do something about this? I'm leaning towards closing this one as I don't think we have a lot of community users still on 1.11.

**Comment by zakkak** [comment]
It might be worth changing `1.11` branch to use the mandrel builder-image instead of graalvm.

Other than that +1 on doing nothing about it

**Comment by jerboaa** [comment]
> Other than that +1 on doing nothing about it

+1

**Comment by geoand** [comment]
I assume this has been fixed now, right?

**Comment by zakkak** [comment]
> I assume this has been fixed now, right?

No, this is not fixed, using Quarkus 1.11 without specifying the mandrel image as the builder image will result in the error message mentioned in the description of this issue.

This is only worth fixing (by making Quarkus use the mandrel image by default) if we are planning to do a Q 1.11.x release in the future, otherwise I think we should mark it as "won't fix" and close it.

**Comment by geoand** [comment]
Let's close it for now, we can always reopen if need be
