### ISSUE TITLE
Quarkus Native Executable build (using Docker) fails

### ISSUE THREAD

**Issue by amitkumar7566** [quarkusio/quarkus#19916]
### Describe the bug

I am trying to build a Quarkus native executable using docker using the following command "mvn clean package "-Pnative" "-Dquarkus.native.container-build=true" "-Dquarkus.native.container-runtime=docker"

Quarkus version: 2.2.1.Final Maven version : 3.8.1 Java version: 11

and I get the below error:

Error: Annotated class must be final: class io.quarkus.amazon.lambda.http.graal.LambdaContainerHandlerSubstitution
com.oracle.svm.core.util.UserError$UserException: Annotated class must be final: class io.quarkus.amazon.lambda.http.graal.LambdaContainerHandlerSubstitution
        at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
        at com.oracle.svm.core.util.UserError.guarantee(UserError.java:96)
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:280)
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:266)
        at com.oracle.svm.hosted.NativeImageGenerator.createDeclarativeSubstitutionProcessor(NativeImageGenerator.java:936)
        at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:868)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:530)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:491)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:380)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:543)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:573)

### Output of `java -version`

java 11.0.8 2020-07-14 LTS

### GraalVM version (if different from Java)

GraalVM 21.2

### Quarkus version or git rev

2.2.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.1

**Comment by gsmet** [comment]
Fixed in https://github.com/quarkusio/quarkus/pull/19887 . Will be backported to 2.2.2.Final.

**Comment by amitkumar7566** [comment]
@gsmet 

It's not resolved, got back to another error which was coming earlier.

Please refer to issue #20009
