### ISSUE TITLE
Create a main entry point for *ide* runs

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#2143]
I was chatting with someone that had the following arguments:

* some people have a hard time to do mvn calls from their IDE e.g. `mvn compile quarkus:dev`
* and it makes it hard to then attach the debugger
* and he likes that SB and Micronaut do generate a main method in the like of this

```
public class Application {
    public static int main(String[] args) {
        Quarkus.startDev(Application.class);
    }
}
```

I don't know how true the assumptions are and wether we could have the main in our starters?
And even whether this kind of thing is possible with our approach

**Comment by geoand** [comment]
As per the assumption about people finding using maven and/or remote debugger hard:

I have seen this myself a lot in coworkers. Plenty of people I have worked with actively hated interacting with the build tool and preferred to do as much as possible from the IDE.

**Comment by emmanuelbernard** [comment]
Another potential usage is CLI where users would prefer to own `main()`

**Comment by Sanne** [comment]
+1 to have users own their main.

We discussed this use case in a design session for shutdown, and it's listed as one of the goals.

We plan to wrap it the other way around though: the user defines his "main()", Quarkus generates its own main so to invoke the user's one and be able to cleanup its own resources in a generated finally block which wraps it.

Needs a volunteer to be implemented though...

**Comment by thiagolocatelli** [comment]
+1 for this. Quarkus could make available a class similar to io.quarkus.runner.GeneratedMain for development/debugging purposes. I am not sure what exactly goes inside this GeneratedMain, but it could be a simplified version or something like that, just to give developers a chance to run and debug within an IDE.

**Comment by JChrist** [comment]
I tried to have a go at this, as I consider this extremely important for day-to-day use.
I've stumbled a bit on how the dev run lifecycle goes, because (as I understood) the logic is split between the DevMojo and the DevModeMain. 
My current line of thinking (which I'm not yet sure is the best way to do it) is that this could be handled by replicating the logic of dependency/classpath matching from the DevMojo to the DevModeMain. Then a user could include the quarkus-development-mode artifact in their dependencies (possibly in test scope) and generate their own main, which would be required to simply delegate to DevModeMain.
I would appreciate your thoughts on this approach

**Comment by rverma-nikiai** [comment]
This is similar to what spring-boot does, with spring-devtools. This proved to be good for spring, I think we don't need to reinvent the wheel here :). If someone needs a hot reload they can use this else can skip this. I am more inclined towards frameworks which can sync code changes directly inside a kubernetes pod with minimal layer rebuilds. Bonus if it can work with google's jlib (https://github.com/GoogleContainerTools/jib), both spring boot and Micronaut supports it completely.

**Comment by geoand** [comment]
Quarkus' remote-dev can be used in Kubernetes pods and it's much much more efficient that anything else I have seen.

**Comment by JChrist** [comment]
For anyone interested, one _hacky_ way for easy debugging inside the IDE is a custom test class under test sources named `TestMain` so that it doesn't match surefire/failsafe patters, which uses `@QuarkusTest` and simply sleeps:

```Java
@QuarkusTest
public class TestMain {
    @Test
    public void startApp() throws Exception {
        while (true) {
            TimeUnit.SECONDS.sleep(1);
        }
    }
}
```

This uses the test http port (8081 by default) as described in the documentation, so either use it under port 8081, or add `quarkus.http.test-port=8080` in `application.properties`

**Comment by cricket007** [comment]
What's wrong with having IDE plugins expose the run/debug hooks via buttons & keymappings?

**Comment by michael-schnell** [comment]
I guess this is solved now and can be closed, as there is now a possibility to create a "main" method:
https://quarkus.io/guides/lifecycle

**Comment by mageddo** [comment]
> I guess this is solved now and can be closed, as there is now a possibility to create a "main" method:
> https://quarkus.io/guides/lifecycle

Still doesn't works for me, [see an example](https://github.com/mageddo/java-examples/tree/f005b74/quarkus/quarkus-manual-main-lifecycle). Tested on Intellij 2019.3

Looks like it's related to Intellij's [output path](https://github.com/quarkusio/quarkus/issues/8737)


```
Exception in thread "main" java.lang.RuntimeException: io.quarkus.bootstrap.BootstrapException: Failed to determine the Maven artifact associated with the application
	at io.quarkus.launcher.QuarkusLauncher.launch(QuarkusLauncher.java:46)
	at io.quarkus.runtime.Quarkus.launchFromIDE(Quarkus.java:93)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:79)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
	at com.mageddo.resource.Main.main(Main.java:14)
Caused by: io.quarkus.bootstrap.BootstrapException: Failed to determine the Maven artifact associated with the application
	at io.quarkus.bootstrap.BootstrapAppModelFactory.resolveAppModel(BootstrapAppModelFactory.java:241)
	at io.quarkus.bootstrap.app.QuarkusBootstrap.bootstrap(QuarkusBootstrap.java:140)
	at io.quarkus.launcher.QuarkusLauncher.launch(QuarkusLauncher.java:41)
	... 4 more
Disconnected from the target VM, address: '127.0.0.1:60377', transport: 'socket'

Process finished with exit code 1

````

**Comment by michael-schnell** [comment]
Weird... I'm using Eclipse, there it works fine.

**Comment by ivan-sirosh** [comment]
have the same error on gradle build

```
Exception in thread "main" java.lang.RuntimeException: io.quarkus.bootstrap.BootstrapException: Failed to determine the Maven artifact associated with the application
	at io.quarkus.launcher.QuarkusLauncher.launch(QuarkusLauncher.java:46)
	at io.quarkus.runtime.Quarkus.launchFromIDE(Quarkus.java:93)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:79)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
	at com.wtools.Runner.main(Runner.java:12)
Caused by: io.quarkus.bootstrap.BootstrapException: Failed to determine the Maven artifact associated with the application
	at io.quarkus.bootstrap.BootstrapAppModelFactory.resolveAppModel(BootstrapAppModelFactory.java:241)
	at io.quarkus.bootstrap.app.QuarkusBootstrap.bootstrap(QuarkusBootstrap.java:140)
	at io.quarkus.launcher.QuarkusLauncher.launch(QuarkusLauncher.java:41)
	... 4 more
```

**Comment by ymolists** [comment]
I am having the same issue as well with intellij and gradle.

**Comment by dansiviter** [comment]
This seems to still be an issue.

* IDE: VS Code 1.50.1
* JDK: AdoptOpenJDK 14.0.1.7-hotspot
* Quarkus: 1.9.0.Final
* Dependencies: `io.quarkus:quarkus-resteasy`
* Main class:

```java
@QuarkusMain
public class Main {
  public static void main(String... args) {
    Quarkus.run(args);
  }
}
```
* Stacktrace:
```
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at io.quarkus.launcher.QuarkusLauncher.launch(QuarkusLauncher.java:57)
        at io.quarkus.runtime.Quarkus.launchFromIDE(Quarkus.java:92)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:79)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:104)
        at uk.dansiviter.microservices.Main.main(Main.java:10)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at io.quarkus.launcher.QuarkusLauncher.launch(QuarkusLauncher.java:54)
        ... 5 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.ClassNotFoundException: io.quarkus.deployment.dev.IDEDevModeMain
        at io.quarkus.bootstrap.IDELauncherImpl.launch(IDELauncherImpl.java:60)
        ... 10 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: io.quarkus.deployment.dev.IDEDevModeMain
        at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:132)
        at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:82)
        at io.quarkus.bootstrap.IDELauncherImpl.launch(IDELauncherImpl.java:58)
        ... 10 more
Caused by: java.lang.ClassNotFoundException: io.quarkus.deployment.dev.IDEDevModeMain
        at io.quarkus.launcher.RuntimeLaunchClassLoader.findClass(RuntimeLaunchClassLoader.java:25)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:412)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:365)
        at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:127)
        ... 12 more
```
* Notes: Add `io.quarkus:quarkus-core-deployment` as a dependency (at `provided` scope so it's not needlessly bundled). Gets a little further but no features are being found.

**Comment by stuartwdouglas** [comment]
This has been implemented
