### ISSUE TITLE
Hibernate and Panache entities not enhanced in external jars

### ISSUE THREAD

**Issue by noseka1** [quarkusio/quarkus#2196]
I have two Maven projects: _Photo_ and _Monolith_. Note that these are two separate Maven projects as opposed to being two modules in a multi-module Maven project.

_Photo_ project defines an entity class _PhotoItem_:

```
@Entity
public class PhotoItem extends PanacheEntity {
  ...
} 
```
_Photo_ project builds a _photo.jar_ that includes the compiled _PhotoItem.class_.

Project _Monolith_ depends on project _Photo_. It pulls the _photo.jar_ as a dependency and tries to call:

```
PhotoItem.findById(...)
```

Unfortunately, this call invokes the _PanacheEntityBase.findById()_ default implementation that just throws an exception: `IllegalStateException("This method is normally automatically overridden in subclasses: did you forget to annotate your entity with @Entity?")`

After decompiling the _PhotoItem.class_ from the _photo.jar_ I verified that the implementation of `findById()` is indeed missing and hence the inherited default implementation is called. The `findById()` generated method is included in the _photo-runner.jar_ though. How should I make Quarkus generate that method and include it in the _photo.jar_ as well?

Thanks a lot for your help. Let me know if you have any questions.

**Comment by gsmet** [comment]
@noseka1 could you try to add this to your `photo` project:
```
<plugin>
    <groupId>org.jboss.jandex</groupId>
    <artifactId>jandex-maven-plugin</artifactId>
    <version>1.0.3</version>
    <executions>
        <execution>
            <id>make-index</id>
            <goals>
                <goal>jandex</goal>
            </goals>
        </execution>
    </executions>
    <dependencies>
        <dependency>
            <groupId>org.jboss</groupId>
            <artifactId>jandex</artifactId>
            <version>2.1.1.Final</version>
        </dependency>
    </dependencies>
</plugin>
```
That should build a Jandex index, which will allow for the classes to be found when Panache tries to instrument them.

**Comment by noseka1** [comment]
@gsmet Thanks for the suggestion. I added the plugin definition into the `photo` project _pom.xml_. I double-checked that the _PhotoItem_ class gets added into the _jandex.idx_.

I started my _Monolith_ project using:
```
mvn clean compile quarkus:dev -Ddebug
```
And stepped through it with a debugger. I think the problem is that _io/quarkus/runner/RuntimeClassLoader.java:168_ says:
```
Path classLoc = applicationClasses.resolve(fileName);
```
This path resolution fails for my _PhotoItem_ class because it is not located in the _target/classes_ directory of the _Monolith_ project but is pulled as a dependency in the _photo.jar_. It seems that at the moment Quarkus class transformation is only executed on the classes in the current project while classes pulled in through Maven dependencies are excluded from the transformation proccess.

**Comment by FroMage** [comment]
So, this is a classloader issue, because if I run the test from Maven it works (with the fix @gsmet indicated of adding the index), but if I run it from the IDE it does not. Actually something really weird happens is that in both cases if I print all the class methods they exist, but when I call them they fail, so in the IDE we really have two versions of the imported entity class visible.

**Comment by FroMage** [comment]
With a bit more testing I can validate that it works from tests and `quarkus:dev` if I have the index. It probably failed before because the index got removed.

But the trick is that it does not work with the runner jar since the imported entity is kept inside its jar unenhanced, referenced by the `META-INF/MANIFEST.MF`. I guess we could fix this either by producing enhanced jars from the start (even when we're not assembling an app, so from a non-assembly maven plugin) or do like for `PanacheEntity` and duplicate it in the main app jar. I wonder why this one is special, though.

**Comment by FroMage** [comment]
I have been able to change the way we build the jar so that we would generate augmented versions of imported entities, as well as `PanacheEntity`, and now it works also in the `java -jar xxx-runner.jar` case, because the main jar contains the enhanced entities.

But it does not work for `native-image` because apparently it will use the classes from the jars listed in the manifest over the main jar classes :(

**Comment by FroMage** [comment]
Perhaps an alternative is to enhance the contents of the produced `lib/xxx.jar` from which the entities originated, rather than add them to the main jar.

**Comment by FroMage** [comment]
https://github.com/stuartwdouglas/quarkus/tree/augmentation-of-archives fixes this. Remains to update the Hibernate and Panache docs to mention that external entities should have the jandex build plugin in order to work. I'll do that.

**Comment by FroMage** [comment]
Docs are at https://github.com/quarkusio/quarkus/pull/2636

**Comment by FroMage** [comment]
@stuartwdouglas can we get a PR for your fix?

**Comment by FroMage** [comment]
This was fixed on master with 705727e784c15d76be90d30de098e38666540c66

**Comment by soberich** [comment]
@FroMage sorry for pinging you specifically. It's just that you more active. This one is still not working for me. I believe it should work from master now? In a meanwhile I have put my playground on Github to reference in several issues with Quarkus. Maybe you can look at it.

**Comment by FroMage** [comment]
OK I'll take a look.

**Comment by soberich** [comment]
@FroMage Just to notice - I have NOT tried from current master! I reread my message which could be confusing and saw you reopened. I meant as a question - should it work from current master?

**Comment by FroMage** [comment]
Oh, yeah, please try from the current master it should totally work.

**Comment by soberich** [comment]
@FroMage I checked in current `999-SNAPSHOT` from `OSS-snapshot` which is from 2019-06-12 I think and in didn't work either.
The `runtime-jakarta` module in the one which manages quarkus runtime. `build.gradle.kts` is quite messy, sorry, but it should be working aas you said. 
Additionally, when tried to annotate service with `@Transactional` and it throwed

```log
Caused by: java.lang.NoSuchMethodError: io.quarkus.arc.ArcContainer.isCurrentRequestAsync()Z
 at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.handleIfAsyncStarted(TransactionalInterceptorBase.java:114)
 at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:105)
 at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:48)
 at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:62)
 at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:42)
 at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
 at io.quarkus.arc.InvocationContextImpl$InterceptorInvocation.invoke(InvocationContextImpl.java:270)
 at io.quarkus.arc.InvocationContextImpl.invokeNext(InvocationContextImpl.java:149)
 at io.quarkus.arc.InvocationContextImpl.proceed(InvocationContextImpl.java:173)
 at com.example.marvel.web.rest.jakarta.EmployeeBlockingServiceNamespaceImpl_Subclass.listEmployees(Unknown Source)
 at com.example.marvel.web.rest.jakarta.EmployeeBlockingServiceNamespaceImpl_ClientProxy.listEmployees(Unknown Source)
 at com.example.marvel.web.rest.jakarta.EmployeeOrchestrationResource.getEmployees(EmployeeOrchestrationResource.kt:60)
 at com.example.marvel.web.rest.jakarta.EmployeeOrchestrationResource_ClientProxy.getEmployees(Unknown Source)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:498)
 at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:151)
 ... 71 more
 on Quarkus 999-SNAPSHOT by 2019-06-12
```

But the main thing is this issue with external jar. Transactions I can report later. Also, as additional input - I use `persistence.xml`  - it may be relevant (hibernate executes schema creation fine, so `persistence.xml` works in general).
if you execute `./gradlew runtime-jakarta:quarkusDev` and then hit endpoint with `GET` at `http://localhost:8080/api/employee ` you'll see the exception
`"This method is normally automatically overridden in subclasses: did you forget to annotate your entity with @Entity?"`

**Comment by FroMage** [comment]
This exceptions shows you're running some code which was from my PR but never made it to master. You must have some confused artifact resolution on your machine, can you check? Note that You can try with the latest RC, it should also have the fix.

**Comment by gsmet** [comment]
I'm closing this one for 0.17.0 as the initial issue has been solved and we need an entry in the release notes.

Please open a new issue if encounter something else.
