### ISSUE TITLE
[CI] - Quarkus Super Heroes + Quarkus main

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus#23425]
This issue will be open and closed dependent on the state of https://github.com/quarkusio/quarkus-super-heroes building against Quarkus main snapshot.

If you have interest in being notified of this subscribe to the issue.

**Comment by gsmet** [comment]
I adjusted the name for consistency. I will add it to status.quarkus.io once we validate it works.

**Comment by edeandrea** [comment]
Thanks! I only followed the naming convention that the template generated for me. I'm working on the rest of the setup right now.

**Comment by gsmet** [comment]
Ah, thanks for the info. I fixed the template.

**Comment by edeandrea** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/quarkusio/quarkus-super-heroes/actions/runs/1804675279

**Comment by geoand** [comment]
We at least need https://github.com/quarkusio/quarkus-super-heroes/pull/23 to the build passing

**Comment by edeandrea** [comment]
> We at least need [quarkusio/quarkus-super-heroes#23](https://github.com/quarkusio/quarkus-super-heroes/pull/23) to the build passing

quarkusio/quarkus-super-heroes#23 was merged today.

**Comment by edeandrea** [comment]
Build fixed:
* Link to latest CI run: https://github.com/quarkusio/quarkus-super-heroes/actions/runs/1810466311

**Comment by edeandrea** [comment]
@gsmet how do we get this to show up on https://status.quarkus.io ?

**Comment by edeandrea** [comment]
Unfortunately, the build failed:
* Link to latest CI run: https://github.com/quarkusio/quarkus-super-heroes/actions/runs/1827712172

**Comment by edeandrea** [comment]
Closing this in favor of #23612
