### ISSUE TITLE
Hibernate Reactive Panache MSSQL Native Build

### ISSUE THREAD

**Issue by sxs737** [quarkusio/quarkus#23739]
### Describe the bug

After Calling listAll()  on a table few times with 1000 rows I am getting below error on AKS
```
ERROR [org.hib.rea.errors] (vert.x-eventloop-thread-0) HR000057: Failed to execute statement [$1]: $2could not execute query: java.util.concurrent.CompletionException: io.vertx.core.impl.NoStackTraceThrowable: Timeout
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:632)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
        at io.vertx.core.Future.lambda$toCompletionStage$2(Future.java:362)
        at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:153)
        at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75)
        at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230)
        at io.vertx.core.impl.future.Mapping.onFailure(Mapping.java:45)
        at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75)
        at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230)
        at io.vertx.core.impl.future.PromiseImpl.tryFail(PromiseImpl.java:23)
        at io.vertx.core.impl.future.PromiseImpl.onFailure(PromiseImpl.java:54)
        at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:43)
        at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:23)
        at io.vertx.sqlclient.impl.pool.SqlConnectionPool$1PoolRequest.lambda$null$0(SqlConnectionPool.java:202)
        at io.vertx.core.net.impl.pool.SimpleConnectionPool$Cancel.run(SimpleConnectionPool.java:671)
        at io.vertx.core.net.impl.pool.CombinerExecutor.submit(CombinerExecutor.java:50)
        at io.vertx.core.net.impl.pool.SimpleConnectionPool.execute(SimpleConnectionPool.java:240)
        at io.vertx.core.net.impl.pool.SimpleConnectionPool.cancel(SimpleConnectionPool.java:633)
        at io.vertx.sqlclient.impl.pool.SqlConnectionPool$1PoolRequest.lambda$onEnqueue$1(SqlConnectionPool.java:199)
        at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:893)
        at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:860)
        at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:50)
        at io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:168)
        at io.vertx.core.impl.AbstractContext.emit(AbstractContext.java:53)
        at io.vertx.core.impl.VertxImpl$InternalTimerHandler.run(VertxImpl.java:883)
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:829)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:596)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: io.vertx.core.impl.NoStackTraceThrowable: Timeout
```

### Expected behavior

In the JVM Mode it works fine in local even though it takes more time to execute the query

### Output of `java -version`

11.4

### GraalVM version (if different from Java)

ubi-quarkus-native-s2i:21.3.0-java11

### Quarkus version or git rev

2.7.1.Final

**Comment by DavideD** [comment]
This error usually happens when there is a call to something that's not reactive or Quarkus doesn't recognize as reactive. Could you show us the code that's causing this issue (and the signature of the method from which is called), please?

**Comment by sxs737** [comment]
it is giving above error for getSearchInfo() Method for employee entity
I do see another method in it which still needs to be converted to Reactive getSearchComboBoxData() which has @Blocking on it in Resource Class but its not called right now . Any suggestion on converting it to reactive I have a  [stackoverflow Question open for that ](https://stackoverflow.com/questions/71055586/how-to-filter-and-collect-on-uni-quarkus-panache-reactive) 

Also error occurs only in Native Build Docker Image in Kubernetes and does not give any error in local quarkus:dev mode

Thank you very much for all your help !! 

```
package com.infoDirectory.entity;

import java.time.Duration;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.stream.Collectors;

import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.infoDirectory.model.ComboboxRequest;
import com.infoDirectory.model.InfoDirectoryComboboxLists;
import com.infoDirectory.model.SearchRequest;

import io.quarkus.hibernate.reactive.panache.PanacheEntityBase;
import io.quarkus.hibernate.reactive.panache.PanacheQuery;
import io.quarkus.logging.Log;
import io.smallrye.mutiny.Uni;

@Entity
@Table(name = "EMPLOYEE")
public class employee extends PanacheEntityBase {

	@Id
	@Column(name = "EMPLOYEE_NUMBER")
	public String employeeNumber;

	@Column(name = "FIRSTNAME")
	public String firstName;

	@Column(name = "LASTNAME")
	public String lastName;

	@Column(name = "LOCATION")
	public String location;


	@Column(name = "JOB_TITLE")
	public String jobTitle;

	@Column(name = "ADDRESS_LINE_1")
	public String addressLine1;

	@Column(name = "ADDRESS_LINE_2")
	public String addressLine2;

	@Column(name = "TOWN_OR_CITY")
	public String townCity;

	@Column(name = "STATE")
	public String state;

	@Column(name = "POSTAL_CODE")
	public String postalCode;
	
	@Column(name = "COUNTRY")
	public String country;


	public static Uni<InfoDirectoryComboboxLists> getSearchComboBoxData(ComboboxRequest comboboxRequest) {
		Map<String, Object> parameters = new HashMap<String, Object>();
		addIfNotNull(parameters, "location", comboboxRequest.getLocation());
		addIfNotNull(parameters, "jobTitle", comboboxRequest.getJobTitle());
		addIfNotNull(parameters, "townCity", comboboxRequest.getTownCity());
		addIfNotNull(parameters, "state", comboboxRequest.getState());
		

		String str = parameters.entrySet().stream()
				.map(entry -> entry.getKey() + "=:" + entry.getKey())
				.collect(Collectors.joining(" and "));

		PanacheQuery<employee> query = find(str.toString(), parameters);

		List<employee> response = query.list().await().atMost(Duration.ofSeconds(60));

		InfoDirectoryComboboxLists infoDirectoryComboboxLists = new InfoDirectoryComboboxLists();

		infoDirectoryComboboxLists.setJobTitleList(
				(response.stream().collect(Collectors.mapping(employee::getJobTitle, Collectors.toList())))
						.stream().filter(Objects::nonNull).distinct().sorted().collect(Collectors.toList()));
		
		infoDirectoryComboboxLists.setTownList(
				(response.stream().collect(Collectors.mapping(employee::getTownCity, Collectors.toList())))
						.stream().filter(Objects::nonNull).distinct().sorted().collect(Collectors.toList()));
						
		infoDirectoryComboboxLists.setCountryList(
				(response.stream().collect(Collectors.mapping(employee::getCountry, Collectors.toList())))
						.stream().filter(Objects::nonNull).distinct().sorted().collect(Collectors.toList()));
						
		infoDirectoryComboboxLists.setStateList(
				(response.stream().collect(Collectors.mapping(employee::getState, Collectors.toList())))
						.stream().filter(Objects::nonNull).distinct().sorted().collect(Collectors.toList()));

		return Uni.createFrom().item(infoDirectoryComboboxLists);
	}

	public static Uni<List<employee>> getSearchInfo(SearchRequest searchRequest) {
		Map<String, Object> parameters = new HashMap<String, Object>();
		addIfNotNull(parameters, "firstName", searchRequest.getFirstName());
		addIfNotNull(parameters, "lastName", searchRequest.getLastName());
		addIfNotNull(parameters, "location", searchRequest.getLocation());
		addIfNotNull(parameters, "jobTitle", searchRequest.getJobTitle());
		addIfNotNull(parameters, "townCity", searchRequest.getTownCity());
		addIfNotNull(parameters, "state", searchRequest.getState());
		addIfNotNull(parameters, "country", searchRequest.getCountry());
		

		String str = parameters.entrySet().stream()
				.map(entry -> entry.getKey() + "=:" + entry.getKey())
				.collect(Collectors.joining(" and "));

		
		PanacheQuery<employee> query = find(str.toString(), parameters);
		return query.list();
		
	}

	private static void addIfNotNull(Map<String, Object> map, String key, String value) {
		if (value != null && !value.isEmpty()) {
			map.put(key, value);
		}
	}

}
```

Resource Class

```
package com.infoDirectory.api;

import static javax.ws.rs.core.Response.Status.NOT_FOUND;

import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.validation.Valid;
import javax.ws.rs.Consumes;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.WebApplicationException;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;

import com.infoDirectory.entity.employee;
import com.infoDirectory.model.ComboboxRequest;
import com.infoDirectory.model.EmployeeInfoRequest;

import com.infoDirectory.model.InfoDirectoryComboboxLists;


import org.eclipse.microprofile.metrics.MetricUnits;
import org.eclipse.microprofile.metrics.annotation.Counted;
import org.eclipse.microprofile.metrics.annotation.Timed;
import org.eclipse.microprofile.openapi.annotations.Operation;
import org.jboss.resteasy.reactive.RestPath;

import io.quarkus.hibernate.reactive.panache.Panache;
import io.smallrye.common.annotation.Blocking;
import io.smallrye.mutiny.Uni;

@Path("/api/v1")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public class InfoDirectoryResource {

	
	@Counted(name = "getComboboxDataCount", absolute = true)
	@Timed(name = "getComboboxDataTimer", absolute = true, unit = MetricUnits.MILLISECONDS)
	@POST
	@Path("/comboboxData")
	@Blocking
	@Operation(summary = "Get data to all Comboboxes / Dependent comboboxes")
	public Uni<InfoDirectoryComboboxLists> getComboboxData(@Valid ComboboxRequest comboboxRequest) {
		return employee.getComboboxData(comboboxRequest);
	}
	
	@Counted(name = "getSearchInfoCount", absolute = true)
	@Timed(name = "getSearchInfoTimer", absolute = true, unit = MetricUnits.MILLISECONDS)
	@POST
	@Path("/search")
	@Operation(summary = "Retrives data as per the data provided for Search")
	public Uni<List<employee>> getSearchInfo(SearchRequest searchRequest) { 
		return employee.getSearchInfo(searchRequest);
	}
	

}
```

**Comment by ethan-gallant** [comment]
Hey @sxs737! Your problem appears that you're blocking the Vert.x event loop thread with this line:
`List<employee> response = query.list().await().atMost(Duration.ofSeconds(60));`

Effectively, you're making the thread wait for that result to be processed, making the Uni it returns Uniless (sorry bad pun, I mean useless).

You can resolve the issue likely by changing your method out for something like this:

```java
public static Uni<InfoDirectoryComboboxLists> getSearchComboBoxData(ComboboxRequest comboboxRequest) {
        Map<String, Object> parameters = new HashMap<String, Object>();
        addIfNotNull(parameters, "location", comboboxRequest.getLocation());
        addIfNotNull(parameters, "jobTitle", comboboxRequest.getJobTitle());
        addIfNotNull(parameters, "townCity", comboboxRequest.getTownCity());
        addIfNotNull(parameters, "state", comboboxRequest.getState());


        String str = parameters.entrySet().stream()
                .map(entry -> entry.getKey() + "=:" + entry.getKey())
                .collect(Collectors.joining(" and "));

        PanacheQuery<employee> query = find(str.toString(), parameters);

        // Says that after recieving the List<Employee> from the database, we transform it
        return query.list().onItem().transformToUni(response -> {
            // We provide the instruction to transform the List<Employee> into a InfoDirectoryComboboxLists
            // This is then run in a reactive fashion (similar to doing CompletableFuture.handle())
            InfoDirectoryComboboxLists infoDirectoryComboboxLists = new InfoDirectoryComboboxLists();

            infoDirectoryComboboxLists.setJobTitleList(
                    (response.stream().collect(Collectors.mapping(employee::getJobTitle, Collectors.toList())))
                            .stream().filter(Objects::nonNull).distinct().sorted().collect(Collectors.toList()));

            infoDirectoryComboboxLists.setTownList(
                    (response.stream().collect(Collectors.mapping(employee::getTownCity, Collectors.toList())))
                            .stream().filter(Objects::nonNull).distinct().sorted().collect(Collectors.toList()));

            infoDirectoryComboboxLists.setCountryList(
                    (response.stream().collect(Collectors.mapping(employee::getCountry, Collectors.toList())))
                            .stream().filter(Objects::nonNull).distinct().sorted().collect(Collectors.toList()));

            infoDirectoryComboboxLists.setStateList(
                    (response.stream().collect(Collectors.mapping(employee::getState, Collectors.toList())))
                            .stream().filter(Objects::nonNull).distinct().sorted().collect(Collectors.toList()));
        });
    }
```

Haven't been able to test it compiling as I don't have your source but something like that should work.

**Comment by sxs737** [comment]
@ethan-gallant Thank you very much !! . 
I have removed the @Blocking from the **getComboboxData()** and added your suggested code change . I will let you know if i am still getting error . That error was thrown in the other method **getSearchInfo()** which does not have any await() . it might be that call to @Blocking from the **getComboboxData()** was causing Block on execution of **getSearchInfo()**

**Comment by geoand** [comment]
> This error usually happens when there is a call to something that's not reactive or Quarkus doesn't recognize as reactive

@DavideD any way we can determine this and provide a better error message?

**Comment by DavideD** [comment]
It should be possible. I don't know why we have this error message.

Normally one would have a message from the `vertx-blocked-thread-checker` that says something like:
```
[WARN] [20:vertx-blocked-thread-checker] Thread Thread[vert.x-eventloop-thread-2,5,main] has been blocked for 3671 ms, time limit is 2000 ms
```

I suspect some extension is hiding it or the timeout comes from somewhere else.

**Comment by franciscoGarrigo** [comment]
Hello

I got this issue too, but in a differente way.  My application works fine but at some time, after consuming several messages this exceptions shows. What should i do?  Open new issue or use this for explain completely my problem?

**Comment by tehapap** [comment]
Hi!

I've got the same issue with quarkus-hibernate-reactive-panache + quarkus-reactive-pg-client + quarkus-smallrye-graphql

```
@GraphQLApi
public class BookResource {

    @Query("allBooks")
    @Description("Get all existing books")
    public Uni<List<Book>> listAllBooks() {
        return Book.listAll();
    }
}
```
The endpoint works well only 4 times, then mentioned above timeout exception appears. Always reproducible.

**Comment by DavideD** [comment]
Could you create a test case?

**Comment by DavideD** [comment]
Does it only happen with a native build?

**Comment by mikeleitz** [comment]
> Does it only happen with a native build?

I haven't tried it via native yet. It happens running it in the IDE.

**Comment by DavideD** [comment]
> I'll put something together tonight and post here. Probably 9 hours from this post.

Thanks a lot

**Comment by DavideD** [comment]
Maybe there are other places where you are using `@Transactional`.  `@Transactional` doesn't work with Hibernate Reactive and Panache. Make sure to check that you are using `@ReactiveTransactional` instead. Please, let me know if this helps.

**Comment by mikeleitz** [comment]
Replaced the two places where I was using @Transactional with @ReactiveTransactional. Same error.
<img width="1159" alt="Xnapper-2022-06-24-07 41 20" src="https://user-images.githubusercontent.com/40745367/175538221-d01d26d9-32d2-4cb1-8d4c-6ea2293c6a64.png">

**Comment by DavideD** [comment]
I've tried to create something that I can run on my repository: https://github.com/DavideD/quarkus-23739
But I'm not familiar enough with the security API. @mikeleitz, If you could help me fix that project so that I can reproduce the error, I would be able to finally figure out what's going on.

**Comment by mikeleitz** [comment]
Ok, I'll work on this tonight.

**Comment by tehapap** [comment]
> Hi!
> 
> I've got the same issue with quarkus-hibernate-reactive-panache + quarkus-reactive-pg-client + quarkus-smallrye-graphql
> 
> ```
> @GraphQLApi
> public class BookResource {
> 
>     @Query("allBooks")
>     @Description("Get all existing books")
>     public Uni<List<Book>> listAllBooks() {
>         return Book.listAll();
>     }
> }
> ```
> 
> The endpoint works well only 4 times, then mentioned above timeout exception appears. Always reproducible.

Fixed in 2.10 for me

**Comment by mikeleitz** [comment]
I didn't work on this last night but I will tonight.

I did verify the issue is still happening with 2.10.

**Comment by DavideD** [comment]
Thanks a lot!
I can start the project now.

Could you also tell me the steps to reproduce the error?

**Comment by mikeleitz** [comment]
Send me an email and I'll reply with the creds and instructions

leitz at mikeleitz.com

**Comment by DavideD** [comment]
You can send it to davide@hibernate.org

**Comment by mikeleitz** [comment]
Sent.

**Comment by DavideD** [comment]
We are still trying to figure out what's the problem with it. 
As a workaround, it seems to work if you don't use panache:
1. Remove @ReactiveTransactional
2. Add
    ```
    @Inject
    Mutiny.SessionFactory factory;
     ``` 
3.  Change the returned code to:
     ```
             return factory.withSession( RolesAugmentor::count )
                .map( item -> {
                          QuarkusSecurityIdentity.Builder builder = QuarkusSecurityIdentity.builder()
                                  .setPrincipal( identity.getPrincipal() )
                                  .addAttributes( identity.getAttributes() )
                                  .addCredentials( identity.getCredentials() )
                                  .addRoles( identity.getRoles() );

                          List.of( "admin" ).stream().forEach( role -> builder.addRole( role ) );

                          return builder.build();
                      }
                );
    }

    private static Uni<Long> count(Mutiny.Session session) {
        return session
                .createQuery( "select count(u) from PopUser u", Long.class )
                .getSingleResult();
    }
     ```

**Comment by DavideD** [comment]
What I've found is that, when using Panache,  a new session is created for each request but the dispose method is never called and therefore the session never gets closed.

**Comment by DavideD** [comment]
I've created a testcase using one of the quickstarts: https://github.com/DavideD/quarkus-quickstarts/tree/oidc-test/security-openid-connect-quickstart

**Comment by DavideD** [comment]
@mkouba Any idea why the dispose in `ReactiveSessionProducer` doesn't get called? (the Producer gets called everytime). One theory is that we might need to add an `@Unremovable` in the dispose method in `ReactiveSessionProducer`

**Comment by mkouba** [comment]
> Any idea why the dispose in ReactiveSessionProducer doesn't get called? (the Producer gets called everytime).

So the disposer method would be called when the bean is destroyed, i.e. when destroyed explicitly or when the context where the bean instance lives (contextual instance using the spec wording) is destroyed. It might be something related to context propagation. I'll need to take a look at the testcase you mentioned in https://github.com/quarkusio/quarkus/issues/23739#issuecomment-1171380717.

> One theory is that we might need to add an @Unremovable in the dispose method in ReactiveSessionProducer

That's not a good theory. `@Unremovable` has nothing to do with disposer methods.

**Comment by DavideD** [comment]
I think I know what's happening: the `ActivateRequestContextInterceptor` doesn't consider that the method is reactive and returns a Uni. [Therefore it terminates the request context too soon](https://github.com/quarkusio/quarkus/blob/6273be7ab40c56605b50e1e237b8db9d0575a5db/independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/ActivateRequestContextInterceptor.java#L22).

**Comment by mkouba** [comment]
Well, I have no idea when exactly is `SecurityIdentityAugmentor.augment()` invoked and in which context but wasn't the issue that the session was never closed (https://github.com/quarkusio/quarkus/issues/23739#issuecomment-1170314689)? Because `requestContext.terminate()` always destroys all beans created in the current request context.

In any case, `@ActivateRequestContext` is definitely not reactive-aware and its behavior is mandated by the CDI spec.

**Comment by DavideD** [comment]
Yes, but because it's reactive `requestContext.terminate()` gets  called before the session creation.
The session gets created later, when the method returned uni gets subcribed, so there's no session to close when `terminate` is invoked.

**Comment by DavideD** [comment]
In this case the session is created by Panache when we call `Panache.count()`

**Comment by FroMage** [comment]
> In any case, @ActivateRequestContext is definitely not reactive-aware and its behavior is mandated by the CDI spec

Well, you could also say that `@Transactional` is mandated by some spec, and yet we made it work OOTB with reactive return types, because we had to.
And we're doing exactly the same for any method which needs a CDI request context: we always delay the end of the request context until the request is done, by hooking onto the returned reactive type. Otherwise they're always broken, and we don't want that.
So `@ActivateRequestContext` should be consistent and also delay the request termination until the method's returned reactive type is done, right @cescoffier ?

**Comment by cescoffier** [comment]
Totally agree @FroMage

**Comment by DavideD** [comment]
I've tried to create a simpler testcase to show the error: https://github.com/DavideD/quarkus/commit/f75fcb7cc6276fd564f62a183322ee31f18db218

**Comment by mikeleitz** [comment]
I appreciate everyone working on this. 👍

**Comment by DavideD** [comment]
I think I might have a fix for this: https://github.com/DavideD/quarkus/tree/reactive-activerequestcontext
Once applied, it seems to solve both tests.

I have some more questions though:
* Should we also make it work for `Multi`?
* Should we check `CompletionStage`?

**Comment by DavideD** [comment]
I've sent a PR, it should make it easier to discuss it

**Comment by mkouba** [comment]
> Well, you could also say that @Transactional is mandated by some spec, and yet we made it work OOTB with reactive return types, because we had to.

@cescoffier @FroMage what exactly do we do? I thought that one should never use `@Transactional` with hibernate reactive and if really needed then just use `@ReactiveTransactional` instead...

**Comment by DavideD** [comment]
`@Transactional` doesn't work with Hibernate Reactive, but you can use it in other cases: https://quarkus.io/guides/transaction#reactive-extensions

That said, this use case seems simpler and I wouldn't introduce a second annotation.

**Comment by DavideD** [comment]
> I think the same error happens with @Scheduled

Also `@PostConstruct` [doesn't seem to work with Reactive](https://stackoverflow.com/questions/73000578/using-transaction-in-postconstruct/73020890#73020890). 

(I'm putting it here because I don't want to create a new issue for now and I don't want to forget about it)

**Comment by mkouba** [comment]
> I think the same error happens with `@Scheduled`:
> 
> ```
>     @Scheduled(every = "2s")
>     Uni<Void> scheduleRefresh() {
>         return fruitRepository.listAll().replaceWithVoid();
>     }
> ```

Hm, I think that [`@Scheduled` non-blocking methods](https://quarkus.io/guides/scheduler-reference#non-blocking-methods) should work just fine. It was fixed in https://github.com/quarkusio/quarkus/pull/25260 for 2.9.0.Final. What kind of error do you have in mind?

**Comment by DavideD** [comment]
> Hm, I think that [`@Scheduled` non-blocking methods](https://quarkus.io/guides/scheduler-reference#non-blocking-methods) should work just fine. It was fixed in #25260 for 2.9.0.Final. What kind of error do you have in mind?

After 3 queries you will see the same error you see for this issue because the session doesn't get closed.

**Comment by mkouba** [comment]
Ok. Do we have a reproducer I can look at? I'm kind of lost in the comments of this issue.

**Comment by DavideD** [comment]
You can see the error in the quickstart for `hibernate-reactive-panache-quickstart` on this branch: https://github.com/DavideD/quarkus-quickstarts/tree/scheduler

**Comment by mkouba** [comment]
> You can see the error in the quickstart for `hibernate-reactive-panache-quickstart` on this branch: https://github.com/DavideD/quarkus-quickstarts/tree/scheduler

This PR should fix the problem: https://github.com/quarkusio/quarkus/pull/27108

**Comment by fediazgon** [comment]
I'm having the same problem with version `2.11.2.Final` after adding a custom `SecurityIdentityAugmentor` that needs `@ ActivateRequestContext` to access a repository as describe in the [documentation](https://quarkus.io/guides/security-customization#security-identity-customization).

**Comment by Sanne** [comment]
do we know if #27108 solved this problem? @DavideD ?

**Comment by DavideD** [comment]
@Sanne They are two different issues. It doesn't solve this one. But I'm not sure why that fix has been merged without issues and my PR isn't. They use the same approach.

**Comment by FroMage** [comment]
AFAICT all interceptors that create request scopes should extend the lifecycle of those request scopes to the returned reactive type, exactly like @DavideD 's PR and `@Transactional` do (for a different type of context).
So what's valid for `@Transactional` should also be the norm for `@Scheduled` and `@ActivateRequestContext` and whatever other meta-annotation that creates/destroys a request context.

**Comment by chengkuangan** [comment]
Hi,

I am having the same problem with Quarkus Platform `2.16.5.Final`. I am using PostgreSQL (not limited to MySQL as per the initial reported title), I can confirm that this problem is consistent which failed after 4th time of DB queries (i.e. failed at 5th attempt and onwards). I am using `Reactive PostgreSQL` with `Fungy`.

If I am using normal non-reactive PostgreSQL extension, the DB operations works fine.

The code for the query is simple with the `ProviderEntity` is extending `io.quarkus.hibernate.reactive.panache.PanacheEntityBase`

```
@Funq("providers")
    public Uni<List<ProviderEntity>> getProviders(){
        return ProviderEntity.listAll();
    }
```

Any idea what's wrong?

Error thrown at command prompt:

```
2023-05-10 14:38:15,073 ERROR [org.hib.rea.errors] (vert.x-eventloop-thread-2) HR000057: Failed to execute statement [select provideren0_.id as id1_1_, provideren0_.providerId as provider2_1_, provideren0_.val as val3_1_ from indexes.provider provideren0_]: could not execute query: java.util.concurrent.CompletionException: io.vertx.core.impl.NoStackTraceThrowable: Timeout
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:636)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
        at io.vertx.core.Future.lambda$toCompletionStage$3(Future.java:386)
        at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:153)
        at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75)
        at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230)
        at io.vertx.core.impl.future.Mapping.onFailure(Mapping.java:45)
        at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75)
        at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230)
        at io.vertx.core.impl.future.PromiseImpl.tryFail(PromiseImpl.java:23)
        at io.vertx.core.impl.future.PromiseImpl.onFailure(PromiseImpl.java:54)
        at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:43)
        at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:23)
        at io.vertx.sqlclient.impl.pool.SqlConnectionPool$1PoolRequest.lambda$null$1(SqlConnectionPool.java:218)
        at io.vertx.core.net.impl.pool.SimpleConnectionPool$Cancel.run(SimpleConnectionPool.java:676)
        at io.vertx.core.net.impl.pool.CombinerExecutor.submit(CombinerExecutor.java:50)
        at io.vertx.core.net.impl.pool.SimpleConnectionPool.execute(SimpleConnectionPool.java:245)
        at io.vertx.core.net.impl.pool.SimpleConnectionPool.cancel(SimpleConnectionPool.java:638)
        at io.vertx.sqlclient.impl.pool.SqlConnectionPool$1PoolRequest.lambda$onEnqueue$2(SqlConnectionPool.java:215)
        at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:932)
        at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:903)
        at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:55)
        at io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:158)
        at io.vertx.core.impl.ContextInternal.emit(ContextInternal.java:194)
        at io.vertx.core.impl.VertxImpl$InternalTimerHandler.run(VertxImpl.java:921)
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.vertx.core.impl.NoStackTraceThrowable: Timeout
```

**Comment by DavideD** [comment]
@chengkuangan, I haven't tried, but could you annotate the method with `@WithSession`? 
I think what's happening is that the session never get closed and connections never get released. That's why you have the error at the 5th attempt.

A workaround is to use Hibernate Reactive without Panache:
```
    @Inject
    Mutiny.SessionFactory sf;

    @Funq("providers")
    public Uni<List<ProviderEntity>> getProviders(){
        return sf.withSession(s -> s.createQuery( "from ProviderEntity", ProviderEntity.class).getResultList();
    }
```

But I'm not familiar with Funqy and you should probably create a separate issue for this.

**Comment by chengkuangan** [comment]
@DavideD 

May I know which extension and package does this `@WithSession` located?

**Comment by DavideD** [comment]
Ah, sorry, you are using Quarkus 2. It's been introduce in Quarkus 3 as [part of Hibernate Reactive Panache common](https://github.com/quarkusio/quarkus/blob/main/extensions/panache/hibernate-reactive-panache-common/runtime/src/main/java/io/quarkus/hibernate/reactive/panache/common/WithSession.java).

**Comment by paomian** [comment]
Hello

I got this issue too, but in a differente way. My application works fine but at some time, I request http server by large concurrent. It will cause this error. and will not return to normal.

```
2023-06-30 10:55:25,013 SEVERE [io.ope.exp.int.grp.OkHttpGrpcExporter] (OkHttp http://jaeger-collector.jaeger.svc:4317/...) Failed to export spans. The request could not be executed. Full error message: Failed to connect to jaeger-collector.jaeger.svc/10.0.10.186:4317
2023-06-30 10:55:25,033 SEVERE [io.ope.exp.int.grp.OkHttpGrpcExporter] (OkHttp http://jaeger-collector.jaeger.svc:4317/...) Failed to export spans. The request could not be executed. Full error message: Failed to connect to jaeger-collector.jaeger.svc/10.0.10.186:4317
2023-06-30 10:55:25,036 SEVERE [io.ope.exp.int.grp.OkHttpGrpcExporter] (OkHttp http://jaeger-collector.jaeger.svc:4317/...) Failed to export spans. The request could not be executed. Full error message: Failed to connect to jaeger-collector.jaeger.svc/10.0.10.186:4317
2023-06-30 10:55:25,360 SEVERE [io.ope.exp.int.grp.OkHttpGrpcExporter] (OkHttp http://jaeger-collector.jaeger.svc:4317/...) Failed to export spans. The request could not be executed. Full error message: Failed to connect to jaeger-collector.jaeger.svc/10.0.10.186:4317
2023-06-30 10:55:25,696 SEVERE [io.ope.exp.int.grp.OkHttpGrpcExporter] (OkHttp http://jaeger-collector.jaeger.svc:4317/...) Failed to export spans. The request could not be executed. Full error message: Failed to connect to jaeger-collector.jaeger.svc/10.0.10.186:4317
2023-06-30 10:55:26,158 SEVERE [io.ope.exp.int.grp.OkHttpGrpcExporter] (OkHttp http://jaeger-collector.jaeger.svc:4317/...) Too many log messages detected. Will only log once per minute from now on.
2023-06-30 10:55:26,158 SEVERE [io.ope.exp.int.grp.OkHttpGrpcExporter] (OkHttp http://jaeger-collector.jaeger.svc:4317/...) Failed to export spans. The request could not be executed. Full error message: Failed to connect to jaeger-collector.jaeger.svc/10.0.10.186:4317
2023-06-30 10:57:19,862 SEVERE [io.ope.exp.int.grp.OkHttpGrpcExporter] (OkHttp http://jaeger-collector.jaeger.svc:4317/...) Failed to export spans. The request could not be executed. Full error message: Failed to connect to jaeger-collector.jaeger.svc/10.0.10.186:4317
2023-06-30 10:57:31,883 SEVERE [io.ope.exp.int.grp.OkHttpGrpcExporter] (OkHttp http://jaeger-collector.jaeger.svc:4317/...) Failed to export spans. The request could not be executed. Full error message: Failed to connect to jaeger-collector.jaeger.svc/10.0.10.186:4317
2023-06-30 10:58:21,227 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-1) HTTP Request to /teams failed, error id: 663ed54c-d5f7-406d-8287-009a20bcdbfb-2: io.vertx.core.impl.NoStackTraceThrowable: Timeout

2023-06-30 10:58:21,227 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-0) HTTP Request to /teams failed, error id: 663ed54c-d5f7-406d-8287-009a20bcdbfb-1: io.vertx.core.impl.NoStackTraceThrowable: Timeout

2023-06-30 10:58:21,234 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-1) HTTP Request to /teams failed, error id: 663ed54c-d5f7-406d-8287-009a20bcdbfb-3: io.vertx.core.impl.NoStackTraceThrowable: Timeout

2023-06-30 10:58:21,235 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-1) HTTP Request to /teams failed, error id: 663ed54c-d5f7-406d-8287-009a20bcdbfb-4: io.vertx.core.impl.NoStackTraceThrowable: Timeout

2023-06-30 10:58:21,237 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-1) HTTP Request to /teams failed, error id: 663ed54c-d5f7-406d-8287-009a20bcdbfb-5: io.vertx.core.impl.NoStackTraceThrowable: Timeout
```

log where  above have no stack.
my timed task throw same error but has stack.
```
2023-06-30 10:59:24,003 ERROR [io.qua.sch.com.run.StatusEmitterInvoker] (vert.x-eventloop-thread-0) Error occurred while executing task for trigger IntervalTrigger [id=secret, interval=600000]: java.util.concurrent.CompletionException: io.vertx.core.impl.NoStackTraceThrowable: Timeout
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:874)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at io.smallrye.context.impl.wrappers.SlowContextualConsumer.accept(SlowContextualConsumer.java:21)
	at io.smallrye.mutiny.helpers.UniCallbackSubscriber.onFailure(UniCallbackSubscriber.java:62)
	at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.onFailure(UniOperatorProcessor.java:55)
	at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.onFailure(UniOperatorProcessor.java:55)
	at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.onFailure(UniOnItemOrFailureFlatMap.java:67)
	at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.onFailure(UniOnItemOrFailureFlatMap.java:67)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownFailure$KnownFailureSubscription.forward(UniCreateFromKnownFailure.java:38)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownFailure.subscribe(UniCreateFromKnownFailure.java:23)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.performInnerSubscription(UniOnItemOrFailureFlatMap.java:99)
	at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.onItem(UniOnItemOrFailureFlatMap.java:54)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem$KnownItemSubscription.forward(UniCreateFromKnownItem.java:38)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem.subscribe(UniCreateFromKnownItem.java:23)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap.subscribe(UniOnItemOrFailureFlatMap.java:27)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.performInnerSubscription(UniOnItemOrFailureFlatMap.java:99)
	at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.onFailure(UniOnItemOrFailureFlatMap.java:65)
	at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.onFailure(UniOperatorProcessor.java:55)
	at io.smallrye.mutiny.operators.uni.UniOnItemConsume$UniOnItemComsumeProcessor.onFailure(UniOnItemConsume.java:65)
	at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.onFailure(UniOperatorProcessor.java:55)
	at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.onFailure(UniOperatorProcessor.java:55)
	at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.onFailure(UniOperatorProcessor.java:55)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage$CompletionStageUniSubscription.forwardResult(UniCreateFromCompletionStage.java:58)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at io.vertx.core.Future.lambda$toCompletionStage$3(Future.java:538)
	at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:153)
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75)
	at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230)
	at io.vertx.core.impl.future.Mapping.onFailure(Mapping.java:45)
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75)
	at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230)
	at io.vertx.core.impl.future.PromiseImpl.tryFail(PromiseImpl.java:23)
	at io.vertx.core.impl.future.PromiseImpl.onFailure(PromiseImpl.java:54)
	at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:43)
	at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:23)
	at io.vertx.sqlclient.impl.pool.SqlConnectionPool$1PoolRequest.lambda$null$1(SqlConnectionPool.java:224)
	at io.vertx.core.net.impl.pool.SimpleConnectionPool$Cancel.run(SimpleConnectionPool.java:676)
	at io.vertx.core.net.impl.pool.CombinerExecutor.submit(CombinerExecutor.java:56)
	at io.vertx.core.net.impl.pool.SimpleConnectionPool.execute(SimpleConnectionPool.java:245)
	at io.vertx.core.net.impl.pool.SimpleConnectionPool.cancel(SimpleConnectionPool.java:638)
	at io.vertx.sqlclient.impl.pool.SqlConnectionPool$1PoolRequest.lambda$onEnqueue$2(SqlConnectionPool.java:221)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:948)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:919)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:55)
	at io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:158)
	at io.vertx.core.impl.ContextInternal.emit(ContextInternal.java:194)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.run(VertxImpl.java:937)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.vertx.core.impl.NoStackTraceThrowable: Timeout
```

The database is ok. I have two container. one is broken,other is ok.

**Comment by DavideD** [comment]
@paomian We need more details. Which version of Quarkus are you using? Which operation are you try to run?
Does it only happen under stress?

**Comment by DavideD** [comment]
We just fixed an error in Hibernate Reactive related to a race condition when updating entities. Maybe that's what happening: https://github.com/hibernate/hibernate-reactive/issues/1687

**Comment by paomian** [comment]
@DavideD I use 3.1.3.Final.
I just do a multi query operation.

> Does it only happen under stress?

Maybe not,Sometimes without stress it can occur for no reason

**Comment by paomian** [comment]
Maybe reproduce in dev mode, I dump thread got this.
```
"vert.x-eventloop-thread-8@27478" prio=5 tid=0xb1 nid=NA waiting
  java.lang.Thread.State: WAITING
	 blocks JPA Startup Thread@27502
	 blocks vert.x-eventloop-thread-7@27477
	  at jdk.internal.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
	  at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1864)
	  at java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463)
	  at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434)
	  at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1898)
	  at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2117)
	  at org.hibernate.reactive.provider.service.ReactiveImprovedExtractionContextImpl.getQueryResultSet(ReactiveImprovedExtractionContextImpl.java:113)
	  at org.hibernate.reactive.provider.service.ReactiveImprovedExtractionContextImpl.getQueryResults(ReactiveImprovedExtractionContextImpl.java:79)
	  at org.hibernate.tool.schema.extract.internal.SequenceInformationExtractorLegacyImpl.extractMetadata(SequenceInformationExtractorLegacyImpl.java:39)
	  at org.hibernate.tool.schema.extract.internal.DatabaseInformationImpl.initializeSequences(DatabaseInformationImpl.java:66)
	  at org.hibernate.tool.schema.extract.internal.DatabaseInformationImpl.<init>(DatabaseInformationImpl.java:60)
	  at org.hibernate.tool.schema.internal.Helper.buildDatabaseInformation(Helper.java:187)
	  at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.doMigration(AbstractSchemaMigrator.java:98)
	  at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:284)
	  at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.lambda$process$5(SchemaManagementToolCoordinator.java:143)
	  at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator$$Lambda$2520/0x0000000801fc24a0.accept(Unknown Source:-1)
	  at java.util.HashMap.forEach(HashMap.java:1421)
	  at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:140)
	  at io.quarkus.hibernate.orm.runtime.observers.SessionFactoryObserverForSchemaExport.sessionFactoryCreated(SessionFactoryObserverForSchemaExport.java:21)
	  at org.hibernate.internal.SessionFactoryObserverChain.sessionFactoryCreated(SessionFactoryObserverChain.java:35)
	  at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:292)
	  at org.hibernate.reactive.session.impl.ReactiveSessionFactoryImpl.<init>(ReactiveSessionFactoryImpl.java:32)
	  at io.quarkus.hibernate.reactive.runtime.boot.FastBootReactiveEntityManagerFactoryBuilder.build(FastBootReactiveEntityManagerFactoryBuilder.java:31)
	  at io.quarkus.hibernate.reactive.runtime.FastBootHibernateReactivePersistenceProvider.createEntityManagerFactory(FastBootHibernateReactivePersistenceProvider.java:92)
	  at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
	  at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
	  at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:156)
	  - locked <0x6b86> (a io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit)
	  at io.quarkus.hibernate.orm.runtime.JPAConfig.getEntityManagerFactory(JPAConfig.java:104)
	  at io.quarkus.hibernate.orm.runtime.HibernateOrmRecorder$3.apply(HibernateOrmRecorder.java:110)
	  at io.quarkus.hibernate.orm.runtime.HibernateOrmRecorder$3.apply(HibernateOrmRecorder.java:106)
	  at org.hibernate.SessionFactory_9c40b3d5cbb6ee6bb4cf2cb7bab0a1fda6694fe5_Synthetic_Bean.createSynthetic(Unknown Source:-1)
	  at org.hibernate.SessionFactory_9c40b3d5cbb6ee6bb4cf2cb7bab0a1fda6694fe5_Synthetic_Bean.doCreate(Unknown Source:-1)
	  at org.hibernate.SessionFactory_9c40b3d5cbb6ee6bb4cf2cb7bab0a1fda6694fe5_Synthetic_Bean.create(Unknown Source:-1)
	  at org.hibernate.SessionFactory_9c40b3d5cbb6ee6bb4cf2cb7bab0a1fda6694fe5_Synthetic_Bean.create(Unknown Source:-1)
	  at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:113)
	  at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:37)
	  at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:34)
	  at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	  - locked <0x6b87> (a io.quarkus.arc.impl.LazyValue)
	  at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	  at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:34)
	  at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:21)
	  at org.hibernate.SessionFactory_9c40b3d5cbb6ee6bb4cf2cb7bab0a1fda6694fe5_Synthetic_ClientProxy.arc$delegate(Unknown Source:-1)
	  at org.hibernate.SessionFactory_9c40b3d5cbb6ee6bb4cf2cb7bab0a1fda6694fe5_Synthetic_ClientProxy.unwrap(Unknown Source:-1)
	  at io.quarkus.hibernate.reactive.runtime.ReactiveSessionFactoryProducer.mutinySessionFactory(ReactiveSessionFactoryProducer.java:40)
	  at io.quarkus.hibernate.reactive.runtime.ReactiveSessionFactoryProducer_ProducerMethod_mutinySessionFactory_f400be8ad6884ffa846bcddd4116ae0c9f200ae3_Bean.doCreate(Unknown Source:-1)
	  at io.quarkus.hibernate.reactive.runtime.ReactiveSessionFactoryProducer_ProducerMethod_mutinySessionFactory_f400be8ad6884ffa846bcddd4116ae0c9f200ae3_Bean.create(Unknown Source:-1)
	  at io.quarkus.hibernate.reactive.runtime.ReactiveSessionFactoryProducer_ProducerMethod_mutinySessionFactory_f400be8ad6884ffa846bcddd4116ae0c9f200ae3_Bean.create(Unknown Source:-1)
	  at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:113)
	  at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:37)
	  at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:34)
	  at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	  - locked <0x6b85> (a io.quarkus.arc.impl.LazyValue)
	  at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	  at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:34)
	  at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:21)
	  at org.hibernate.reactive.mutiny.impl.ReactiveSessionFactoryProducer_ProducerMethod_mutinySessionFactory_f400be8ad6884ffa846bcddd4116ae0c9f200ae3_ClientProxy.arc$delegate(Unknown Source:-1)
	  at org.hibernate.reactive.mutiny.impl.ReactiveSessionFactoryProducer_ProducerMethod_mutinySessionFactory_f400be8ad6884ffa846bcddd4116ae0c9f200ae3_ClientProxy.openSession(Unknown Source:-1)
	  at io.quarkus.hibernate.reactive.panache.common.runtime.SessionOperations.withSession(SessionOperations.java:121)
	  at io.quarkus.hibernate.reactive.panache.common.runtime.WithSessionInterceptor.intercept(WithSessionInterceptor.java:20)
	  at io.quarkus.hibernate.reactive.panache.common.runtime.WithSessionInterceptor_Bean.intercept(Unknown Source:-1)
	  at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	  at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
	  at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
	  at somthing_Subclass.getTeams(Unknown Source:-1)
	  at somthing$quarkusrestinvoker$getTeams_7a149508ca2c00668d5163d9aeaafa88c8a024f4.invoke(Unknown Source:-1)
	  at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	  at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	  at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
	  at org.jboss.resteasy.reactive.server.handlers.RestInitialHandler.beginProcessing(RestInitialHandler.java:48)
	  at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:23)
	  at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:10)
	  at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	  at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
	  at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	  at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:58)
	  at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:36)
	  at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	  at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
	  at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	  at io.quarkus.vertx.http.runtime.security.AbstractHttpAuthorizer.doPermissionCheck(AbstractHttpAuthorizer.java:110)
	  at io.quarkus.vertx.http.runtime.security.AbstractHttpAuthorizer.checkPermission(AbstractHttpAuthorizer.java:93)
	  at io.quarkus.vertx.http.runtime.security.HttpAuthorizer.checkPermission(HttpAuthorizer.java:15)
	  at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2.handle(HttpSecurityRecorder.java:85)
	  at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2.handle(HttpSecurityRecorder.java:77)
	  at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	  at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
	  at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	  at io.quarkus.resteasy.reactive.server.runtime.ResteasyReactiveRecorder$13.handle(ResteasyReactiveRecorder.java:380)
	  at io.quarkus.resteasy.reactive.server.runtime.ResteasyReactiveRecorder$13.handle(ResteasyReactiveRecorder.java:373)
	  at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	  at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
	  at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	  at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$AbstractAuthenticationHandler.handle(HttpSecurityRecorder.java:505)
	  at io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$AbstractAuthenticationHandler.handle(HttpSecurityRecorder.java:368)
	  at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	  at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
	  at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	  at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup.handleHotReplacementRequest(VertxHttpHotReplacementSetup.java:135)
	  at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$$Lambda$115/0x00000008010ed200.handle(Unknown Source:-1)
	  at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:437)
	  at io.quarkus.vertx.http.runtime.VertxHttpRecorder$5.handle(VertxHttpRecorder.java:433)
	  at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	  at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
	  at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	  at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:68)
	  at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:37)
	  at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$2.handle(HttpServerCommonHandlers.java:82)
	  at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$2.handle(HttpServerCommonHandlers.java:65)
	  at io.quarkus.vertx.http.runtime.VertxHttpRecorder$1.handle(VertxHttpRecorder.java:180)
	  at io.quarkus.vertx.http.runtime.VertxHttpRecorder$1.handle(VertxHttpRecorder.java:156)
	  at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:55)
	  at io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:158)
	  at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:167)
	  at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:158)
	  at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:153)
	  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	  at io.vertx.core.http.impl.Http1xUpgradeToH2CHandler.channelRead(Http1xUpgradeToH2CHandler.java:124)
	  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	  at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	  at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	  at io.vertx.core.http.impl.Http1xOrH2CHandler.end(Http1xOrH2CHandler.java:61)
	  at io.vertx.core.http.impl.Http1xOrH2CHandler.channelRead(Http1xOrH2CHandler.java:38)
	  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	  at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	  at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	  at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	  at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	  at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	  at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	  at java.lang.Thread.run(Thread.java:833)

```

**Comment by DavideD** [comment]
```
	  at org.hibernate.reactive.provider.service.ReactiveImprovedExtractionContextImpl.getQueryResultSet(ReactiveImprovedExtractionContextImpl.java:113)
```
It's seems related to the start up, when Hibernate gets the info from the database.

We've just fixed an issue about [Quarkus not selecting the right dialect version for MSSQL](https://github.com/quarkusio/quarkus/issues/34032), but this seems different.

I cannot do much without a test case. You could update one of the [quickstarts](https://github.com/quarkusio/quarkus-quickstarts) so that it recreates the issue.

**Comment by paomian** [comment]
ok, I will do some work get more info .
