### ISSUE TITLE
native docker container image is not created/pushed

### ISSUE THREAD

**Issue by grubermi** [quarkusio/quarkus#23836]
### Describe the bug

We want to create a native binary in a container and push the resulting contianer image to our docker registry by using `mvn clean package -Pnative -Dquarkus.native.container-build=true -Dquarkus.container-image.push=true  -Dquarkus.container-image.registry=our.docker.registry:5000 `.
Until version 2.6.1.Final this works fine. Since we updated to version 2.7.1.Final, this command does not create a container image, that contains the native binary. Further, it does not try to push any container image to our registry. It only creates the native binary in the target directory.

### Expected behavior

When executing `mvn clean package -Pnative -Dquarkus.native.container-build=true -Dquarkus.container-image.push=true  -Dquarkus.container-image.registry=our.docker.registry:5000` a native container image gets built and pushed to the docker registry.

### Actual behavior

The container image neither gets built, nor it is tried to push a image to the docker registry.

### Output of `uname -a` or `ver`

Linux jenkins-slave 5.4.0-96-generic #109-Ubuntu SMP Wed Jan 12 16:49:16 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.13" 

### Quarkus version or git rev

2.7.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3

**Comment by geoand** [comment]
Please attach a sample project that exhibits the problematic behavior as I was not able to reproducer it.

**Comment by grubermi** [comment]
I have shrinked our current project to the absolute essential, that is required to reproduce the behaviour in the attached file.
[Dummy.zip](https://github.com/quarkusio/quarkus/files/8114523/Dummy.zip)
The command that I am executing is `mvn clean package -Pnative -Dquarkus.native.container-build=true -Dquarkus.container-image.push=true -Dquarkus.container-image.registry=our.docker.registry:5000 `.
If i change the quarkus-version to 2.6.1.Final in this dummy project everything works as expected.

**Comment by geoand** [comment]
Fixed by https://github.com/quarkusio/quarkus/pull/23861

**Comment by grubermi** [comment]
We just updated the Quarkus-version in our project to 2.7.3.Final, but we are still facing the same behaviour: The container-image is neighter built nor pushed. This also happens, when I build the attached Dummy-project with version 2.7.3.Final. 
Am I doing something wrong?
@geoand Could you please take a look at this again?

**Comment by geoand** [comment]
You are absolutely right.

The fix was only done for JVM build, not native 🤦🏼 .

https://github.com/quarkusio/quarkus/pull/24159 fixes the native build as well.
