### ISSUE TITLE
Distinct ObjectMappers for RestEasy Reactive / RestEasy Reactive Client

### ISSUE THREAD

**Issue by chonton** [quarkusio/quarkus#23979]
### Description

Quarkus allows a program to use specify a custom Jackson ObjectMapper by using CDI producer method or customize the ObjectMapper with ObjectMapperCustomizer instances.

I need to have different behaviors for RestEasy Reactive Client use and RestEasy Reactive use. Specifically, I want the service implementation to be set with .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, true) and the client to have .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)

### Implementation ideas

Perhaps annotate the CDI producer method and the ObjectMapperCustomizer(s) with with a new qualifier:

```java
package io.quarkus.jackson.runtime;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
import javax.inject.Qualifier;
import javax.ws.rs.RuntimeType;

@Qualifier
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.METHOD, ElementType.FIELD, ElementType.PARAMETER, ElementType.TYPE})
public @interface ObjectMapperUse {
  RuntimeType value();
}
```

How much backwards compatibility is required?  Is there a fallback to unqualified producer if qualified producer is unavailable?

**Comment by manofthepeace** [comment]
Hi I have a need in my application that would need an even more broader solution that the one proposed in the PR. I was playing it it myself but could not make it work. I would be nice if in fact any Jax-rs resource could have it's own ObjectMapper, on demand.

In my, again, special case. I have 2 rests clients, and both are from different hosts. One returns time in a long format (millis), the other in a ISO string.

Jackson does not support out of the box long millis --> zoneddatetime so we wrote out custom deserializer for it, we need to register it as a module, so it can be a bean, so we can inject in it. But since we register our own, we break the one from the JavaTimeModule, which works for the other api.

I was looking at his answer on stackoverflow https://stackoverflow.com/a/63542422 which for me would solve all the case, but unfortunately I cannot make it work.

Having something like this, as a registered provider, would I think solve all the cases I can think of. In my case, the getContext() is never called, so it does not work.. I think having that working, would fix the case from @chonton and mine as well. A jax-rs server that needs a special ObjectMapper could have it this way, multiple could have multiple if really needed, and the same for jax-rs client, could use the default, of the one in the provider context if any. An application can have any number of rest client, so having `@ClientObjectMapper` makes little sense to me unfortunately, since any hosts can have their own format/needs. I know ObjectMapper is heavy, but in my case I would need 1 for quarkus, 2 for rest clients.

```
public class ClientObjectMapper1 implements ContextResolver<ObjectMapper> {

    @Named("clientMapper1")
    @Inject
    ObjectMapper mapper;

    @Override
    public ObjectMapper getContext(Class<?> type) {
        return mapper;
    }
}
```

**Comment by hamburml** [comment]
@manofthepeace The stackoverflow answer does work with the rest-client dependency but sadly not with rest-client-reactive :(

**Comment by westarne** [comment]
Seems like this is related to a problem we encountered. We initially created an issue about ObjectMappers not being specific for the clients https://github.com/quarkusio/quarkus/issues/26152 that was seemingly resolved with https://github.com/quarkusio/quarkus/pull/27203.

But we now noticed that it is not resolved or not working when using `quarkus-resteasy-reactive-jackson` in addition to the `quarkus-rest-client-reactive-jackson`.

If you setup a base project in which [this test](https://github.com/Sgitario/quarkus/blob/d9a9b55d9e7147d6578677daae07f619bacfbfc0/integration-tests/rest-client-reactive/src/test/java/io/quarkus/it/rest/client/ClientWithCustomObjectMapperTest.java) succeeds (using `quarkus-rest-client-reactive-jackson`) and then add `quarkus-resteasy-reactive-jackson` as a dependency, the test fails since the whole ObjectMapper resolving from the context is not called anymore.

Otherwise I think this could be the solution to your problem.

**Comment by geoand** [comment]
Not yet.

We'll see what we can do for Quarkus 3.1

**Comment by Sgitario** [comment]
I don't follow what is missing here. After https://github.com/quarkusio/quarkus/pull/31422 is fixed, we should be able to configure different object mappers by distinct clients and the server. I've written a test case to ensure this is working: https://github.com/quarkusio/quarkus/pull/31711

**Comment by geoand** [comment]
I still don't like the fact that we need a ContextResolver to do this. Ideally we would have a CDI qualifier that would allow users to specify the ObjectMapper that could apply to all or some of the REST Client objects.

It's something I'll look into when I have more time (post Quarkus 3.0 most likely), so let's leave this open

**Comment by chonton** [comment]
@geoand Quarkus 3.2.1 has been released... Do you have time to look at this?

**Comment by geoand** [comment]
I do want to revisit this for sure!

But it will probably be in September or so

**Comment by geoand** [comment]
We actually sort of have a way to do this currently that was introduced in https://github.com/quarkusio/quarkus/pull/27203.

@Sgitario as `ContextResolver` is an API that is non-intuitive to use, I wonder if should introduce one or all of the following:

* A config property (both per client and global) that will allow users to specify some kind of resolver for `ObjectMapper `
* An annotation for the same
* A method in `QuarkusRestClientBuilder`

WDYT?

**Comment by Sgitario** [comment]
> We actually sort of have a way to do this currently that was introduced in #27203.
> 
> @Sgitario as `ContextResolver` is an API that is non-intuitive to use, I wonder if should introduce one or all of the following:
> 
> * A config property (both per client and global) that will allow users to specify some kind of resolver for `ObjectMapper `
> * An annotation for the same
> * A method in `QuarkusRestClientBuilder`
> 
> WDYT?

ObjectMapper only makes sense when using the Jackson dependency, so I'm reluctant to add a method for this in `QuarkusRestClientBuilder` or via config properties which are meant for general-purpose usage only. 

Even though we could probably add a config property only for the REST Client Jackson property, I think adding an annotation for this is the way to go.

**Comment by geoand** [comment]
> ObjectMapper only makes sense when using the Jackson dependency, so I'm reluctant to add a method for this in QuarkusRestClientBuilder or via config properties which are meant for general-purpose usage only.

Really good point.

> Even though we could probably add a config property only for the REST Client Jackson property, I think adding an annotation for this is the way to go.

Yeah, my only issue is that one would need to add the annotation to every REST Client, which is why I proposed the globalk config property.

**Comment by Sgitario** [comment]
> > ObjectMapper only makes sense when using the Jackson dependency, so I'm reluctant to add a method for this in QuarkusRestClientBuilder or via config properties which are meant for general-purpose usage only.
> 
> Really good point.
> 
> > Even though we could probably add a config property only for the REST Client Jackson property, I think adding an annotation for this is the way to go.
> 
> Yeah, my only issue is that one would need to add the annotation to every REST Client, which is why I proposed the global config property.

I will work on this (annotation + global property) in a couple of days.

**Comment by geoand** [comment]
🙏🏼

**Comment by geoand** [comment]
An alternative to the annotation would be to have a `default` or `static` method on the interface which could produce the `ObjectMapper` (given the global Quarkus one).

**Comment by Sgitario** [comment]
I started looking into this and let's try first to put all the options here to better decide how to proceed.

At the moment, we can only provide ObjectMappers via ContextResolvers.

This is an example of usage for a single client:

```java
    @Path("/server")
    @Produces(MediaType.APPLICATION_JSON)
    @RegisterProvider(MyCustomObjectMapper.class)
    public interface MyClient {
        @GET
        Request get();
    }

   public static class MyCustomObjectMapper implements ContextResolver<ObjectMapper> {

        @Override
        public ObjectMapper getContext(Class<?> type) {
            return new ObjectMapper();
        }
    }
```

Or how to use it for all the clients and/or servers (we can use the `@ConstrainedTo` annotation to mark the usage for client or server only):

```java
   @Provider
   public static class MyCustomObjectMapper implements ContextResolver<ObjectMapper> {

        @Override
        public ObjectMapper getContext(Class<?> type) {
            return new ObjectMapper();
        }
    }
```

Let's now enumerate the options we have:

- OPTION A: add a new annotation for ObjectMappers only:

```java
    @Path("/server")
    @Produces(MediaType.APPLICATION_JSON)
    @ObjectMapper(MyCustomObjectMapper.class)
    public interface MyClient {
        @GET
        Request get();
    }

   public class MyCustomObjectMapper implements ObjectMapperSupplier {

        @Override
        public ObjectMapper get() {
            return new ObjectMapper();
        }
    }
```

Note that the interface `ObjectMapperSupplier` is simply a `public interface ObjectMapperSupplier extends Supplier<ObjectMapper>`. 

The new annotation `@ObjectMapper` could also be used for the server. 
Internally, it would wrap the provided object mapper instance into the context resolver, so we could reuse most of the existing code and also be compatible with existing APIs like `Providers`. 

To apply an ObjectMapper to multiple clients, we could allow using:

```java
   @ObjectMapper
   @ConstrainedTo(RuntimeType.CLIENT)
   public class MyCustomObjectMapper implements ObjectMapperSupplier {

        @Override
        public ObjectMapper get() {
            return new ObjectMapper();
        }
    }
```

- OPTION B: have a `default` or `static` method on the interface

```java
    @Path("/server")
    @Produces(MediaType.APPLICATION_JSON)
    public interface MyClient {
        @GET
        Request get();

        default ObjectMapper customObjectMapper() {
           return new ObjectMapper();
        }
    }
```

Internally, it would work as option A (annotations) and the advantage is that users would not need to learn about new annotations. 

The disadvantage is that does not resolve the fact that we can't apply the custom object mapper for multiple clients.

**NOTE:** I don't see any options to provide the custom object mapper via properties because, at the moment, there are no properties only related to jackson, but for the extensions (jaxb, jackson, jsonb). 

@geoand wdyt? I even see options A and B are compatible with each other, though I see option A is more user-friendly. Also, If you see other options, even including properties, let me know.

**Comment by geoand** [comment]
First of all, I think that none of the options should affect the server, it's far more likely in real applications that the client will need customizations (as it communicates with systems outside the developer's control).

As for which option is better, I think we need to think about the case where an application has multiple rest clients and potentially needs to have a different mapper for each one. In that case, which option makes things easier? Probably B.
Also, I would like us to be able to give the user the original ObjectMapper, so they can call `copy` (if they so choose) thus inheriting all the settings of the default one.

**Comment by Sgitario** [comment]
> As for which option is better, I think we need to think about the case where an application has multiple rest clients and potentially needs to have a different mapper for each one. In that case, which option makes things easier? Probably B. 

Also, there are already existing use cases that use the same mechanism (for ex: to provide custom exception mappers).

> Also, I would like us to be able to give the user the original ObjectMapper, so they can call `copy` (if they so choose) thus inheriting all the settings of the default one.

This can be done in both options. 

> First of all, I think that none of the options should affect the server, it's far more likely in real applications that the client will need customizations (as it communicates with systems outside the developer's control).
> 

Yet, users that want all the clients to use a custom object mapper would need to provide it using:

```java
   @Provider
   @ConstrainedTo(RuntimeType.CLIENT)
   public static class MyCustomObjectMapper implements ContextResolver<ObjectMapper> {

        @Override
        public ObjectMapper getContext(Class<?> type) {
            return new ObjectMapper();
        }
    }
```

Actually, I would need to verify we can do this, but it would simply be a matter of documenting this use case. 

In conclusion, let's go for option B + documenting the case users want to apply the same object mapper for all the clients. We can always implement option A in the future if and only if needed/requested. Are you ok with this?

**Comment by geoand** [comment]
> Yet, users that want all the clients to use a custom object mapper would need to provide it using:

I really don't want users to have to use `@ConstrainedTo(RuntimeType.CLIENT)` for this. I really want the feature limited to the client only :)

**Comment by geoand** [comment]
> In conclusion, let's go for option B + documenting the case users want to apply the same object mapper for all the clients. We can always implement option A in the future if and only if needed/requested. Are you ok with this?

+1
