### ISSUE TITLE
ReactiveClientHeadersFactory ignores rest-client @Produces headers

### ISSUE THREAD

**Issue by herasimau** [quarkusio/quarkus#24054]
### Describe the bug

When i use `@RegisterClientHeaders(ReactiveHeaderFactory.class) `
`public class ReactiveHeaderFactory extends  ReactiveClientHeadersFactory`

The Annotation `@Produces(MediaType.APPLICATION_OCTET_STREAM) `
in rest-client is ignored and expected headers are not injected.

The detail of error:
1. Endpoint exposed with Resteasy that consumes application/json:
    `@GET
      @Consumes(MediaType.APPLICATION_JSON)
    `
2. After i execute rest-client(with reactive-headers) call where i cannot see 
expected headers injected by `@Produces(MediaType.APPLICATION_OCTET_STREAM) `

If i remove `@RegisterClientHeaders(ReactiveHeaderFactory.class) ` the headers are injected as exptected.

I have created the sample project where you can simulate the issue (to speed-up you can inside the project [mockoon](https://mockoon.com/) environment and [postman](https://www.postman.com/) collection)

### Expected behavior

When i use `ReactiveClientHeadersFactory` with rest-client
i expect that `@Produces(MediaType.APPLICATION_OCTET_STREAM)`
will include necessary headers

### Actual behavior

When i use `ReactiveClientHeadersFactory` with rest-client
i expect that `@Produces(MediaType.APPLICATION_OCTET_STREAM)`
will include necessary headers but they are not present

### How to Reproduce?

Checkout project https://github.com/herasimau/quarkus-reactiv-header-problem

Import postman collection
Import mockoon environment 
Start quarkus

Run postman end-points:

- http://localhost:9084/header/without-reactive-headers - WORKS
- http://localhost:9084/header/with-reactive-headers - DOESN'NT WORKS

### Output of `uname -a` or `ver`

Darwin Leanids-MacBook-Pro.local 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "11.0.14" 2022-01-18 OpenJDK Runtime Environment GraalVM CE 22.0.0.2 (build 11.0.14+9-jvmci-22.0-b05)

### Quarkus version or git rev

2.7.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d) Maven home: /opt/homebrew/Cellar/maven/3.8.1

**Comment by michalszynkiewicz** [comment]
How do I run this mockoon? 

I created a test like this in the project and I see the accept header is printed
```java
package com.quarkus;

import io.quarkus.test.junit.QuarkusTest;
import org.eclipse.microprofile.rest.client.inject.RestClient;

import javax.ws.rs.GET;
import javax.ws.rs.HeaderParam;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import java.util.concurrent.ExecutionException;

@QuarkusTest
public class Test {

    @RestClient
    ServiceWithoutReactiveHeaders clientWoHeaders;
    @RestClient
    ServiceWithReactiveHeaders clientWHeaders;

    @org.junit.jupiter.api.Test
    void shouldPassAccept() throws ExecutionException, InterruptedException {
        clientWHeaders.getOctet().subscribe().asCompletionStage().get();
    }

    @org.junit.jupiter.api.Test
    void shouldPassAccept2() throws ExecutionException, InterruptedException {
        clientWoHeaders.getOctet().subscribe().asCompletionStage().get();
    }

    @Path("/octet")
    public static class Resource {

        @GET
        @Produces(MediaType.APPLICATION_OCTET_STREAM)
        public String get(@HeaderParam("Accept") String accept,
                          @HeaderParam("Token") String token) {
            System.out.println("accept: " + accept);
            System.out.println("token: " + token);
            return "foo";
        }
    }
}

```

**Comment by herasimau** [comment]
Hi @michalszynkiewicz,

Thanks for your response, 
i have simplified  by including LocalOctetResource instead of mockoon, so to replicate the issue:

1. git pull
2. start quarkus
3. Execute curl that will fail
```
curl --location --request GET 'http://localhost:9084/header/with-reactive-headers' \
--header 'Accept: application/json'
```
4. Execute curl that will work
```
curl --location --request GET 'http://localhost:9084/header/without-reactive-headers' \
--header 'Accept: application/json'
```

**Comment by michalszynkiewicz** [comment]
wireshark suggests it's actually headers from the initiating call that get passed, weird, I'll continue looking into it

**Comment by michalszynkiewicz** [comment]
the PR linked above should fix it.
With it, if you change `getHeaders` in your factory to sth like this it will work as you expect:
```java
  @Override
  public Uni<MultivaluedMap<String, String>> getHeaders(MultivaluedMap<String, String> incomingHeaders) {
    MultivaluedMap<String, String> map = new MultivaluedTreeMap<>();
    map.putSingle("Token", "MyHeader");
    return Uni.createFrom().item(map);
  }
```

**Comment by herasimau** [comment]
Hi @michalszynkiewicz , i have updated example project with your suggestion,
but unfortunately it still fails, to replicate just make `git pull` and retry the curl's, thanks!

**Comment by michalszynkiewicz** [comment]
I'll change the signature of the method in this PR, sorry for the inconvenience. It will also get the headers that come from `@HeaderParam`, etc as a parameter.
