### ISSUE TITLE
quarkus application can't reach consul server. Openshift scenario

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#24277]
### Describe the bug

Application code: https://github.com/quarkus-qe/quarkus-test-framework/tree/main/examples/consul

When I try to deploy a Quarkus application that uses `consul` over OCP 4.9, I am getting the following error:

```
16:03:32,789 INFO  [app] Mar 11, 2022 3:03:30 PM io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider
16:03:32,789 INFO  [app] WARN: Default DNS servers: [/2001:4860:4860:0:0:0:0:8888:53, /2001:4860:4860:0:0:0:0:8844:53] (Google Public DNS as a fallback)
16:03:32,789 INFO  [app] Mar 11, 2022 3:03:30 PM io.quarkus.runtime.ApplicationLifecycleManager run
16:03:32,789 INFO  [app] ERROR: Failed to start application (with profile prod)
16:03:32,790 INFO  [app] java.net.SocketException: Network is unreachable
16:03:32,790 INFO  [app]        at java.base/sun.nio.ch.DatagramChannelImpl.send0(Native Method)
16:03:32,790 INFO  [app]        at java.base/sun.nio.ch.DatagramChannelImpl.sendFromNativeBuffer(DatagramChannelImpl.java:587)
16:03:32,790 INFO  [app]        at java.base/sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:549)
16:03:32,790 INFO  [app]        at java.base/sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:532)
16:03:32,791 INFO  [app]        at io.netty.channel.socket.nio.NioDatagramChannel.doWriteMessage(NioDatagramChannel.java:296)
16:03:32,791 INFO  [app]        at io.netty.channel.nio.AbstractNioMessageChannel.doWrite(AbstractNioMessageChannel.java:143)
16:03:32,791 INFO  [app]        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:931)
16:03:32,791 INFO  [app]        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:354)
16:03:32,792 INFO  [app]        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:895)
16:03:32,792 INFO  [app]        at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)
16:03:32,792 INFO  [app]        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
16:03:32,792 INFO  [app]        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:742)
16:03:32,793 INFO  [app]        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:728)
16:03:32,793 INFO  [app]        at io.netty.channel.DefaultChannelPipeline.flush(DefaultChannelPipeline.java:967)
16:03:32,793 INFO  [app]        at io.netty.channel.AbstractChannel.flush(AbstractChannel.java:254)
16:03:32,793 INFO  [app]        at io.netty.resolver.dns.DnsNameResolver.flushQueries(DnsNameResolver.java:1257)
16:03:32,793 INFO  [app]        at io.netty.resolver.dns.DnsResolveContext.internalResolve(DnsResolveContext.java:361)
16:03:32,794 INFO  [app]        at io.netty.resolver.dns.DnsResolveContext.doSearchDomainQuery(DnsResolveContext.java:284)
16:03:32,794 INFO  [app]        at io.netty.resolver.dns.DnsAddressResolveContext.doSearchDomainQuery(DnsAddressResolveContext.java:96)
16:03:32,794 INFO  [app]        at io.netty.resolver.dns.DnsResolveContext.resolve(DnsResolveContext.java:249)
16:03:32,794 INFO  [app]        at io.netty.resolver.dns.DnsNameResolver.doResolveAllUncached0(DnsNameResolver.java:1158)
16:03:32,795 INFO  [app]        at io.netty.resolver.dns.DnsNameResolver.doResolveAllUncached(DnsNameResolver.java:1131)
16:03:32,795 INFO  [app]        at io.netty.resolver.dns.DnsNameResolver.doResolveUncached(DnsNameResolver.java:1033)
16:03:32,795 INFO  [app]        at io.netty.resolver.dns.DnsNameResolver.doResolve(DnsNameResolver.java:975)
16:03:32,796 INFO  [app]        at io.netty.resolver.dns.DnsNameResolver.doResolve(DnsNameResolver.java:812)
16:03:32,797 INFO  [app]        at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
16:03:32,797 INFO  [app]        at io.netty.resolver.dns.InflightNameResolver.resolve(InflightNameResolver.java:100)
16:03:32,798 INFO  [app]        at io.netty.resolver.dns.InflightNameResolver.resolve(InflightNameResolver.java:66)
16:03:32,798 INFO  [app]        at io.netty.resolver.dns.InflightNameResolver.resolve(InflightNameResolver.java:51)
16:03:32,798 INFO  [app]        at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
16:03:32,799 INFO  [app]        at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
16:03:32,799 INFO  [app]        at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
16:03:32,799 INFO  [app]        at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
16:03:32,800 INFO  [app]        at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:162)
16:03:32,800 INFO  [app]        at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:139)
16:03:32,800 INFO  [app]        at io.vertx.core.net.impl.ChannelProvider.handleConnect(ChannelProvider.java:154)
16:03:32,801 INFO  [app]        at io.vertx.core.net.impl.ChannelProvider.connect(ChannelProvider.java:104)
16:03:32,801 INFO  [app]        at io.vertx.core.net.impl.ChannelProvider.connect(ChannelProvider.java:90)
16:03:32,801 INFO  [app]        at io.vertx.core.net.impl.NetClientImpl.connectInternal(NetClientImpl.java:247)
16:03:32,801 INFO  [app]        at io.vertx.core.net.impl.NetClientImpl.lambda$connectInternal$5(NetClientImpl.java:267)
16:03:32,802 INFO  [app]        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
16:03:32,802 INFO  [app]        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
16:03:32,802 INFO  [app]        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
16:03:32,802 INFO  [app]        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
16:03:32,803 INFO  [app]        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
16:03:32,803 INFO  [app]        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
16:03:32,803 INFO  [app]        at java.base/java.lang.Thread.run(Thread.java:829)
```
The same scenario use to work as expected with Quarkus 2.2.5.Final

Could be related to: https://github.com/quarkusio/quarkus/issues/23519
I didn't see any note in the migration guide, related to consul: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.7

### How to Reproduce?

Project: `git clone git@github.com:quarkus-qe/quarkus-test-framework.git`
cmd: ` mvn clean verify -Pexamples -pl examples/consul -Dopenshift -Dit.test=OpenShiftGreetingResourceIT`

Note: you need to be logged into an Openshift in order to run this test. 

### Output of `java -version`

JDK 11/17

### Quarkus version or git rev

Quarkus 2.7.0.Final and above

### Additional information

Works as expected with Quarkus 2.6.3.Final and lower versions

**Comment by gsmet** [comment]
@cescoffier didn't we get rid of this behavior:

> 16:03:32,789 INFO  [app] WARN: Default DNS servers: [/2001:4860:4860:0:0:0:0:8888:53, /2001:4860:4860:0:0:0:0:8844:53] (Google Public DNS as a fallback)

**Comment by geoand** [comment]
It likely worked in 2.x because IIRC, it was the extension was not using the Vert.x client back then

**Comment by cescoffier** [comment]
Which extension is it used to connect to Consul? It's likely wrong. I fixed the Vault extension but did nothing around Consul.

**Comment by geoand** [comment]
I'll look at fixing the consul extension in the same way

**Comment by geoand** [comment]
https://github.com/quarkiverse/quarkus-config-extensions/pull/58 should fix the issue

**Comment by fedinskiy** [comment]
Which version of Quarkus will contain this fix? The issue still can be reproduced for 2.7.5.Final

**Comment by rsvoboda** [comment]
https://github.com/quarkiverse/quarkus-config-extensions/commits/1.0.2 contains `Disable the async DNS resolver when starting the Vert.x instance` commit

**Comment by geoand** [comment]
Thanks @rsvoboda. Wasn't at my machine
