### ISSUE TITLE
REST clients are documented in Open API and clients with the same path as controllers cause incorrect Open API documentation for the controllers

### ISSUE THREAD

**Issue by josephearl** [quarkusio/quarkus#24412]
### Describe the bug

I have a controller as follows:

```
@ApplicationScoped
@Path("/api/v1/foos")
@AllArgsConstructor
public class FooController {
  private final FooClient fooClient;

  @GET
  @Produces(MediaType.APPLICATION_JSON)
  @APIResponses(
      value = {
        @APIResponse(
            responseCode = "200",
            description = "Foos",
            content = @Content(schema = @Schema(implementation = FoosResponse.class))),
        @APIResponse(responseCode = "500", description = "Unexpected error"),
      })
  public FoosResponse getFoos(
      @QueryParam("page") @DefaultValue("0") int page,
      @QueryParam("limit") @DefaultValue("50") int limit) {
    return foosClient.getFoos(page, limit);
  }
}
```

where `FooClient` is:

```
public interface FooClient {
  FoosResponse getFoos(int page, int limit);
}
```

The Open API documentation is correctly displayed in Swagger UI.

![1-only-controller](https://user-images.githubusercontent.com/2513147/159031359-7668ac1c-f8ee-4c99-9df2-c30fb25c1995.png)

If I add the JAX RS annotations to `FooClient` as follows:

```
@Path("/api/v1")
@RegisterRestClient(configKey = "foo")
public interface FooClient {
  @GET
  @Path("/foos")
  @Produces(MediaType.APPLICATION_JSON)
  FoosResponse getFoos(int page, int limit);
}
```

Then it replaces the Open API documentation from my controller and adds a body (of type $int32) to the GET request which makes the Swagger UI unusable (actually it seems to be merging them? the query parameter defaults are only defined on the controller).

![2-rest-client-controller-same-paths](https://user-images.githubusercontent.com/2513147/159031279-289737f9-dfbb-4f2d-b168-1f6e37cfef97.png)

I've noticed if I change the path on the rest client to be `/bars` so it is not the same as the controller then the API documentation for my controller is correct, but the rest client is shown in the API documentation under a `default` heading.

![3-rest-client-controller-different-paths](https://user-images.githubusercontent.com/2513147/159031312-7b5c0959-fd67-4464-8767-44be4dcd626f.png)

(NB: screenshots are from 2.7.4.Final but I tested with 2.7.5.Final as well and got the same results)

### Expected behavior

REST clients are not documented in the Open API documentation. They are not a public interface.

If a REST client and a controller have the same path, the API documentation for the controller should not be affected.

### Actual behavior

REST clients are documented in the Open API documentation.

If a REST client and a controller have the same path, the API documentation for the controller is affected.

### Output of `uname -a` or `ver`

Darwin Josephs-MacBook-Pro.local 20.6.0 Darwin Kernel Version 20.6.0: Tue Oct 12 18:33:42 PDT 2021; root:xnu-7195.141.8~1/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18

### Quarkus version or git rev

2.7.5.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.4.1

**Comment by gsmet** [comment]
Can you try to override the `smallrye-openapi` version to `2.1.22` in your project and see how it goes?

We had a similar report and things should be fixed in this version.

**Comment by josephearl** [comment]
I tried that @gsmet but it did not fix or improve anything

I changed `enforcedPlatform` to `platform` for the Quarkus platform and added:

```
implementation('io.smallrye:smallrye-open-api-core') {
  version { strictly '2.1.22' }
}
```

And it seems to have worked overriding the version:

```
./gradlew -q dependencies --configuration quarkusDev | grep smallrye-open-api
+--- io.smallrye:smallrye-open-api-core:{strictly 2.1.22} -> 2.1.22
|    +--- io.smallrye:smallrye-open-api-core:2.1.21 -> 2.1.22 (c)
|    +--- io.smallrye:smallrye-open-api-core:2.1.21 -> 2.1.22 (*)
```

**Comment by gsmet** [comment]
Could you prepare a small reproducer?

**Comment by josephearl** [comment]
Here you go @gsmet https://github.com/josephearl/quarkus-24412

**Comment by josephearl** [comment]
OK so it looks the issue is because I have another bean `FakeFooClient` for testing which implements `FooClient`:

```
@Named("fake")
@ApplicationScoped
public class FakeFooClient implements FooClient {
  @Override
  public FoosResponse getFoos(int page, int limit) {
    return new FoosResponse("fakefoo1, fakefoo2");
  }
}
```

and that is causing the documentation issue

If I refactor it to move the annotations out of that `FooClient` interface:

* `FooClient` - just the method definition, no annotations
* `FakeFooClient implements FooClient` - as before
* `RestFooClient extends FooClient` - adds the REST client annotations to the method

**Comment by phillip-kruger** [comment]
Can you try with the latest snapshot ? I think this might be fixed

**Comment by MikeEdgar** [comment]
@josephearl you might also try using `mp.openapi.scan.exclude.classes` to exclude the `FakeFooClient`.

**Comment by josephearl** [comment]
@MikeEdgar thanks your suggestion worked

@phillip-kruger I did try using the latest snapshot with but this gave me a build error:

```
Execution failed for task ':quarkusDev'.
> 'void io.quarkus.deployment.dev.DevModeContext$ModuleInfo.<init>(io.quarkus.bootstrap.model.AppArtifactKey, java.lang.String, java.lang.String, java.util.Set, java.lang.String, java.lang.String, java.lang.String, java.util.Set, java.lang.String, java.lang.String)'

Caused by: java.lang.NoSuchMethodError: 'void io.quarkus.deployment.dev.DevModeContext$ModuleInfo.<init>(io.quarkus.bootstrap.model.AppArtifactKey, java.lang.String, java.lang.String, java.util.Set, java.lang.String, java.lang.String, java.lang.String, java.util.Set, java.lang.String, java.lang.String)'
        at io.quarkus.gradle.tasks.QuarkusDev.addLocalProject(QuarkusDev.java:395)
```

**Comment by josephearl** [comment]
Happy for this to be closed given @MikeEdgar's suggestion worked

**Comment by phillip-kruger** [comment]
Great ! Thanks @MikeEdgar , thanks @josephearl !
