### ISSUE TITLE
Async Events behave inconsistently on Exceptions

### ISSUE THREAD

**Issue by JHahnHRO** [quarkusio/quarkus#24646]
### Describe the bug

If an event is fired (and observed) asynchronously, the returned CompletionStage behaves differently in the case of exceptions depending on the number of observers that threw exceptions. This violates the [CDI Spec, 10.5.1](https://jakarta.ee/specifications/cdi/3.0/jakarta-cdi-spec-3.0.html#async_exception).

### Expected behavior

Both test methods should be green.

### Actual behavior

The test case  `testSingleFailure` fails, because the `CompletionStage` contains the `IllegalArgumentException` directly instead of a `CompletionException` containing the `IllegalArgumentException` as the spec requires.

```
java.lang.AssertionError: 
Expecting actual throwable to be an instance of:
  java.util.concurrent.CompletionException
but was:
  java.lang.IllegalArgumentException
	at com.example.EventTest$Observer1.failOn42And47(EventDecoratorTest.java:71)
	at com.example.EventTest_Observer1_Observer_failOn42And47_df18bd4f87120ec5a98ebc09b259d85482e10edc.notify(Unknown Source)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:320)
	...(10 remaining lines not displayed - this can be changed with Assertions.setMaxStackTraceElementsDisplayed)

	at com.example.EventTest.testSingleFailure(EventDecoratorTest.java:43)
```

### How to Reproduce?

```
// imports

@QuarkusTest
class EventTest {

    @Inject
    Observer1 observer1;

    @Inject
    Observer2 observer2;

    @Inject
    Event<Integer> event;

    @Test
    void testSingleFailure() throws InterruptedException, TimeoutException {
        final CompletionStage<Integer> stage = event.fireAsync(42);

        try {
            stage.toCompletableFuture().get(30, TimeUnit.SECONDS);
            failBecauseExceptionWasNotThrown(ExecutionException.class);
        } catch (ExecutionException ex) {
            assertThat(ex.getCause()).isInstanceOf(CompletionException.class)
                    .extracting(Throwable::getSuppressed, as(ARRAY))
                    .hasSize(1)
                    .hasAtLeastOneElementOfType(IllegalArgumentException.class);
        }
    }

    @Test
    void testTwoFailures() throws InterruptedException, TimeoutException {
        final CompletionStage<Integer> stage = event.fireAsync(47);

        try {
            stage.toCompletableFuture().get(30, TimeUnit.SECONDS);
            failBecauseExceptionWasNotThrown(ExecutionException.class);
        } catch (ExecutionException ex) {
            assertThat(ex.getCause()).isInstanceOf(CompletionException.class)
                    .extracting(Throwable::getSuppressed, as(ARRAY))
                    .hasSize(2)
                    .hasAtLeastOneElementOfType(IllegalArgumentException.class)
                    .hasAtLeastOneElementOfType(IllegalStateException.class);
        }
    }

    @ApplicationScoped
    static class Observer1 {

        void failOn42And47(@ObservesAsync int value) {
            if (value == 42 || value == 47) {
                throw new IllegalArgumentException();
            }
        }
    }

    @ApplicationScoped
    static class Observer2 {

        void failOn47(@ObservesAsync int value) {
            if (value == 47) {
                throw new IllegalStateException();
            }
        }
    }
}
```

### Output of `java -version`

11.0.11, vendor: AdoptOpenJDK, runtime: C:\Program Files\AdoptOpenJDK\jdk-11.0.11.9-hotspot

### Quarkus version or git rev

2.7.5.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

**Comment by JHahnHRO** [comment]
I still think this is a bug, but I have found that Weld shows the same behaviour as Arc: https://issues.redhat.com/browse/WELD-2711

**Comment by mkouba** [comment]
I think that it actually behaves as defined. If you look at the javadoc of `CompletableFuture` you can read:
```
In case of exceptional completion with a CompletionException,
 * methods {@link #get()} and {@link #get(long, TimeUnit)} throw an
 * {@link ExecutionException} with the same cause as held in the
 * corresponding CompletionException.
```
So the cause is unwrapped.


I also think that the spec wording is a bit confusing. First of all, the section title is misleading: _"Handling **multiple** exceptions thrown during an asynchronous event"_ . The spec is clear that the `CompletionStage ` _"will complete exceptionally with `java.util.concurrent.CompletionException` exception"_. But then the next sentence only talks about plural: _"CompletionException contains all exceptions thrown by observers as suppressed exceptions."_. And the TCK seems to [test multiple exceptions](https://github.com/eclipse-ee4j/cdi-tck/tree/2.0.3.Final/impl/src/main/java/org/jboss/cdi/tck/tests/event/observer/async/handlingExceptions) as well.

I personally think that the current behavior makes sense because suppressed exceptions are designed for cases where multiple exceptions occur and only one can be propagated.

**Comment by manovotn** [comment]
So Arc appears to behave slightly differently (compared to Weld) and IMO incorrectly in that it skips aggregation under `CompletionException` when there is only one exception thrown. We should fix that.

**Comment by JHahnHRO** [comment]
Oh, so my Test using CompletableFuture was confusing the matter. If I rewrite them to this:
```

    @Test
    void testSingleFailure() throws InterruptedException {
        BlockingQueue<Throwable> output = new ArrayBlockingQueue<>(1);
        event.fireAsync(42).whenComplete((integer, throwable) -> {
            output.offer(throwable);
        });

        assertThat(output.poll(30, TimeUnit.SECONDS)).isNotNull()
                .isInstanceOf(CompletionException.class)
                .extracting(Throwable::getSuppressed, as(ARRAY))
                .hasSize(1)
                .hasAtLeastOneElementOfType(IllegalArgumentException.class);
    }

    @Test
    void testTwoFailures() throws InterruptedException {
        BlockingQueue<Throwable> output = new ArrayBlockingQueue<>(1);
        event.fireAsync(47).whenComplete((integer, throwable) -> {
            output.offer(throwable);
        });

        assertThat(output.poll(30, TimeUnit.SECONDS)).isNotNull()
                .isInstanceOf(CompletionException.class)
                .extracting(Throwable::getSuppressed, as(ARRAY))
                .hasSize(2)
                .hasAtLeastOneElementOfType(IllegalArgumentException.class)
                .hasAtLeastOneElementOfType(IllegalStateException.class);
    }
```

It seems that Weld makes the test cases green, but Arc still fails `testSingleFailure`

**Comment by manovotn** [comment]
> It seems that Weld makes the test cases green, but Arc still fails testSingleFailure

Yep, that's what I am saying.
We'll fix it in Arc and I'll close the Weld issue.
