### ISSUE TITLE
smallrye.mutiny.TimeoutException when trying to connect to redis in Sentinel mode

### ISSUE THREAD

**Issue by srigano** [quarkusio/quarkus#24694]
### Describe the bug

I'm using quarkus 2.7.5.Final.
With redis client, In standalone mode, it works fine:

![image](https://user-images.githubusercontent.com/43664834/161269441-0d128e81-ce3d-4286-ad90-90a41a71ffff.png)

but in sentinel mode it doesn't work:

![image](https://user-images.githubusercontent.com/43664834/161269781-7e32d89c-33d8-444f-b3a6-000cd24f7c80.png)

i think this issue could come from the value of quarkus.redis.hosts variable.

I actually put this value : 
quarkus.redis.hosts=redis://[IP]:8001

At this point, quarkus doesn't know my database Name.

in the help page, i can read this =

![image](https://user-images.githubusercontent.com/43664834/161270801-267d3179-3b48-40f0-bfe6-532f6d626e1c.png)

but i think there is a mistake here: 
![image](https://user-images.githubusercontent.com/43664834/161270900-40b9c1d8-c438-4340-be58-6999dac3e71a.png)

if i put my databasename like this:

quarkus.redis.hosts=redis://[IP]:8001/MYDBNAME

i got a FormatNumberException.

this error seems to be normal, because in the vertx Redis Client documentation (https://vertx.io/docs/vertx-redis-client/java/#_connecting_to_redis) we can see this:

![image](https://user-images.githubusercontent.com/43664834/161271124-81d1cc31-3935-4a5b-8c34-58bf6efa1eba.png)

So the key is :be should not put  a database name, but a database number which is expected by the redis client...

Anyway even with a database number it doesn't work for me, I'm getting a timeout exception and I don't know why....

Thank you for you help

I put my code, juste below.
 

### How to Reproduce?

here is my code:

1. in my pom.xml file:
```
<dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-redis-client</artifactId>
</dependency>
```

2. in my resource file:
```
import javax.inject.Inject;
import javax.ws.rs.GET;
import javax.ws.rs.Path;

import fr.ca.cat.echeance.redis.RedisService;

@Path("/redis")
public class RedisResource {
	
    @Inject RedisService redisService;

    @GET
    @Path("/get")
    public String sentinel() {
        //redisService.set("blah", "blih");
        String result = redisService.get("blah");
        return result;
    }
}
```

3. in my service file:

```
@Singleton
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public class RedisService {

    @Inject RedisClient redisClient;   

    public String get(String key) {
        return redisClient.get(key).toString();
    }

    public void set(String key, String value) {
        redisClient.set(Arrays.asList(key, value));
    }

}
```

4. in my application.properties file, add (replace [IP_ADRESSE] by the good value):

#Redis 
quarkus.redis.hosts=redis://[IP_ADRESS]:8001
quarkus.redis.client-type=sentinel
quarkus.redis.password=mypass

### Output of `uname -a` or `ver`

linux

### Output of `java -version`

jdk 11

### Quarkus version or git rev

2.7.5.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn 3.8.2

**Comment by srigano** [comment]
Hi,
Anyone ?

**Comment by cescoffier** [comment]
The timeout indicate that it was not able to store the data within a 10s delay (I think that's the defailt(. 
We would need a proper reproducer indicating how you ran your redis.

**Comment by srigano** [comment]
I unfortunately don't have the hand to the redis cluster.
But I can run some config commands. I'm going to do that.

**Comment by srigano** [comment]
any idea ?

**Comment by cescoffier** [comment]
I believe this is fixed in https://github.com/quarkusio/quarkus/pull/26268

**Comment by srigano** [comment]
Hello,

This is not fixed.
I am using Quarkus 2.13.2. I tried to use the new Quarkus Redis Client API and also, the Vertx Redis Client API.
Both doesn't works.
I'm still gettings the same error.

Here is my application.properties:

`quarkus.redis.hosts=redis://x.x.x.x:8001/1,redis://y.y.y.y:8001/1,redis://z.z.z.z:8001/1
quarkus.redis.client-type=sentinel
quarkus.redis.password=${REDIS_PASSWORD}
quarkus.redis.master-name=${REDIS_DB_NAME}`

whats does mean the arg "db-number" ?

**Comment by srigano** [comment]
Here is my code:

RedisRessource:
`@Consumes(MediaType.APPLICATION_JSON)
@Produces(MediaType.APPLICATION_JSON)
@Path("/redis")
public class RedisResource {
    private static final Logger Log = Logger.getLogger(RedisResource.class);  

    @Inject RedisService redisService;

    @POST
    @Path("/add")
    public MyRedisObject add(MyRedisObject myRedisObject) {
        redisService.add(myRedisObject);
        return myRedisObject;
    }

    @GET
    @Path("/read/{key}")
    public String get(String key) {
        MyRedisObject myRedisObject = redisService.get(key);
        key = myRedisObject.getKey();
        return key;
    }`

RedisService:
`@ApplicationScoped
public class RedisService {

    
    @Inject RedisDataSource redisDataSource;
    @Inject RedisAPI redisAPI;

    private SetCommands<String, MyRedisObject> commands = null;

    public RedisService(RedisDataSource ds) {
        commands = redisDataSource.set(MyRedisObject.class);
    }

    public void add(MyRedisObject myRedisObject) {
        commands.sadd("key", myRedisObject);
    }

    public MyRedisObject get(String key) {
        MyRedisObject returnValue = commands.spop(key);
        return returnValue;

    }`

MyRedisObject:
`public class MyRedisObject {
    public String key; 
    public String value; 

    public MyRedisObject(String key, String value) {
        this.key = key;
        this.value = value;
    }

    public MyRedisObject() {
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }    `

-> doesn't work and i don't know what i'm doing wrong regarding to the documation...

**Comment by cescoffier** [comment]
How do you run your Redis in sentinel mode? 
Note that it seems that this mode is likely going to be replaced by the clustered mode.

**Comment by Ladicek** [comment]
I have no idea why the timeout should occur here, but I'd like to point out that until https://github.com/vert-x3/vertx-redis-client/pull/429 is merged and gets into Quarkus, sentinel users should always configure both `quarkus.redis.master-name` and `quarkus.redis.role`. They should default to the documented values, but that defaulting currently has a bug.

**Comment by geoand** [comment]
@Ladicek is there anything else that has to done about this one?

**Comment by Ladicek** [comment]
It is quite possible that the bug was caused by the Vert.x Redis client issue, which has been fixed, but I don't really know. I don't think we ever got a reproducer for this.

**Comment by geoand** [comment]
Gotcha, thanks.

Let's close then, and if this is still a problem, I would recommend folks to open a new issue (ideally with a reproducer)

**Comment by srigano** [comment]
I Will try again with the last 3.14 version.

Le ven. 20 sept. 2024, 13:13, Ladislav Thon ***@***.***> a
écrit :
