### ISSUE TITLE
"java.lang.RuntimeException: method call not supported" thrown when using Rest Client

### ISSUE THREAD

**Issue by dwamara** [quarkusio/quarkus#2657]
**Describe the bug**
When using the rest client to call another service, a "java.lang.RuntimeException: method call not supported" is thrown by the calling service

**Expected behavior**
Either a correct response should be returned (the called service has been successfully tested separately)

**Actual behavior**
A strange "java.lang.RuntimeException: method call not supported" is returned when making the call to the other service with the rest client.
```
2019-05-30 15:13:27,221 ERROR [io.und.request] (executor-thread-1) UT005023: Exception handling request to /gateway/checkers/register: java.lang.RuntimeException: method call not supported
	at io.smallrye.restclient.PartialResponse.notSupported(PartialResponse.java:72)
	at io.smallrye.restclient.PartialResponse.getEntity(PartialResponse.java:68)
	at org.jboss.resteasy.core.ExceptionHandler.unwrapException(ExceptionHandler.java:175)
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:104)
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:209)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:496)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:252)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:153)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:362)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:156)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:238)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:234)
	at io.quarkus.resteasy.runtime.ResteasyFilter.doFilter(ResteasyFilter.java:45)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
...
```

**To Reproduce**
1.  Create 2 rest services, one will have to call the other. The service called should return the JSON representation of an Object, not a simple String
2. Configure the rest client on one of the services to call the other
3. Call the service

**Configuration**
``` 
com.dwitech.ib24.gateway.boundary.remote.BookingsService/mp-rest/url=http://localhost:9093/
com.dwitech.ib24.gateway.boundary.remote.CheckersService/mp-rest/url=http://localhost:9093/
```

```
import com.dwitech.ib24.common.entity.request.checker.RegisterCheckerRequest;
import org.eclipse.microprofile.rest.client.inject.RegisterRestClient;

import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.Response;

@Path("/bookings")
@RegisterRestClient
@Produces("application/json")
public interface CheckersService {
	@POST @Path("/register") Response register(RegisterCheckerRequest request);
}
```

```
@Path("/gateway")
@Produces(APPLICATION_JSON)
public class GatewayEndpoint {
    @Inject @RestClient CheckersService checkersService;

    @POST @Path("/checkers/register")
    @Timed(name = "registerCheckerTime", description = "Monitor the time registerChecker Method takes", unit = MILLISECONDS, absolute = true)
    @Counted(name = "registerCheckerCount", absolute = true, monotonic = true, displayName = "registerCheckerCount", description = "Monitor how many times registerChecker method was called")
    @Metered(name = "registerCheckerMeter", unit = MILLISECONDS, description = "Monitor the rate events occurred", absolute = true)
    public Response registerChecker(RegisterCheckerRequest request) { return checkersService.register(request); }
}
```

```
@ApplicationScoped
@Path("/checkers")
@Produces({APPLICATION_JSON})
@Consumes({APPLICATION_JSON})
public class CheckersEndpoint {
    @Inject Checkers checkers;

    @POST @Path("/register")
    @Timed(name = "registerTime", description = "Monitor the time registerChecker Method takes", unit = MILLISECONDS, absolute = true)
    @Counted(name = "registerCount", absolute = true, monotonic = true, displayName = "registerCheckerCount", description = "Monitor how many times registerChecker method was called")
    @Metered(name = "registerMeter", unit = MILLISECONDS, description = "Monitor the rate events occurred", absolute = true)
    public RegisterCheckerResponse register(final RegisterCheckerRequest request) {
        RegisterCheckerResponse response = checkers.register(request);
        return response;
    }
}
```
**Environment (please complete the following information):**
- Output of uname -a or ver: Darwin DWI-MBP15-1 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
- Output of java -version: JDK8 u202
- GraalVM version (if different from Java): 1.0.0-rc14
- Quarkus version or git rev: 0.15.0

**Additional informations:**
Could this be related to https://github.com/smallrye/smallrye-rest-client/issues/11 ? This beats any purpose of having a central gateway receiving all the requests and passing them to the appropriate services.

**Comment by kameshsampath** [comment]
this is a show stopper for all the external service calls that might return JSON

**Comment by dwamara** [comment]
@kameshsampath all my external service calls do.

**Comment by gsmet** [comment]
@kameshsampath @dwamara could you work on a simple reproducer? That would help.

**Comment by dwamara** [comment]
I'll modify one of my code producing this error and will upload it tonight.

**Comment by gsmet** [comment]
Thank you. We are in the process of changing the REST client implementation but it's a good opportunity to check if the new one still has the issue.

/cc @kenfinnigan @asoldano

**Comment by dwamara** [comment]
@gsmet @kenfinnigan @asoldano @patriot1burke
Here is the reproducer: https://github.com/dwamara/quarkus-rest-client_bug2657

**Comment by kenfinnigan** [comment]
Thanks

**Comment by kameshsampath** [comment]
@gsmet - am not able to reproduce it now :( the same code is returning the results to me, but I have added the source code in the gist https://gist.github.com/kameshsampath/66b140f6f9c94fa7d20f918fae9ca15e. I am not sure it has something to do with backend response :( ..

**Comment by dwamara** [comment]
@kameshsampath 
Check if you can have it with my reproducer (https://github.com/quarkusio/quarkus/issues/2657#issuecomment-506482312) I had the problem with the 0.15.0 version of Quarkus and was on my side able to reproduce it with the 0.17.0. 
The source code of the io.smallrye.restclient.PartialResponse that is used by Quarkus explicitly has
```    
    public Object getEntity() {
        throw this.notSupported();
    }

    private RuntimeException notSupported() {
        RuntimeException ex = new RuntimeException("method call not supported");
        ex.printStackTrace();
        return ex;
    }

    public synchronized <T> T readEntity(Class<T> entityType) {
        if (entityType.isAssignableFrom(String.class)) {
            return readStringEntity(this.entityStream);
        } else {
            throw this.notSupported();
        }
    }
```

**Comment by dwamara** [comment]
I've just bumped the Quarkus version to 0.18.0 in the reproducer. Still able to reproduce it, just in case.

**Comment by kameshsampath** [comment]
Will try and let you know @Daniel Wamara<mailto:notifications@github.com>

**Comment by dwamara** [comment]
@gsmet @kenfinnigan @asoldano
Do you guys have any alternative solution or temporary recommendation for the rest client? We're at the moment completely stuck in our development: all the different services have been implemented but calling each other is at the moment a no-go.

**Comment by kenfinnigan** [comment]
A PR to update to use RESTEasy as the Client implementation is underway: https://github.com/quarkusio/quarkus/pull/3209

Though I just looked at the reproducer and noticed that https://github.com/dwamara/quarkus-rest-client_bug2657/blob/master/caller/src/main/java/bug2657/boundary/remote/CalledService.java and https://github.com/dwamara/quarkus-rest-client_bug2657/blob/master/caller/src/main/java/bug2657/boundary/CallerEndpoint.java don't have `@Consumes(JSON)` on the classes/methods.

**Comment by dwamara** [comment]
Now you make me look stupid, I bumped the version to 0.19.1 and added the forgotten annotation and it seems to work now.

**Comment by kenfinnigan** [comment]
The error with the `PartialResponse` is because of an exception in the call, which is a problem, maybe just not the one that would have been expected.

I think this should be fixed with the update in the PR

**Comment by csotiriou** [comment]
@kenfinnigan Unfortunately, the problem persists in the case of a bad response. I am using Quarkus 0.19.1, and when I get an error 503, I get a "Method Call Not Supported" as an error from my service.

**Comment by kenfinnigan** [comment]
Though annoying, it does make sense, kind of. It's saying that you can't have a partial response unless the return type supports it.

But, I'm not sure why an HTTP error in the call means it's a partial response.

**Comment by kenfinnigan** [comment]
Is this still a problem with 0.27?

**Comment by kenfinnigan** [comment]
Verified fixed with 1.0
