### ISSUE TITLE
I think collision with kotlin allopen plugin

### ISSUE THREAD

**Issue by jon890** [quarkusio/quarkus#29875]
### Describe the bug

I use hibernate reactive with kotlin
So I write down my entites to kotlin class (it is final class)
and I apply kotlin allopen plugin
and I start my quarkus application to quarkus dev command.

First build, It is working well
but running hot reloading and I think that don't applied kotlin allopen plugin.

### Expected behavior

Live Coding activate and applied kotlin allopen plugin.

### Actual behavior

I think the Kotlin allopen plugin doesn't applied to Live Coding

### How to Reproduce?

1. Write your entity with kotlin
2. edit your source code
3. Boom

### Output of `uname -a` or `ver`

Darwin kbt.local 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18 OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8) OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (build 17.0.5+8, mixed mode)

### GraalVM version (if different from Java)

no

### Quarkus version or git rev

2.1.5 FINAL

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

7.5.1

**Comment by geoand** [comment]
Are you really using Quarkus `2.1.5`? If so, that version is very old and I would suggest trying `2.15.0.Final` and reporting back.

**Comment by jon890** [comment]
> Are you really using Quarkus `2.1.5`? If so, that version is very old and I would suggest trying `2.15.0.Final` and reporting back.

I made a typo, I am using 2.15.0.Final!

**Comment by geoand** [comment]
@glefloch haven't we addressed this one?

**Comment by Feavy** [comment]
Tthe issue is still there with latest version at the time (Quarkus 3.5.1 with Kotlin 1.9.10)

Hot reload doesn't work with allOpen kotlin plugin.

**Comment by mschorsch** [comment]
I've found a workaround: https://github.com/quarkusio/quarkus/issues/37109#issuecomment-1828352002
