### ISSUE TITLE
QuarkusTest loads @ApplicationPath class twice

### ISSUE THREAD

**Issue by mgagliardo91** [quarkusio/quarkus#3138]
**Describe the bug**
When running a test defined with `@QuarkusTest` using the maven-failsafe-plugin, I am receiving an error that appears to be related to quarkus attempting to load a class we use to defines the `@ApplicationPath` twice.

```
org.junit.jupiter.api.extension.TestInstantiationException:
TestInstanceFactory [io.quarkus.test.junit.QuarkusTestExtension] failed to instantiate test class [com.cloudbees.sdm.injector.github.flink.FlinkConfigurationIT]: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.resteasy.server.common.deployment.ResteasyServerCommonProcessor#build threw an exception: java.lang.RuntimeException: Multiple classes ( com.cloudbees.sdm.injector.github.GitHubApplication,com.cloudbees.sdm.injector.github.GitHubApplication) have been annotated with @ApplicationPath which is currently not supported
Caused by: java.lang.RuntimeException:
io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.resteasy.server.common.deployment.ResteasyServerCommonProcessor#build threw an exception: java.lang.RuntimeException: Multiple classes ( com.cloudbees.sdm.injector.github.GitHubApplication,com.cloudbees.sdm.injector.github.GitHubApplication) have been annotated with @ApplicationPath which is currently not supported
Caused by: io.quarkus.builder.BuildException:
Build failure: Build failed due to errors
	[error]: Build step io.quarkus.resteasy.server.common.deployment.ResteasyServerCommonProcessor#build threw an exception: java.lang.RuntimeException: Multiple classes ( com.cloudbees.sdm.injector.github.GitHubApplication,com.cloudbees.sdm.injector.github.GitHubApplication) have been annotated with @ApplicationPath which is currently not supported
Caused by: java.lang.RuntimeException: Multiple classes ( com.cloudbees.sdm.injector.github.GitHubApplication,com.cloudbees.sdm.injector.github.GitHubApplication) have been annotated with @ApplicationPath which is currently not supported
```

**Expected behavior**
The integration test loads all dependent application classes once, and completes successfully.

**Actual behavior**
Errors are thrown indicating `Multiple classes have been annotated with @ApplicationPath which is currently not supported`

**To Reproduce**
1. Run `mvn integration-test` within a quarkus app that defines the `maven-failsafe-plugin`

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin ip-192-168-86-68.ec2.internal 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64
 - Output of `java -version`: openjdk version "1.8.0_212"
 - Quarkus version or git rev: 0.18.0

**Comment by gsmet** [comment]
@aloubyansky is it related to the issue you were trying to solve?

**Comment by aloubyansky** [comment]
Yes, looks the same as #3117

**Comment by aloubyansky** [comment]
Which Quarkus extensions are you using in this test @mgagliardo91?

**Comment by aloubyansky** [comment]
Now that #3117 has been merged, this should be fixed. @mgagliardo91 is there a chance you can try current master branch to make sure it works for you? Thanks.

**Comment by chonton** [comment]
I am still seeing a similar problem using quarkus version 0.20.0
Any surefire tests marked with @QuarkusTest  pollutes test-classes; I wonder if this is problem?

**Comment by aloubyansky** [comment]
It clearly isn't just any app with `@ApplicationPath` and `maven-failsafe-plugin`. There has to be some other detail which breaks it. As an example, I've adjusted https://github.com/quarkusio/quarkus-quickstarts/tree/master/getting-started following the description but it still worked. Would you mind trying that exercise and communicating the instructions to make it fail as in your original scenario?

In principle, this error can be a result of either:
1) multiple classes (with different paths, could still be the same name) are annotated with `@ApplicationPath` appear on the classpath;
2) the same class is indexed by Quarkus twice.

Quarkus test extension does use `test-classes` as an output location for the generated so called `wiring` classes to workaround the classloading limitations of the Maven testing plugins. I doubt this is the cause of the issue though.
I am guessing it's scenario 2). Which could happen, e.g. if
* `META-INF/beans.xml` or `META-INF/jandex.idx` appears in the dir/jar that contains the class annotated with `@ApplicationPath` (which is supposed to be unnecessary)
* or there is a `@BuildStep(applicationArchiveMarkers="path_matching_start_of_your_app_class_package` (which is unlikely unless you developed your own Quarkus extension that includes it).

Please provide more details to investigate it further. Thanks.

**Comment by snoopdave** [comment]
I'm still seeing this problem with Quarkus 0.27.0

**Comment by gsmet** [comment]
@snoopdave can you provide a reproducer? That would be helpful.

**Comment by tomgeorge** [comment]
We are currently encountering this issue on github.com/eclipse/che-workspace-telemetry-client in the `backend-base` module.

**Comment by stuartwdouglas** [comment]
I this still an issue with 1.3.0? Without a reproducer we can't really tell exactly what the problem is.

**Comment by stuartwdouglas** [comment]
I am going to close this for now, without a reproducer it is hard to know what the original problem was, and there have been a large number of changes since this was reported that may have already fixed it. If it is still a problem feel free to re-open with more details.
