### ISSUE TITLE
Elasticsearch Dev Services gives `Operation not permitted` on startup when using Podman

### ISSUE THREAD

**Issue by phillip-kruger** [quarkusio/quarkus#31960]
### Describe the bug

When starting up a app that uses elasticsearch dev services I get:

`chroot: cannot change root directory to '/': Operation not permitted`

I am using podman, not sure if that is the issue. 

### Expected behavior

Elasticsearch should start

### Actual behavior

It does not

### Output of `uname -a` or `ver`

Linux pkruger-laptop 6.1.18-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Mar 11 16:09:14 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment (Red_Hat-17.0.6.0.10-1.fc37) (build 17.0.6+10)
OpenJDK 64-Bit Server VM (Red_Hat-17.0.6.0.10-1.fc37) (build 17.0.6+10, mixed mode, sharing)

### Quarkus version or git rev

999-SNAPSHOT

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0)
Maven home: /opt/Maven/apache-maven-3.8.5
Java version: 17.0.6, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-17-openjdk-17.0.6.0.10-1.fc37.x86_64
Default locale: en_AU, platform encoding: UTF-8
OS name: "linux", version: "6.1.18-200.fc37.x86_64", arch: "amd64", family: "unix"

### Additional information

Output of `docker -v` is:
`podman version 4.4.2`

**Comment by yrodiere** [comment]
This does seem specific to podman, though caused by a bug in the ES container: https://github.com/elastic/cloud-on-k8s/issues/5212

It would seem Elasticsearch 8 isn't affected anymore, in which case moving to ES 8 as the default would solve the problem. Can you try setting this, see if that helps?

```
quarkus.elasticsearch.devservices.image-name=docker.elastic.co/elasticsearch/elasticsearch:8.6.0
```

**Comment by phillip-kruger** [comment]
I did try that initially but got some other error, but let me try again. I'll report back here

**Comment by phillip-kruger** [comment]
Please see the PR for response on upgrade to v8

**Comment by yrodiere** [comment]
Note a workaround is to use ES 8 in dev services through [this configuration property](https://quarkus.io/guides/elasticsearch-dev-services#quarkus-elasticsearch-devservices-elasticsearch-dev-services-build-time-config_quarkus.elasticsearch.devservices.image-name):

```
quarkus.elasticsearch.devservices.image-name=docker.elastic.co/elasticsearch/elasticsearch:8.6.2
```

And if you're using Hibernate Search, don't forget to update the version expected by Hibernate Search as well:

```
quarkus.hibernate-search-orm.elasticsearch.version=8
```

It will complain as it doesn't know of Elasticsearch 8, but I don't know of any actual bugs, so it *should* be fine.

**Comment by holly-cummins** [comment]
Interestingly, elasticsearch wasn't one of the tests that failed when on the [first run of the Linux Quarkus CI](https://github.com/holly-cummins/quarkus/actions/runs/4844611295). Does this mean we have a test coverage issue, or is this fixed by another change?

**Comment by yrodiere** [comment]
This is not fixed as far as I know. And Elasticsearch did start in your run:

```
2023-04-30T16:52:15.6012960Z [INFO] --- docker-maven-plugin:0.42.1:start (docker-start) @ quarkus-integration-test-hibernate-search-orm-elasticsearch ---
2023-04-30T16:52:16.4869115Z [INFO] DOCKER> [docker.io/elastic/elasticsearch:7.16.3] "elasticsearch": Start container ab2df0147d7b
2023-04-30T16:52:16.7247490Z [INFO] DOCKER> [docker.io/elastic/elasticsearch:7.16.3] "elasticsearch": Waiting on url http://localhost:9200 with method GET for status 200.
2023-04-30T16:52:20.7618655Z 16:52:20.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:20,440Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "version[7.16.3], pid[2], build[default/docker/4e6e4eab2297e949ec994e688dad46290d018022/2022-01-06T23:43:02.825887787Z], OS[Linux/5.15.0-1036-azure/amd64], JVM[Eclipse Adoptium/OpenJDK 64-Bit Server VM/17.0.1/17.0.1+12]" }
2023-04-30T16:52:20.7620713Z 16:52:20.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:20,447Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "JVM home [/usr/share/elasticsearch/jdk], using bundled JDK [true]" }
2023-04-30T16:52:20.7652867Z 16:52:20.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:20,448Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "JVM arguments [-Xshare:auto, -Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -XX:+ShowCodeDetailsInExceptionMessages, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j2.formatMsgNoLookups=true, -Djava.locale.providers=SPI,COMPAT, --add-opens=java.base/java.io=ALL-UNNAMED, -XX:+UseG1GC, -Djava.io.tmpdir=/tmp/elasticsearch-225884224910287996, -XX:+HeapDumpOnOutOfMemoryError, -XX:+ExitOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Des.cgroups.hierarchy.override=/, -Xms512m, -Xmx512m, -XX:MaxDirectMemorySize=268435456, -XX:G1HeapRegionSize=4m, -XX:InitiatingHeapOccupancyPercent=30, -XX:G1ReservePercent=15, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/usr/share/elasticsearch/config, -Des.distribution.flavor=default, -Des.distribution.type=docker, -Des.bundled_jdk=true]" }
2023-04-30T16:52:23.7617678Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,384Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [aggs-matrix-stats]" }
2023-04-30T16:52:23.7619189Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,384Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [analysis-common]" }
2023-04-30T16:52:23.7621475Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,386Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [constant-keyword]" }
2023-04-30T16:52:23.7623996Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,386Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [frozen-indices]" }
2023-04-30T16:52:23.7627960Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,387Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [ingest-common]" }
2023-04-30T16:52:23.7685399Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,388Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [ingest-geoip]" }
2023-04-30T16:52:23.7749393Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,392Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [ingest-user-agent]" }
2023-04-30T16:52:23.7750707Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,393Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [kibana]" }
2023-04-30T16:52:23.7752109Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,393Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [lang-expression]" }
2023-04-30T16:52:23.7753253Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,394Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [lang-mustache]" }
2023-04-30T16:52:23.7754361Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,395Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [lang-painless]" }
2023-04-30T16:52:23.7755464Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,395Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [legacy-geo]" }
2023-04-30T16:52:23.7756570Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,396Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [mapper-extras]" }
2023-04-30T16:52:23.7757685Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,396Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [mapper-version]" }
2023-04-30T16:52:23.7758791Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,397Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [parent-join]" }
2023-04-30T16:52:23.7760132Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,397Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [percolator]" }
2023-04-30T16:52:23.7761229Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,398Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [rank-eval]" }
2023-04-30T16:52:23.7762229Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,399Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [reindex]" }
2023-04-30T16:52:23.7763556Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,399Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [repositories-metering-api]" }
2023-04-30T16:52:23.7764732Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,400Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [repository-encrypted]" }
2023-04-30T16:52:23.7765848Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,400Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [repository-url]" }
2023-04-30T16:52:23.7766994Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,401Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [runtime-fields-common]" }
2023-04-30T16:52:23.7768289Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,401Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [search-business-rules]" }
2023-04-30T16:52:23.7818903Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,402Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [searchable-snapshots]" }
2023-04-30T16:52:23.7820134Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,403Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [snapshot-repo-test-kit]" }
2023-04-30T16:52:23.7821268Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,403Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [spatial]" }
2023-04-30T16:52:23.7822563Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,404Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [transform]" }
2023-04-30T16:52:23.7823792Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,404Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [transport-netty4]" }
2023-04-30T16:52:23.7824904Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,405Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [unsigned-long]" }
2023-04-30T16:52:23.7826125Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,405Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [vector-tile]" }
2023-04-30T16:52:23.7827405Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,406Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [vectors]" }
2023-04-30T16:52:23.7828489Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,406Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [wildcard]" }
2023-04-30T16:52:23.7829624Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,406Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [x-pack-aggregate-metric]" }
2023-04-30T16:52:23.7830774Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,407Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [x-pack-analytics]" }
2023-04-30T16:52:23.7831888Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,407Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [x-pack-async]" }
2023-04-30T16:52:23.7833008Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,407Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [x-pack-async-search]" }
2023-04-30T16:52:23.7834259Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,408Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [x-pack-autoscaling]" }
2023-04-30T16:52:23.7835330Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,408Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [x-pack-ccr]" }
2023-04-30T16:52:23.7836354Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,408Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [x-pack-core]" }
2023-04-30T16:52:23.7837390Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,408Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [x-pack-data-streams]" }
2023-04-30T16:52:23.7838446Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,409Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [x-pack-deprecation]" }
2023-04-30T16:52:23.7839489Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,409Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [x-pack-enrich]" }
2023-04-30T16:52:23.7840509Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,409Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [x-pack-eql]" }
2023-04-30T16:52:23.7841729Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,410Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [x-pack-fleet]" }
2023-04-30T16:52:23.7843032Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,410Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [x-pack-graph]" }
2023-04-30T16:52:23.7844473Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,410Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [x-pack-identity-provider]" }
2023-04-30T16:52:23.7845593Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,411Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [x-pack-ilm]" }
2023-04-30T16:52:23.7846694Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,411Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [x-pack-logstash]" }
2023-04-30T16:52:23.7848050Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,411Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [x-pack-ml]" }
2023-04-30T16:52:23.7849181Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,412Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [x-pack-monitoring]" }
2023-04-30T16:52:23.7850284Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,412Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [x-pack-ql]" }
2023-04-30T16:52:23.7851375Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,412Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [x-pack-rollup]" }
2023-04-30T16:52:23.7852569Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,413Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [x-pack-security]" }
2023-04-30T16:52:23.7853694Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,414Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [x-pack-shutdown]" }
2023-04-30T16:52:23.7854788Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,414Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [x-pack-sql]" }
2023-04-30T16:52:23.7856983Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,414Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [x-pack-stack]" }
2023-04-30T16:52:23.7858123Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,415Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [x-pack-text-structure]" }
2023-04-30T16:52:23.7859381Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,415Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [x-pack-voting-only-node]" }
2023-04-30T16:52:23.7860429Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,415Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "loaded module [x-pack-watcher]" }
2023-04-30T16:52:23.7861582Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,416Z", "level": "INFO", "component": "o.e.p.PluginsService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "no plugins loaded" }
2023-04-30T16:52:23.7862827Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,465Z", "level": "INFO", "component": "o.e.e.NodeEnvironment", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "using [1] data paths, mounts [[/ (overlay)]], net usable_space [23.2gb], net total_space [83.1gb], types [overlay]" }
2023-04-30T16:52:23.7864015Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,466Z", "level": "INFO", "component": "o.e.e.NodeEnvironment", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "heap size [512mb], compressed ordinary object pointers [true]" }
2023-04-30T16:52:23.7865720Z 16:52:23.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:23,495Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "node name [ab2df0147d7b], node ID [ja3AcgL5S7GCRhAfHuNdKA], cluster name [docker-cluster], roles [transform, data_frozen, master, remote_cluster_client, data, ml, data_content, data_hot, data_warm, data_cold, ingest]" }
2023-04-30T16:52:29.2615798Z 16:52:28.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:28,993Z", "level": "INFO", "component": "o.e.x.m.p.l.CppLogMessageHandler", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "[controller/205] [Main.cc@122] controller (64 bit): Version 7.16.3 (Build b71e71b93f3e4d) Copyright (c) 2021 Elasticsearch BV" }
2023-04-30T16:52:29.7616118Z 16:52:29.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:29,416Z", "level": "INFO", "component": "o.e.i.g.ConfigDatabases", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "initialized default databases [[GeoLite2-Country.mmdb, GeoLite2-City.mmdb, GeoLite2-ASN.mmdb]], config databases [[]] and watching [/usr/share/elasticsearch/config/ingest-geoip] for changes" }
2023-04-30T16:52:29.7618227Z 16:52:29.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:29,418Z", "level": "INFO", "component": "o.e.i.g.DatabaseNodeService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "initialized database registry, using geoip-databases directory [/tmp/elasticsearch-225884224910287996/geoip-databases/ja3AcgL5S7GCRhAfHuNdKA]" }
2023-04-30T16:52:30.1299015Z 16:52:30.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:30,053Z", "level": "INFO", "component": "o.e.t.NettyAllocator", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "creating NettyAllocator with the following configs: [name=unpooled, suggested_max_allocation_size=1mb, factors={es.unsafe.use_unpooled_allocator=null, g1gc_enabled=true, g1gc_region_size=4mb, heap_size=512mb}]" }
2023-04-30T16:52:30.1303869Z 16:52:30.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:30,128Z", "level": "INFO", "component": "o.e.d.DiscoveryModule", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "using discovery type [single-node] and seed hosts providers [settings]" }
2023-04-30T16:52:31.0122214Z 16:52:30.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:30,583Z", "level": "INFO", "component": "o.e.g.DanglingIndicesState", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "gateway.auto_import_dangling_indices is disabled, dangling indices will not be automatically detected or imported and must be managed manually" }
2023-04-30T16:52:31.3587716Z 16:52:31.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:31,101Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "initialized" }
2023-04-30T16:52:31.3589573Z 16:52:31.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:31,103Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "starting ..." }
2023-04-30T16:52:31.3591279Z 16:52:31.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:31,114Z", "level": "INFO", "component": "o.e.x.s.c.f.PersistentCache", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "persistent cache index loaded" }
2023-04-30T16:52:31.3593814Z 16:52:31.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:31,115Z", "level": "INFO", "component": "o.e.x.d.l.DeprecationIndexingComponent", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "deprecation component started" }
2023-04-30T16:52:31.3596181Z 16:52:31.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:31,241Z", "level": "INFO", "component": "o.e.t.TransportService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "publish_address {10.88.0.192:9300}, bound_addresses {[::]:9300}" }
2023-04-30T16:52:31.3598203Z 16:52:31.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:31,356Z", "level": "INFO", "component": "o.e.c.c.Coordinator", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "setting initial configuration to VotingConfiguration{ja3AcgL5S7GCRhAfHuNdKA}" }
2023-04-30T16:52:31.6953187Z 16:52:31.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:31,461Z", "level": "INFO", "component": "o.e.c.s.MasterService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "elected-as-master ([1] nodes joined)[{ab2df0147d7b}{ja3AcgL5S7GCRhAfHuNdKA}{3lR9GKEERVqKjHnxgkHmaA}{10.88.0.192}{10.88.0.192:9300}{cdfhilmrstw} elect leader, _BECOME_MASTER_TASK_, _FINISH_ELECTION_], term: 1, version: 1, delta: master node changed {previous [], current [{ab2df0147d7b}{ja3AcgL5S7GCRhAfHuNdKA}{3lR9GKEERVqKjHnxgkHmaA}{10.88.0.192}{10.88.0.192:9300}{cdfhilmrstw}]}" }
2023-04-30T16:52:31.6955774Z 16:52:31.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:31,486Z", "level": "INFO", "component": "o.e.c.c.CoordinationState", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "cluster UUID set to [ozXp4G_USeOlpGe-LxAGyA]" }
2023-04-30T16:52:31.6957832Z 16:52:31.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:31,502Z", "level": "INFO", "component": "o.e.c.s.ClusterApplierService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "master node changed {previous [], current [{ab2df0147d7b}{ja3AcgL5S7GCRhAfHuNdKA}{3lR9GKEERVqKjHnxgkHmaA}{10.88.0.192}{10.88.0.192:9300}{cdfhilmrstw}]}, term: 1, version: 1, reason: Publication{term=1, version=1}" }
2023-04-30T16:52:31.6960135Z 16:52:31.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:31,559Z", "level": "INFO", "component": "o.e.h.AbstractHttpServerTransport", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "publish_address {10.88.0.192:9200}, bound_addresses {[::]:9200}", "cluster.uuid": "ozXp4G_USeOlpGe-LxAGyA", "node.id": "ja3AcgL5S7GCRhAfHuNdKA"  }
2023-04-30T16:52:31.6961799Z 16:52:31.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:31,559Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "started", "cluster.uuid": "ozXp4G_USeOlpGe-LxAGyA", "node.id": "ja3AcgL5S7GCRhAfHuNdKA"  }
2023-04-30T16:52:31.6963350Z 16:52:31.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:31,692Z", "level": "INFO", "component": "o.e.g.GatewayService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "recovered [0] indices into cluster_state", "cluster.uuid": "ozXp4G_USeOlpGe-LxAGyA", "node.id": "ja3AcgL5S7GCRhAfHuNdKA"  }
2023-04-30T16:52:32.1122856Z [INFO] DOCKER> [docker.io/elastic/elasticsearch:7.16.3] "elasticsearch": Waited on url http://localhost:9200 15387 ms
2023-04-30T16:52:32.1124773Z [INFO] 
2023-04-30T16:52:32.1126181Z [INFO] --- maven-surefire-plugin:3.0.0:test (default-test) @ quarkus-integration-test-hibernate-search-orm-elasticsearch ---
2023-04-30T16:52:32.1418099Z [INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
2023-04-30T16:52:32.1532597Z [INFO] Surefire report directory: /home/runner/work/quarkus/quarkus/integration-tests/hibernate-search-orm-elasticsearch/target/surefire-reports
2023-04-30T16:52:32.1648867Z [INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
2023-04-30T16:52:32.1722216Z [INFO] 
2023-04-30T16:52:32.1769123Z [INFO] -------------------------------------------------------
2023-04-30T16:52:32.1772298Z [INFO]  T E S T S
2023-04-30T16:52:32.1776160Z [INFO] -------------------------------------------------------
2023-04-30T16:52:32.4758892Z 16:52:32.000 Elasticsearch:{"type": "server", "timestamp": "2023-04-30T16:52:32,097Z", "level": "INFO", "component": "o.e.c.m.MetadataIndexTemplateService", "cluster.name": "docker-cluster", "node.name": "ab2df0147d7b", "message": "adding index template [.ml-notifications-000002] for index patterns [.ml-notifications-000002]", "cluster.uuid": "ozXp4G_USeOlpGe-LxAGyA", "node.id": "ja3AcgL5S7GCRhAfHuNdKA"  }
```

Maybe this run does not use podman everywhere?

**Comment by holly-cummins** [comment]
That's a good point, @yrodiere, if we can see elasticsearch start, it's not a coverage problem. :) It could be a version difference, since we seem to have several podman-related issues where it works on one version and then doesn't work on a different dot version. I suspect OS also makes a difference, but here CI and the initial issue are both Linux. It could also be a rootfuliness issue. I'm seeing some differences in the opposite direction, too, where things fail on the Podman CI but pass locally.

This is the version info from the CI 

```
2023-04-30T19:59:00.8148494Z Server: linux/amd64/ubuntu-22.04
2023-04-30T19:59:00.8148720Z  Podman Engine:
2023-04-30T19:59:00.8148970Z   Version:          4.5.0
2023-04-30T19:59:00.8149197Z   APIVersion:       4.5.0
2023-04-30T19:59:00.8149398Z   Arch:             amd64
```
