### ISSUE TITLE
Quarkus Hibernate search programmatic API

### ISSUE THREAD

**Issue by mhautman** [quarkusio/quarkus#32760]
### Description

Hi,

I have a requirement where I need to be able to define a prefix for the index names. (So different environments can use the same ElasticSearch instance) 

I found this is possible with hibernate-search using the programmatic API (https://docs.jboss.org/hibernate/stable/search/reference/en-US/html_single/#hsearch-mapping-programmaticapi), however I didn't find any support for it in Quarkus Hibernate search extension because the property to point to the mapping is missing (hibernate.search.mapping.configurer)

Could this be implemented/added? Or am I missing something?

Thanks in advance.

Regards,
Morgan

**Comment by yrodiere** [comment]
Hey,

> I have a requirement where I need to be able to define a prefix for the index names. (So different environments can use the same ElasticSearch instance)

You may want to use a [layout strategy](https://docs.jboss.org/hibernate/search/6.1/reference/en-US/html_single/#backend-elasticsearch-indexlayout). Just implement `IndexLayoutStrategy` and annotate with `@SearchExtension`.

See also [quarkus.hibernate-search-orm.elasticsearch.layout.strategy](https://quarkus.io/guides/hibernate-search-orm-elasticsearch#quarkus-hibernate-search-orm-elasticsearch_quarkus.hibernate-search-orm.elasticsearch.layout.strategy).

> I found this is possible with hibernate-search using the programmatic API
> Could this be implemented/added? Or am I missing something?

It could be implemented, it's just that nobody had any use for it so far, so it wasn't deemed a priority. If anyone is interested in providing a pull request, I'd suggest they have a look at how support for analysis configurers is implemented in Quarkus and take inspiration from that. A few pointers:

* [declaring the config property](https://github.com/quarkusio/quarkus/blob/dc3f4cfe408ce2f542c15ef9b66efa4074af48c4/extensions/hibernate-search-orm-elasticsearch/runtime/src/main/java/io/quarkus/hibernate/search/orm/elasticsearch/runtime/HibernateSearchElasticsearchBuildTimeConfigPersistenceUnit.java#L169-L188). In this case it's not a backend property though, so you'll do that in  you'll want a "mapping" config group directly within `HibernateSearchElasticsearchBuildTimeConfigPersistenceUnit`, next to `CoordinationConfig coordination();`.
* [forwarding the config to Hibernate Search](https://github.com/quarkusio/quarkus/blob/42aa4e63115ace6342ae1cca5d077f8368faa0c2/extensions/hibernate-search-orm-elasticsearch/runtime/src/main/java/io/quarkus/hibernate/search/orm/elasticsearch/runtime/HibernateSearchElasticsearchRecorder.java#L280-L285). In this case it's not a backend property though, so you'll do that in `HibernateSearchElasticsearchRecorder.HibernateSearchIntegrationStaticInitListener#contributeBootProperties` and use `addConfig` instead of `addBackendConfig`.
* adding an integration test to `integration-tests/hibernate-search-orm-elasticsearch`: [the test in JVM mode](https://github.com/quarkusio/quarkus/blob/f9d0518eb08978ba574e9132e8e40f7cf5a3489d/integration-tests/hibernate-search-orm-elasticsearch/src/test/java/io/quarkus/it/hibernate/search/orm/elasticsearch/AnalysisTest.java), [the test in native mode](https://github.com/quarkusio/quarkus/blob/f9d0518eb08978ba574e9132e8e40f7cf5a3489d/integration-tests/hibernate-search-orm-elasticsearch/src/test/java/io/quarkus/it/hibernate/search/orm/elasticsearch/AnalysisInGraalIT.java), [the REST service backing the test](https://github.com/quarkusio/quarkus/blob/ebee0a4b66d1b4dba9c51165e78d22fbf3b90d3e/integration-tests/hibernate-search-orm-elasticsearch/src/main/java/io/quarkus/it/hibernate/search/orm/elasticsearch/analysis/AnalysisTestResource.java#L22).

There will be limitations though, in particular Quarkus may not be able to auto-detect all classes that need reflection because it usually does so at build time (based on annotations), and programmatic mapping happens later (on static init). So, when using programmatic mapping, developers may need to [register some of their mapped classes for reflection manually](https://quarkus.io/guides/writing-native-applications-tips#registering-for-reflection).

**Comment by mhautman** [comment]
Hey Yoann,

I Implemented it indeed with a custom layout strategy and it works like a charm, thanks for the pointer!

**Comment by yrodiere** [comment]
Nice, thanks for the feedback. Let's leave the issue open as programmatic mapping still isn't available in Quarkus at the moment :)

**Comment by yrodiere** [comment]
FWIW, regarding this:

> There will be limitations though, in particular Quarkus may not be able to auto-detect all classes that need reflection because it usually does so at build time (based on annotations), and programmatic mapping happens later (on static init). So, when using programmatic mapping, developers may need to [register some of their mapped classes for reflection manually](https://quarkus.io/guides/writing-native-applications-tips#registering-for-reflection).

It seems GraalVM is able to detect reflection needs based on `java.lang.reflect.Constructor`/`java.lang.reflect.Method`/`java.lang.reflect.Field` instances in the heap at the end of static init. So we may not need to register extra classes for  reflection after all; programmatic mapping may only need a configuration property + `@SearchExtension` support to work properly. We'll need (native) tests to check that, though.

**Comment by cthiebault** [comment]
> Hey Yoann,
> 
> I Implemented it indeed with a custom layout strategy and it works like a charm, thanks for the pointer!

Hello @mhautman 

I'm trying to achieve the same thing but I have some issue to retrieve the configurable prefix and use it in my `IndexLayoutStrategy` custom implementation. See https://github.com/quarkusio/quarkus/issues/41384

How did you manage to do it?
