### ISSUE TITLE
Injecting @Context parameters into application constructor doesn't work

### ISSUE THREAD

**Issue by dteleguin** [quarkusio/quarkus#3535]
**Describe the bug**
When trying to inject `@Context` data as JAX-RS application's constructor arguments, non-working instances are injected. At the same time, obtaining the instances directly from ResteasyContext works just fine.

**Expected behavior**
Valid context data should be passed to the constructor.

**Actual behavior**
Proxy instances are injected, but any actual invocation results in an NPE.

**To Reproduce**
```java
@ApplicationPath("/app")
public class HelloApplication extends Application {

    private static final Logger LOG = Logger.getLogger(HelloApplication.class.getName());

    public HelloApplication(@Context ServletContext context) {
        ServletContext _context = ResteasyContext.getContextData(ServletContext.class);
        LOG.info(_context.getContextPath()); // "/hello" (see application.properties)
        LOG.info(context.getContextPath()); // NPE
    }

}
```
```
18:48:32,823 INFO  [hel.HelloApplication] /hello
18:48:32,843 ERROR [io.qua.dev.DevModeMain] Failed to start quarkus: java.lang.ExceptionInInitializerError
...
Caused by: java.lang.NullPointerException
	at io.quarkus.arc.runtimebean.RuntimeBeanProducers_ProducerMethod_produce_javax_servlet_ServletContext_bf21a9e8fbc5a3846fb05b4fa0859e0917b2202f_0efff9b05c5fcc59fa745b0f107f7f6ab8435e86_ClientProxy.getContextPath(RuntimeBeanProducers_ProducerMethod_produce_javax_servlet_ServletContext_bf21a9e8fbc5a3846fb05b4fa0859e0917b2202f_0efff9b05c5fcc59fa745b0f107f7f6ab8435e86_ClientProxy.zig:128)
	at hello.HelloApplication.<init>(HelloApplication.java:18)
	at hello.HelloApplication_Bean.create(HelloApplication_Bean.zig:156)
	at hello.HelloApplication_Bean.create(HelloApplication_Bean.zig:98)
```

**Configuration**
```properties
quarkus.servlet.context-path = /hello
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux 5.1.1 x86_64
 - Output of `java -version`: Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
 - GraalVM version (if different from Java): 19.1.1
 - Quarkus version or git rev: 0.20.0

**Comment by edewit** [comment]
I couldn't reproduce this anymore it might have been fixed my version is `0.22.0`

**Comment by dteleguin** [comment]
I still see it on both 0.22 and 0.23, only the error is slightly different:
```
15:40:08,991 INFO  [io.qua.dep.QuarkusAugmentor] Beginning quarkus augmentation
15:40:09,331 INFO  [org.jbo.threads] JBoss Threads version 3.0.0.Beta5
15:40:10,015 INFO  [io.qua.dep.QuarkusAugmentor] Quarkus augmentation completed in 1024ms
15:40:10,242 INFO  [hel.HelloApplication] /hello
15:40:10,279 ERROR [io.qua.dev.DevModeMain] Failed to start quarkus: java.lang.ExceptionInInitializerError
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        ...
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl1.<clinit>(ApplicationImpl1.zig:229)
	...
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at io.quarkus.undertow.runtime.UndertowDeploymentRecorder.bootServletContainer(UndertowDeploymentRecorder.java:479)
	...
Caused by: java.lang.NullPointerException
	at io.quarkus.arc.runtimebean.RuntimeBeanProducers_ProducerMethod_produce_javax_servlet_ServletContext_bf21a9e8fbc5a3846fb05b4fa0859e0917b2202f_0efff9b05c5fcc59fa745b0f107f7f6ab8435e86_ClientProxy.getContextPath(RuntimeBeanProducers_ProducerMethod_produce_javax_servlet_ServletContext_bf21a9e8fbc5a3846fb05b4fa0859e0917b2202f_0efff9b05c5fcc59fa745b0f107f7f6ab8435e86_ClientProxy.zig:128)
	at hello.HelloApplication.<init>(HelloApplication.java:18)
	at hello.HelloApplication_Bean.create(HelloApplication_Bean.zig:60)
	at hello.HelloApplication_Bean.create(HelloApplication_Bean.zig:28)
```

**Comment by gsmet** [comment]
@geoand @mkouba could you have a look at that one?

**Comment by geoand** [comment]
Sure thing, I'll check it out

**Comment by geoand** [comment]
I looked into this one and it turns out to be a timing issue. Basically when `Application` is created the ServletContext isn't a bean yet which means it can't be injected via `@Context`.

Is constructor injection even supported for `Application` classes by the spec? I am asking because I don't know if it makes sense to work on this or not.

**Comment by mkouba** [comment]
So I've just verified that injecting `javax.servlet.ServletContext` works fine in 1.0.0.CR1 - it's a bean provided by undertow extension. However, it's injected by CDI and not resteasy and the `@Context` annotation is simply ignored.

**Comment by rsvoboda** [comment]
> I am asking because I don't know if it makes sense to work on this or not.

who should decide ?

**Comment by mkouba** [comment]
There was a discussion about unifying CDI and JAX-RS injection. See also https://groups.google.com/forum/#!msg/quarkus-dev/yuu1nhdgLJ8/6A03nGtmCAAJ.

> who should decide ?

I'm not quite sure. But (1) a workaround exists - use field injection, (2) if there is enough interest in the community we should raise the priority.

**Comment by geoand** [comment]
This is a really fringe issue that has very little affect, so let's close
