### ISSUE TITLE
Sporadic "Failed to export spans. The request could not be executed. Full error message: Stream was closed"

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#35686]
### Describe the bug

I'm seeing the following error in the logs every now and then:
```
SEVERE [io.qua.ope.run.exp.otl.VertxGrpcExporter] (vert.x-eventloop-thread-1) Failed to export spans. The request could not be executed. Full error message: Stream was closed
```
OTLP sink is a Jaeger container (1.48.0, no collector in between), all apps are running in a docker compose setup.
I can see those errors locally and on our central testing VMs.

I do see plenty of spans in Jaeger though.

I haven't seen this issue before in Quarkus 2.16.

Any hints on where to start looking/debugging?

### How to Reproduce?

n/a ATM

### Output of `java -version`

Java 17

### Quarkus version or git rev

3.3.1

### Additional information

I'm also seeing sporadic messages like:
> WARN [io.qua.ope.run.QuarkusContextStorage] (executor-thread-143) Context in storage not the expected context, Scope.close was not called correctly

and
> ERROR [io.ver.cor.net.imp.ConnectionBase] (vert.x-eventloop-thread-1) NULL

But not everytime are those messages logged together.

**Comment by famod** [comment]
@brunobat no, Jaeger is alive and kicking all the time. There's also no warning or error in its logs.

**Comment by brunobat** [comment]
@famod I was talking about the quarkus server instances

**Comment by famod** [comment]
@brunobat ah, sorry. No, it happens mutliple times during a UI regression test suite execution that runs 45 mind or so (but doesn't cause that much load).

**Comment by brunobat** [comment]
Umm... This totally smells to a thread being shutdown and then later used to send the last remaining spans.
Would you be able to confirm this or come up with a reproducer?

**Comment by famod** [comment]
Setting vert.x' ConnectionBase to DEBUG reveals:
> [io.ver.cor.net.imp.ConnectionBase] (vert.x-eventloop-thread-5) The connection will be closed due to timeout

Trying to dig deeper...

**Comment by famod** [comment]
So it turns out that some export requests take longer that the default 10s to be processed by jaeger.
Setting `quarkus.otel.exporter.otlp.traces.timeout=30S` resolves this issue for me.
Seems like that even with very low local load we export too much, probably due to the jdbc spans and an export factor of 1.0 (100%).

So this is probably a won't fix, but maybe we could print a more actionable message?
I can see that a `io.vertx.core.http.HttpClosedException: Stream was closed` is caught/handled (only the message is logged though).
What about:
- logging `toString()` of the exception instead of just the message (which could theoretically be null)
- adding something like "Try increasing quarkus.otel.exporter.otlp.traces.timeout and/or reducing the number of exported items by lowering the sampling rate."

**Comment by famod** [comment]
Btw, I'm under the impression that VertxGrpcExporter will never use http 2, or am I wrong? (setting 2 didn't improve my timeout issue though)

**Comment by brunobat** [comment]
Hi @famod. Thanks for the debugging. 
I was able to reproduce the issue but by killing Jaeger:
`SEVERE traceId=, parentId=, spanId=, sampled= [io.qu.op.ru.ex.ot.VertxGrpcExporter] (vert.x-eventloop-thread-1) Failed to export spans. The request could not be executed. Full error message: Stream was closed`
This message will show up if either end of the connection abruptly disconnects.
Will create a PR...

**Comment by famod** [comment]
> This message will show up if either end of the connection abruptly disconnects while transmitting the spans.

Makes sense. In my case it's vert.x killing it due to timeout.

**Comment by jimkont** [comment]
Not sure if this is the same issue but I also get a `Stream was closed` error when I try the new Vertex-based GRPC exporter with version 3.4.2. Unfortunately, I get this only in the production environment and cannot reproduce it locally. Some error logs that I get near that error are the following:

 * `Failed to export spans. The request could not be executed. Full error message: Cannot create stream 3 greater than Last-Stream-ID 1 from GOAWAY.` from `"vert.x-eventloop-thread-1"`
 * `Thread Thread[vert.x-eventloop-thread-1,5,main] has been blocked for 3820 ms, time limit is 2000 ms` from `"vertx-blocked-thread-checker"`
 * `Failed to export spans. The request could not be executed. Full error message: Stream was closed` from `"vert.x-eventloop-thread-1"`

sharing in case log 1 or 2 could be causing the stream to close. 
In production we are using aws-lambda with snap start enabled, in case this brings some more context

**Comment by brunobat** [comment]
Thanks @jimkont. 
Can you please format it in plain text? We cannot see how many log lines are there.
It looks like you have a `Broken pipe`... There was a communication problem with the collector, either in transit or the 
collector was non responsive.

Because it's a lambda, most likely, the function is being shutdown before it has time to send the trace... That's unfortunate and should be solved, in the future, by this issue: https://github.com/quarkusio/quarkus/issues/29448
In the meantime, you need to speedup the flush of the exporter with these properties:
```application.properties
#1 ms
quarkus.otel.bsp.schedule.delay=PT0.001S
quarkus.otel.bsp.max.queue.size=1
quarkus.otel.bsp.max.export.batch.size=1
```

**Comment by jimkont** [comment]
I see, looking into the communication problem. wrt the logs, they come from log aggregation tool in json, I could not verify if they come from the same lambda instance as they get executed after the lambda invocation and lose all the context. I get multiple logs of all the lines there.

Thanks for the lambda configuration hints. Would it also help if I place an `@PreDestroy` hook on the class that handles the requests, inject a `spanProcessor: SpanProcessor` and run `spanProcessor.forceFlush().join(seconds, TimeUnit.SECONDS)`?

**Comment by brunobat** [comment]
We do force the flush but it doesn't seem to be enough: https://github.com/quarkusio/quarkus/blob/09cd8797e531692a18edb9e0fd1c72c9930c8b4c/extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/OpenTelemetryDestroyer.java#L17

**Comment by luneo7** [comment]
We bumped from Quarkus 3.2.x to 3.4.x and we started to get a lot of those logs `io.opentelemetry.sdk.internal.ThrottlingLogger doLog Failed to export spans. The request could not be executed. Full error message: Stream was closed` and before we weren't getting any error,  in our case we export to an AWS OTEL Collector, the collector is running without any error, and it logs no error.

**Comment by luneo7** [comment]
We are actually seeing this error as well in the OTEL collector side: `zapgrpc/zapgrpc.go:195 [core] [Server #1] grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing" {"grpc_log": true}` ... the Vert.x client implementation seems to be handling something different there... since with the OkHTTP client we do not see this error

**Comment by brunobat** [comment]
@luneo7, this will hopefully help: https://github.com/quarkusio/quarkus/pull/36538

**Comment by luneo7** [comment]
Don’t think that it will help as the PR is handling the shutdown, and those logs are happening during the app execution. Even increasing the timeout, and decreasing the batch size didn’t solve it, it reduced the amount of logs but it is still there, but if with OkHTTP that didn’t happen, something is being handled differently by the Vert.x GRPC client…

**Comment by brunobat** [comment]
@luneo7 are you able to get a reproducer?

**Comment by famod** [comment]
While checking something else, I realized that I can reproduce this issue sporadically with the [`opentelemetry-quickstart`](https://github.com/quarkusio/quarkus-quickstarts/tree/main/opentelemetry-quickstart):
- `mvn clean install` (just to make sure it runs in general)
- `docker compose up -d` (watch out, you'll need [#quarkus-quickstarts/1348](https://github.com/quarkusio/quarkus-quickstarts/pull/1348) for compose to work)
- `curl http://localhost:8080/hello` a few times (or use something like [`hey`](https://github.com/rakyll/hey))

**Comment by brunobat** [comment]
Thanks @famod. I'm also working on a setup that produces this error consistently.

**Comment by luneo7** [comment]
Have been sniffing packets to see if there is any difference between OkHttp and Vert.x... the OkHttp client adds content-length, whereas Vert.x adds grpc-accept-encoding (OkHttp uses only accept-encoding)

OkHttp:
<img width="923" alt="image" src="https://github.com/quarkusio/quarkus/assets/8834774/6a4e5e48-0ad8-4e8d-9021-9a608af0e7a3">

Vert.x:
<img width="894" alt="image" src="https://github.com/quarkusio/quarkus/assets/8834774/fc0e2d52-e47d-444f-904d-877f98e286bc">

Besides that didn't find a major difference that would make the connection die, as it happens with Vert.x but doesn't with OkHttp....

One thing that I noted is that OkHttp has a call timeout which is what OTEL uses to set the timeout, and it works by verifying the whole operation... Vert.x on the other hand is setting read timeout with the same value as the OkHttp timeout (`tracesConfig.timeout()`)... just that read timeout is totally different than the call timeout... with vert.x grpc client there is no way to set the whole timeout because we have no access to the `RequestOptions`.... doesn't matter much since the default timeout in the RequestOptions is 0, which means no timeout...

I've found one issue with the current Vert.x implementation is that we have an streaming response, and in the `ClientRequestOnSuccessHandler` we do `request.send(buffer).onSuccess` and the handler there is trying to parse status and other stuff that won't exist at that time, while debugging I've found that `GrpcStatus` is always null and and `statusMessage` is null as well... the fix for that would be actually processing the status when the response ends... we need to run the code/message extraction in the responde endhandler the code would look something like:

```java
request.send(buffer).onSuccess(new Handler<>() {
                    @Override
                    public void handle(GrpcClientResponse<Buffer, Buffer> response) {
                        response.endHandler(new Handler<Void>() {
                                    @Override
                                    public void handle(Void event) {
                                        GrpcStatus status = getStatus(response);
                                        if (status == GrpcStatus.OK) {
                                            exporterMetrics.addSuccess(numItems);
                                            result.succeed();
                                            return;
                                        }
                                        String statusMessage = getStatusMessage(response);
                                        if (statusMessage == null) {
                                            exporterMetrics.addSuccess(numItems);
                                            result.succeed();
                                            return;
                                        }

                                        logAppropriateWarning(status, statusMessage);
                                        exporterMetrics.addFailed(numItems);
                                        result.fail();
                                    }
                                })
                                .exceptionHandler(new Handler<Throwable>() {
                                    @Override
                                    public void handle(Throwable t) {
                                        exporterMetrics.addFailed(numItems);
                                        logger.log(
                                                Level.SEVERE,
                                                "Failed to export "
                                                        + type
                                                        + "s. Stream failed. Full error message: "
                                                        + t.getMessage());
                                        result.fail();
                                    }
                                });
                    }

```

Still don't think that fixing the response parsing will fix the issue... just wanted to share these findings...

In the mean time internally we have made an okhttp exporter extension and we are using that with Quarkus 3.5 overriding (removing) the Vert.x exporter, and not seeing any errors... one thing that I noted that might have brought errors to the default exporter on Quarkus is that the OkHttp version is defaulted to 3.14.9 and okio 1.7.9... and OTEL uses 4.11.0 which brings also a new okio... so there was a version mismatch there... but with our extension we forced the new okhttp version 4.12.0 and okio 3.6.0... with that we had no memory issues nor anything else...

**Comment by luneo7** [comment]
And here is an stack trace for one of those stream closed:
```
handle:340, VertxGrpcExporter$ClientRequestOnSuccessHandler$2 (io.quarkus.opentelemetry.runtime.exporter.otlp)
handle:337, VertxGrpcExporter$ClientRequestOnSuccessHandler$2 (io.quarkus.opentelemetry.runtime.exporter.otlp)
onFailure:117, FutureImpl$2 (io.vertx.core.impl.future)
onFailure:268, FutureImpl$ListenerArray (io.vertx.core.impl.future)
emitFailure:75, FutureBase (io.vertx.core.impl.future)
tryFail:230, FutureImpl (io.vertx.core.impl.future)
onFailure:45, Mapping (io.vertx.core.impl.future)
emitFailure:75, FutureBase (io.vertx.core.impl.future)
tryFail:230, FutureImpl (io.vertx.core.impl.future)
tryFail:23, PromiseImpl (io.vertx.core.impl.future)
fail:183, HttpClientRequestBase (io.vertx.core.http.impl)
handleException:178, HttpClientRequestBase (io.vertx.core.http.impl)
handleException:81, HttpClientRequestImpl (io.vertx.core.http.impl)
handle:-1, 1562917048 (io.vertx.core.http.impl.HttpClientRequestImpl$$Lambda$1069)
handleException:542, Http2ClientConnection$StreamImpl (io.vertx.core.http.impl)
handle:-1, 1652996321 (io.vertx.core.http.impl.VertxHttp2Stream$$Lambda$1092)
emit:55, EventLoopContext (io.vertx.core.impl)
emit:297, ContextBase (io.vertx.core.impl)
onException:95, VertxHttp2Stream (io.vertx.core.http.impl)
onStreamClosed:154, Http2ConnectionBase (io.vertx.core.http.impl)
onStreamClosed:188, VertxHttp2ConnectionHandler (io.vertx.core.http.impl)
notifyClosed:357, DefaultHttp2Connection (io.netty.handler.codec.http2)
removeFromActiveStreams:1007, DefaultHttp2Connection$ActiveStreams (io.netty.handler.codec.http2)
deactivate:963, DefaultHttp2Connection$ActiveStreams (io.netty.handler.codec.http2)
close:515, DefaultHttp2Connection$DefaultStream (io.netty.handler.codec.http2)
close:153, DefaultHttp2Connection (io.netty.handler.codec.http2)
channelInactive:217, Http2ConnectionHandler$BaseDecoder (io.netty.handler.codec.http2)
channelInactive:432, Http2ConnectionHandler (io.netty.handler.codec.http2)
channelInactive:149, VertxHttp2ConnectionHandler (io.vertx.core.http.impl)
invokeChannelInactive:305, AbstractChannelHandlerContext (io.netty.channel)
invokeChannelInactive:281, AbstractChannelHandlerContext (io.netty.channel)
fireChannelInactive:274, AbstractChannelHandlerContext (io.netty.channel)
channelInactive:81, ChannelInboundHandlerAdapter (io.netty.channel)
channelInactive:277, IdleStateHandler (io.netty.handler.timeout)
invokeChannelInactive:303, AbstractChannelHandlerContext (io.netty.channel)
invokeChannelInactive:281, AbstractChannelHandlerContext (io.netty.channel)
fireChannelInactive:274, AbstractChannelHandlerContext (io.netty.channel)
channelInactive:1405, DefaultChannelPipeline$HeadContext (io.netty.channel)
invokeChannelInactive:301, AbstractChannelHandlerContext (io.netty.channel)
invokeChannelInactive:281, AbstractChannelHandlerContext (io.netty.channel)
fireChannelInactive:901, DefaultChannelPipeline (io.netty.channel)
run:813, AbstractChannel$AbstractUnsafe$7 (io.netty.channel)
runTask:173, AbstractEventExecutor (io.netty.util.concurrent)
safeExecute:166, AbstractEventExecutor (io.netty.util.concurrent)
runAllTasks:470, SingleThreadEventExecutor (io.netty.util.concurrent)
run:569, NioEventLoop (io.netty.channel.nio)
run:997, SingleThreadEventExecutor$4 (io.netty.util.concurrent)
run:74, ThreadExecutorMap$2 (io.netty.util.internal)
run:30, FastThreadLocalRunnable (io.netty.util.concurrent)
run:829, Thread (java.lang)
```

**Comment by brunobat** [comment]
Thanks for debugging this @luneo7. Those are great insights.
We decided to remove OkHttp because it depends on Kotlin and we don't provide support for Kotlin based libs, which is the case of OkHttp v4.x+. Same for Wildfly and EAP. 
That's the reason of the version mismatch.
We now need to polish the vert.x client.
An interesting exercise should be to test the vert.x client with the `http/protobuf` protocol, not with `grpc`. FYI, there are discussions in  OTel Java to move the default from `grpc` to `http/protobuf`.

**Comment by luneo7** [comment]
Don't think this is actually related to Quarkus Vert.x client implementation (there is a bug in the Quarkus Vert.x GRCP Exporter when reading the status and status message with the current implementation, as of today it will never ever read those, but that is not causing the stream to close). I have rewritten everything from scratch trying to find something, fixed locally the status and status message retrieval/parsing... and it every time with different implementations it ends in the same error happening from time to time... which kinda points that Netty might be somehow misinterpreting a GRPC message/return from the OTEL collector, so we need to actually debug all the returns with a proxy or a sniffer and check which return form OTEL is making Netty wanna close the stream...

**Comment by brunobat** [comment]
@luneo7 can you please submit a PR with the status handling improvement. We can start from there.

**Comment by luneo7** [comment]
I might have found the issue, it might be related to connection pooling or the actually the lack of it, I will do some more tests tomorrow and if everything goes right I will open the PR with the fixes

**Comment by luneo7** [comment]
Hey @brunobat created a PR that fix the status/statusMessage parsing https://github.com/quarkusio/quarkus/pull/37091 ... I am still testing the other stuff that might (or not) fix the stream closed thing

**Comment by luneo7** [comment]
After the changes above I am not seeing the `apgrpc/zapgrpc.go:195 [core] [Server #1] grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport is closing" {"grpc_log": true}` error in the server logs anymore in my tests =]

**Comment by luneo7** [comment]
Not specifically related... but trying the HTTP exporter, and checking some tracing... it seems that the vert.x http client for OTEL is running on an event loop thread, should it be?

![image](https://github.com/quarkusio/quarkus/assets/8834774/a835b736-3bb9-4d82-83a8-bd629397dd83)

**Comment by brunobat** [comment]
This issue might be a duplicated from https://github.com/quarkusio/quarkus/issues/25102
Taking a look.

**Comment by plevart** [comment]
We are experiencing the issue on Quarkus 3.6.4. on a very lightly loaded development environment. So a speculation above that the default of `quarkus.otel.exporter.otlp.traces.timeout=10` might not be enough is unlikely. We are using otlp grpc port on Grafana Tempo to store traces. The "distributor" (a service that accepts traces) reports the following in the log:

```
level=error ts=2024-01-13T07:47:28.277777424Z caller=rate_limited_logger.go:27 msg="pusher failed to consume trace data" err="context canceled"
```

...which is consistent with your findings. I experimentally changed one deployment to use `http/protobuf` protocol instead of `grpc` and it fixed the issue.

**Comment by famod** [comment]
So what's the status of this?

@plevart 
>  I experimentally changed one deployment to use `http/protobuf` protocol instead of `grpc` and it fixed the issue.

Can you share more details please? Thanks!

**Comment by oudesnepelaar** [comment]
Hi all, for what it's worth I can report we're seeing this issue as well. We use Quarkus + OTEL in a production environment and we recently upgraded to Quarkus 3.6.7. We started seeing this error a lot, and then we increased the timeout as mentioned earlier in the thread, which does reduce the frequency substantially, but does not solve the problem.

**Comment by oudesnepelaar** [comment]
Small update: when switching to http/protobuf ( https://quarkus.io/blog/quarkus-observability-3-3/ ), the problem indeed seems to be no longer occuring. For our purpose this is an acceptable workaround.

**Comment by brunobat** [comment]
@oudesnepelaar This last PR https://github.com/quarkusio/quarkus/pull/37091 should fix the issue.
Please let us know if it worked for you,

**Comment by pospa78** [comment]
I tried switching to quarkus 3.7.3 on one service, but unfortunately the error still appears.
_VertxGrpcExporter - Failed to export spans. The request could not be executed. Full error message: Stream was closed_

We have about 12 services with this problem and it generates thousands of logged errors daily.

**Comment by brunobat** [comment]
@pospa78 can you change to `http/protobuf` instead?
This will become the default soon, anyway.

**Comment by jimkont** [comment]
using`http/protobuf` in 3.7.3 (and earlier) has  a similar issue as @famod mentioned, throws multiple warnings with connection was closed instead of stream was closed
```
Failed to export spans. The request could not be executed. Full error message: Connection was closed: io.vertx.core.http.HttpClosedException: Connection was closed
```

**Comment by geoand** [comment]
I am **not** able to reproduce the issue using the instructions mentioned [here](https://github.com/quarkusio/quarkus/issues/35686#issuecomment-1799305217).

**Comment by brunobat** [comment]
> I am **not** able to reproduce the issue using the instructions mentioned [here](https://github.com/quarkusio/quarkus/issues/35686#issuecomment-1799305217).

Have you tried to generate significant load?

**Comment by geoand** [comment]
Yup

**Comment by jimkont** [comment]
a simple reproducer for me is this app class
```

@QuarkusMain(name = "test")
class Test(
) : QuarkusApplication {

    @WithSpan
    override fun run(@SpanAttribute vararg args: String?): Int {
        foo()
        bar()
        fooBar()
        return 0
    }

    @WithSpan
    fun foo() {
        Thread.sleep(5000)
    }

    @WithSpan
    fun bar() {
        Thread.sleep(5000)
    }

    @WithSpan
    fun fooBar() {
        foo()
        bar()
    }
}
```

using 
```
quarkus:
  package:
    main-class: test
  otel:
    service:
      name: "name"
    exporter:
      otlp:
        traces:
          protocol: http/protobuf
          endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}
          compression: GZIP
    experimental:
      shutdown-wait-time: PT60S
    sdk:
      disabled: false
```
I had the same issue before with the grpc exporter but I found the http one a bit more stable

**Comment by oudesnepelaar** [comment]
Shouldn't the http/protobuf go to port 4318? When I try it on 4318 in our
system, with Quarkus 3.6.7, the issue completely disappears for me.

**Comment by rikcarve** [comment]
Still same issue with Quarkus 3.7.3 and http/protobuf

**Comment by geoand** [comment]
@rikcarve do you perhaps have a sample project I can use to reproduce the problem trivially?

**Comment by geoand** [comment]
@jimkont mind packaging that as an application I can try? Furthermore, what collector are you using?

**Comment by geoand** [comment]
There is a good chance that this manifests because our code only retries once, while the OpenTelemtry code relying on OkHttp seems to retry 5 times.

**Comment by rikcarve** [comment]
> @rikcarve do you perhaps have a sample project I can use to reproduce the problem trivially?

Unfortunately not, but I will also try to strip down. In fact, there is not much, just a simple REST service using quarkus-resteasy-jsonb and quarkus-opentelemetry. But we also have issues in reproducing, e.g. it does not happen locally (quarkus:dev) just once deployed on a test system

**Comment by geoand** [comment]
Yeah, I was afraid of that. The only thing I can think of to do now is to enhance retrying.

**Comment by luneo7** [comment]
Don't think this is retrying... using the OkHttp version I don't see it retrying, and using okhttp I don't see any error log on the OTEL collector side... the thing that is totally different between the vertx and okhttp now besides retrying is that okhttp has its own pool, and the vertx client is using a shared pool, and it seems that under heavy load the request stays in the pool for a while... so the request might be getting cancelled asynchronously... I think that because this is a background task, and telemetry shouldn't impact the capacity of handling requests, and now it is competing with a shared pool... we should make the client use its own pool...

**Comment by geoand** [comment]
> Don't think this is retrying... using the OkHttp version I don't see it retrying, and using okhttp I don't see any error log on the OTEL collector side.

You would not see any error with OkHttp as the retry is handled silently

**Comment by gsmet** [comment]
> okhttp has its own pool, and the vertx client is using a shared pool, and it seems that under heavy load the request stays in the pool for a while

I don't know for sure if it's related to the problem but I wonder if it's something of interest anyway.
In this very case, sharing the same pool might not be the best idea.

**Comment by geoand** [comment]
That analysis does not really apply to Vert.x as the requests are done on an event loop. 
If we added a new event loop pool, apart from the overhead we have tried so hard to keep down, we risk running into the lovely context propagation issues.

**Comment by rikcarve** [comment]
I had another look at our code. It seems it does not happen when calling the resteasy endpoint, but only when 1 of our extension endpoint is called. They are based on pure vertx handlers and added in a custom quarkus extension.

**Comment by geoand** [comment]
@rikcarve can you paste what the handler looks like?

**Comment by rikcarve** [comment]
> @rikcarve can you paste the code of the handler?

```java
public class ControlPortProbeHandler implements Handler<RoutingContext> {
    @Override
    public void handle(RoutingContext context) {
        RequestScopeHelper.withRequestScope(() -> {
            try (var outputStream = new ByteArrayOutputStream()) {
                HttpServerResponse response = context.response();

                SmallRyeHealthReporter reporter = CDI.current().select(SmallRyeHealthReporter.class).get();
                SmallRyeHealth health = reporter.getHealth();

                if (health.isDown()) {
                    response.setStatusCode(503);
                }

                response.headers().set(HttpHeaders.CONTENT_TYPE, "application/json; charset=UTF-8");

                reporter.reportHealth(outputStream, health);
                response.end(Buffer.buffer(outputStream.toByteArray()));

            } catch (IOException e) {
                System.getLogger("ControlPortProbeHandler").log(INFO, e);
            }
        });
    }
}
```

Added with
```java
    @BuildStep
    @Record(ExecutionTime.RUNTIME_INIT)
    RouteBuildItem enableRoute(NonApplicationRootPathBuildItem nonApplicationRootPathBuildItem, ControlPortRecorder recorder, MyConfig config) {
        String root = config.controlport.root.orElse(config.application);
        return nonApplicationRootPathBuildItem.routeBuilder()
                .route("/" + root + "/rest/controlport/enable/:port")
                .routeConfigKey("quarkus.my.controlport.enable-path")
                .handler(recorder.enableHandler())
                .handlerType(HandlerType.BLOCKING)
                .displayOnNotFoundPage()
                .build();
    }
```

**Comment by geoand** [comment]
Thanks!

**Comment by jimkont** [comment]
it turns out I cannot reproduce it locally either, as @rikcarve noted, the example I pasted was a wrong endpoint port, apologies for the confusion.

But we are also observing these errors during deployment. In our case, we are using the `quarkus-amazon-lambda` extension with snapstart enabled

**Comment by geoand** [comment]
In any case, https://github.com/quarkusio/quarkus/pull/38895  makes things more robust

**Comment by luneo7** [comment]
> You would not see any error with OkHttp as the retry is handled silently
What I am saying is that on the server side there is no error log with OkHttp, and with Vert.x client there is a server error log in the collector that comes at the same time as the quarkus error log

**Comment by luneo7** [comment]
One thing that I also noted, is that for OkHTTP, the default max pool size is 5, whereas with vertx we are not setting `setHttp2MaxPoolSize`, so it defaults to `1` (since `DEFAULT_HTTP2_MAX_POOL_SIZE = 1`).... dunno if it also has some impact on something...

**Comment by geoand** [comment]
It shouldn't matter, since we are only making a single (non blocking) call every x secondy

**Comment by luneo7** [comment]
I think that we can make more than one request at time, since there is batch max export span size, defaults 512, or 5 seconds, so if we have a bunch of requests and they exceed 512 under 5 seconds we are going to have simultaneous calls or at least try to

**Comment by geoand** [comment]
When requests are done in a non blocking manner, the queue size does not have the same semantics.

I will however take another look

**Comment by geoand** [comment]
Moreover `quarkus.otel.bsp.max.queue.size` is not the same thing as what @luneo7 described above

**Comment by geoand** [comment]
@cescoffier @vietj what is the reason for `DEFAULT_HTTP2_MAX_POOL_SIZE` being `1`?

**Comment by geoand** [comment]
The only thing I can think of is (maybe was?) that there is some weird in Netty or Vert.x gRPC handling that occasionally causes a connection issue.
With the introduction of more retries in https://github.com/quarkusio/quarkus/pull/38895 that should hopefully go away.

**Comment by cescoffier** [comment]
@geoand @vietj I don't have the exact reason, but...

It's HTTP/2. Each connection can contain streams (channels) to multiplex on a single connection. So, for a client that connects to a single endpoint (which seems to be the case here), establishing a single connection and using streams makes a lot of sense. Now, if your client needs to connect to multiple endpoints (different hostname:port) when, yes, this property needs to be increased. 

If, within a single connection, you reach the maximum number of allowed streams, this is because the server limits that number (for capacity reasons) - so creating a second connection is counterproductive.

**Comment by geoand** [comment]
Right, I thought of the multiplexing after asking the question :)

**Comment by famod** [comment]
So I see that the grpc variant has received a robustness enhancement, which is nice.
I could give that a spin, but given that http/protobuf will become the default soon I'm leaning towards http/protobuf.
Are the last thoughts on pool size etc. also relevant for http/protobuf?

Thing is: I gave http/protobuf a try for at least a day and yes, I used the proper port 4318 for that. Request go directly to Jaeger (through some Hashicorp connect sidecars that handle TLS transparently), no separate collector involved.
Timeout was doubled to 20s.
Still, the error pops up every 5-10 minutes with not that much going on except some scheduled jobs.
I also tried gzip compression to no avail.

Would it make sense to log more details? E.g. how many spans were involved?

**Comment by brunobat** [comment]
> So I see that the grpc variant has received a robustness enhancement, which is nice. I could give that a spin, but given that http/protobuf will become the default soon I'm leaning towards http/protobuf. Are the last thoughts on pool size etc. also relevant for http/protobuf?

Yes, the queue size and other properties above are independent from protocol and should also work in `http/protobub`.

> 
> Thing is: I gave http/protobuf a try for at least a day and yes, I used the proper port 4318 for that. Request go directly to Jaeger (through some Hashicorp connect sidecars that handle TLS transparently), no separate collector involved. Timeout was doubled to 20s. Still, the error pops up every 5-10 minutes with not that much going on except some scheduled jobs. I also tried gzip compression to no avail.
> 
> Would it make sense to log more details? E.g. how many spans were involved?

That can be added to some of the error messages, yes.

**Comment by vietj** [comment]
> @cescoffier @vietj what is the reason for `DEFAULT_HTTP2_MAX_POOL_SIZE` being `1`?

_Clients SHOULD NOT open more than one HTTP/2 connection to a given host and port pair_

https://httpwg.org/specs/rfc9113.html#rfc.section.9.1

**Comment by geoand** [comment]
Thanks!

**Comment by geoand** [comment]
In light of [this](https://github.com/quarkusio/quarkus/pull/38895#issuecomment-1964503335), I am going to close this as fixed. 
We can surely reopen if the problem reappears

**Comment by alexandreqo** [comment]
Para resolver o problema que você está enfrentando, você precisará adicionar uma configuração específica no seu arquivo application.properties e expor a porta correta no seu arquivo docker-compose.yaml.

Passo 1: Atualizar application.properties
Adicione a seguinte linha ao seu arquivo application.properties:
```
quarkus.otel.exporter.otlp.traces.endpoint=http://localhost:4317
```
Essa linha define o endpoint do OpenTelemetry para exportar traces. No caso, estamos configurando para que o endpoint seja http://localhost:4317.

Passo 2: Atualizar docker-compose.yaml
No seu arquivo docker-compose.yaml, você precisa expor a porta 4317 do serviço Jaeger. Adicione ou ajuste a configuração do Jaeger conforme exemplo abaixo:

```
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "4317:4317"  # Exponha a porta 4317 ADICIONE ESSA LINHA
```
Ao fazer isso, você garante que a porta 4317, utilizada para o endpoint de traces do OpenTelemetry, estará acessível.

Resumo
Adicione quarkus.otel.exporter.otlp.traces.endpoint=http://localhost:4317 ao application.properties.
Certifique-se de que a porta 4317 está exposta no serviço Jaeger no docker-compose.yaml.
Se precisar de mais alguma coisa, por favor, avise.
