### ISSUE TITLE
Native build fails on GraalVM built with JDK11

### ISSUE THREAD

**Issue by zeldanerd24** [quarkusio/quarkus#3645]
**Describe the bug**
When building a native executable on a project with the Vert.x extension, using a GraalVM built with JDK11, the build fails.

**Expected behavior**
The build completes successfully.

**Actual behavior**
Build completes exceptionally with the following stacktrace:
```
Error: substitution target for io.quarkus.vertx.runtime.graal.Target_sun_misc_URLClassPath is not loaded. Use field `onlyWith` in the `TargetClass` annotation to make substitution only active when needed.
com.oracle.svm.core.util.UserError$UserException: substitution target for io.quarkus.vertx.runtime.graal.Target_sun_misc_URLClassPath is not loaded. Use field `onlyWith` in the `TargetClass` annotation to make substitution only active when needed.
        at com.oracle.svm.core.util.UserError.abort(UserError.java:65)
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.findTargetClass(AnnotationSubstitutionProcessor.java:823)
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:252)
        at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:230)
        at com.oracle.svm.hosted.NativeImageGenerator.createDeclarativeSubstitutionProcessor(NativeImageGenerator.java:863)
        at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:817)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:520)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:440)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**To Reproduce**
1. Set the JAVA_HOME env variable to the JDK11 path
2. Build GraalVM from source with JDK11 (instructions can be found on their [GitHub repo](https://github.com/oracle/graal/blob/master/vm/README.md))
3. Set the GRAALVM_HOME env variable to /_graal-vm-build-dir_/latest_graalvm_home
4. Create a Quarkus project with the `quarkus-vertx` extension
5. Attempt to build native with `-Dnative-image.docker-build=false` for Maven, or `--docker-build=false` for Gradle

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
```
Linux kermit 3.10.0-957.el7.x86_64 #1 SMP Thu Oct 4 20:48:51 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
 - Output of `java -version`: 
```
openjdk version "11.0.4" 2019-07-16 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.4+11-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.4+11-LTS, mixed mode, sharing)
```
 - GraalVM version (if different from Java): 19.1.1 built from source with JDK11
 - Quarkus version or git rev: 0.20.0
 - Gradle version: 5.5.1

**Comment by gsmet** [comment]
GraalVM does not support JDK 11 yet. You need to use JDK 8 for GraalVM - at least for the time being.

**Comment by greyskyy** [comment]
> GraalVM does not support JDK 11 yet. You need to use JDK 8 for GraalVM - at least for the time being.

@gsmet doesn't this seems to be a quarkus issue? not a GRAAL one?  it seems like the vert.x extension is missing an annotation property.  JDK8 doesn't flag the issue, but it manifests in JDK11.  I could be miss-reading though.

**Comment by gsmet** [comment]
Well this one looks like a Quarkus issue: the Vert.x substitution should probably be conditioned so you're right there's something we should fix.

But in any case, GraalVM still has issues with JDK 11 so there's a good chance it won't run in the end. But you might get lucky as there is steady progress on this.

**Comment by gsmet** [comment]
The fact that GraalVM does not support it means we don't test it and thus you might have issue with it.

This issue could be fixed by adding an `onlyWith` clause to the annotation (it's a simple predicate to code) testing the JDK. But you might have to implement another substitution for the new JDK 11 code.

Feel free to give it a go if you're interested in it, we would love to be more prepared for when GraalVM adds JDK 11 support.

**Comment by gsmet** [comment]
@greyskyy well, if you got further, it's probably worth a PR :).

**Comment by gsmet** [comment]
This particular issue has been fixed and we are making progress toward JDK 11 support.

But in any case, we need JDK 11 support in GraalVM.

I'm closing this one as the original issue has been fixed recently.

**Comment by manodupont** [comment]
Now the JDK Support for 11 and Graal for JDK 11 too, and I still have this
```
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] docker run -v /Users/manueldupont/cjl-scheduler/target/cjl-api-scheduler-1.0.0-SNAPSHOT-native-image-source-jar:/project:z --env LANG=C --rm quay.io/quarkus/ubi-quarkus-native-image:20.2.0-java11 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-DCoordinatorEnvironmentBean.transactionStatusManagerEnable=false -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=1 -J-Drx.unsafe-disable=true -J-Duser.language=en -J-Dfile.encoding=UTF-8 --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -jar cjl-api-scheduler-1.0.0-SNAPSHOT-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -J-Xmx16g -H:-AddAllCharsets -H:EnableURLProtocols=http,https --enable-all-security-services --no-server -H:-UseServiceLoaderFeature -H:+StackTrace cjl-api-scheduler-1.0.0-SNAPSHOT-runner
[cjl-api-scheduler-1.0.0-SNAPSHOT-runner:24]    classlist: 105,428.85 ms,  0.85 GB
[cjl-api-scheduler-1.0.0-SNAPSHOT-runner:24]        setup:   1,837.60 ms,  0.85 GB
Error: substitution target for io.quarkus.runtime.graal.Target_org_slf4j_LoggerFactory is not loaded. Use field `onlyWith` in the `TargetClass` annotation to make substitution only active when needed.
com.oracle.svm.core.util.UserError$UserException: substitution target for io.quarkus.runtime.graal.Target_org_slf4j_LoggerFactory is not loaded. Use field `onlyWith` in the `TargetClass` annotation to make substitution only active when needed.
	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.findTargetClass(AnnotationSubstitutionProcessor.java:839)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:252)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:230)
	at com.oracle.svm.hosted.NativeImageGenerator.createDeclarativeSubstitutionProcessor(NativeImageGenerator.java:915)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:852)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:553)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:468)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Error: Image build request failed with exit status 1
```

**Comment by white-collar** [comment]
As far as I understand problem is still stirring on ? I have the same

```
Error: could not find target field: private static org.apache.camel.quarkus.support.common.runtime.graal.SubstituteBeansWeakCache org.apache.camel.quarkus.support.common.runtime.graal.SubstituteBeansIntrospector.declaredMethodCache
com.oracle.svm.core.util.UserError$UserException: could not find target field: private static org.apache.camel.quarkus.support.common.runtime.graal.SubstituteBeansWeakCache org.apache.camel.quarkus.support.common.runtime.graal.SubstituteBeansIntrospector.declaredMethodCache
        at com.oracle.svm.core.util.UserError.abort(UserError.java:73)
```

**Comment by gsmet** [comment]
@white-collar this has nothing to do with this issue. Make sure your Camel Quarkus and Camel dependencies are consistent and if you still have the issue, you should open an issue in the Camel Quarkus project.
