### ISSUE TITLE
NPE in ArcTestRequestScopeProvider.setup() in native mode with dependency on deployment test jar

### ISSUE THREAD

**Issue by vsevel** [quarkusio/quarkus#3790]
while working on the quarkus vault extension, I encountered a NPE in ArcTestRequestScopeProvider in native mode, after adding a test jar (which contains helper classes to start and configure vault for integration testing) as a test dependency of integration test jpa-postgresql.

may be the issue is in the way I developed the vault extension, and specifically the test jar.
or may be there is a lack of robustness in the quarkus test framework (ie: protecting from NPE), or there is a situation that is not handled when testing native, and an improvement could be done in the test framework.

**To Reproduce**
go to branch:
https://github.com/vsevel/quarkus/tree/issue_NPE_ArcTestRequestScopeProvider

and execute:
```
docker run -d --rm --publish 5432:5432 --name build-postgres -e POSTGRES_USER=hibernate_orm_test -e POSTGRES_PASSWORD=hibernate_orm_test -e POSTGRES_DB=hibernate_orm_test -d postgres:10.5

./mvnw -am clean install \
    --settings azure-mvn-settings.xml \
    -Dnative-image.docker-build -Dtest-postgresql -Dtest-elasticsearch -Dtest-dynamodb -Ddynamodb-local.port=8000 -Dnative-image.xmx=6g -Dnative -Dno-format \
    -pl integration-tests/jpa-postgresql
```

**Expected behavior**
the build should pass

**Actual behavior**
the build fails with:
```
[INFO] Running io.quarkus.it.jpa.postgresql.JPAFunctionalityInGraalITCase
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.001 s <<< FAILURE! - in io.quarkus.it.jpa.postgresql.JPAFunctionalityInGraalITCase
[ERROR] testJPAFunctionalityFromServlet  Time elapsed: 0 s  <<< ERROR!
java.lang.NullPointerException
        at io.quarkus.arc.deployment.ArcTestRequestScopeProvider.setup(ArcTestRequestScopeProvider.java:12)
        at io.quarkus.test.common.TestScopeManager.tearDown(TestScopeManager.java:27)
        at io.quarkus.test.junit.QuarkusTestExtension.beforeEach(QuarkusTestExtension.java:308)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeEachCallbacks$1(TestMethodTestDescriptor.java:151)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeMethodsOrCallbacksUntilExceptionOccurs$5(TestMethodTestDescriptor.java:187)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeMethodsOrCallbacksUntilExceptionOccurs(TestMethodTestDescriptor.java:187)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeEachCallbacks(TestMethodTestDescriptor.java:150)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:129)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:69)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:142)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:117)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux quarkus-fedora 4.15.0-1040-gcp #42~16.04.1-Ubuntu SMP Wed Aug 7 16:42:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~16.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
 - GraalVM version (if different from Java): /home/vvsevel/graalvm-ce-19.1.1/bin/java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-20190711120915.buildslave.jdk8u-src-tar--b08)
OpenJDK 64-Bit GraalVM CE 19.1.1 (build 25.222-b08-jvmci-19.1-b01, mixed mode)
 - Quarkus version or git rev: 

**Additional context**
In the meantime, to workaround the issue in the vault extension, I changed the code to:
https://github.com/vsevel/quarkus/blob/master/extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ArcTestRequestScopeProvider.java#L13-L31

**Comment by mkouba** [comment]
My guess would be that this NPE is caused by the [bug](https://github.com/quarkusio/quarkus/issues/3784) you've already fixed in another [PR](https://github.com/quarkusio/quarkus/pull/3789) ;-). Anyway, I do agree that `ArcTestRequestScopeProvider` should be more robust and log a warning if no `ArcContainer` is available. Would you care to send a PR?

**Comment by vsevel** [comment]
@mkouba 

> My guess would be that this NPE is caused by the bug you've already fixed in another PR ;-)

I thought the same. I did a quick test, but the fix for the other PR did not seem to solve it. I will double check it now that it has been merged.

> ArcTestRequestScopeProvider should be more robust and log a warning

my initial thinking was not to solve it using a test and a warning, because I was afraid to hide a root cause and potentially not using this opportunity to correct a bug (if any) somwhere else.

> Would you care to send a PR?

but yes if everybody believes that the right solution is simply to make the code more robust, I can take care of it.

**Comment by mkouba** [comment]
> I did a quick test, but the fix for the other PR did not seem to solve it.

Well, in that case we should find the root cause first. Is it still reproducible with your branch?

> but yes if everybody believes that the right solution is simply to make the code more robust, I can take care of it.

I believe it's a good solution ;-).

**Comment by vsevel** [comment]
@mkouba I rebased the branch on master, and verified we still had the issue. shall I start now on the PR, or do you want to take a look first at the branch?

**Comment by mkouba** [comment]
Ok. I can see the problem now. The `quarkus-vault-deployment` dependency brings in the `quarkus-arc-deployment` artifact which contains the `ArcTestRequestScopeProvider`.

One thing we could do is to skip TestScopeManager.setup()/tearDown() for a substra

**Comment by mkouba** [comment]
I'm sorry for closing the issue - it wasn't me but some odd keyboard shortcut ;-).

**Comment by vsevel** [comment]
>  The quarkus-vault-deployment dependency brings in the quarkus-arc-deployment

it is there for the AdditionalBeanBuildItem. 

I completed the refactoring discussed here https://github.com/quarkusio/quarkus/pull/2897#issuecomment-527574691 around a spi approach, as opposed to relying on reflection.
I also got rid of the org.eclipse.microprofile.config.spi.ConfigSource in vault (which caused me some issues with the native integration test jpa-postresql-vault), and started relying on a RunTimeConfigurationSourceBuildItem to register the VaultConfigSource.
I also simplified the dependencies by externalizing all testcontainer supporting classes in a new module vault-test, which allows modules such as jpa-postresql-vault to not depend on a test jar of quarkus-vault-deployment anymore. 

all these changes combined (not sure if the last one had any influence) resolved this present issue (either the arc container is not null, or we do not go through ArcTestRequestScopeProvider anymore).

what shall we do:
 - close the bug because the issue was how quarkus-vault was designed
 - go ahead and make the code more robust as discussed above
 - may be the other suggestion "One thing we could do is to skip TestScopeManager.setup()/tearDown() for a substrate test. "

@mkouba @stuartwdouglas please advise how you want to move forward

**Comment by mkouba** [comment]
> it is there for the AdditionalBeanBuildItem.

I do undestand why you need the `AdditionalBeanBuildItem` in the `VaultProcessor` but why do you add the `quarkus-vault-deployment` dependency in the integration test pom? If you need to test the extension you should add the `quarkus-vault` runtime dependency.

> what shall we do:

I'd say we should do both:
1. make `ArcTestRequestScopeProvider` more robust so that it does not throw NPE
2. skip `TestScopeManager.setup()/tearDown()` for a substrate test

But this could be addressed in a separate PR.

**Comment by vsevel** [comment]
@mkouba 

> but why do you add the quarkus-vault-deployment dependency in the integration test pom

it is not the quarkus-vault-deployment that I need, but its test jar, which used to contain testcontainers supporting classes. this is the last item (ie: vault-test) I was discussing in my comment above.
but that part is gone. I introduced a separate module https://github.com/vsevel/quarkus/tree/master/extensions/vault/test and now refer to it in https://github.com/vsevel/quarkus/blob/master/integration-tests/jpa-postgresql-vault/pom.xml#L45-L50 (plus quarkus-vault runtime obviously).

I will shortly create the PR for "make ArcTestRequestScopeProvider more robust so that it does not throw NPE"

thanks for your help.

**Comment by vsevel** [comment]
waiting for CI on https://github.com/quarkusio/quarkus/pull/3869
