### ISSUE TITLE
NPE thrown in Host header parsing (regression)

### ISSUE THREAD

**Issue by mailq** [quarkusio/quarkus#38230]
### Describe the bug

I see NPEs in the access logs when at least the Host-HTTP-Header is broken/invalid.

This looks like a regression of issue #14536.

### Expected behavior

No NPE and stacktrace in the logs.

### How to Reproduce?

1. Create a quarkus starter project (with Gradle)
2. Enable JAX-RS
3. Create simple HelloWorld resource
4. Set quarkus.http.access-log.enabled=true
5. Run it
6. Execute `curl -H "Host:" http://localhost:8080/foo -Lv`

### Output of `uname -a` or `ver`

Linux redacted 6.5.0-14-generic #14-Ubuntu SMP PREEMPT_DYNAMIC Tue Nov 14 14:59:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

OpenJDK Runtime Environment (build 17.0.9+9-Ubuntu-123.10)

### Quarkus version or git rev

3.6.6

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.5

### Additional information

I know that the real culprit is not the mentioned cURL-request . I see the exact kind of stack traces in the log, but don't know the definite source of it. I can narrow it down to a Nagios health check, but don't know the exact request and headers, yet. I'll try to provide that information when I got a real TCP dump of it.

**Comment by gsmet** [comment]
Could you add the full stacktrace in the description?

**Comment by mailq** [comment]
Absolutely, yes:
```
2024-01-16 22:56:56,040 ERROR [io.qua.ver.htt.run.fil.QuarkusRequestWrapper] (vert.x-eventloop-thread-0) Failed to run io.quarkus.vertx.http.runtime.filters.accesslog.AccessLogHandler$1@264d4507: java.lang.NullPointerException
        at io.vertx.core.net.impl.HostAndPortImpl.<init>(HostAndPortImpl.java:141)
        at io.vertx.core.net.HostAndPort.create(HostAndPort.java:20)
        at io.vertx.ext.web.impl.ForwardedParser.calculate(ForwardedParser.java:137)
        at io.vertx.ext.web.impl.ForwardedParser.remoteAddress(ForwardedParser.java:103)
        at io.vertx.ext.web.impl.HttpServerRequestWrapper.remoteAddress(HttpServerRequestWrapper.java:152)
        at io.quarkus.vertx.http.runtime.attribute.RemoteHostAttribute.readAttribute(RemoteHostAttribute.java:23)
        at io.quarkus.vertx.http.runtime.attribute.SubstituteEmptyWrapper$SubstituteEmptyAttribute.readAttribute(SubstituteEmptyWrapper.java:29)
        at io.quarkus.vertx.http.runtime.attribute.CompositeExchangeAttribute.readAttribute(CompositeExchangeAttribute.java:23)
        at io.quarkus.vertx.http.runtime.filters.accesslog.AccessLogHandler$1.handle(AccessLogHandler.java:148)
        at io.quarkus.vertx.http.runtime.filters.accesslog.AccessLogHandler$1.handle(AccessLogHandler.java:145)
        at io.quarkus.vertx.http.runtime.filters.QuarkusRequestWrapper.done(QuarkusRequestWrapper.java:73)
        at io.quarkus.vertx.http.runtime.filters.QuarkusRequestWrapper$ResponseWrapper$3.handle(QuarkusRequestWrapper.java:143)
        at io.quarkus.vertx.http.runtime.filters.QuarkusRequestWrapper$ResponseWrapper$3.handle(QuarkusRequestWrapper.java:140)
        at io.vertx.core.http.impl.Http1xServerResponse.end(Http1xServerResponse.java:442)
        at io.vertx.core.http.impl.Http1xServerResponse.end(Http1xServerResponse.java:410)
        at io.vertx.core.http.impl.Http1xServerResponse.end(Http1xServerResponse.java:478)
        at io.quarkus.vertx.http.runtime.filters.AbstractResponseWrapper.end(AbstractResponseWrapper.java:244)
        at org.jboss.resteasy.reactive.server.vertx.VertxResteasyReactiveRequestContext.end(VertxResteasyReactiveRequestContext.java:351)
        at org.jboss.resteasy.reactive.server.handlers.ResponseWriterHandler.handle(ResponseWriterHandler.java:43)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:147)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at org.jboss.resteasy.reactive.server.handlers.RestInitialHandler.beginProcessing(RestInitialHandler.java:48)
        at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:23)
        at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:10)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1286)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:144)
        at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:59)
        at io.quarkus.vertx.http.runtime.options.HttpServerCommonHandlers$1.handle(HttpServerCommonHandlers.java:37)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1286)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:144)
        at io.quarkus.resteasy.reactive.server.runtime.ResteasyReactiveRecorder$13.handle(ResteasyReactiveRecorder.java:339)
        at io.quarkus.resteasy.reactive.server.runtime.ResteasyReactiveRecorder$13.handle(ResteasyReactiveRecorder.java:332)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1286)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:144)
        at io.quarkus.vertx.http.runtime.filters.accesslog.AccessLogHandler.handle(AccessLogHandler.java:151)
        at io.quarkus.vertx.http.runtime.filters.accesslog.AccessLogHandler.handle(AccessLogHandler.java:93)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1286)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:177)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:144)
        at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$4.handle(VertxHttpHotReplacementSetup.java:192)
        at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$4.handle(VertxHttpHotReplacementSetup.java:181)
        at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
        at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by geoand** [comment]
Thanks, I'll have a look

**Comment by geoand** [comment]
This has already been fixed in `main` as part of bump to Vert.x `4.5.1`. However the problem does manifest in the 3.2 line, so I think we'll need a Vert.x `4.4.7` and a new Quarkus release using it as some point.

cc @vietj @cescoffier

**Comment by cescoffier** [comment]
Yes, it has been fixed in Vert.x

**Comment by geoand** [comment]
Right, but the bug still exists in the 4.4.z which Quarkus 3.2.z uses.

**Comment by cescoffier** [comment]
https://github.com/eclipse-vertx/vert.x/pull/4884 is in Vert.x 4.4.

**Comment by mailq** [comment]
Just got the exact request and that does not even have a Host header.
To simulate the culprit request I run
```
nc localhost 8080 << EOF
GET / HTTP/1.0
User-Agent: check_http/v2.3.3 (nagios-plugins 2.3.3)
Connection: close
Accept: */*

EOF
```
This "bug" exists in Quarkus 3.6.6 with Vert.x 4.4.6. Sure one should change the request in Nagios, but nontheless it looks like a valid HTTP request to me.

Therefore this issue should not be closed. The cURL-Host-Command fails and also the netcat command fails. Although I'm currently looking for the main cause. Or should I open an issue in Vert.x?

**Comment by geoand** [comment]
> Therefore this issue should not be closed.

The issue was closed because the problem no longer occurs in Quarkus `main`. If you can prove otherwise, I'll reopen it.

**Comment by gsmet** [comment]
What's weird is that the PR pointed by @cescoffier is apparently in 4.4.6 if the milestone attached to the PR is right. And if it's the fix then we shouldn't have the issue in 3.2. Is there more to it @cescoffier ?

**Comment by cescoffier** [comment]
I will check, but yes, I'm surprised we still have the bug.

**Comment by mailq** [comment]
New information and verification. Reproduced with the simplest Vert.x starter project.

```
public class MainVerticle extends AbstractVerticle {

  @Override
  public void start(Promise<Void> startPromise) throws Exception {
    var router = Router.router(vertx);
    router.route().handler(LoggerHandler.create());
    vertx.createHttpServer().requestHandler(router).listen(8080, http -> {
      if (http.succeeded()) {
        startPromise.complete();
        System.out.println("HTTP server started on port 8080");
      } else {
        startPromise.fail(http.cause());
      }
    });
  }
```
The netcat command above fails in version 4.4.6 and also in 4.5.0. In 4.5.1 it works flawlessly.

Btw: The general request handling never fails. It is just the access logging that throws the Exception.

So it will work (again) in the future when Vert.x 4.5.1 is integrated.

**Comment by geoand** [comment]
> So it will work (again) in the future when Vert.x 4.5.1 is integrated.

This is already the case in `main`, so the upcoming Quarkus `3.7.0.CR1` will include it.

**Comment by cescoffier** [comment]
Thanks for the pire vertx reproducer! I will ping the vertx team and see when we can have a 4.4 with the patch.
