### ISSUE TITLE
dev mode reload - rabbitmq - multiple rabbitmq connections

### ISSUE THREAD

**Issue by rastislavpapp** [quarkusio/quarkus#39433]
### Describe the bug

I'm consuming from a rabbitmq queue in my quarkus app. When reloading the app in dev mode, I'm expecting that the app will disconnect from RabbitMQ, and then connect again. This is what happens, but after the reload, there is 2 connections to the queue instead of 1. I think it's because when disconnecting, a shutdown handler of a queue consumer is triggered (see `io.vertx.rabbitmq.impl.RabbitMQClientImpl#basicConsumer`), which reconnects back. And then the app reloads and connects again. 

### Expected behavior

after dev mode reload, there should be only 1 connection to consumed queue

### Actual behavior

after dev mode reload, there are multiple connections to consumed queue

**Comment by cescoffier** [comment]
Which version of Quarkus are you using? I fixed an issue related to that recently.

**Comment by rastislavpapp** [comment]
3.8.2

**Comment by cescoffier** [comment]
Could you provide a standalone minimal reproducer?

**Comment by rastislavpapp** [comment]
Reproduction would need an existing rabbitmq server, as using devservices would affect the problem itself (I think, I can't get docker to work on my machine because of company policy)... so the reproducer would just be an app with a connection to rabbitmq server. I created a simple one - https://github.com/rastislavpapp/quarkus-39433-bug-reproducer

The issue happens every time I restart (via dev mode).

**Comment by Inithron** [comment]
Hi,
Currently the [shared server](https://quarkus.io/guides/mongodb-dev-services#shared-server) of the MongoDB extension and the [shared broker](https://quarkus.io/guides/kafka#shared-broker) of the Kafka extension are not working properly. For both issues exists already: #38678 & #41788. But on both issues is since one month no or no more progress. So I did a research to see if the creator of these issues and I am the only one who are affect of this problem, or if there are more. And I figured out that there are more. Here is a list of all open issues which are (from my point of view) related to the problem:

- #38678
- #41788
- #40376
- #6536
- #39433
- #27243
- #25474
- #40005
- #20037

As a short summary:
It should be possible to share resources in dev and on test mode. It is totally fine not to share the resources in test mode by default, but at least there should be the possibility to enable this option.

Due to the case that many extensions are affected by this issue, it would be great to solve this issue in a central place, if possible. If not maybe the contributors of the different extensions could support each other to solve the issues for each extension individually.

**Comment by seb5433** [comment]
@rastislavpapp did you find a temporary solution for this bug?

**Comment by gsmet** [comment]
@ozangunalp this one looks annoying and in the way of the Quarkus developer experience as it makes dev mode kinda unusable.

Any chance you could have a look in January?

**Comment by ozangunalp** [comment]
@gsmet normally it has been fixed with the latest reactive messaging release. I didn't have time to close these issues. I'll re-test and close them in early January.

**Comment by medcrypt-matt** [comment]
Still a problem with 3.15.2 when using RabbitMQ 4.0-management docker image as opposed to the default dev services impl.
