### ISSUE TITLE
Qute using varargs yields "Method X not found on the base object" error 

### ISSUE THREAD

**Issue by markus-lehr-dedalus** [quarkusio/quarkus#40072]
### Describe the bug

When using Qute 2.16.12 I am trying to call a CDI bean's method with the signature 
`public String executeFunction(Invocable invocable, String functionName, Object... args)`.
Calling this function without any arguments works fine, however, providing one or more arguments (myProperty is a string in this case) results in
`Rendering error: Method "executeFunction(jsExecutionContext,"jsFunctionName",myProperty.or(null))" not found on the base object "*packages*.FunctionTemplateExtension_Subclass" in expression {cdi:functionTemplateExtension.executeFunction(jsExecutionContext,"jsFunctionName",myProperty.or(null))}`

### Expected behavior

The method is called correctly and the resulting string is rendered.

### Actual behavior

The method is not called and a TemplateException with the message:
`Rendering error: Method "executeFunction(jsExecutionContext,"jsFunctionName",myProperty.or(null))" not found on the base object "*packages*.FunctionTemplateExtension_Subclass" in expression {cdi:functionTemplateExtension.executeFunction(jsExecutionContext,"jsFunctionName",myProperty.or(null))}`
is thrown.

### How to Reproduce?

Render a Qute template in Qute 2.16.12 with the string
`{cdi:functionTemplateExtension.executeFunction(jsExecutionContext,"coalesce",param1,param2)}`
on an extension (marked as `@Dependent @Named("functionTemplateExtension")`) with a method `public String executeFunction(Invocable invocable, String functionName, Object... args)`  

### Output of `uname -a` or `ver`

Linux Hostname 5.15.146.1-microsoft-standard-WSL2 #1 SMP Thu Jan 11 04:09:03 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

 openjdk version "17.0.9" 2023-10-17 LTS OpenJDK Runtime Environment Corretto-17.0.9.8.1 (build 17.0.9+8-LTS) OpenJDK 64-Bit Server VM Corretto-17.0.9.8.1 (build 17.0.9+8-LTS, mixed mode, sharing)

### Quarkus version or git rev

2.16.12.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3 (Red Hat 3.6.3-13)

### Additional information

I've seen other reports mentioning errors with 1 varargs parameter ( e.g. https://github.com/quarkusio/quarkus/issues/31449 ), but they don't seem connected as my version should contain the fix and the errors still occur when having two or more parameters.

**Comment by mkouba** [comment]
@markus-lehr-dedalus Have you tried with some newer version, i.e. Quarkus 3.2 or 3.8? I do remember that some problems with varargs parameters were fixed.

**Comment by markus-lehr-dedalus** [comment]
> Have you tried with some newer version, i.e. Quarkus 3.2 or 3.8?

I created a small reproducer project with both Quarkus 3.8.3 and 3.2.11.Final and indeed the varargs issue persists for CDI beans.
If you look at the test: [QuteVarargsTest.java](https://github.com/markus-lehr-dedalus/qute-varargs-reproducer/blob/master/src/test/java/org/example/QuteVarargsTest.java)
You can see that varargs work with static namespaced extension methods (first few tests with obj:varargs) but not with the cdi bean's method (i.e. the last 3 tests fail). (Just to prove that the cdi bean *is* being called and works for non-varargs methods, I created an identity method which just returns whatever int is being haded to it).

**Comment by mkouba** [comment]
@markus-lehr-dedalus So I've tried to reproduce the problem locally and found an error in the test. The [first parameter](https://github.com/markus-lehr-dedalus/qute-varargs-reproducer/blob/master/src/main/java/org/example/CdiExtension.java#L9) of the method declared on the `CdiExtension` is `long` but you pass an integer literal in the template. If you change the type of the param to `int` or modify the template like `{cdi:varargsTemplateExtension.varargs(5l, foo)}` then the test passes.

That said, I understand that Java does convert the type automatically (Widening Primitive Conversion) but templates don't support this feature yet.

**Comment by markus-lehr-dedalus** [comment]
@mkouba - Thank you for trying this out! Yes if I change the signature to match (I've tried Strings to ensure not confusing ints and longs again..) the tests pass on both 3.2 and 3.8 versions.

I'm still running into the issue with the 2.16 version my company uses, but I'll just use the workaround of calling a wrapper method on a non-cdi bean.
```java
@TemplateExtension(namespace = "obj")
public class ObjectExtensionMethods {
    public static Object[] varargs(Object... args) {
        return args;
    }
}
```

(Not knowing the workflow on this repo I'm fine with this ticket being closed)

**Comment by mkouba** [comment]
> @mkouba - Thank you for trying this out! Yes if I change the signature to match (I've tried Strings to ensure not confusing ints and longs again..) the tests pass on both 3.2 and 3.8 versions.

:+1: 

> 
> I'm still running into the issue with the 2.16 version my company uses, but I'll just use the workaround of calling a wrapper method on a non-cdi bean.

Unfortunately, we do not plan to backport any qute-related fixes into 2.16. But your workaround seems reasonable. 

> 
> ```java
> @TemplateExtension(namespace = "obj")
> public class ObjectExtensionMethods {
>     public static Object[] varargs(Object... args) {
>         return args;
>     }
> }
> ```
> 
> (Not knowing the workflow on this repo I'm fine with this ticket being closed)

Yes, I will close this issue and create a new one to implement "Widening Primitive Conversion" in templates.
