### ISSUE TITLE
When Using Liquibase in Native Mode a ServiceConfigurationError is Logged

### ISSUE THREAD

**Issue by gcw-it** [quarkusio/quarkus#40575]
### Describe the bug

When Using Liquibase in Native Mode a ServiceConfigurationError is Logged.
This happens at least with Postgresql and H2.
The issue occurs at least since Quarkus 3.8.2
The error occurs for a local as well as an in-container build.
There seem to be no negative consequences of this error, besides polluting the application log.

### Expected behavior

No Error is logged.

### Actual behavior

At Quarkus start the following error is logged:

```
INFO  [liq.servicelocator] (main) Cannot load service: java.util.ServiceConfigurationError: liquibase.command.CommandStep: Provider liquibase.command.core.StartH2CommandStep not found
	at java.base@21.0.3/java.util.ServiceLoader.fail(ServiceLoader.java:593)
	at java.base@21.0.3/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1219)
	at java.base@21.0.3/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1228)
	at java.base@21.0.3/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
	at java.base@21.0.3/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
	at java.base@21.0.3/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
	at liquibase.servicelocator.StandardServiceLocator.findInstances(StandardServiceLocator.java:22)
	at liquibase.command.CommandFactory.findAllInstances(CommandFactory.java:244)
	at liquibase.command.CommandFactory.computePipelineForCommandDefinition(CommandFactory.java:71)
	at liquibase.command.CommandFactory.getCommandDefinition(CommandFactory.java:50)
	at liquibase.command.CommandScope.<init>(CommandScope.java:64)
	at liquibase.Liquibase.lambda$validate$25(Liquibase.java:1365)
	at liquibase.Scope.lambda$child$0(Scope.java:190)
	at liquibase.Scope.child(Scope.java:199)
	at liquibase.Scopefor child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:168)
	at liquibase.Liquibase.runInScope(Liquibase.java:1436)
	at liquibase.Liquibase.validate(Liquibase.java:1364)
	at io.quarkus.liquibase.runtime.LiquibaseRecorder.doStartActions(LiquibaseRecorder.java:79)
	at io.quarkus.deployment.steps.LiquibaseProcessor$startLiquibase1744275855.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.LiquibaseProcessor$startLiquibase1744275855.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
```

The error is exactly the same for Postgresql and H2.
It probably occurs for other databases as well.

### How to Reproduce?

1. Use the `liquibase-quickstart` from `quarkus-quickstarters`.
2. Run a H2 instance with **remote database creation** enabled.
3. Compile and run the app in native mode.

### Output of `uname -a` or `ver`

Darwin 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:11:05 PDT 2024; root:xnu-10063.101.17~1/RELEASE_X86_64 x86_64

### Output of `java -version`

java 21.0.3 2024-04-16 LTS Java(TM) SE Runtime Environment Oracle GraalVM 21.0.3+7.1 (build 21.0.3+7-LTS-jvmci-23.1-b37) Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 21.0.3+7.1 (build 21.0.3+7-LTS-jvmci-23.1-b37, mixed mode, sharing)

### Quarkus version or git rev

3.10.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)

**Comment by geoand** [comment]
cc @famod you looked into this last

**Comment by HerrDerb** [comment]
Does this fix only the h2 issue? We too experience this with postgres

**Comment by geoand** [comment]
Right, this was closed by mistake.

**Comment by geoand** [comment]
How does one reproduce this for postgres?

**Comment by HerrDerb** [comment]
I'll try to provide a reproducer

**Comment by gcw-it** [comment]
You can use the steps outlined in issue [40574](https://github.com/quarkusio/quarkus/issues/40574) under _How to Reproduce? _ to replicate the error for postgres.

**Comment by geoand** [comment]
I can confirm that I get:

```
liquibase.exception.DatabaseException: Error executing SQL UPDATE public.databasechangeloglock SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1: ERROR: relation "public.databasechangeloglock" does not exist
```

when using Postgres, but I have no idea what that means.

**Comment by HerrDerb** [comment]
Yes, especially when you don't have an h2 dependency.

**Comment by geoand** [comment]
My best guess is that we should always do `() -> true` from https://github.com/quarkusio/quarkus/blob/509ec821a35d7d8edb0ee8a4d917468415786c72/extensions/liquibase/deployment/src/main/java/io/quarkus/liquibase/deployment/LiquibaseProcessor.java#L256.

Do you want to try that out in your applications?

**Comment by gcw-it** [comment]
> Brilliant, thank you. ~I can approve that we also use `quarkus.liquibase.migrate-at-start=true`~ We seem NOT to set `quarkus.liquibase.clean-at-start=true`

You're right. This setting is only required to reproduce the issue addressed in the linked topic.  
In this context the setting is unnecessary.

**Comment by HerrDerb** [comment]
> My best guess is that we should always do `() -> true` from
> 
> https://github.com/quarkusio/quarkus/blob/509ec821a35d7d8edb0ee8a4d917468415786c72/extensions/liquibase/deployment/src/main/java/io/quarkus/liquibase/deployment/LiquibaseProcessor.java#L256
> 
> .
> Do you want to try that out in your applications?

Without having it tried yet, as far as I understand, I agree that this probably should not be filtered out as the class will be loaded by the service loader of liquibase: https://github.com/liquibase/liquibase/blob/master/liquibase-standard/src/main/resources/META-INF/services/liquibase.command.CommandStep#L31

**Comment by Khanhtran9x** [comment]
Hello team, I am still facing this issue when running native image, it is still not fixed, could you guy the process for this issue and when the fix could be released? Many thanks
`2024-06-22 10:12:39,768 INFO  [liq.database] (main) Set default schema name to public
2024-06-22 10:12:39,786 INFO  [liq.lockservice] (main) Successfully acquired change log lock
2024-06-22 10:12:39,788 INFO  [liq.servicelocator] (main) Cannot load service: java.util.ServiceConfigurationError: liquibase.command.CommandStep: Provider liquibase.command.core.StartH2CommandStep not found
        at java.base@21.0.3/java.util.ServiceLoader.fail(ServiceLoader.java:593)
        at java.base@21.0.3/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1219)
        at java.base@21.0.3/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1228)
        at java.base@21.0.3/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
        at java.base@21.0.3/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
        at java.base@21.0.3/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
        at liquibase.servicelocator.StandardServiceLocator.findInstances(StandardServiceLocator.java:22)
        at liquibase.command.CommandFactory.findAllInstances(CommandFactory.java:244)
        at liquibase.command.CommandFactory.computePipelineForCommandDefinition(CommandFactory.java:71)
        at liquibase.command.CommandFactory.getCommandDefinition(CommandFactory.java:50)
        at liquibase.command.CommandScope.<init>(CommandScope.java:64)
        at liquibase.Liquibase.lambda$validate$25(Liquibase.java:1365)
        at liquibase.Scope.lambda$child$0(Scope.java:190)
        at liquibase.Scope.child(Scope.java:199)
        at liquibase.Scope.child(Scope.java:189)
        at liquibase.Scope.child(Scope.java:168)
        at liquibase.Liquibase.runInScope(Liquibase.java:1436)
        at liquibase.Liquibase.validate(Liquibase.java:1364)
        at io.quarkus.liquibase.runtime.LiquibaseRecorder.doStartActions(LiquibaseRecorder.java:82)
        at io.quarkus.deployment.steps.LiquibaseProcessor$startLiquibase1744275855.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.LiquibaseProcessor$startLiquibase1744275855.deploy(Unknown Source)
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)

2024-06-22 10:12:39,793 INFO  [liq.command] (main) Logging exception.
ERROR: Exception Details
ERROR: Exception Primary Class:  XSDLookUpException
ERROR: Exception Primary Reason:  Unable to resolve xml entity http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.8.xsd. liquibase.secureParsing is set to 'true' which does not allow remote lookups. Check for spelling or capitalization errors and missing extensions such as liquibase-commercial in your XSD definition. Or, set it to 'false' to allow remote lookups of xsd files.
ERROR: Exception Primary Source:  PostgreSQL 15.3
2024-06-22 10:12:39,793 INFO  [liq.command] (main) Command execution complete
2024-06-22 10:12:39,796 INFO  [liq.lockservice] (main) Successfully released change log lock
2024-06-22 10:12:39,802 ERROR [io.qua.run.Application] (main) Failed to start application (with profile [prod]): java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Caused by: java.lang.IllegalStateException: Error starting Liquibase
        at io.quarkus.liquibase.runtime.LiquibaseRecorder.doStartActions(LiquibaseRecorder.java:93)
        at io.quarkus.deployment.steps.LiquibaseProcessor$startLiquibase1744275855.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.LiquibaseProcessor$startLiquibase1744275855.deploy(Unknown Source)
        ... 7 more
Caused by: liquibase.exception.CommandExecutionException: liquibase.exception.ChangeLogParseException: liquibase.parser.core.xml.XSDLookUpException: Unable to resolve xml entity http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.8.xsd. liquibase.secureParsing is set to 'true' which does not allow remote lookups. Check for spelling or capitalization errors and missing extensions such as liquibase-commercial in your XSD definition. Or, set it to 'false' to allow remote lookups of xsd files.
        at liquibase.command.CommandScope.execute(CommandScope.java:257)
        at liquibase.Liquibase.lambda$validate$25(Liquibase.java:1369)
        at liquibase.Scope.lambda$child$0(Scope.java:190)
        at liquibase.Scope.child(Scope.java:199)
        at liquibase.Scope.child(Scope.java:189)
        at liquibase.Scope.child(Scope.java:168)
        at liquibase.Liquibase.runInScope(Liquibase.java:1436)
        at liquibase.Liquibase.validate(Liquibase.java:1364)
        at io.quarkus.liquibase.runtime.LiquibaseRecorder.doStartActions(LiquibaseRecorder.java:82)
        ... 9 more
Caused by: liquibase.exception.ChangeLogParseException: liquibase.parser.core.xml.XSDLookUpException: Unable to resolve xml entity http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.8.xsd. liquibase.secureParsing is set to 'true' which does not allow remote lookups. Check for spelling or capitalization errors and missing extensions such as liquibase-commercial in your XSD definition. Or, set it to 'false' to allow remote lookups of xsd files.
        at liquibase.parser.core.xml.XMLChangeLogSAXParser.parseToNode(XMLChangeLogSAXParser.java:154)
        at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:15)
        at liquibase.command.core.helpers.DatabaseChangelogCommandStep.lambda$getDatabaseChangeLog$0(DatabaseChangelogCommandStep.java:129)
        at liquibase.Scope.child(Scope.java:199)
        at liquibase.Scope.child(Scope.java:175)
        at liquibase.command.core.helpers.DatabaseChangelogCommandStep.getDatabaseChangeLog(DatabaseChangelogCommandStep.java:128)
        at liquibase.command.core.helpers.DatabaseChangelogCommandStep.run(DatabaseChangelogCommandStep.java:87)
        at liquibase.command.CommandScope.execute(CommandScope.java:219)
        ... 17 more
Caused by: liquibase.parser.core.xml.XSDLookUpException: Unable to resolve xml entity http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.8.xsd. liquibase.secureParsing is set to 'true' which does not allow remote lookups. Check for spelling or capitalization errors and missing extensions such as liquibase-commercial in your XSD definition. Or, set it to 'false' to allow remote lookups of xsd files.
        at liquibase.parser.core.xml.LiquibaseEntityResolver.resolveEntity(LiquibaseEntityResolver.java:75)
        at java.xml@21.0.3/com.sun.org.apache.xerces.internal.util.EntityResolver2Wrapper.resolveEntity(EntityResolver2Wrapper.java:178)
        at java.xml@21.0.3/com.sun.org.apache.xerces.internal.impl.XMLEntityManager.resolveEntity(XMLEntityManager.java:1135)
        at java.xml@21.0.3/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.resolveDocument(XMLSchemaLoader.java:663)
        at java.xml@21.0.3/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.findSchemaGrammar(XMLSchemaValidator.java:2695)
        at java.xml@21.0.3/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:2070)
        at java.xml@21.0.3/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.startElement(XMLSchemaValidator.java:830)
        at java.xml@21.0.3/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:376)
        at java.xml@21.0.3/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl$NSContentDriver.scanRootElementHook(XMLNSDocumentScannerImpl.java:615)
        at java.xml@21.0.3/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3079)
        at java.xml@21.0.3/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:836)
        at java.xml@21.0.3/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
        at java.xml@21.0.3/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:114)
        at java.xml@21.0.3/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:542)
        at java.xml@21.0.3/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:889)
        at java.xml@21.0.3/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:825)
        at java.xml@21.0.3/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at java.xml@21.0.3/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224)
        at java.xml@21.0.3/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:637)
        at liquibase.parser.core.xml.XMLChangeLogSAXParser.parseToNode(XMLChangeLogSAXParser.java:121)
        ... 24 more`

**Comment by geoand** [comment]
Can someone try https://github.com/quarkusio/quarkus/pull/41414 and see if it fixes their problem?
