### ISSUE TITLE
Rest Client + Spring Di issue

### ISSUE THREAD

**Issue by lbernardomaia** [quarkusio/quarkus#4169]
**Describe the bug**
Looks like there an issue to run the Rest Client with Spring Di.

The error can be reproduced using the rest-client project from quarkus-quickstarts.

CountriesResource:
```
@Path("/country")
public class CountriesResource {

//    @Inject
    @Autowired
    @RestClient
    CountriesService countriesService;


    @GET
    @Path("/name/{name}")
    @Produces(MediaType.APPLICATION_JSON)
    public Set<Country> name(@PathParam("name") String name) {
        return countriesService.getByName(name);
    }

    @GET
    @Path("/name-async/{name}")
    @Produces(MediaType.APPLICATION_JSON)
    public CompletionStage<Set<Country>> nameAsync(@PathParam("name") String name) {
        return countriesService.getByNameAsync(name);
    }
}
```

Pom.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.acme</groupId>
    <artifactId>rest-client</artifactId>
    <version>1.0-SNAPSHOT</version>
    <properties>
        <quarkus.version>0.22.0</quarkus.version>
        <spring.version>5.1.4.RELEASE</spring.version>
        <surefire-plugin.version>2.22.1</surefire-plugin.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.quarkus</groupId>
                <artifactId>quarkus-bom</artifactId>
                <version>${quarkus.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-spring-di</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy-jsonb</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest-client</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-junit5</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${surefire-plugin.version}</version>
                <configuration>
                    <systemProperties>
                        <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                    </systemProperties>
                </configuration>
            </plugin>
            <plugin>
                <groupId>io.quarkus</groupId>
                <artifactId>quarkus-maven-plugin</artifactId>
                <version>${quarkus.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>build</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    <profiles>
        <profile>
            <id>native</id>
            <activation>
                <property>
                    <name>native</name>
                </property>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>io.quarkus</groupId>
                        <artifactId>quarkus-maven-plugin</artifactId>
                        <version>${quarkus.version}</version>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>native-image</goal>
                                </goals>
                                <configuration>
                                    <enableHttpUrlHandler>true</enableHttpUrlHandler>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-failsafe-plugin</artifactId>
                        <version>${surefire-plugin.version}</version>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>integration-test</goal>
                                    <goal>verify</goal>
                                </goals>
                                <configuration>
                                    <systemProperties>
                                        <native.image.path>${project.build.directory}/${project.build.finalName}-runner</native.image.path>
                                    </systemProperties>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
```

When a run `mvn verify -Pnative` I get the following log:

```
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: org.apache.logging.log4j.Level. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Trace: 
        at parsing org.apache.commons.logging.LogAdapter$Log4jLog.warn(LogAdapter.java:220)
Call path from entry point to org.apache.commons.logging.LogAdapter$Log4jLog.warn(Object, Throwable): 
        at org.apache.commons.logging.LogAdapter$Log4jLog.warn(LogAdapter.java:220)
        at org.apache.http.conn.util.PublicSuffixMatcherLoader.getDefault(PublicSuffixMatcherLoader.java:94)
        at org.jboss.resteasy.client.jaxrs.engines.ClientHttpEngineBuilder43.build(ClientHttpEngineBuilder43.java:72)
        at org.jboss.resteasy.client.jaxrs.internal.ResteasyClientBuilderImpl.build(ResteasyClientBuilderImpl.java:368)
        at org.jboss.resteasy.microprofile.client.RestClientBuilderImpl.build(RestClientBuilderImpl.java:264)
        at io.quarkus.restclient.runtime.RestClientBase.create(RestClientBase.java:32)
        at org.acme.restclient.CountriesService_227c24c32108bffd8a2bb75ee3e89bd56a30c183_Synthetic_Bean.create(CountriesService_227c24c32108bffd8a2bb75ee3e89bd56a30c183_Synthetic_Bean.zig:203)
        at org.acme.restclient.CountriesService_227c24c32108bffd8a2bb75ee3e89bd56a30c183_Synthetic_Bean.create(CountriesService_227c24c32108bffd8a2bb75ee3e89bd56a30c183_Synthetic_Bean.zig:40)
        at io.quarkus.undertow.runtime.HttpSessionContext.lambda$getContextualInstances$0(HttpSessionContext.java:138)
        at io.quarkus.undertow.runtime.HttpSessionContext$$Lambda$499/1748125487.apply(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.SpinedBuffer.forEach(SpinedBuffer.java:246)
        at java.util.stream.Nodes$SpinedNodeBuilder.forEach(Nodes.java:1262)
        at java.util.stream.SpinedBuffer.toString(SpinedBuffer.java:269)
        at java.lang.String.valueOf(String.java:2994)
        at java.lang.StringBuilder.append(StringBuilder.java:131)
        at com.oracle.svm.core.amd64.AMD64CPUFeatureAccess.verifyHostSupportsArchitecture(AMD64CPUFeatureAccess.java:179)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:125)
        at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
--------------------------------------------------------------------------------------------
-- WARNING: The above stack trace is not a real stack trace, it is a theoretical call tree---
-- If an interface has multiple implementations SVM will just display one potential call  ---
-- path to the interface. This is often meaningless, and what you actually need to know is---
-- the path to the constructor of the object that implements this interface.              ---
-- Quarkus has attempted to generate a more meaningful call flow analysis below          ---
---------------------------------------------------------------------------------------------

Possible path to org.apache.commons.logging.LogAdapter$Log4jLog.warn(java.lang.Object, java.lang.Throwable):v
        org.apache.commons.logging.LogAdapter$Log4jLog.warn(java.lang.Object, java.lang.Throwable):v
This is an implementation of org.apache.commons.logging.Log printing path to constructors of org.apache.commons.logging.LogAdapter$Log4jLog


Possible path to org.apache.commons.logging.LogAdapter$Log4jLog.<init>(java.lang.String):v
        org.apache.commons.logging.LogAdapter$Log4jLog.<init>(java.lang.String):v
        org.apache.commons.logging.LogAdapter$Log4jAdapter.createLog(java.lang.String):o
        org.apache.commons.logging.LogAdapter.createLog(java.lang.String):o
        org.apache.commons.logging.LogFactory.getLog(java.lang.String):o
        org.apache.commons.logging.LogFactory.getLog(java.lang.Class):o
        org.apache.http.conn.ssl.DefaultHostnameVerifier.<init>(org.apache.http.conn.util.PublicSuffixMatcher):v
        org.jboss.resteasy.client.jaxrs.engines.ClientHttpEngineBuilder43.build():o
        org.jboss.resteasy.client.jaxrs.ClientHttpEngineBuilder.build():o
        org.jboss.resteasy.client.jaxrs.internal.ResteasyClientBuilderImpl.build():o
        org.jboss.resteasy.client.jaxrs.ResteasyClientBuilder.build():o
        org.jboss.resteasy.microprofile.client.RestClientBuilderImpl.build(java.lang.Class):j
        org.eclipse.microprofile.rest.client.RestClientBuilder.build(java.lang.Class):j
        io.quarkus.restclient.runtime.RestClientBase.create():j
        org.acme.restclient.CountriesService_227c24c32108bffd8a2bb75ee3e89bd56a30c183_Synthetic_Bean.create(javax.enterprise.context.spi.CreationalContext):o
        org.acme.restclient.CountriesService_227c24c32108bffd8a2bb75ee3e89bd56a30c183_Synthetic_Bean.create(javax.enterprise.context.spi.CreationalContext):o
        org.acme.restclient.CountriesService_227c24c32108bffd8a2bb75ee3e89bd56a30c183_Synthetic_Bean.create(javax.enterprise.context.spi.CreationalContext):j
This is an implementation of io.quarkus.arc.InjectableBean printing path to constructors of org.acme.restclient.CountriesService_227c24c32108bffd8a2bb75ee3e89bd56a30c183_Synthetic_Bean

```

**Comment by gsmet** [comment]
I don't know why Spring causes this but we shouldn't have `commons-logging` in the classpath: we should use the JBoss Logging adapter.

@geoand could you have a look?

**Comment by geoand** [comment]
Hi,

I think this has already been resolved on master since I remember seeing it before. Let me check and I'll post back the details

**Comment by geoand** [comment]
I had missed spring-di!

Should be fixed in #4170. 

Thanks for reporting!

**Comment by manodupont** [comment]
Sorry to interrupt, whats the fix exactly ?!? I did remove every logging stuff from my app and I still have that! Whats the dep I should exclude ?!

thanks
