### ISSUE TITLE
Quarkus CLI TLS command generating Quarkus DEV certificate authority succeeds but ends with error exit code

### ISSUE THREAD

**Issue by michalvavrik** [quarkusio/quarkus#42894]
### Describe the bug

I am using Quarkus CLI tls command in CI so I care about exit codes, it seems that command for generation of CA succeeds based on output, but still sets error code.

### Expected behavior

If the command has reason to exit with error code, then logging should make it clear something failed.

### Actual behavior

Printed console output seems fine, but the error code is returned.

```
[mvavrik@fedora code-with-quarkus]$ quarkus tls generate-quarkus-ca --truststore -r
Aug 30, 2024 9:55:22 AM io.quarkus.tls.cli.GenerateCACommand call
INFO: 🔥 Generating Quarkus Dev CA certificate...
Aug 30, 2024 9:55:22 AM io.smallrye.certs.ca.CaGenerator generate
INFO: 🔥 Root CA certificate generated successfully!
Aug 30, 2024 9:55:22 AM io.quarkus.tls.cli.GenerateCACommand call
INFO: 🔥 Generating p12 truststore...
Aug 30, 2024 9:55:22 AM io.smallrye.certs.ca.CaGenerator generateTrustStore
INFO: 🔥 Generating p12 truststore...
Aug 30, 2024 9:55:22 AM io.smallrye.certs.ca.CaGenerator generateTrustStore
INFO: 🔥 Truststore generated successfully: /tmp/code-with-quarkus/quarkus-ca-truststore.p12.
Aug 30, 2024 9:55:22 AM io.quarkus.tls.cli.GenerateCACommand call
INFO: ✅ Truststore generated successfully.
Aug 30, 2024 9:55:22 AM io.quarkus.tls.cli.GenerateCACommand call
INFO: ✅ Quarkus Development CA generated and installed
[mvavrik@fedora code-with-quarkus]$ echo $?
1
```

### How to Reproduce?

```
quarkus create app --extensions=tls-registry
cd code-with-quarkus/
quarkus tls generate-quarkus-ca --truststore -r
echo $?
```

### Output of `uname -a` or `ver`

Fedora 40

### Output of `java -version`

OpenJDK 21

### Quarkus version or git rev

999-SNAPSHOT and 3.14.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.9

### Additional information

Quarkus CLI 3.14.1

**Comment by cescoffier** [comment]
Should be fixed in https://github.com/quarkusio/quarkus/issues/42752.

**Comment by michalvavrik** [comment]
> Should be fixed in #42752.

thanks I didn't mention. I tested it with Quarkus CLI build from 999-SNAPSHOT and I still get it. I am not quite sure what I am doing wrong. I'll play with it for a while and report back or close the issue.

**Comment by michalvavrik** [comment]
I had HEAD on commit before #42752, sorry about that.
