### ISSUE TITLE
Smallrye fault tolerance  retry policy goes in StackOverflowError

### ISSUE THREAD

**Issue by joystuffs** [quarkusio/quarkus#47422]
### Describe the bug

Hi, 

I noticed an unexpected behavior after updating Smallrye fault tolerance

from

```
 io.quarkus:quarkus-smallrye-fault-tolerance:3.15.3
 io.smallrye:smallrye-fault-tolerance:6.4.0
```

to

```
io.quarkus:quarkus-smallrye-fault-tolerance:3.20.0
io.smallrye:smallrye-fault-tolerance:6.9.0
```
Out of nowhere, I started getting a StackOverflowError, something that never happened in the previous version.

<pre> <code> 
java.util.concurrent.CompletionException: java.lang.StackOverflowError at
java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) at
java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) at
java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) at
java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(Unknown Source) at
java.base/java.util.concurrent.CompletableFuture.whenComplete(Unknown Source) 	at
java.base/java.util.concurrent.CompletableFuture$MinimalStage.whenComplete(Unknown Source) at
io.quarkus.scheduler.common.runtime.DefaultInvoker.invoke(DefaultInvoker.java:25) at
io.quarkus.scheduler.common.runtime.DelegateInvoker.invokeDelegate(DelegateInvoker.java:29) at
io.quarkus.scheduler.common.runtime.StatusEmitterInvoker.invoke(StatusEmitterInvoker.java:35) at
io.quarkus.scheduler.common.runtime.DelegateInvoker.invokeDelegate(DelegateInvoker.java:29) at
io.quarkus.scheduler.common.runtime.DelegateInvoker.invokeComplete(DelegateInvoker.java:36) at
io.quarkus.scheduler.common.runtime.OffloadingInvoker$2.call(OffloadingInvoker.java:54) at
io.quarkus.scheduler.common.runtime.OffloadingInvoker$2.call(OffloadingInvoker.java:51) at
io.vertx.core.impl.ContextImpl.lambda$executeBlocking$4(ContextImpl.java:192) at
io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:270) at
io.vertx.core.impl.ContextImpl$1.execute(ContextImpl.java:221) at
io.vertx.core.impl.WorkerTask.run(WorkerTask.java:56) at
io.quarkus.vertx.core.runtime.VertxCoreRecorder$15.runWith(VertxCoreRecorder.java:643) at
org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675) at
org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654) at
org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1627) at
org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1594) at
org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11) at
org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11) at
io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) at
java.base/java.lang.Thread.run(Unknown Source)
 </code> </pre>

below the programmatically `TypedGuard ` used for the retries.

I followed the official update guide to rewrite the retry policy, even though the actual code change was minimal.

ref : https://smallrye.io/docs/smallrye-fault-tolerance/6.9.0/reference/programmatic-api.html

```
TypedGuard.create(Response.class)
                .withDescription("retry policy")
                .withRetry()
                .maxDuration(30, ChronoUnit.SECONDS)
                .maxRetries(-1)
                .abortOn(DomainException.class)
                .retryOn(List.of(DomainRetryableException.class))
                .done()
                .withTimeout()
                .duration(10, ChronoUnit.SECONDS)
                .done()
                .build();
```

maybe there is a new config , I'm missing.

any clue of the stackOverFlow? 

### Expected behavior

have the same behavior as in the previous version

### Actual behavior

Out of nowhere, I started getting a StackOverflowError, something that never happened in the previous version.

### How to Reproduce?

below the TypedGuard used for the retry

```
TypedGuard.create(Response.class)
                .withDescription("retry policy")
                .withRetry()
                .maxDuration(30, ChronoUnit.SECONDS)
                .maxRetries(-1)
                .abortOn(DomainException.class)
                .retryOn(List.of(DomainRetryableException.class))
                .done()
                .withTimeout()
                .duration(10, ChronoUnit.SECONDS)
                .done()
                .build();
```

### Output of `java -version`

21

### Quarkus version or git rev

3.20.0

**Comment by Ladicek** [comment]
That shouldn't be occuring, no. There's likely a bug. I'll try to reproduce.

**Comment by joystuffs** [comment]
I did more tests and below the recurrent exception : 

<pre> <code>ERROR [io.qua.ver.cor.run.VertxCoreRecorder] (vert.x-eventloop-thread-7) Uncaught exception received by Vert.x: java.lang.NoClassDefFoundError: Could not initialize class io.smallrye.faulttolerance.core.retry.RetryEvents$Finished
	at io.smallrye.faulttolerance.core.retry.Retry.afterDelay(Retry.java:160)
	at io.smallrye.faulttolerance.core.retry.Retry.doRetry(Retry.java:69)
	at io.smallrye.faulttolerance.core.retry.Retry.apply(Retry.java:59)
	at io.smallrye.faulttolerance.core.fallback.Fallback.apply(Fallback.java:35)
	at io.smallrye.faulttolerance.core.metrics.MetricsCollector.apply(MetricsCollector.java:98)
	at io.smallrye.faulttolerance.core.metrics.DelegatingMetricsCollector.apply(DelegatingMetricsCollector.java:37)
	at io.smallrye.faulttolerance.core.async.SyncAsyncSplit.apply(SyncAsyncSplit.java:23)
	at io.smallrye.faulttolerance.apiimpl.GuardCommon.guard(GuardCommon.java:69)
	at io.smallrye.faulttolerance.apiimpl.TypedGuardImpl.guard(TypedGuardImpl.java:111)
	at io.smallrye.faulttolerance.apiimpl.TypedGuardImpl.call(TypedGuardImpl.java:97)
	at io.smallrye.faulttolerance.apiimpl.LazyTypedGuard.call(LazyTypedGuard.java:23)
	at example.com.api.Service.runService.process(runService.java:115)
	at example.com.api.Service.runService.lambda$execute$0(runService.java:71)
	at java.base/java.util.HashMap.forEach(HashMap.java:1429)
	at example.com.api.Service.runService(Service.java:71)
	at io.quarkus.vertx.runtime.EventConsumerInvoker.invokeBean(EventConsumerInvoker.java:79)
	at io.quarkus.vertx.runtime.EventConsumerInvoker.invoke(EventConsumerInvoker.java:51)
	at io.quarkus.vertx.runtime.VertxEventBusConsumerRecorder$3$1$2.call(VertxEventBusConsumerRecorder.java:150)
	at io.quarkus.vertx.runtime.VertxEventBusConsumerRecorder$3$1$2.call(VertxEventBusConsumerRecorder.java:146)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$4(ContextImpl.java:192)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:270)
	at io.vertx.core.impl.ContextImpl$1.execute(ContextImpl.java:221)
	at io.vertx.core.impl.WorkerTask.run(WorkerTask.java:56)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2675)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2654)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1591)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.StackOverflowError [in thread "vert.x-worker-thread-3"]
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:524)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:517)
	at io.smallrye.faulttolerance.core.retry.RetryEvents$Finished.<clinit>(RetryEvents.java:18)
	at io.smallrye.faulttolerance.core.retry.Retry.afterDelay(Retry.java:160)
	at io.smallrye.faulttolerance.core.retry.Retry.lambda$doRetry$0(Retry.java:87)
	at io.smallrye.faulttolerance.core.retry.SyncDelayAsAsync.after(SyncDelayAsAsync.java:27)
	at io.smallrye.faulttolerance.core.retry.Retry.doRetry(Retry.java:86)
	at io.smallrye.faulttolerance.core.retry.Retry.lambda$afterDelay$1(Retry.java:154)
	at io.smallrye.faulttolerance.core.FutureImpl.attemptDelivery(FutureImpl.java:159)
	at io.smallrye.faulttolerance.core.FutureImpl.then(FutureImpl.java:90)
	at io.smallrye.faulttolerance.core.retry.Retry.afterDelay(Retry.java:129)
	at io.smallrye.faulttolerance.core.retry.Retry.lambda$doRetry$0(Retry.java:87)
	at io.smallrye.faulttolerance.core.retry.SyncDelayAsAsync.after(SyncDelayAsAsync.java:27)
	at io.smallrye.faulttolerance.core.retry.Retry.doRetry(Retry.java:86)...
```</code> </pre>

The stack trace goes on indefinitely, suggesting repeated retry attempts.

this doesn't happen at all with 

```
io.quarkus:quarkus-smallrye-fault-tolerance:3.15.3
io.smallrye:smallrye-fault-tolerance:6.4.0
```

**Comment by Ladicek** [comment]
I guess I know why this happens, the synchronous retry implementation used a `while` loop, but it uses recursion now (after the big async unification). We'll probably have to add a trampoline, or something like that.

**Comment by joystuffs** [comment]
Good to know,  thanks for the feedback!

Looking at the SmallRye blog, I noticed there was a major refactoring starting with version 6.7.0:

 https://smallrye.io/blog/fault-tolerance-6-7-0/

I'm not sure if the issue you mentioned is related to that.

assuming I want to keep  Quarkus 3.20, what would you suggest in this case?

**Comment by Ladicek** [comment]
That is indeed the cause. I should be able to fix the issue next week or the week after that, and that fix should be backportable to 3.20.

**Comment by Ladicek** [comment]
This should be fixed by https://github.com/smallrye/smallrye-fault-tolerance/pull/1120

**Comment by Ladicek** [comment]
Gee, I didn't mean to close this by merging the upstream PR. This issue is still valid, should be closed by bumping SRye FT to a new version.

**Comment by joystuffs** [comment]
so what is the next step? If I understood correctly, this fix is part of quarkus `3.20` , right?

sorry but I didn't get this part :

"This issue is still valid, should be closed by bumping SRye FT to a new version."

does this mean there would a minor version shipped with ` 3.20`  like `io.smallrye:smallrye-fault-tolerance:6.9.1`?

**Comment by Ladicek** [comment]
Yes, the PR to bump to SmallRye Fault Tolerance 6.9.1 is https://github.com/quarkusio/quarkus/pull/47496. Merging that will fix this issue. I also marked it for backporting to Quarkus 3.20.

**Comment by gsmet** [comment]
And you can override the version in your project already.

**Comment by Ladicek** [comment]
Ah, yeah, good point. That's a good stopgap measure.

**Comment by joystuffs** [comment]
btw I was playing around with the async `TypedGuard` and I have the same exception.
the sample code remains the same beside the completionStage

```
    private TypedGuard<CompletionStage<Response>> getRetryPolicy() {
        return TypedGuard.create(new TypeLiteral<CompletionStage<Response>>() {})
                .withDescription("retry policy")
                .withRetry()
                .maxDuration(30, ChronoUnit.SECONDS)
                .maxRetries(-1)
                .abortOn(MpapException.class)
               .retryOn(List.of(DomainRetryableException.class))
                .done()
                .withTimeout().duration(10, ChronoUnit.SECONDS).done()
                .withThreadOffload(true)
                .build();
    }

```

probably I'm doing something wrong with the TypedGuard.

**Comment by Ladicek** [comment]
This can easily happen even if you guard a `CompletionStage`-returning action, if the guarded action is actually synchronous (regardless of its return type). Could that be the case?

**Comment by joystuffs** [comment]
yes, correct. 
thank you for the feedback.
