### ISSUE TITLE
Using nested JUnit test classes with QuarkusTest breaks non-Quarkus tests

### ISSUE THREAD

**Issue by rodcheater** [quarkusio/quarkus#47657]
### Describe the bug

I have a test annotated with `@QuarkusTest` which includes some `@Nested` classes. This is fine on its own but it breaks non-Quarkus tests in some weird and wonderful ways.

For example:

```
✗ ./gradlew test       

> Task :test FAILED

GreetingResourceTest > testHelloEndpoint() FAILED
    java.util.ServiceConfigurationError: io.smallrye.config.SmallRyeConfigFactory: io.quarkus.runtime.configuration.QuarkusConfigFactory not a subtype
        at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1244)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
        at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
        at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
        at io.smallrye.config.SmallRyeConfigProviderResolver.getFactoryFor(SmallRyeConfigProviderResolver.java:102)
        at io.smallrye.config.SmallRyeConfigProviderResolver.getConfig(SmallRyeConfigProviderResolver.java:78)
        at io.smallrye.config.SmallRyeConfigProviderResolver.getConfig(SmallRyeConfigProviderResolver.java:66)
        at io.quarkus.test.config.TestConfigProviderResolver.getConfig(TestConfigProviderResolver.java:36)
        at org.eclipse.microprofile.config.ConfigProvider.getConfig(ConfigProvider.java:85)
        at org.acme.GreetingResource.<init>(GreetingResource.kt:12)
        at org.acme.GreetingResourceTest.testHelloEndpoint(GreetingResourceTest.kt:8)

2 tests completed, 1 failed
```

This is in Quarkus 3.22.0; earlier versions are not affected.

### Expected behavior

Having nested test classes in a Quarkus test should not affect other tests.

### Actual behavior

Having nested test classes in a Quarkus test breaks non-Quarkus tests.

### How to Reproduce?

Reproducer: [quarkus-reproducer.zip](https://github.com/user-attachments/files/20008450/quarkus-reproducer.zip)

** Steps to reproduce **

1. Run `./gradlew test`

** Expected result **

The build succeeds.

** Actual result **

The build fails due to failing tests.

Note that ` ./gradlew test --tests GreetingResourceTest` and `./gradlew test --tests GreetingResourceQuarkusTest` both succeed.

### Output of `uname -a` or `ver`

Darwin Rods-MacBook-Pro.local 24.4.0 Darwin Kernel Version 24.4.0: Fri Apr 11 18:33:40 PDT 2025; root:xnu-11417.101.15~117/RELEASE_ARM64_T6031 arm64

### Output of `java -version`

openjdk version "21.0.6" 2025-01-21 OpenJDK Runtime Environment Homebrew (build 21.0.6) OpenJDK 64-Bit Server VM Homebrew (build 21.0.6, mixed mode, sharing)

### Quarkus version or git rev

3.22.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.14

**Comment by geoand** [comment]
cc @holly-cummins

**Comment by LadislavBrecka** [comment]
I encountered the same issue after upgrading from `3.21.4` to `3.22.1` of `io.quarkus.platform:quarkus-bom.`

I'm running a mix of `@QuarkusTest `tests alongside plain unit tests, and after the upgrade, some of the plain tests started failing.

I found that removing all `@Nested` classes from the `@QuarkusTest` tests resolved the issue.

**Comment by t1** [comment]
I'm not sure if this is the same issue, but it may be related. I have restructured a large test class with `@Nested` classes, several levels deep. They run just fine in the IDE, but on the command line, I get `...Test Failed to evaluate condition [io.quarkus.test.junit.QuarkusTestExtension]: Non-viable test classloader, jdk.internal.loader.ClassLoaders$AppClassLoader@76ed5528. Is this a re-run of a failing test?` for the root and the first level of nested classes, but not for those within.

In 3.21.1, I got `Provider "quarkus" not installed` for the same tests, which was even weirder!

**Comment by holly-cummins** [comment]
I also had seen the  3.21.1 failure `Provider "quarkus" not installed` failure is and fixed it in some PR or another, but that doesn't help with the multi-level nested tests. I'll investigate both issues, thanks @t1 and @rodcheater!

**Comment by t1** [comment]
I'm trying to build a reproducer, but it seems to need more than multi-nested tests.

**Comment by t1** [comment]
Oh, when I said "on the command line", I meant in dev-mode. Sorry if I caused confusion.

And another observation: if I try to execute only the test class with the nested classes by going into the dev mode command line (hit `:`) and enter `test pattern include <my-test-class>`, it executes nothing!

**Comment by t1** [comment]
I have a reproducer, but I think it's not worth sharing.

**Comment by t1** [comment]
Yet another detail that _could_ help finding the issue (or it's separate): it reports three errors in my case, but still reports `0 tests failed`

**Comment by holly-cummins** [comment]
@rodcheater do you mind updating the issue title to say this is on gradle? And thank you for the clear reproducer.

**Comment by holly-cummins** [comment]
This is fixed by https://github.com/quarkusio/quarkus/pull/47365

**Comment by holly-cummins** [comment]
Oh, and there's a workaround for this, which is that in the non-Quarkus tests, calling 

```
Thread.currentThread().setContextClassLoader(ClassLoader.getSystemClassLoader());
```

should get things working again.

**Comment by t1** [comment]
I still get errors when running the tests from dev-mode: `Internal error: ClassLoader QuarkusClassLoader:Deployment Class Loader: TEST for <myapp>-<version>-SNAPSHOT@<id> does not have a linked curated application.`

The strangest thing is that this is reported as errors, but the total failures is still zero.

I'm not sure if this issue should be reopened (which I'm not allowed to), or if I should open a new one. @holly-cummins ?
