### ISSUE TITLE
BlockingNotAllowedException on non-reactive REST API calls after updating from 3.24.5 to 3.25.1

### ISSUE THREAD

**Issue by MarcScheib** [quarkusio/quarkus#49421]
### Describe the bug

Since my update from version 3.24.1 to 3.25.1 I see a similar problem, but I am not using Mutiny return types. My setup is a simple as the following:

```
        final AttachmentDTO attachment = attachmentClient.uploadReceipt(request.getAttachment());
        final Response attachmentData = attachmentsClient.attachments().download(attachment.getId());
        final InputStream streamData = attachmentData.readEntity(InputStream.class);
        final ParseReceiptMultipartFormDTO payload = new ParseReceiptMultipartFormDTO();
        payload.setReceipt(streamData);
        final ReceiptDTO receipt = parseClient.receipts().parse(payload);
```

On Quarkus 3.24.1, this is working fine and I get a response within `receipt`, but when updating to 2.25.0, the very same code throws the following exception on the `parseClient.receipts().parse(payload)` line (see below).

I tried already several different things, adding annotations (@Blocking, @Nonblocking, etc.), wrap it in reactive behavior, changing the client to return Uni. Nothing of this worked.

```
2025-08-03 16:57:02,105 SEVERE [com.cyc.eam.jax.rs.ext.map.AbstractExceptionMapper] (executor-thread-4) Uncaught exception: http://localhost:3333/business/command/accounting/accounts/b3913534-aecc-4922-a9ca-4bf8d8e8ce00/transactions/receipt-transaction (POST) [Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryrwyorucGBZZOBsUp; Accept: application/json, text/plain, */*]: org.jboss.resteasy.reactive.common.core.BlockingNotAllowedException: Attempting a blocking read on io thread
	at org.jboss.resteasy.reactive.client.handlers.VertxClientInputStream$VertxBlockingInput.readBlocking(VertxClientInputStream.java:187)
	at org.jboss.resteasy.reactive.client.handlers.VertxClientInputStream.readIntoBuffer(VertxClientInputStream.java:69)
	at org.jboss.resteasy.reactive.client.handlers.VertxClientInputStream.close(VertxClientInputStream.java:97)
	at org.jboss.resteasy.reactive.common.providers.serialisers.InputStreamMessageBodyHandler.writeTo(InputStreamMessageBodyHandler.java:41)
	at org.jboss.resteasy.reactive.common.providers.serialisers.InputStreamMessageBodyHandler.writeTo(InputStreamMessageBodyHandler.java:33)
	at org.jboss.resteasy.reactive.common.providers.serialisers.InputStreamMessageBodyHandler.writeTo(InputStreamMessageBodyHandler.java:15)
	at org.jboss.resteasy.reactive.client.impl.ClientSerialisers.invokeClientWriter(ClientSerialisers.java:122)
	at org.jboss.resteasy.reactive.client.impl.multipart.QuarkusMultipartForm.preparePojos(QuarkusMultipartForm.java:55)
	at org.jboss.resteasy.reactive.client.handlers.ClientSendRequestHandler.setMultipartHeadersAndPrepareBody(ClientSendRequestHandler.java:494)
	at org.jboss.resteasy.reactive.client.handlers.ClientSendRequestHandler$1.accept(ClientSendRequestHandler.java:118)
	at org.jboss.resteasy.reactive.client.handlers.ClientSendRequestHandler$1.accept(ClientSendRequestHandler.java:101)
	at io.smallrye.context.impl.wrappers.SlowContextualConsumer.accept(SlowContextualConsumer.java:21)
	at io.smallrye.mutiny.helpers.UniCallbackSubscriber.onItem(UniCallbackSubscriber.java:73)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:60)
	at org.jboss.resteasy.reactive.client.AsyncResultUni.lambda$subscribe$1(AsyncResultUni.java:35)
	at io.vertx.core.impl.future.FutureImpl$4.onSuccess(FutureImpl.java:176)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:66)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:259)
	at io.vertx.core.http.impl.HttpClientImpl.lambda$null$3(HttpClientImpl.java:392)
	at io.vertx.core.impl.future.FutureImpl$4.onSuccess(FutureImpl.java:176)
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:60)
	at io.vertx.core.impl.ContextImpl.execute(ContextImpl.java:312)
	at io.vertx.core.impl.DuplicatedContext.execute(DuplicatedContext.java:168)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:57)
	at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:231)
	at io.vertx.core.impl.future.FutureImpl.onComplete(FutureImpl.java:199)
	at io.vertx.core.http.impl.Http1xClientConnection.createStream(Http1xClientConnection.java:1294)
	at io.vertx.core.http.impl.Http1xClientConnection.lambda$createStream$9(Http1xClientConnection.java:1300)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:998)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Expected behavior

After updating, the code still works as before, i.e. the REST calls simply execute and no exception is thrown.

### Actual behavior

A BlockingNotAllowedException is thrown on the second REST call.

### How to Reproduce?

The behavior can be reproduced using the following repository: https://github.com/CycriLabs/quarkus-reproducer
It contains two branches:
- main: running on 3.24.5 and working
- [blocking-error](https://github.com/CycriLabs/quarkus-reproducer/tree/blocking-error): running on 3.25.1 and showing the error

The reproduction is very close to the original app setup (keycloak, consul, database, etc.), api-gateway and micro-services with service registration/discovery. Only process engine is missing (quarkus-zeebe (Camunda 8)).

The `test.http` contains the REST call to execute. If everything works fine, it returns a 200, otherwise a 500.

### Output of `uname -a` or `ver`

MINGW64_NT-10.0-26100 xxxx 3.6.3-7674c51e.x86_64 2025-07-01 09:13 UTC x86_64 Msy

### Output of `java -version`

OpenJDK Runtime Environment Temurin-21.0.6+7 (build 21.0.6+7-LTS

### Quarkus version or git rev

3.25.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven Daemon (mvnd) 1.0-m8 windows-amd64 native client (0f4bdb6df5e74453d8d558d292789da4e66a7933) Terminal: org.jline.terminal.impl.jansi.win.JansiWinSysTerminal Apache Maven 3.9.5 (57804ffe001d7215b5e7bcb531cf83df38f93546)

**Comment by ChMThiel** [comment]
Same for me on reading entityStream in ClientResponseFilter. Any ideas?

**Comment by KaiSuchomel** [comment]
@geoand Can you support here, or do you know someone who can? This is currently a blocker for our Quarkus Update to 3.25.X

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/49692 might be a fix, but I have no idea as I don't know how to use the reproducer in this issue

**Comment by KaiSuchomel** [comment]
> [#49692](https://github.com/quarkusio/quarkus/pull/49692) might be a fix, but I have no idea as I don't know how to use the reproducer in this issue

Sounds good, with which release will #49692 be available??

**Comment by geoand** [comment]
Dunno, just got back from PTO so I have a ton of things to catch up on

**Comment by MarcScheib** [comment]
@geoand I built quarkus based on your PR and as described in the Contribution Guide. It seems like the bug is still present (see below).
Either my build was wrong (at least it started with the correct version output 999-SNAPSHOT and I did not add the SNAPSHOT mirrors) or the PR did not resolve the bug.
Can you give me any hints how I can improve the reproducer for you? Alternatively, of course I can test PRs myself.

```
{
	"details": "Error id 318cbc13-f5b3-4b85-9aa4-c76327e4c472-1, org.jboss.resteasy.reactive.common.core.BlockingNotAllowedException: Attempting a blocking read on io thread",
	"stack": "org.jboss.resteasy.reactive.common.core.BlockingNotAllowedException: Attempting a blocking read on io thread\r\n\tat org.jboss.resteasy.reactive.client.handlers.VertxClientInputStream$VertxBlockingInput.readBlocking(VertxClientInputStream.java:187)\r\n\tat org.jboss.resteasy.reactive.client.handlers.VertxClientInputStream.readIntoBuffer(VertxClientInputStream.java:69)\r\n\tat org.jboss.resteasy.reactive.client.handlers.VertxClientInputStream.close(VertxClientInputStream.java:97)\r\n\tat org.jboss.resteasy.reactive.common.providers.serialisers.InputStreamMessageBodyHandler.writeTo(InputStreamMessageBodyHandler.java:41)\r\n\tat org.jboss.resteasy.reactive.common.providers.serialisers.InputStreamMessageBodyHandler.writeTo(InputStreamMessageBodyHandler.java:33)\r\n\tat org.jboss.resteasy.reactive.common.providers.serialisers.InputStreamMessageBodyHandler.writeTo(InputStreamMessageBodyHandler.java:15)\r\n\tat org.jboss.resteasy.reactive.client.impl.ClientSerialisers.invokeClientWriter(ClientSerialisers.java:122)\r\n\tat org.jboss.resteasy.reactive.client.impl.multipart.QuarkusMultipartForm.preparePojos(QuarkusMultipartForm.java:55)\r\n\tat org.jboss.resteasy.reactive.client.handlers.ClientSendRequestHandler.setMultipartHeadersAndPrepareBody(ClientSendRequestHandler.java:494)\r\n\tat org.jboss.resteasy.reactive.client.handlers.ClientSendRequestHandler$1.accept(ClientSendRequestHandler.java:118)\r\n\tat org.jboss.resteasy.reactive.client.handlers.ClientSendRequestHandler$1.accept(ClientSendRequestHandler.java:101)\r\n\tat io.smallrye.context.impl.wrappers.SlowContextualConsumer.accept(SlowContextualConsumer.java:21)\r\n\tat io.smallrye.mutiny.helpers.UniCallbackSubscriber.onItem(UniCallbackSubscriber.java:73)\r\n\tat io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:60)\r\n\tat org.jboss.resteasy.reactive.client.AsyncResultUni.lambda$subscribe$1(AsyncResultUni.java:35)\r\n\tat io.vertx.core.impl.future.FutureImpl$4.onSuccess(FutureImpl.java:176)\r\n\tat io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:66)\r\n\tat io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:259)\r\n\tat io.vertx.core.http.impl.HttpClientImpl.lambda$null$3(HttpClientImpl.java:392)\r\n\tat io.vertx.core.impl.future.FutureImpl$4.onSuccess(FutureImpl.java:176)\r\n\tat io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:60)\r\n\tat io.vertx.core.impl.ContextImpl.execute(ContextImpl.java:312)\r\n\tat io.vertx.core.impl.DuplicatedContext.execute(DuplicatedContext.java:168)\r\n\tat io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:57)\r\n\tat io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:231)\r\n\tat io.vertx.core.impl.future.FutureImpl.onComplete(FutureImpl.java:199)\r\n\tat io.vertx.core.http.impl.Http1xClientConnection.createStream(Http1xClientConnection.java:1313)\r\n\tat io.vertx.core.http.impl.HttpClientImpl.lambda$doRequest$4(HttpClientImpl.java:372)\r\n\tat io.vertx.core.net.impl.pool.Endpoint.lambda$getConnection$0(Endpoint.java:52)\r\n\tat io.vertx.core.http.impl.SharedClientHttpStreamEndpoint$Request.handle(SharedClientHttpStreamEndpoint.java:162)\r\n\tat io.vertx.core.http.impl.SharedClientHttpStreamEndpoint$Request.handle(SharedClientHttpStreamEndpoint.java:123)\r\n\tat io.vertx.core.impl.ContextImpl.emit(ContextImpl.java:342)\r\n\tat io.vertx.core.impl.ContextImpl.emit(ContextImpl.java:335)\r\n\tat io.vertx.core.net.impl.pool.SimpleConnectionPool$LeaseImpl.emit(SimpleConnectionPool.java:714)\r\n\tat io.vertx.core.net.impl.pool.SimpleConnectionPool$Acquire$2.run(SimpleConnectionPool.java:577)\r\n\tat io.vertx.core.net.impl.pool.Task.runNextTasks(Task.java:43)\r\n\tat io.vertx.core.net.impl.pool.CombinerExecutor.submit(CombinerExecutor.java:91)\r\n\tat io.vertx.core.net.impl.pool.SimpleConnectionPool.execute(SimpleConnectionPool.java:244)\r\n\tat io.vertx.core.net.impl.pool.SimpleConnectionPool.acquire(SimpleConnectionPool.java:639)\r\n\tat io.vertx.core.http.impl.SharedClientHttpStreamEndpoint$Request.acquire(SharedClientHttpStreamEndpoint.java:166)\r\n\tat io.vertx.core.http.impl.SharedClientHttpStreamEndpoint.requestConnection2(SharedClientHttpStreamEndpoint.java:173)\r\n\tat io.vertx.core.http.impl.ClientHttpEndpointBase.requestConnection(ClientHttpEndpointBase.java:49)\r\n\tat io.vertx.core.net.impl.pool.Endpoint.getConnection(Endpoint.java:41)\r\n\tat io.vertx.core.net.impl.pool.ConnectionManager.getConnection(ConnectionManager.java:51)\r\n\tat io.vertx.core.http.impl.HttpClientImpl.doRequest(HttpClientImpl.java:368)\r\n\tat io.vertx.core.http.impl.HttpClientImpl.doRequest(HttpClientImpl.java:325)\r\n\tat io.vertx.core.http.impl.HttpClientImpl.request(HttpClientImpl.java:184)\r\n\tat org.jboss.resteasy.reactive.client.handlers.ClientSendRequestHandler$5.lambda$apply$0(ClientSendRequestHandler.java:468)\r\n\tat io.smallrye.context.impl.wrappers.SlowContextualConsumer.accept(SlowContextualConsumer.java:21)\r\n\tat org.jboss.resteasy.reactive.client.AsyncResultUni.subscribe(AsyncResultUni.java:31)\r\n\tat io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:35)\r\n\tat io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.performInnerSubscription(UniOnItemTransformToUni.java:81)\r\n\tat io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:57)\r\n\tat io.smallrye.mutiny.operators.uni.UniOnItemConsume$UniOnItemComsumeProcessor.onItem(UniOnItemConsume.java:43)\r\n\tat io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:43)\r\n\tat io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem$KnownItemSubscription.forward(UniCreateFromKnownItem.java:38)\r\n\tat io.smallrye.mutiny.operators.uni.builders.UniCreateFromKnownItem.subscribe(UniCreateFromKnownItem.java:23)\r\n\tat io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:35)\r\n\tat io.smallrye.mutiny.operators.uni.UniOnItemTransform.subscribe(UniOnItemTransform.java:22)\r\n\tat io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:35)\r\n\tat io.smallrye.mutiny.operators.uni.UniOnItemConsume.subscribe(UniOnItemConsume.java:30)\r\n\tat io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:35)\r\n\tat io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni.subscribe(UniOnItemTransformToUni.java:25)\r\n\tat io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:35)\r\n\tat io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:51)\r\n\tat io.smallrye.mutiny.groups.UniSubscribe.with(UniSubscribe.java:110)\r\n\tat io.smallrye.mutiny.groups.UniSubscribe.with(UniSubscribe.java:88)\r\n\tat org.jboss.resteasy.reactive.client.handlers.ClientSendRequestHandler.handle(ClientSendRequestHandler.java:101)\r\n\tat org.jboss.resteasy.reactive.client.handlers.ClientSendRequestHandler.handle(ClientSendRequestHandler.java:70)\r\n\tat org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.invokeHandler(AbstractResteasyReactiveContext.java:231)\r\n\tat org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)\r\n\tat io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)\r\n\tat org.jboss.resteasy.reactive.client.handlers.ClientSwitchToRequestContextRestHandler$1$1.handle(ClientSwitchToRequestContextRestHandler.java:38)\r\n\tat org.jboss.resteasy.reactive.client.handlers.ClientSwitchToRequestContextRestHandler$1$1.handle(ClientSwitchToRequestContextRestHandler.java:35)\r\n\tat io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:270)\r\n\tat io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:252)\r\n\tat io.vertx.core.impl.ContextInternal.lambda$runOnContext$0(ContextInternal.java:50)\r\n\tat io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)\r\n\tat io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)\r\n\tat io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)\r\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)\r\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:998)\r\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\r\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\r\n\tat java.base/java.lang.Thread.run(Thread.java:1583)"
}
```

**Comment by geoand** [comment]
@MarcScheib thanks. I really just need some instructions on how to use your reproducer to see the issue in action

**Comment by geoand** [comment]
Additionally, I just pushed an update to https://github.com/quarkusio/quarkus/pull/49692 so you might want to try again

**Comment by KaiSuchomel** [comment]
@geoand The Fix you provided with #49692 fixed our Issue. I will retry when a official release is available. Thx.

**Comment by geoand** [comment]
Thanks a lot for checking and reporting back @KaiSuchomel !

**Comment by chvsnraju** [comment]
@geoand  - Thanks for fixing this. We are also having this issue and holding our upgrade. May I know which release version this fix would be part of?

**Comment by geoand** [comment]
🙏🏽 

It will likely be part of `3.26.1`

**Comment by chvsnraju** [comment]
Thank you !

**Comment by geoand** [comment]
YW!

**Comment by MarcScheib** [comment]
> Additionally, I just pushed an update to [#49692](https://github.com/quarkusio/quarkus/pull/49692) so you might want to try again

@geoand I did a test based on your latest PR and it still did not work. I ll retest based on main hopefully over the weekend and provide feedback.

--- 

For the reproducer it should simply be:
1. `git clone -b blocking-error git@github.com:CycriLabs/quarkus-reproducer.git`
2. `cd quarkus-reproducer`
3. `mvn clean package`
4. `setup.sh` (sets up keycloak + consul + postgres)

Then you can start both applications (service-a and api-gateway) and use the `test.http` file to call the endpoint.

**Comment by geoand** [comment]
Thanks @MarcScheib.

I tried, but got:

```
[ERROR] Failed to execute goal on project service-a-server: Could not resolve dependencies for project com.cycrilabs:service-a-server:jar:0.1.0-SNAPSHOT
[ERROR] dependency: com.cycrilabs:service-a-client:jar:0.1.0-SNAPSHOT (compile)
[ERROR]         Could not find artifact com.cycrilabs:service-a-client:jar:0.1.0-SNAPSHOT
[ERROR] 
```

**Comment by MarcScheib** [comment]
> Thanks [@MarcScheib](https://github.com/MarcScheib).
> 
> I tried, but got:
> 
> ```
> [ERROR] Failed to execute goal on project service-a-server: Could not resolve dependencies for project com.cycrilabs:service-a-server:jar:0.1.0-SNAPSHOT
> [ERROR] dependency: com.cycrilabs:service-a-client:jar:0.1.0-SNAPSHOT (compile)
> [ERROR]         Could not find artifact com.cycrilabs:service-a-client:jar:0.1.0-SNAPSHOT
> [ERROR] 
> ```

@geoand oh sorry. Due to the client-server-module split a `mvn install` is required for the client-jar's. If necessary I can simplify the setup. The purpose was to be as close as possible to the real setup.

**Comment by geoand** [comment]
>  necessary I can simplify the setup

Please do. A minimal sample that simply showcases the problem at hand would be ideal

**Comment by chvsnraju** [comment]
@geoand  - A quick update, I just tried upgrading to the latest version 3.26.2, now working fine, issue is fixed, thanks for helping with this.

**Comment by geoand** [comment]
Thanks for the update!

**Comment by MarcScheib** [comment]
@geoand I tested with 3.26.2 and the original issue is still there.

I simplified the reproducer: https://github.com/CycriLabs/quarkus-reproducer/tree/blocking-error 

1. `git clone -b blocking-error git@github.com:CycriLabs/quarkus-reproducer.git`
2. `cd quarkus-reproducer`
3. `./mvnw clean package`
4. `setup.sh` (consul + postgres)

Then, start both services `api-gateway` and `service-a`. In the `test.http` is an example request to trigger the error.

**Comment by geoand** [comment]
Thanks, I'll check tomorrow

**Comment by geoand** [comment]
@MarcScheib I tried your reproducer.

> In the test.http is an example request to trigger the error.

The  `### Get access token` request doesn't work at all since no service listens on `8080`.
The `### Create receipt transaction` works just fine

**Comment by MarcScheib** [comment]
> [@MarcScheib](https://github.com/MarcScheib) I tried your reproducer.
> 
> > In the test.http is an example request to trigger the error.
> 
> The `### Get access token` request doesn't work at all since no service listens on `8080`. The `### Create receipt transaction` works just fine

@geoand  thanks for testing and your time invest.

You can ignore `### Get access token`, only the receipt request is relevant.
I tested again: cleaned my maven repository, switched to a different machine (Linux this time), but the issue is still there. Switching to 3.24 is working, but starting at 3.25 to now 3.26, the error pops up.

Just a side note: the `main` branch has the working version, the `blocking-error` is the non-working version. I' ll try to add an integration test the next days with a pipline showing the issue.

**Comment by geoand** [comment]
Unfortunately, our multipart handling of `InputStream` is not great ATM, see https://github.com/quarkusio/quarkus/issues/47884.
You could sidestep the issue in your reproducer by not using `InputStream` as part of the multipart request that is sent by the client.
