### ISSUE TITLE
Jacoco Coverage not working for "Non-Quarkustest"

### ISSUE THREAD

**Issue by janscheidegger** [quarkusio/quarkus#50830]
### Describe the bug

When having some "normal" JUnit Tests and `@QuarkusTest` Unit tests the coverage from Jacoco ist not collected properly.

```
<plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>0.8.14</version>
                <executions>
                    <execution>
                        <id>default-prepare-agent</id>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                        <configuration>
                            <exclClassLoaders>*QuarkusClassLoader</exclClassLoaders>
                            <destFile>${project.build.directory}/jacoco-quarkus.exec</destFile>
                            <append>true</append>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```
is configured

<img width="835" height="163" alt="Image" src="https://github.com/user-attachments/assets/03956d30-d4a2-4a95-8370-ee9043e5519b" />

convertAddress should be covered by the UnitTest and therefor testcoverage should be 100%

Intellij captures it correctly (Intellij Coverage NOT Jacoco)

<img width="834" height="227" alt="Image" src="https://github.com/user-attachments/assets/1bb99678-6e55-49e5-96cf-d30a6bc9f063" />

### Expected behavior

Coverage should be 100% as all code is covered.

### Actual behavior

Coverage is only applied for the QuarkusTests

### How to Reproduce?

1. Checkout: https://github.com/janscheidegger/jacoco-coverage
2. run `mvn clean verify`
3. check coverage report from jacoco

### Output of `uname -a` or `ver`

OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"

### Output of `java -version`

OpenJDK Runtime Environment Zulu21.44+18-SA (build 21.0.8+9-LTS)

### Quarkus version or git rev

3.29.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.11

**Comment by adampoplawski** [comment]
We had similar ask long time ago, but it is intentional design:
https://quarkus.io/guides/tests-with-coverage#coverage-for-tests-not-using-quarkustest
<img width="979" height="144" alt="Image" src="https://github.com/user-attachments/assets/f3a0a55a-14de-4069-943e-dc3ba971856f" />

We just use Jacoco directly (we have most tests without @QuarkusTest)

**Comment by janscheidegger** [comment]
Yes, I know, that's exactly what I did: https://github.com/janscheidegger/jacoco-coverage/blob/main/pom.xml#L119

**Comment by stefvanderweldevolksbanknl** [comment]
Hmm I'm also experiencing this for tests that have the `@QuarkusTest` annotation. Downgrading to version 3.28.5 is my current workaround.

**Comment by danillob** [comment]
I noticed the same issue yesterday, and it seems that the fix was commited today: https://github.com/quarkusio/quarkus/pull/51246

**Comment by mkouba** [comment]
> I noticed the same issue yesterday, and it seems that the fix was commited today: [#51246](https://github.com/quarkusio/quarkus/pull/51246)

Keep in mind that this only fixes the problem with `QuarkusComponentTest` in 3.29+.

**Comment by jeremisty** [comment]
I have the same issue. Any news regarding a fix ?

**Comment by mkouba** [comment]
@jeremisty The problem with `QuarkusComponentTest` will be fixed in Quarkus 3.31 but I suppose that you have problems with regular unit tests, right?

**Comment by RomainWilbert** [comment]
Same here with Junit test and Quarkus 3.29.2

**Comment by jeremisty** [comment]
> [@jeremisty](https://github.com/jeremisty) The problem with `QuarkusComponentTest` will be fixed in Quarkus 3.31 but I suppose that you have problems with regular unit tests, right?

Yes the problem is with @QuarkusTest annotation. Do you have  any news on which version the fix will be embeded ?

**Comment by Sbruk** [comment]
> [@jeremisty](https://github.com/jeremisty) The problem with `QuarkusComponentTest` will be fixed in Quarkus 3.31 but I suppose that you have problems with regular unit tests, right?

Hello @mkouba,

Would you have any update about the management of regular JUnit tests (no `@QuarkusTest`, no `@QuarkusComponentTest`, just `@Test` on the methods) in this context?

Thanks!

**Comment by mkouba** [comment]
> > [@jeremisty](https://github.com/jeremisty) The problem with `QuarkusComponentTest` will be fixed in Quarkus 3.31 but I suppose that you have problems with regular unit tests, right?
> 
> Hello [@mkouba](https://github.com/mkouba),
> 
> Would you have any update about the management of regular JUnit tests (no `@QuarkusTest`, no `@QuarkusComponentTest`, just `@Test` on the methods) in this context?
> 
> Thanks!

For regular JUnit tests you should be able to use the `jacoco-maven-plugin` directly and append the coverage to the destFile as described in https://quarkus.io/guides/tests-with-coverage#coverage-for-tests-not-using-quarkustest.

**Comment by Sbruk** [comment]
Hello @mkouba,

This plugin is already integrated in our project with the config detailed in the documentation you shared. However, we still have some plain old JUnit tests' results that are not taken into account.

Here is a [reproducer](https://github.com/user-attachments/files/29623741/code-with-quarkus.zip), which also contains the generated JaCoCo reports.

**Quarkus** 3.33.2.1
**Apache Maven** 3.9.16 (2bdd9fddda4b155ebf8000e807eb73fd829a51d5)
**Java version**:
openjdk version "25.0.3" 2026-04-21 LTS
OpenJDK Runtime Environment Temurin-25.0.3+9 (build 25.0.3+9-LTS)
OpenJDK 64-Bit Server VM Temurin-25.0.3+9 (build 25.0.3+9-LTS, mixed mode, sharing)

In this project, you can find the following classes:
- QuarkusTestService, which has `@ApplicationScoped` and is tested by QuarkusTestServiceTest which has `@QuarkusTest` and reports a coverage of 100%
- QuarkusComponentTestService, which has `@ApplicationScoped` and is tested by QuarkusComponentTestServiceTest which has `@QuarkusComponentTest` and reports a coverage of 100%
- QuarkusComponentTestUtils, which has `@ApplicationScoped` and is tested by QuarkusComponentTestUtilsTest which has `@QuarkusComponentTest` and reports a coverage of 100%
- PlainOldStringUtils, which does not have `@ApplicationScoped`. It is just a plain old utils class with a private constructor and one single static class and is tested by PlainOldStringUtilsTest which does not have `@QuarkusTest` or `@QuarkusComponentTest` and reports a coverage of 0%

The last two classes, **QuarkusComponentTestUtils** and **PlainOldStringUtils** (and the associated test classes) have the same code, except that in the latter the method is static.

Thanks for your help!

**Comment by mkouba** [comment]
> Hello [@mkouba](https://github.com/mkouba),
> 
> This plugin is already integrated in our project with the config detailed in the documentation you shared. However, we still have some plain old JUnit tests' results that are not taken into account.
> 
> Here is a [reproducer](https://github.com/user-attachments/files/29623741/code-with-quarkus.zip), which also contains the generated JaCoCo reports.
> 
> **Quarkus** 3.33.2.1 **Apache Maven** 3.9.16 (2bdd9fddda4b155ebf8000e807eb73fd829a51d5) **Java version**: openjdk version "25.0.3" 2026-04-21 LTS OpenJDK Runtime Environment Temurin-25.0.3+9 (build 25.0.3+9-LTS) OpenJDK 64-Bit Server VM Temurin-25.0.3+9 (build 25.0.3+9-LTS, mixed mode, sharing)
> 
> In this project, you can find the following classes:
> 
>     * QuarkusTestService, which has `@ApplicationScoped` and is tested by QuarkusTestServiceTest which has `@QuarkusTest` and reports a coverage of 100%
> 
>     * QuarkusComponentTestService, which has `@ApplicationScoped` and is tested by QuarkusComponentTestServiceTest which has `@QuarkusComponentTest` and reports a coverage of 100%
> 
>     * QuarkusComponentTestUtils, which has `@ApplicationScoped` and is tested by QuarkusComponentTestUtilsTest which has `@QuarkusComponentTest` and reports a coverage of 100%
> 
>     * PlainOldStringUtils, which does not have `@ApplicationScoped`. It is just a plain old utils class with a private constructor and one single static class and is tested by PlainOldStringUtilsTest which does not have `@QuarkusTest` or `@QuarkusComponentTest` and reports a coverage of 0%
> 
> 
> The last two classes, **QuarkusComponentTestUtils** and **PlainOldStringUtils** (and the associated test classes) have the same code, except that in the latter the method is static.
> 
> Thanks for your help!

@Sbruk You should fix the `maven-surefire-plugin` configuration - `<argLine>@{argLine}</argLine>` -> `<argLine>@{surefireArgLine}</argLine>`.

**Comment by Sbruk** [comment]
Hello @mkouba,

I've updated my [pom.xml](https://github.com/user-attachments/files/29631726/pom.xml) accordingly and I still get the same result:
<img width="2359" height="332" alt="Image" src="https://github.com/user-attachments/assets/1a0d2379-1a88-440e-89aa-c466e670726a" />

Here are the [jacoco-report.zip](https://github.com/user-attachments/files/29631762/jacoco-report.zip), if that can help.

Thanks

**Comment by mkouba** [comment]
> Hello [@mkouba](https://github.com/mkouba),
> 
> I've updated my [pom.xml](https://github.com/user-attachments/files/29631726/pom.xml) accordingly and I still get the same result: <img alt="Image" width="2000" height="281" src="https://private-user-images.githubusercontent.com/40559410/616804056-1a0d2379-1a88-440e-89aa-c466e670726a.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODMwNzU3NjUsIm5iZiI6MTc4MzA3NTQ2NSwicGF0aCI6Ii80MDU1OTQxMC82MTY4MDQwNTYtMWEwZDIzNzktMWE4OC00NDBlLTg5YWEtYzQ2NmU2NzA3MjZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNzAzVDEwNDQyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlYTI5MDlkZDU0YzNjYjg4MjA3NGY0ZTEyZTFhMzE4NDI5OThmYjFhNTMxOGExNDU3ZGZjYTMzZGM2OWIyMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.8geMwe-w3cWXzAZcQn2-d6Qa9RE6Xu0jx25ToUiA2K4">
> 
> Here are the [jacoco-report.zip](https://github.com/user-attachments/files/29631762/jacoco-report.zip), if that can help.
> 
> Thanks

That's weird. What command did you run after you changed the pom.xml`?

**Comment by Sbruk** [comment]
I've tried:
* **mvn verify** as per the documentation https://quarkus.io/guides/tests-with-coverage#running-the-tests-with-coverage - In that case, no jacoco report is even generated.
* **mvn test**, same result
* In IntelliJ, Right click > "Run 'Tests in 'org.acme''" - Reports are generated but as per my previous screenshot, with a 0% coverage on PlainOldStringUtilstests.

**Comment by mkouba** [comment]
> I've tried:
> 
>   * **mvn verify** as per the documentation https://quarkus.io/guides/tests-with-coverage#running-the-tests-with-coverage - In that case, no jacoco report is even generated.

That's superweird, because for `mvn verify`, Maven should also execute `test`, i.e. all unit tests, `QuarkusComponentTest`s and `QuarkusTest`s. And I did run `mvn clean verify` when I tested your setup.

> 
>   * **mvn test**, same result
> 
>   * In IntelliJ, Right click > "Run 'Tests in 'org.acme''" - Reports are generated but as per my previous screenshot, with a 0% coverage on PlainOldStringUtilstests.

**Comment by Sbruk** [comment]
Should I understand that it works as expected on your machine? If so, how could we investigate more?

**Comment by mkouba** [comment]
> Should I understand that it works as expected on your machine? If so, how could we investigate more?

Yes, but I have no idea what could be wrong. All I did was the `<argLine>@{surefireArgLine}</argLine>` fix mentioned above and `mvn clean verify`.
