### ISSUE TITLE
Quarkus 3.29.2 - Testcontainers version: 1.21.3 - Docker environment not found Linux Fedora

### ISSUE THREAD

**Issue by DaveO-Home** [quarkusio/quarkus#51002]
### Description

Upgraded:
```
 Upgrade  containerd.io-0:2.1.5-1.fc42.x86_64                               User            docker-ce-stable
  Upgrade  docker-ce-3:29.0.0-1.fc42.x86_64                                  User            docker-ce-stable
  Upgrade  docker-ce-cli-1:29.0.0-1.fc42.x86_64                              User            docker-ce-stable
  Upgrade  docker-ce-rootless-extras-0:29.0.0-1.fc42.x86_64                  Weak Dependency docker-ce-stable
  Replaced docker-ce-3:28.5.2-1.fc42.x86_64                                  User            @System
  Replaced docker-ce-cli-1:28.5.2-1.fc42.x86_64                              User            @System
  Replaced docker-ce-rootless-extras-0:28.5.2-1.fc42.x86_64                  Weak Dependency @System
```
Getting:
```
11/12 13:30 ERROR [org.test.dock.DockerClientProviderStrategy-266] Could not find a valid Docker environment. Please check configuration. Attempted configurations were:
        UnixSocketClientProviderStrategy: failed with exception BadRequestException (Status 400: {"message":"client version 1.32 is too old. Minimum supported API version is 1.44, please upgrade your client to a newer version"}
)
        DockerDesktopClientProviderStrategy: failed with exception NullPointerException (Cannot invoke "java.nio.file.Path.toString()" because the return value of "org.testcontainers.dockerclient.DockerDesktopClientProviderStrategy.getSocketPath()" is null)As no valid configuration was found, execution cannot continue.
```

### Implementation ideas

Even Fedora/Podman is having issues with the new version(starting/stopping containers). Fedora may have issues...

**Comment by geoand** [comment]
There is not much we can do on our side ATM. See https://quarkusio.zulipchat.com/#narrow/channel/187038-dev/topic/DevServices/near/555049672 and https://github.com/testcontainers/testcontainers-java/issues/11212

Hopefully TestContainers will release a new version soon

**Comment by geoand** [comment]
Reopening because TestContainers won't be releasing a new `1.x` release, so we need to fix it

**Comment by LarsSven** [comment]
We are indeed running into this now too, we had to revert our CI back to Docker 28.5.2 to work around this issue.

**Comment by gsmet** [comment]
I'm waiting for CI to go green in https://github.com/quarkusio/quarkus/pull/51009 to trigger the 3.29.3 release.

**Comment by Serkan80** [comment]
@gsmet , @geoand , are you guys going to backport the fix to the LTS version too ? That would be really nice, otherwise we have to wait for a long time until the next LTS contains the fix.

**Comment by geoand** [comment]
Yes, that's what the `triage/backport-3.27` label on the PR is for.

**Comment by timonzi** [comment]
Is there a reason why there is no backport for the 3.20 LTS version? We are currently using a workaround for this problem that works for us and will likely upgrade to the latest LTS version soon, but I am wondering why the fix is missing in 3.20.4.

**Comment by mkouba** [comment]
> Yes, that's what the `triage/backport-3.27` label on the PR is for.

@geoand @gsmet Hm, but this commit does not seem to be backported to 3.27, or?

**Comment by geoand** [comment]
There hasn't been a 3.27 release since the merge of said PR

**Comment by mkouba** [comment]
> There hasn't been a 3.27 release since the merge of said PR

I see. Just FYI I ran into this problem yesterday and it's pretty confusing. `-Dapi.version=1.44` solved the problem but 🤷

**Comment by geoand** [comment]
Yeah I know, it's an unfortunate situation that docker/testcontainers put the community in...

**Comment by oaklandcorp-jkaiser** [comment]
Just curious... Has anyone seen this problem go away in a real application using Quarkus? I noticed in the release change logs that `3.29.3` was the first version to integrate the fix so I tried it and `3.29.4` in a project affected by this issue and I didn't notice any difference. I was monkeying around this morning trying to find a workaround or fix but I couldn't spot any state (like a Docker container or the `.testcontainers.properties`) that should get in the way of fixed version. Luckily the suggested workaround above (`mvn -B verify -Dapi.version=1.44`) does work for the same project but I'd rather have it fixed officially.

I did notice this property when typing up this question. Should this fix or a prior Quarkus upgrade have come with a bump to the TestContainers version?
```
<testcontainers.version>1.19.6</testcontainers.version>
```

**Comment by DaveO-Home** [comment]
It was solved in 3.29.3 for me.... `gradlew quarkusDev` java 25 linux Fedora
```
11/26 09:52 INFO  [io.quar.hibe.orm.depl.HibernateOrmProcessor--1] Hibernate ORM was disabled explicitly by quarkus.hibernate-orm.blocking=false
> :do11/26 09:52 INFO  [org.test.DockerClientFactory-150] Testcontainers version: 1.21.3
<====11/26 09:52 INFO  [org.test.dock.DockerClientProviderStrategy-380] Loaded org.testcontainers.dockerclient.UnixSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first
11/26 09:52 INFO  [io.quar.devs.h2.depl.H2DevServicesProcessor-60] Dev Services for H2 started.
11/26 09:52 INFO  [io.quar.data.depl.devs.DevServicesDatasourceProcessor-383] Dev Services for default datasource (h2) started
     11/26 09:52 INFO  [org.test.dock.DockerClientProviderStrategy-290] Found Docker environment with local Unix socket (unix:///var/run/docker.sock)
11/26 09:52 INFO  [org.test.DockerClientFactory-208] Docker host IP address is localhost
11/26 09:52 INFO  [org.test.DockerClientFactory-241] Connected to docker: 
  Server Version: 29.0.2
  API Version: 1.52
  Operating System: Fedora Linux 43 (Cinnamon)
  Total Memory: 31925 MB
11/26 09:52 INFO  [org.test.imag.PullPolicy-59] Image pull policy will be performed by: DefaultPullPolicy()
11/26 09:52 INFO  [org.test.util.ImageNameSubstitutor-55] Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
11/26 09:52 INFO  [org.test.DockerClientFactory-256] Checking the system...
11/26 09:52 INFO  [org.test.DockerClientFactory-277] ✔︎ Docker server version should be at least 1.6.0

11/26 09:52 INFO  [org.neo4.driv.inte.DriverFactory--1] Driver instance 381660733 created for server uri 'bolt://localhost:7687'

```

**Comment by oaklandcorp-jkaiser** [comment]
Thanks for confirming @DaveO-Home! You made me read a bit more closely this afternoon. Unfortunately I picked the one project in my arsenal that creates some test containers by hand in a `QuarkusTestResourceLifecycleManager` to try things out. I tried another project that just allows dev mode to automatically create the needed test containers and `3.29.4` did do the trick.

**Comment by YassinHajaj** [comment]
Still not fixed on 3.32.2, so I still need to use -Dapi.version=1.44

**Comment by gsmet** [comment]
We are using Testcontainers 2.x in 3.32 so I don't see how it could happen. You would need to provide more information.

**Comment by YassinHajaj** [comment]
I'll try to make a tiny reproducer later today
