### ISSUE TITLE
Issues with rest client

### ISSUE THREAD

**Issue by constantin-ungureanu-github** [quarkusio/quarkus#51227]
### Describe the bug

When using the rest client, there are multiple issues observed:
- multiple threads are open and never closed
- random deadlocks (https://github.com/quarkusio/quarkus/issues/49989) 

When used with multipart, there are also these inconveniences:
- does not delete the created files, leaving a mess behind
- cannot specify if the file is in memory (or at least first x number of bytes)
- cannot send requests in parallel

<img width="1463" height="1312" alt="Image" src="https://github.com/user-attachments/assets/76922bbb-7734-4706-b71c-4937ee1e5b6d" />

### Expected behavior

no issues.

### Actual behavior

nightmare to use rest client in a production application.

### How to Reproduce?

Reproducer is here:
https://github.com/constantin-ungureanu-github/quarkus-rest-client-server

### Output of `java -version`

21

**Comment by geoand** [comment]
Thanks for reporting.

I am not able to reproduce the issue with the large number of threads you posted. Do you have any more details about those threads?

> does not delete the created files, leaving a mess behind

Which files are we talking about?

> cannot send requests in parallel

What **exactly** do you mean by this?

**Comment by constantin-ungureanu-github** [comment]
To reproduce you just need to run debug in your IDE, and the large number of threads pops-up. Have you tried debug?

The multipart client files are never deleted, as per documentation. This is inconvenient as it requires manual tracking of each of these files. And for small files there should just be an option to store in memory, not on file system, always as a file.

https://github.com/constantin-ungureanu-github/quarkus-rest-client-server/blob/main/quarkus-rest-client/src/main/java/org/client/app/Service.java

Here you can see also the parallel being commented out, line 24. You just need to look into the code.
How can one use the rest client to send parallel requests? 

Maybe @cescoffier or others can try to reproduce.

**Comment by constantin-ungureanu-github** [comment]
It seems to create a new thread for each and every call that the rest client is making, but the threads don't seem to ever get closed. I tried even to use the option to specify a number of pool size for rest client, that doesn't seem to do anything.

**Comment by geoand** [comment]
> To reproduce you just need to run debug in your IDE, and the large number of threads pops-up. Have you tried debug?

I would not have asked, had I not done this 😉.  Moreover, the names of those threads are not consistent with anything we do in Quarkus, which makes me wonder if your IDE is creating them. 

> Here you can see also the parallel being commented out, line 24. You just need to look into the code.

Unfortunately, your comments are severely lacking in any detail. 
Despite this, I did actually try it, and the problem is the use of the ForkJoin pool in parallel streams, not the REST Client itself.

> How can one use the rest client to send parallel requests?

The two main ways you can approach this, are:

* Use reactive programming via the REST Client's ability to return `Uni<...>`
* Inject an `ExecutorService` and use that submit REST Client tasks

> Maybe @cescoffier or others can try to reproduce.

Clement has too many things to deal with as it is.

**Comment by constantin-ungureanu-github** [comment]
<img width="1920" height="1137" alt="Image" src="https://github.com/user-attachments/assets/55c1509a-f263-4141-9d03-6a508d9030ff" />

**Comment by cescoffier** [comment]
I doubt that Quarkus is creating these threads. Can you post your config?

**Comment by cescoffier** [comment]
BRW, I believe these files we be deleted once the JVM exists.

**Comment by geoand** [comment]
> BRW, I believe these files we be deleted once the JVM exists.

They will. The reason we can delete them ourselves is that we have no idea of the scope of their use

**Comment by constantin-ungureanu-github** [comment]
My config is Windows + WSL with Podman. java 21 quarkus LTS.
I have very limited time availability, this is why the short comments. Please understand this.
In the weekend I plan to remote debug this.

**Comment by cescoffier** [comment]
> They will. The reason we can delete them ourselves is that we have no idea of the scope of their use

Yes, totally. I think the application code can delete them when it's no more in used.

**Comment by constantin-ungureanu-github** [comment]
I had some availability in the past weekend. I updated the reproducer to use latest quarkus release. Here are my 2 cents:

1. Regarding the infinite number of threads created and not closed observed during running the integrations tests:
- Remote debug shows the actual container does not have any of these threads, attached snapshot
- It happens in on a Windows system, using WSL + podman;
- Tried on a MacOS and doesn't happens
- This is good news, still would be interesting to understand why it appears on Windows machines during integration tests

<img width="865" height="736" alt="Image" src="https://github.com/user-attachments/assets/88bf712d-10f1-496b-9087-94f5e1334703" />

2. Regarding the deletion of files:
- The user must be aware of all the files that get created and take care of cleaning. Is like manually doing garbage collecting. I see that for the server rest there is such an option quarkus.http.body.delete-uploaded-files-on-end=true . Why not also for the client? Not a deal breaking, but somehow inconvenient. 
- The issue is that for small files, there is no way to bypass (at least from documentation as I understand) the file creation and have the content of multipart stored in a buffer or something. This leads to performance dropping, especially in scenarios with lot of small multiparts
- Ideally there would be an option to substitute the file in multipart to some sort of object mapped or better to a buffered stream, where one can specify a number of bytes to be kept in memory, and if that threshold is passed then to move the content to filesystem. 

3. Using the client in parallel.
- It is confusing and error prune that the client cannot be used from inside parallel lambdas. 
- If the client in order to be called in parallel needs to be scheduled on some executor, maybe some documentation should be available. What type of threads the executor should spin? Blocking vs nonblocking. Virtual threads?

4. During running various builds, some random issues pop-up, but only occasionally, so not reproducible:

a)
```
2025-11-29T10:54:30Z WARN  [io.quarkus.vertx.http.runtime.QuarkusErrorHandler] (executor-thread-1) Worker thread pool exhaustion, no more worker threads available - returning a `503 - SERVICE UNAVAILABLE` response.
```

b)
```
2025-11-29T15:17:40Z INFO  [org.client.app.Service] (executor-thread-1) Processed file 322
2025-11-29T15:17:40Z INFO  [org.client.app.Service] (executor-thread-1) Processed file 323
2025-11-29T15:17:40Z INFO  [io.quarkus.opentelemetry.runtime.QuarkusContextStorage] (vert.x-eventloop-thread-3) Context in storage not the expected context, Scope.close was not called correctly. Details: OTel context before: {spanId=4c66c03472961ef9, traceId=949ed8892bee4219b71c69c00eccf7cb, sampled=true, parentId=a30d7ae333100186}. OTel context toAttach: {spanId=a30d7ae333100186, traceId=949ed8892bee4219b71c69c00eccf7cb, sampled=true}
2025-11-29T15:17:40Z INFO  [org.client.app.Service] (executor-thread-1) Processed file 324
2025-11-29T15:17:40Z INFO  [org.client.config.AdapterApplicationLifecycle] (main) The rest client application is shutting down...
2025-11-29T15:17:40Z ERROR [org.client.app.Service] (executor-thread-1) Runtime exception: Client is closed [Error Occurred After Shutdown]: java.lang.IllegalStateException: Client is closed
	at io.vertx.core.http.impl.HttpClientImpl.checkClosed(HttpClientImpl.java:405)
	at io.vertx.core.http.impl.HttpClientImpl.doRequest(HttpClientImpl.java:281)
	at io.vertx.core.http.impl.HttpClientImpl.request(HttpClientImpl.java:184)
	at org.jboss.resteasy.reactive.client.handlers.ClientSendRequestHandler$5.lambda$apply$0(ClientSendRequestHandler.java:468)
```

c) some warnings of otel options being enabled. this is at runtime. I think those should not be warnings, 
```
quarkus-rest-server  | 2025-11-30T23:18:37Z WARN  [io.quarkus.config] (main) Unrecognized configuration key "quarkus.otel.enabled" was provided; it will be ignored; verifythat the dependency extension for this configuration is set or that you did not make a typo
quarkus-rest-server  | 2025-11-30T23:18:37Z WARN  [io.quarkus.config] (main) Unrecognized configuration key "quarkus.otel.logs.enabled" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
quarkus-rest-server  | 2025-11-30T23:18:37Z WARN  [io.quarkus.config] (main) Unrecognized configuration key "quarkus.otel.metrics.enabled" was provided; it will be ignored;
 verify that the dependency extension for this configuration is set or that you did not make a typo
quarkus-rest-server  | 2025-11-30T23:18:37Z WARN  [io.quarkus.config] (main) Unrecognized configuration key "quarkus.otel.logs.handler.enabled" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
quarkus-rest-server  | 2025-11-30T23:18:37Z WARN  [io.quarkus.config] (main) Unrecognized configuration key "quarkus.otel.service.name" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
```


5. issues with http2 enabled
- When http2 is enabled, I noticed sometimes this error:

```
jakarta.ws.rs.ProcessingException: java.io.IOException: Max content exceeded 65536 bytes.
        at org.jboss.resteasy.reactive.client.handlers.ClientSendRequestHandler$4.handle(ClientSendRequestHandler.java:402)
        at org.jboss.resteasy.reactive.client.handlers.ClientSendRequestHandler$4.handle(ClientSendRequestHandler.java:393)
        at io.vertx.core.impl.future.FutureImpl$2.onFailure(FutureImpl.java:117)
        at io.vertx.core.impl.future.FutureImpl$ListenerArray.onFailure(FutureImpl.java:316)
        at io.vertx.core.impl.future.FutureBase.lambda$emitFailure$1(FutureBase.java:75)
        at io.vertx.core.impl.ContextImpl.execute(ContextImpl.java:312)
        at io.vertx.core.impl.DuplicatedContext.execute(DuplicatedContext.java:168)
        at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:72)
        at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:278)
        at io.vertx.core.http.impl.HttpClientRequestBase.fail(HttpClientRequestBase.java:186)
        at io.vertx.core.http.impl.HttpClientRequestBase.handleException(HttpClientRequestBase.java:181)
```

- tried out in the running application to send large files, and sure enough it crashes, see below. This is reproducible, using large files and waiting enough to happen.

```
quarkus-rest-client  | 2025-11-30T23:49:30Z INFO  [org.client.app.Service] (executor-thread-1) Processed file pfx1811028535168346224sfx # 57
quarkus-rest-client  | 2025-11-30T23:50:30Z ERROR [org.client.app.Service] (executor-thread-1) Runtime exception: Stream closed before write could take place: jakarta.ws.rs
.ProcessingException: Stream closed before write could take place
quarkus-rest-client  |  at org.jboss.resteasy.reactive.client.impl.InvocationBuilderImpl.unwrap(InvocationBuilderImpl.java:212)
quarkus-rest-client  |  at org.jboss.resteasy.reactive.client.impl.InvocationBuilderImpl.method(InvocationBuilderImpl.java:328)
quarkus-rest-client  |  at org.server.client.ServerApi$$QuarkusRestClientInterface.test(Unknown Source)
quarkus-rest-client  |  at org.server.client.ServerApi$$CDIWrapper.test(Unknown Source)
quarkus-rest-client  |  at org.client.app.Service.test(Service.java:45)
quarkus-rest-client  |  at org.client.app.Resource.test(Resource.java:31)
quarkus-rest-client  |  at org.client.app.Resource_Subclass.test$$superforward(Unknown Source)
quarkus-rest-client  |  at org.client.app.Resource_Subclass$0.apply(Unknown Source)
quarkus-rest-client  |  at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
quarkus-rest-client  |  at io.quarkus.arc.impl.AroundInvokeInvocationContext$NextAroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:97)
quarkus-rest-client  |  at io.quarkus.hibernate.validator.runtime.interceptor.AbstractMethodValidationInterceptor.validateMethodInvocation(AbstractMethodValidationIntercept
or.java:73)
quarkus-rest-client  |  at io.quarkus.hibernate.validator.runtime.jaxrs.ResteasyReactiveEndPointValidationInterceptor.validateMethodInvocation(ResteasyReactiveEndPointValid
ationInterceptor.java:21)
quarkus-rest-client  |  at io.quarkus.hibernate.validator.runtime.jaxrs.ResteasyReactiveEndPointValidationInterceptor_Bean.intercept(Unknown Source)
quarkus-rest-client  |  at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
quarkus-rest-client  |  at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:70)
quarkus-rest-client  |  at io.quarkus.arc.impl.AroundInvokeInvocationContext$NextAroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:97)
quarkus-rest-client  |  at io.quarkus.micrometer.runtime.MicrometerCountedInterceptor.countedMethod(MicrometerCountedInterceptor.java:95)
quarkus-rest-client  |  at io.quarkus.micrometer.runtime.MicrometerCountedInterceptor_Bean.intercept(Unknown Source)
quarkus-rest-client  |  at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
quarkus-rest-client  |  at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:70)
quarkus-rest-client  |  at io.quarkus.arc.impl.AroundInvokeInvocationContext$NextAroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:97)
quarkus-rest-client  |  at io.quarkus.micrometer.runtime.MicrometerTimedInterceptor.timedMethod(MicrometerTimedInterceptor.java:79)
quarkus-rest-client  |  at io.quarkus.micrometer.runtime.MicrometerTimedInterceptor_Bean.intercept(Unknown Source)
quarkus-rest-client  |  at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
quarkus-rest-client  |  at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:70)
quarkus-rest-client  |  at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
quarkus-rest-client  |  at io.quarkus.opentelemetry.runtime.tracing.cdi.WithSpanInterceptor.span(WithSpanInterceptor.java:151)
quarkus-rest-client  |  at io.quarkus.opentelemetry.runtime.tracing.cdi.WithSpanInterceptor_Bean.intercept(Unknown Source)
quarkus-rest-client  |  at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
quarkus-rest-client  |  at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
quarkus-rest-client  |  at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
quarkus-rest-client  |  at org.client.app.Resource_Subclass.test(Unknown Source)
quarkus-rest-client  |  at org.client.app.Resource$quarkusrestinvoker$test_9614356e46471472e3b7700741e09146498ec95f.invoke(Unknown Source)
quarkus-rest-client  |  at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
quarkus-rest-client  |  at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:183)
quarkus-rest-client  |  at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
quarkus-rest-client  |  at io.quarkus.vertx.core.runtime.VertxCoreRecorder$15.runWith(VertxCoreRecorder.java:645)
quarkus-rest-client  |  at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2651)
quarkus-rest-client  |  at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2630)
quarkus-rest-client  |  at org.jboss.threads.EnhancedQueueExecutor.runThreadBody(EnhancedQueueExecutor.java:1622)
quarkus-rest-client  |  at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1589)
quarkus-rest-client  |  at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
quarkus-rest-client  |  at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
quarkus-rest-client  |  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
quarkus-rest-client  |  at java.base/java.lang.Thread.run(Thread.java:1583)
quarkus-rest-client  | Caused by: io.netty.handler.codec.http2.Http2Exception$StreamException: Stream closed before write could take place
quarkus-rest-client  |  at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:171)
quarkus-rest-client  |  at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$FlowState.cancel(DefaultHttp2RemoteFlowController.java:479)
quarkus-rest-client  |  at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$1.onStreamClosed(DefaultHttp2RemoteFlowController.java:103)
quarkus-rest-client  |  at io.netty.handler.codec.http2.DefaultHttp2Connection.notifyClosed(DefaultHttp2Connection.java:355)
quarkus-rest-client  |  at io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams.removeFromActiveStreams(DefaultHttp2Connection.java:1043)
quarkus-rest-client  |  at io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams.deactivate(DefaultHttp2Connection.java:999)
quarkus-rest-client  |  at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultStream.close(DefaultHttp2Connection.java:515)
quarkus-rest-client  |  at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultStream.close(DefaultHttp2Connection.java:521)
quarkus-rest-client  |  at io.netty.handler.codec.http2.Http2ConnectionHandler.doCloseStream(Http2ConnectionHandler.java:919)
quarkus-rest-client  |  at io.netty.handler.codec.http2.Http2ConnectionHandler.closeStream(Http2ConnectionHandler.java:627)
quarkus-rest-client  |  at io.netty.handler.codec.http2.Http2ConnectionHandler.processRstStreamWriteResult(Http2ConnectionHandler.java:905)
quarkus-rest-client  |  at io.netty.handler.codec.http2.Http2ConnectionHandler.access$1100(Http2ConnectionHandler.java:64)
quarkus-rest-client  |  at io.netty.handler.codec.http2.Http2ConnectionHandler$4.operationComplete(Http2ConnectionHandler.java:820)
quarkus-rest-client  |  at io.netty.handler.codec.http2.Http2ConnectionHandler$4.operationComplete(Http2ConnectionHandler.java:817)
quarkus-rest-client  |  at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:604)
quarkus-rest-client  |  at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:597)
quarkus-rest-client  |  at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:573)
quarkus-rest-client  |  at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:506)
quarkus-rest-client  |  at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:650)
quarkus-rest-client  |  at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:639)
quarkus-rest-client  |  at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:119)
quarkus-rest-client  |  at io.netty.util.internal.PromiseNotificationUtil.trySuccess(PromiseNotificationUtil.java:48)
quarkus-rest-client  |  at io.netty.channel.ChannelOutboundBuffer.safeSuccess(ChannelOutboundBuffer.java:748)
quarkus-rest-client  |  at io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:303)
quarkus-rest-client  |  at io.netty.channel.ChannelOutboundBuffer.removeBytes(ChannelOutboundBuffer.java:383)
quarkus-rest-client  |  at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:420)
quarkus-rest-client  |  at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:929)
quarkus-rest-client  |  at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:359)
quarkus-rest-client  |  at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:893)
quarkus-rest-client  |  at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1319)
quarkus-rest-client  |  at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:935)
quarkus-rest-client  |  at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:921)
quarkus-rest-client  |  at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:907)
quarkus-rest-client  |  at io.netty.handler.logging.LoggingHandler.flush(LoggingHandler.java:304)
quarkus-rest-client  |  at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:937)
quarkus-rest-client  |  at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:921)
quarkus-rest-client  |  at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:907)
quarkus-rest-client  |  at io.netty.handler.codec.http2.Http2ConnectionHandler.flush(Http2ConnectionHandler.java:195)
quarkus-rest-client  |  at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:941)
quarkus-rest-client  |  at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:921)
quarkus-rest-client  |  at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:907)
quarkus-rest-client  |  at io.netty.channel.DefaultChannelPipeline.flush(DefaultChannelPipeline.java:916)
quarkus-rest-client  |  at io.netty.channel.AbstractChannel.flush(AbstractChannel.java:253)
quarkus-rest-client  |  at io.vertx.core.http.impl.VertxHttp2ConnectionHandler.checkFlush(VertxHttp2ConnectionHandler.java:247)
quarkus-rest-client  |  at io.vertx.core.http.impl.VertxHttp2ConnectionHandler.writeReset(VertxHttp2ConnectionHandler.java:290)
quarkus-rest-client  |  at io.vertx.core.http.impl.VertxHttp2Stream.doWriteReset(VertxHttp2Stream.java:286)
quarkus-rest-client  |  at io.vertx.core.http.impl.Http2ClientConnection$Stream.doWriteReset(Http2ClientConnection.java:302)
quarkus-rest-client  |  at io.vertx.core.http.impl.VertxHttp2Stream.writeReset(VertxHttp2Stream.java:273)
quarkus-rest-client  |  at io.vertx.core.impl.ContextImpl.emit(ContextImpl.java:342)
quarkus-rest-client  |  at io.vertx.core.impl.ContextImpl.emit(ContextImpl.java:335)
quarkus-rest-client  |  at io.vertx.core.http.impl.Http2ClientConnection$StreamImpl.reset(Http2ClientConnection.java:705)
quarkus-rest-client  |  at io.vertx.core.http.impl.Http2UpgradeClientConnection$DelegatingStream.reset(Http2UpgradeClientConnection.java:233)
quarkus-rest-client  |  at io.vertx.core.http.impl.HttpClientRequestBase.reset(HttpClientRequestBase.java:268)
quarkus-rest-client  |  at io.vertx.core.http.impl.HttpClientRequestBase.handleTimeout(HttpClientRequestBase.java:238)
quarkus-rest-client  |  at io.vertx.core.http.impl.HttpClientRequestBase.lambda$setTimeout$1(HttpClientRequestBase.java:169)
quarkus-rest-client  |  at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:1100)
quarkus-rest-client  |  at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:1071)
quarkus-rest-client  |  at io.vertx.core.impl.ContextImpl.emit(ContextImpl.java:342)
quarkus-rest-client  |  at io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:163)
quarkus-rest-client  |  at io.vertx.core.impl.ContextInternal.emit(ContextInternal.java:200)
quarkus-rest-client  |  at io.vertx.core.impl.VertxImpl$InternalTimerHandler.run(VertxImpl.java:1089)
quarkus-rest-client  |  at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
quarkus-rest-client  |  at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:160)
quarkus-rest-client  |  at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
quarkus-rest-client  |  at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
quarkus-rest-client  |  at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
quarkus-rest-client  |  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
quarkus-rest-client  |  at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:998)
quarkus-rest-client  |  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
quarkus-rest-client  |  ... 2 more
```

6. The rest client deadlock. This was actually the most critical part for which I created this repo. Is not reproducible in this repo, not sure what are the conditions when it happens. But it is still happening (on a different project that I cannot share here). I'll try when time allows it to give it some more shots. Maybe is also related to the host machine being Windows, or maybe is related to podman. 

```
@QuarkusTest has detected a hang, as there has been no test activity in PT10M
To configure this timeout use the quarkus.test.hang-detection-timeout config property
A stack trace is below to help diagnose the potential hang
=== Stack Trace ===
Thread main: WAITING
  Waiting on java.util.concurrent.CountDownLatch$Sync@739c67fb
  Stack:
    java.base@21.0.9/jdk.internal.misc.Unsafe.park(Native Method)
    java.base@21.0.9/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
    java.base@21.0.9/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:754)
    java.base@21.0.9/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1099)
    java.base@21.0.9/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:230)
    io.quarkus.vertx.core.runtime.VertxCoreRecorder.destroy(VertxCoreRecorder.java:436)
    io.quarkus.vertx.core.runtime.VertxCoreRecorder$1.run(VertxCoreRecorder.java:111)
    io.quarkus.runtime.StartupContext.runAllAndClear(StartupContext.java:79)
    io.quarkus.runtime.StartupContext.close(StartupContext.java:71)
    io.quarkus.runner.ApplicationImpl.doStop(Unknown Source)
    io.quarkus.runtime.Application.stop(Application.java:208)
    io.quarkus.runtime.Application.stop(Application.java:155)
    io.quarkus.runtime.Application.close(Application.java:137)
    io.quarkus.runner.bootstrap.StartupActionImpl$3.close(StartupActionImpl.java:362)
    io.quarkus.runner.bootstrap.RunningQuarkusApplicationImpl.close(RunningQuarkusApplicationImpl.java:35)
    io.quarkus.test.junit.QuarkusTestExtension$4.close(QuarkusTestExtension.java:266)
    io.quarkus.test.junit.QuarkusTestExtension$ExtensionState.doClose(QuarkusTestExtension.java:1177)
    io.quarkus.test.junit.QuarkusTestExtensionState.close(QuarkusTestExtensionState.java:114)
    io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:633)
    io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:685)
    app//org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor$$Lambda/0x00000266548c8800.invoke(Unknown Source)
    app//org.junit.jupiter.engine.descriptor.CallbackSupport.lambda$invokeBeforeCallbacks$0(CallbackSupport.java:34)
    app//org.junit.jupiter.engine.descriptor.CallbackSupport$$Lambda/0x00000266548c5800.execute(Unknown Source)
    app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
    app//org.junit.jupiter.engine.descriptor.CallbackSupport.invokeBeforeCallbacks(CallbackSupport.java:34)
    app//org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:434)
    app//org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:243)
    app//org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:87)
    app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:154)
    app//org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda/0x000002665481f408.execute(Unknown Source)
    app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
    app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:147)
    app//org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda/0x000002665481f1f0.invoke(Unknown Source)
    app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
    app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:145)
    app//org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda/0x0000026654821c80.execute(Unknown Source)
    app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
    app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:144)
    app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:101)
    app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService$$Lambda/0x000002665481ca28.accept(Unknown Source)
    java.base@21.0.9/java.util.ArrayList.forEach(ArrayList.java:1596)
    app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
    app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:161)
    app//org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda/0x000002665481f408.execute(Unknown Source)
    app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
    app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:147)
    app//org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda/0x000002665481f1f0.invoke(Unknown Source)
    app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
    app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:145)
    app//org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda/0x0000026654821c80.execute(Unknown Source)
    app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
    app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:144)
    app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:101)
    app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
    app//org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
    app//org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
    app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.executeEngine(EngineExecutionOrchestrator.java:230)
    app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.failOrExecuteEngine(EngineExecutionOrchestrator.java:204)
    app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:172)
    app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:101)
    app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:64)
    app//org.junit.platform.launcher.core.EngineExecutionOrchestrator$$Lambda/0x0000026654834888.accept(Unknown Source)
    app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:150)
    app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:63)
    app//org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:109)
    app//org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:91)
    app//org.junit.platform.launcher.core.DelegatingLauncher.execute(DelegatingLauncher.java:47)
    app//org.junit.platform.launcher.core.InterceptingLauncher.lambda$execute$1(InterceptingLauncher.java:39)
    app//org.junit.platform.launcher.core.InterceptingLauncher$$Lambda/0x000002665483b8e0.proceed(Unknown Source)
    app//org.junit.platform.launcher.core.ClasspathAlignmentCheckingLauncherInterceptor.intercept(ClasspathAlignmentCheckingLauncherInterceptor.java:25)
    app//org.junit.platform.launcher.core.InterceptingLauncher.execute(InterceptingLauncher.java:38)
    app//org.junit.platform.launcher.core.DelegatingLauncher.execute(DelegatingLauncher.java:47)
    app//org.apache.maven.surefire.junitplatform.LauncherAdapter.executeWithoutCancellationToken(LauncherAdapter.java:60)
    app//org.apache.maven.surefire.junitplatform.LauncherAdapter.execute(LauncherAdapter.java:52)
    app//org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:203)
    app//org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:168)
    app//org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:136)
    app//org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
    app//org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
    app//org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
    app//org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
Thread Reference Handler: RUNNABLE
  Stack:
    java.base@21.0.9/java.lang.ref.Reference.waitForReferencePendingList(Native Method)
    java.base@21.0.9/java.lang.ref.Reference.processPendingReferences(Reference.java:246)
    java.base@21.0.9/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:208)
Thread Finalizer: WAITING
  Waiting on java.lang.ref.NativeReferenceQueue$Lock@ae0c9a1
  Stack:
    java.base@21.0.9/java.lang.Object.wait0(Native Method)
    java.base@21.0.9/java.lang.Object.wait(Object.java:366)
    java.base@21.0.9/java.lang.Object.wait(Object.java:339)
    java.base@21.0.9/java.lang.ref.NativeReferenceQueue.await(NativeReferenceQueue.java:48)
    java.base@21.0.9/java.lang.ref.ReferenceQueue.remove0(ReferenceQueue.java:158)
    java.base@21.0.9/java.lang.ref.NativeReferenceQueue.remove(NativeReferenceQueue.java:89)
    java.base@21.0.9/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:173)
....
```

**Comment by geoand** [comment]
Regarding the parallel REST client usage issue:

We've already fixed the underlying classloader issue in #50635 (available since Quarkus 3.29.1).

**If you're on Quarkus 3.29.1 or later:** The fix is already included.

**If you're on an earlier version (like 3.27.x):** You can use this workaround when launching tests:

```
-Djava.util.concurrent.ForkJoinPool.common.threadFactory=io.quarkus.bootstrap.forkjoin.QuarkusForkJoinWorkerThreadFactory
```

This will prevent the `IllegalStateException` you're experiencing when using the REST client in parallel.

**Comment by geoand** [comment]
> some warnings of otel options being enabled. this is at runtime. I think those should not be warnings,

Quarkus explicitly adds these, this is a feature

**Comment by geoand** [comment]
> I'll try when time allows it to give it some more shots

Thanks! Are there any debug logs logged from Vert.x that show any relevant information for this deadlock?

**Comment by geoand** [comment]
Regarding the HTTP/2 error you're seeing:

```
jakarta.ws.rs.ProcessingException: java.io.IOException: Max content exceeded 65536 bytes.
```

This was addressed in #47649 (fixed in Quarkus *3.24.1*) by adding a configuration property that allows you to increase the HTTP/2 upgrade max content length.

Could you try setting the following property in your `application.properties`:

```properties
quarkus.rest-client.http2-upgrade-max-content-length=131072
```

You can adjust the size as needed for your use case. Please let us know if this resolves the HTTP/2 max content issue you're experiencing.

**Comment by constantin-ungureanu-github** [comment]
> Regarding the HTTP/2 error you're seeing:
> 
> ```
> jakarta.ws.rs.ProcessingException: java.io.IOException: Max content exceeded 65536 bytes.
> ```
> 
> This was addressed in [#47649](https://github.com/quarkusio/quarkus/issues/47649) (fixed in Quarkus _3.24.1_) by adding a configuration property that allows you to increase the HTTP/2 upgrade max content length.
> 
> Could you try setting the following property in your `application.properties`:
> 
> quarkus.rest-client.http2-upgrade-max-content-length=131072
> You can adjust the size as needed for your use case. Please let us know if this resolves the HTTP/2 max content issue you're experiencing.


This was very helpful !

quarkus.rest-client.http2=true
quarkus.rest-client.http2-upgrade-max-content-length=2147483647

Setting to lower values still hits the max value, ex: "Max content exceeded 524280 bytes.".

But the most important thing, with rest client http2 enabled the deadlock no longer is happening  (point 6, previous comment) !

**Comment by geoand** [comment]
I'm very glad to hear that!

Let's close the issue, as I believe all the points have been addressed

**Comment by constantin-ungureanu-github** [comment]
Actually retried few more times and still hangs sometimes, although not as often. I don't have other debug logs from Vertx.

```
@QuarkusTest has detected a hang, as there has been no test activity in PT10M
To configure this timeout use the quarkus.test.hang-detection-timeout config property
A stack trace is below to help diagnose the potential hang
=== Stack Trace ===
Thread main: WAITING
  Waiting on java.util.concurrent.CountDownLatch$Sync@4b478627
  Stack:
    java.base@21.0.9/jdk.internal.misc.Unsafe.park(Native Method)
    java.base@21.0.9/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
    java.base@21.0.9/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:754)
    java.base@21.0.9/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1099)
    java.base@21.0.9/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:230)
    io.quarkus.vertx.core.runtime.VertxCoreRecorder.destroy(VertxCoreRecorder.java:436)
    io.quarkus.vertx.core.runtime.VertxCoreRecorder$1.run(VertxCoreRecorder.java:111)
    io.quarkus.runtime.StartupContext.runAllAndClear(StartupContext.java:79)
    io.quarkus.runtime.StartupContext.close(StartupContext.java:71)
    io.quarkus.runner.ApplicationImpl.doStop(Unknown Source)
    io.quarkus.runtime.Application.stop(Application.java:208)
    io.quarkus.runtime.Application.stop(Application.java:155)
    io.quarkus.runtime.Application.close(Application.java:137)
    io.quarkus.runner.bootstrap.StartupActionImpl$3.close(StartupActionImpl.java:361)
    io.quarkus.runner.bootstrap.RunningQuarkusApplicationImpl.close(RunningQuarkusApplicationImpl.java:35)
    io.quarkus.test.junit.QuarkusTestExtension$4.close(QuarkusTestExtension.java:267)
    io.quarkus.test.junit.QuarkusTestExtension$ExtensionState.doClose(QuarkusTestExtension.java:1179)
    io.quarkus.test.junit.QuarkusTestExtensionState.close(QuarkusTestExtensionState.java:114)
    io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:634)
    io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:687)
    app//org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor$$Lambda/0x000002389daa4580.invoke(Unknown Source)
    app//org.junit.jupiter.engine.descriptor.CallbackSupport.lambda$invokeBeforeCallbacks$0(CallbackSupport.java:34)
    app//org.junit.jupiter.engine.descriptor.CallbackSupport$$Lambda/0x000002389daa4988.execute(Unknown Source)
    app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:74)
    app//org.junit.jupiter.engine.descriptor.CallbackSupport.invokeBeforeCallbacks(CallbackSupport.java:34)
    app//org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:436)
    app//org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:247)
    app//org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:88)
    app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$2(NodeTestTask.java:173)
    app//org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda/0x000002389da8f9c8.execute(Unknown Source)
    app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:74)
    app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$1(NodeTestTask.java:166)
    app//org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda/0x000002389da8f7b0.invoke(Unknown Source)
    app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:138)
    app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$0(NodeTestTask.java:164)
    app//org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda/0x000002389da8f3a8.execute(Unknown Source)
    app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:74)
    app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:163)
    app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:116)
    app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService$$Lambda/0x000002389da98000.accept(Unknown Source)
    java.base@21.0.9/java.util.ArrayList.forEach(ArrayList.java:1596)
    app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:42)
    app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$2(NodeTestTask.java:180)
    app//org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda/0x000002389da8f9c8.execute(Unknown Source)
    app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:74)
    app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$1(NodeTestTask.java:166)
    app//org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda/0x000002389da8f7b0.invoke(Unknown Source)
    app//org.junit.platform.engine.support.hierarchical.Node.around(Node.java:138)
    app//org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$0(NodeTestTask.java:164)
    app//org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda/0x000002389da8f3a8.execute(Unknown Source)
    app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:74)
    app//org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:163)
    app//org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:116)
    app//org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:36)
    app//org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:52)
    app//org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:58)
    app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.executeEngine(EngineExecutionOrchestrator.java:246)
    app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.failOrExecuteEngine(EngineExecutionOrchestrator.java:218)
    app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:179)
    app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
    app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:66)
    app//org.junit.platform.launcher.core.EngineExecutionOrchestrator$$Lambda/0x000002389da79dd8.accept(Unknown Source)
    app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:157)
    app//org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:65)
    app//org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:125)
    app//org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
    app//org.junit.platform.launcher.core.DelegatingLauncher.execute(DelegatingLauncher.java:58)
    app//org.junit.platform.launcher.core.InterceptingLauncher.lambda$execute$2(InterceptingLauncher.java:57)
    app//org.junit.platform.launcher.core.InterceptingLauncher$$Lambda/0x000002389da78a90.proceed(Unknown Source)
    app//org.junit.platform.launcher.core.ClasspathAlignmentCheckingLauncherInterceptor.intercept(ClasspathAlignmentCheckingLauncherInterceptor.java:25)
    app//org.junit.platform.launcher.core.InterceptingLauncher.execute(InterceptingLauncher.java:56)
    app//org.junit.platform.launcher.core.DelegatingLauncher.execute(DelegatingLauncher.java:58)
    java.base@21.0.9/java.lang.invoke.LambdaForm$DMH/0x000002389d450000.invokeInterface(LambdaForm$DMH)
    java.base@21.0.9/java.lang.invoke.LambdaForm$MH/0x000002389d16a000.invoke(LambdaForm$MH)
    java.base@21.0.9/java.lang.invoke.Invokers$Holder.invokeExact_MT(Invokers$Holder)
    java.base@21.0.9/jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(DirectMethodHandleAccessor.java:154)
    java.base@21.0.9/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    java.base@21.0.9/java.lang.reflect.Method.invoke(Method.java:580)
    app//org.apache.maven.surefire.api.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:125)
    app//org.apache.maven.surefire.junitplatform.LauncherAdapter.executeWithCancellationToken(LauncherAdapter.java:68)
    app//org.apache.maven.surefire.junitplatform.LauncherAdapter.execute(LauncherAdapter.java:54)
    app//org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:203)
    app//org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:168)
    app//org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:136)
    app//org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
    app//org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
    app//org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
    app//org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
Thread Reference Handler: RUNNABLE
  Stack:
    java.base@21.0.9/java.lang.ref.Reference.waitForReferencePendingList(Native Method)
    java.base@21.0.9/java.lang.ref.Reference.processPendingReferences(Reference.java:246)
    java.base@21.0.9/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:208)
Thread Finalizer: WAITING
  Waiting on java.lang.ref.NativeReferenceQueue$Lock@1627c9b
  Stack:
    java.base@21.0.9/java.lang.Object.wait0(Native Method)
    java.base@21.0.9/java.lang.Object.wait(Object.java:366)
    java.base@21.0.9/java.lang.Object.wait(Object.java:339)
    java.base@21.0.9/java.lang.ref.NativeReferenceQueue.await(NativeReferenceQueue.java:48)
    java.base@21.0.9/java.lang.ref.ReferenceQueue.remove0(ReferenceQueue.java:158)
    java.base@21.0.9/java.lang.ref.NativeReferenceQueue.remove(NativeReferenceQueue.java:89)
    java.base@21.0.9/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:173)
Thread Signal Dispatcher: RUNNABLE
  Stack:
Thread Attach Listener: RUNNABLE
  Stack:
Thread Common-Cleaner: TIMED_WAITING
  Stack:
    java.base@21.0.9/jdk.internal.misc.Unsafe.park(Native Method)
    java.base@21.0.9/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:269)
    java.base@21.0.9/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1852)
    java.base@21.0.9/java.lang.ref.ReferenceQueue.await(ReferenceQueue.java:71)
    java.base@21.0.9/java.lang.ref.ReferenceQueue.remove0(ReferenceQueue.java:143)
    java.base@21.0.9/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:218)
    java.base@21.0.9/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:140)
    java.base@21.0.9/java.lang.Thread.runWith(Thread.java:1596)
    java.base@21.0.9/java.lang.Thread.run(Thread.java:1583)
    java.base@21.0.9/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:186)
Thread Notification Thread: RUNNABLE
  Stack:
Thread pool-1-thread-1: RUNNABLE
  Stack:
    java.base@21.0.9/sun.nio.ch.Iocp.getQueuedCompletionStatus(Native Method)
    java.base@21.0.9/sun.nio.ch.Iocp$EventHandlerTask.run(Iocp.java:323)
    java.base@21.0.9/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:113)
    java.base@21.0.9/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
    java.base@21.0.9/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
    java.base@21.0.9/java.lang.Thread.runWith(Thread.java:1596)
    java.base@21.0.9/java.lang.Thread.run(Thread.java:1583)
Thread pool-1-thread-2: RUNNABLE
  Stack:
    java.base@21.0.9/sun.nio.ch.Iocp.getQueuedCompletionStatus(Native Method)
    java.base@21.0.9/sun.nio.ch.Iocp$EventHandlerTask.run(Iocp.java:323)
    java.base@21.0.9/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:113)
    java.base@21.0.9/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
    java.base@21.0.9/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
    java.base@21.0.9/java.lang.Thread.runWith(Thread.java:1596)
    java.base@21.0.9/java.lang.Thread.run(Thread.java:1583)
Thread surefire-forkedjvm-stream-flusher: TIMED_WAITING
  Stack:
    java.base@21.0.9/jdk.internal.misc.Unsafe.park(Native Method)
    java.base@21.0.9/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:269)
    java.base@21.0.9/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1763)
    java.base@21.0.9/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
    java.base@21.0.9/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
    java.base@21.0.9/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
    java.base@21.0.9/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
    java.base@21.0.9/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
    java.base@21.0.9/java.lang.Thread.runWith(Thread.java:1596)
    java.base@21.0.9/java.lang.Thread.run(Thread.java:1583)
Thread surefire-forkedjvm-command-thread: WAITING
  Waiting on java.util.concurrent.CountDownLatch$Sync@73bca30a
```

**Comment by geoand** [comment]
That issue should be fixed by https://github.com/quarkusio/quarkus/pull/51313
