### ISSUE TITLE
Native Kafka SSL connection bug

### ISSUE THREAD

**Issue by Djela97** [quarkusio/quarkus#5254]
I think i covered everything in this question: https://stackoverflow.com/questions/58709700/is-kafka-ssl-connection-supported-in-native

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 

> Linux hp-450-g3 5.0.0-32-generic #34~18.04.2-Ubuntu SMP Thu Oct 10 10:36:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

 - Output of `java -version`: 

> openjdk version "11.0.4" 2019-07-16
> OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)
> OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode, sharing)

 - GraalVM version (if different from Java): 19.2.1
 - Quarkus version or git rev: 0.28.1

**Comment by gsmet** [comment]
```
Caused by: java.lang.NoSuchMethodException: org.apache.kafka.common.security.authenticator.SaslClientCallbackHandler.<init>
        at java.lang.Class.getConstructor0(DynamicHub.java:3082)
        at java.lang.Class.getDeclaredConstructor(DynamicHub.java:2178)
        at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:312)
```

Looks like we are missing a reflection registration. This should be an easy fix, the hardest part will be to verify it works.

**Comment by cescoffier** [comment]
Any hint to run a kafka broker with the same config?

**Comment by gsmet** [comment]
@irenakezic @anamarija maybe you could help on setting up a Kafka config that triggers the issue for us? I suppose you're familiar with that?

The fix should be easy once we have that.

**Comment by irenakezic** [comment]
@gsmet ok, we will take a look

**Comment by gaetancollaud** [comment]
I had this issue when using confluent cloud platform. Here is my config:

```
mp.messaging.outgoing.match-result.bootstrap.servers={{NODE}}.gcp.confluent.cloud:9092
mp.messaging.outgoing.match-result.ssl.endpoint.identification.algorithm=https
mp.messaging.outgoing.match-result.sasl.mechanism=PLAIN
mp.messaging.outgoing.match-result.request.timeout.ms=20000
mp.messaging.outgoing.match-result.retry.backoff.ms=500
mp.messaging.outgoing.match-result.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="{{KEY}}" password="{{PASSWORD}}";
mp.messaging.outgoing.match-result.security.protocol=SASL_SSL
```

When using the JVM mode it works. It's really just the native mode that fail with:

```
2019-11-17 10:33:27,899 ERROR [io.sma.rea.mes.imp.ConfiguredChannelFactory] (main) Unable to create the publisher or subscriber during initialization: org.apache.kafka.common.KafkaException: Failed to construct kafka producer
backend_1   | 	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:431)
backend_1   | 	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:271)
backend_1   | 	at io.vertx.kafka.client.producer.impl.KafkaWriteStreamImpl.create(KafkaWriteStreamImpl.java:52)
backend_1   | 	at io.vertx.kafka.client.producer.KafkaWriteStream.create(KafkaWriteStream.java:92)
backend_1   | 	at io.smallrye.reactive.messaging.kafka.KafkaSink.<init>(KafkaSink.java:50)
backend_1   | 	at io.smallrye.reactive.messaging.kafka.KafkaConnector.getSubscriberBuilder(KafkaConnector.java:73)
backend_1   | 	at io.smallrye.reactive.messaging.kafka.KafkaConnector_ClientProxy.getSubscriberBuilder(KafkaConnector_ClientProxy.zig:283)
backend_1   | 	at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.createSubscriberBuilder(ConfiguredChannelFactory.java:156)
backend_1   | 	at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.lambda$register$5(ConfiguredChannelFactory.java:124)
backend_1   | 	at java.util.HashMap.forEach(HashMap.java:1289)
backend_1   | 	at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.register(ConfiguredChannelFactory.java:124)
backend_1   | 	at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.initialize(ConfiguredChannelFactory.java:118)
backend_1   | 	at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory_ClientProxy.initialize(ConfiguredChannelFactory_ClientProxy.zig:195)
backend_1   | 	at java.util.Iterator.forEachRemaining(Iterator.java:116)
backend_1   | 	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
backend_1   | 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
backend_1   | 	at io.smallrye.reactive.messaging.extension.MediatorManager.initializeAndRun(MediatorManager.java:132)
backend_1   | 	at io.smallrye.reactive.messaging.extension.MediatorManager_ClientProxy.initializeAndRun(MediatorManager_ClientProxy.zig:100)
backend_1   | 	at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle.onApplicationStart(SmallRyeReactiveMessagingLifecycle.java:20)
backend_1   | 	at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle_Observer_onApplicationStart_4e8937813d9e8faff65c3c07f88fa96615b70e70.notify(SmallRyeReactiveMessagingLifecycle_Observer_onApplicationStart_4e8937813d9e8faff65c3c07f88fa96615b70e70.zig:51)
backend_1   | 	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:224)
backend_1   | 	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:65)
backend_1   | 	at io.quarkus.arc.runtime.LifecycleEventRunner.fireStartupEvent(LifecycleEventRunner.java:23)
backend_1   | 	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:108)
backend_1   | 	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent41.deploy_0(LifecycleEventsBuildStep$startupEvent41.zig:77)
backend_1   | 	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent41.deploy(LifecycleEventsBuildStep$startupEvent41.zig:36)
backend_1   | 	at io.quarkus.runner.ApplicationImpl1.doStart(ApplicationImpl1.zig:201)
backend_1   | 	at io.quarkus.runtime.Application.start(Application.java:94)
backend_1   | 	at io.quarkus.runtime.Application.run(Application.java:218)
backend_1   | 	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:41)
backend_1   | Caused by: org.apache.kafka.common.KafkaException: org.apache.kafka.common.KafkaException: Could not find a public no-argument constructor for org.apache.kafka.common.security.authenticator.SaslClientCallbackHandler
backend_1   | 	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:160)
backend_1   | 	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:146)
backend_1   | 	at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:67)
backend_1   | 	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:99)
backend_1   | 	at org.apache.kafka.clients.producer.KafkaProducer.newSender(KafkaProducer.java:439)
backend_1   | 	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:420)
backend_1   | 	... 29 more
backend_1   | Caused by: org.apache.kafka.common.KafkaException: Could not find a public no-argument constructor for org.apache.kafka.common.security.authenticator.SaslClientCallbackHandler
backend_1   | 	at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:314)
backend_1   | 	at org.apache.kafka.common.network.SaslChannelBuilder.createClientCallbackHandler(SaslChannelBuilder.java:289)
backend_1   | 	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:127)
backend_1   | 	... 34 more
backend_1   | Caused by: java.lang.NoSuchMethodException: org.apache.kafka.common.security.authenticator.SaslClientCallbackHandler.<init>
backend_1   | 	at java.lang.Class.getConstructor0(DynamicHub.java:3082)
backend_1   | 	at java.lang.Class.getDeclaredConstructor(DynamicHub.java:2178)
backend_1   | 	at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:312)
backend_1   | 	... 36 more
backend_1   | 
backend_1   | javax.enterprise.inject.spi.DeploymentException: org.apache.kafka.common.KafkaException: Failed to construct kafka producer
backend_1   | 	at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle.onApplicationStart(SmallRyeReactiveMessagingLifecycle.java:22)
backend_1   | 	at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle_Observer_onApplicationStart_4e8937813d9e8faff65c3c07f88fa96615b70e70.notify(SmallRyeReactiveMessagingLifecycle_Observer_onApplicationStart_4e8937813d9e8faff65c3c07f88fa96615b70e70.zig:51)
backend_1   | 	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:224)
backend_1   | 	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:65)
backend_1   | 	at io.quarkus.arc.runtime.LifecycleEventRunner.fireStartupEvent(LifecycleEventRunner.java:23)
backend_1   | 	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:108)
backend_1   | 	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent41.deploy_0(LifecycleEventsBuildStep$startupEvent41.zig:77)
backend_1   | 	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent41.deploy(LifecycleEventsBuildStep$startupEvent41.zig:36)
backend_1   | 	at io.quarkus.runner.ApplicationImpl1.doStart(ApplicationImpl1.zig:201)
backend_1   | 	at io.quarkus.runtime.Application.start(Application.java:94)
backend_1   | 	at io.quarkus.runtime.Application.run(Application.java:218)
backend_1   | 	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:41)
backend_1   | Caused by: org.apache.kafka.common.KafkaException: Failed to construct kafka producer
backend_1   | 	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:431)
backend_1   | 	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:271)
backend_1   | 	at io.vertx.kafka.client.producer.impl.KafkaWriteStreamImpl.create(KafkaWriteStreamImpl.java:52)
backend_1   | 	at io.vertx.kafka.client.producer.KafkaWriteStream.create(KafkaWriteStream.java:92)
backend_1   | 	at io.smallrye.reactive.messaging.kafka.KafkaSink.<init>(KafkaSink.java:50)
backend_1   | 	at io.smallrye.reactive.messaging.kafka.KafkaConnector.getSubscriberBuilder(KafkaConnector.java:73)
backend_1   | 	at io.smallrye.reactive.messaging.kafka.KafkaConnector_ClientProxy.getSubscriberBuilder(KafkaConnector_ClientProxy.zig:283)
backend_1   | 	at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.createSubscriberBuilder(ConfiguredChannelFactory.java:156)
backend_1   | 	at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.lambda$register$5(ConfiguredChannelFactory.java:124)
backend_1   | 	at java.util.HashMap.forEach(HashMap.java:1289)
backend_1   | 	at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.register(ConfiguredChannelFactory.java:124)
backend_1   | 	at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.initialize(ConfiguredChannelFactory.java:118)
backend_1   | 	at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory_ClientProxy.initialize(ConfiguredChannelFactory_ClientProxy.zig:195)
backend_1   | 	at java.util.Iterator.forEachRemaining(Iterator.java:116)
backend_1   | 	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
backend_1   | 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
backend_1   | 	at io.smallrye.reactive.messaging.extension.MediatorManager.initializeAndRun(MediatorManager.java:132)
backend_1   | 	at io.smallrye.reactive.messaging.extension.MediatorManager_ClientProxy.initializeAndRun(MediatorManager_ClientProxy.zig:100)
backend_1   | 	at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle.onApplicationStart(SmallRyeReactiveMessagingLifecycle.java:20)
backend_1   | 	... 11 more
backend_1   | Caused by: org.apache.kafka.common.KafkaException: org.apache.kafka.common.KafkaException: Could not find a public no-argument constructor for org.apache.kafka.common.security.authenticator.SaslClientCallbackHandler
backend_1   | 	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:160)
backend_1   | 	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:146)
backend_1   | 	at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:67)
backend_1   | 	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:99)
backend_1   | 	at org.apache.kafka.clients.producer.KafkaProducer.newSender(KafkaProducer.java:439)
backend_1   | 	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:420)
backend_1   | 	... 29 more
backend_1   | Caused by: org.apache.kafka.common.KafkaException: Could not find a public no-argument constructor for org.apache.kafka.common.security.authenticator.SaslClientCallbackHandler
backend_1   | 	at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:314)
backend_1   | 	at org.apache.kafka.common.network.SaslChannelBuilder.createClientCallbackHandler(SaslChannelBuilder.java:289)
backend_1   | 	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:127)
backend_1   | 	... 34 more
backend_1   | Caused by: java.lang.NoSuchMethodException: org.apache.kafka.common.security.authenticator.SaslClientCallbackHandler.<init>
backend_1   | 	at java.lang.Class.getConstructor0(DynamicHub.java:3082)
backend_1   | 	at java.lang.Class.getDeclaredConstructor(DynamicHub.java:2178)
backend_1   | 	at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:312)
backend_1   | 	... 36 more
backend_1   | 2019-11-17 10:33:27,976 INFO  [io.sma.rea.mes.ext.MediatorManager] (main) Cancel subscriptions
backend_1   | Exception in thread "main" java.lang.RuntimeException: Failed to start quarkus
backend_1   | 	at io.quarkus.runner.ApplicationImpl1.doStart(ApplicationImpl1.zig:225)
backend_1   | 	at io.quarkus.runtime.Application.start(Application.java:94)
backend_1   | 	at io.quarkus.runtime.Application.run(Application.java:218)
backend_1   | 	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:41)
backend_1   | Caused by: javax.enterprise.inject.spi.DeploymentException: org.apache.kafka.common.KafkaException: Failed to construct kafka producer
backend_1   | 	at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle.onApplicationStart(SmallRyeReactiveMessagingLifecycle.java:22)
backend_1   | 	at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle_Observer_onApplicationStart_4e8937813d9e8faff65c3c07f88fa96615b70e70.notify(SmallRyeReactiveMessagingLifecycle_Observer_onApplicationStart_4e8937813d9e8faff65c3c07f88fa96615b70e70.zig:51)
backend_1   | 	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:224)
backend_1   | 	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:65)
backend_1   | 	at io.quarkus.arc.runtime.LifecycleEventRunner.fireStartupEvent(LifecycleEventRunner.java:23)
backend_1   | 	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:108)
backend_1   | 	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent41.deploy_0(LifecycleEventsBuildStep$startupEvent41.zig:77)
backend_1   | 	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent41.deploy(LifecycleEventsBuildStep$startupEvent41.zig:36)
backend_1   | 	at io.quarkus.runner.ApplicationImpl1.doStart(ApplicationImpl1.zig:201)
backend_1   | 	... 3 more
backend_1   | Caused by: org.apache.kafka.common.KafkaException: Failed to construct kafka producer
backend_1   | 	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:431)
backend_1   | 	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:271)
backend_1   | 	at io.vertx.kafka.client.producer.impl.KafkaWriteStreamImpl.create(KafkaWriteStreamImpl.java:52)
backend_1   | 	at io.vertx.kafka.client.producer.KafkaWriteStream.create(KafkaWriteStream.java:92)
backend_1   | 	at io.smallrye.reactive.messaging.kafka.KafkaSink.<init>(KafkaSink.java:50)
backend_1   | 	at io.smallrye.reactive.messaging.kafka.KafkaConnector.getSubscriberBuilder(KafkaConnector.java:73)
backend_1   | 	at io.smallrye.reactive.messaging.kafka.KafkaConnector_ClientProxy.getSubscriberBuilder(KafkaConnector_ClientProxy.zig:283)
backend_1   | 	at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.createSubscriberBuilder(ConfiguredChannelFactory.java:156)
backend_1   | 	at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.lambda$register$5(ConfiguredChannelFactory.java:124)
backend_1   | 	at java.util.HashMap.forEach(HashMap.java:1289)
backend_1   | 	at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.register(ConfiguredChannelFactory.java:124)
backend_1   | 	at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.initialize(ConfiguredChannelFactory.java:118)
backend_1   | 	at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory_ClientProxy.initialize(ConfiguredChannelFactory_ClientProxy.zig:195)
backend_1   | 	at java.util.Iterator.forEachRemaining(Iterator.java:116)
backend_1   | 	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
backend_1   | 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
backend_1   | 	at io.smallrye.reactive.messaging.extension.MediatorManager.initializeAndRun(MediatorManager.java:132)
backend_1   | 	at io.smallrye.reactive.messaging.extension.MediatorManager_ClientProxy.initializeAndRun(MediatorManager_ClientProxy.zig:100)
backend_1   | 	at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle.onApplicationStart(SmallRyeReactiveMessagingLifecycle.java:20)
backend_1   | 	... 11 more
backend_1   | Caused by: org.apache.kafka.common.KafkaException: org.apache.kafka.common.KafkaException: Could not find a public no-argument constructor for org.apache.kafka.common.security.authenticator.SaslClientCallbackHandler
backend_1   | 	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:160)
backend_1   | 	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:146)
backend_1   | 	at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:67)
backend_1   | 	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:99)
backend_1   | 	at org.apache.kafka.clients.producer.KafkaProducer.newSender(KafkaProducer.java:439)
backend_1   | 	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:420)
backend_1   | 	... 29 more
backend_1   | Caused by: org.apache.kafka.common.KafkaException: Could not find a public no-argument constructor for org.apache.kafka.common.security.authenticator.SaslClientCallbackHandler
backend_1   | 	at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:314)
backend_1   | 	at org.apache.kafka.common.network.SaslChannelBuilder.createClientCallbackHandler(SaslChannelBuilder.java:289)
backend_1   | 	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:127)
backend_1   | 	... 34 more
backend_1   | Caused by: java.lang.NoSuchMethodException: org.apache.kafka.common.security.authenticator.SaslClientCallbackHandler.<init>
backend_1   | 	at java.lang.Class.getConstructor0(DynamicHub.java:3082)
backend_1   | 	at java.lang.Class.getDeclaredConstructor(DynamicHub.java:2178)
backend_1   | 	at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:312)
backend_1   | 	... 36 more
```

**Comment by anamarija** [comment]
Hi, has anybody solved the issue already or can I make a fix?

**Comment by gsmet** [comment]
It's not solved. I think it's really just about adding a couple of reflection registrations.

The question being: how much will it add to the native image to do it by default. We should really do a comparison of the native image size on a sample project with and without the registrations.

A sample project can be found here: https://github.com/quarkusio/quarkus-quickstarts/tree/master/kafka-quickstart .

**Comment by anamarija** [comment]
Hi,
I tried to reproduce the behaviour with a one node broker/replica setup on my local machine. I used various options PLAINTEXT, SSL, SASL_SSL they all seem to work fine on my machine in dev and native. The only problem I did came across was that profile %prod isn't working with reactive messaging and native but thats another issue. Below is the configuration I used. I tried also required and none client authentification .

```
quarkus.ssl.native=true
quarkus.native.enable-all-security-services=true

mp.messaging.outgoing.generated-price.connector=smallrye-kafka
mp.messaging.outgoing.generated-price.ssl.truststore.location=/usr/local/etc/kafka/certs/docker.kafka.server.truststore.jks
mp.messaging.outgoing.generated-price.ssl.truststore.password=kafkadocker
mp.messaging.outgoing.generated-price.ssl.endpoint.identification.algorithm=https
mp.messaging.outgoing.generated-price.sasl.mechanism=PLAIN
mp.messaging.outgoing.generated-price.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret";
mp.messaging.outgoing.generated-price.security.protocol=SASL_SSL
mp.messaging.outgoing.generated-price.topic=prices
mp.messaging.outgoing.generated-price.value.serializer=org.apache.kafka.common.serialization.IntegerSerializer
#
## Configure the Kafka source (we read from it)
mp.messaging.incoming.prices.connector=smallrye-kafka
mp.messaging.incoming.prices.ssl.truststore.location=/usr/local/etc/kafka/certs/docker.kafka.server.truststore.jks
mp.messaging.incoming.prices.ssl.truststore.password=kafkadocker
mp.messaging.incoming.prices.ssl.endpoint.identification.algorithm=https
mp.messaging.incoming.prices.sasl.mechanism=PLAIN
mp.messaging.incoming.prices.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret";
mp.messaging.incoming.prices.security.protocol=SASL_SSL
mp.messaging.incoming.prices.topic=prices
mp.messaging.incoming.prices.value.deserializer=org.apache.kafka.common.serialization.IntegerDeserializer
```

Could you share some additional information from your kafka broker environment.

**Comment by gaetancollaud** [comment]
Hello @anamarija 

I tried again with
```
quarkus.ssl.native=true
quarkus.native.enable-all-security-services=true
```
but same result. This was the only difference with my initial config.

I use confluent cloud. You can create a cluster at https://confluent.cloud/. You have to enter a credit card, but it's cheap ( $0.22 / Gb).

**Comment by cescoffier** [comment]
OH here is how I can reproduce it. Let me know, which that info I should be able to troubleshoot that issue.

**Comment by anamarija** [comment]
Can you export your broker configuration from confluent cloud. Or give me temporal access to it so I can troubleshoot.

**Comment by gaetancollaud** [comment]
@cescoffier @anamarija Please contact me at gaetan.collaud (at) spoud.io so I can give you access to my confluent cloud cluster.

**Comment by anamarija** [comment]
Well I tried to reproduce the error with your confluent node. Everything seems to be working fine on my setup. I provided a sample app for you https://github.com/anamarija/quarkus-kafka-5254-ssl-sasl.git. Which version of quarkus are you using?

**Comment by gaetancollaud** [comment]
I tried your fork and set the version to `1.0.0.CR1`. I still have the error. => https://github.com/gaetancollaud/quarkus-kafka-5254-ssl-sasl/blob/master/pom.xml#L10.

I'm trying to compile the master branch from quarkus to use the latest snapshot but no luck so far (dependency issues).

**Comment by gsmet** [comment]
@gaetancollaud could you explain step by step what you do to reproduce the issue?

How you build the application and run it?

There might be something weird going on. Thanks!

**Comment by gaetancollaud** [comment]
Ok, so first checkout my fork: https://github.com/gaetancollaud/quarkus-kafka-5254-ssl-sasl

You can change the version from `1.0.0.CR1` to `999-SNAPSHOT` I just tried I have the same outcome.

create a file `quarkus-properties.properties` with this content (just adapt the variables)
```
mp.messaging.outgoing.match-result.bootstrap.servers=${BOOTSTRAP_SERVER}
mp.messaging.outgoing.match-result.ssl.endpoint.identification.algorithm=https
mp.messaging.outgoing.match-result.sasl.mechanism=PLAIN
mp.messaging.outgoing.match-result.request.timeout.ms=20000
mp.messaging.outgoing.match-result.retry.backoff.ms=500
mp.messaging.outgoing.match-result.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="${KEY}" password="${PASSWORD}";
mp.messaging.outgoing.match-result.security.protocol=SASL_SSL
mp.messaging.outgoing.match-result.topic=${TOPIC}
mp.messaging.outgoing.match-result.connector=smallrye-kafka
```

compile using maven (I'm on Windows 10 using maven 3.6.0 with java 1.8.0_191 from Oracle):
```
 ./mvnw clean package -Pnative -Dquarkus.native.container-build=true
```

Then build and run using docker-compose:
```
docker-compose build quarkus
docker-compose up quarkus
```

You should see this error:
```
quarkus_1    | 2019-11-20 14:09:37,850 ERROR [io.sma.rea.mes.imp.ConfiguredChannelFactory] (main) Unable to create the publisher or subscriber during initialization: org.apache.kafka.common.KafkaException: Failed to construct kafka producer
quarkus_1    |  at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:431)
quarkus_1    |  at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:271)
quarkus_1    |  at io.vertx.kafka.client.producer.impl.KafkaWriteStreamImpl.create(KafkaWriteStreamImpl.java:52)
quarkus_1    |  at io.vertx.kafka.client.producer.KafkaWriteStream.create(KafkaWriteStream.java:92)
quarkus_1    |  at io.smallrye.reactive.messaging.kafka.KafkaSink.<init>(KafkaSink.java:50)
quarkus_1    |  at io.smallrye.reactive.messaging.kafka.KafkaConnector.getSubscriberBuilder(KafkaConnector.java:73)
quarkus_1    |  at io.smallrye.reactive.messaging.kafka.KafkaConnector_ClientProxy.getSubscriberBuilder(KafkaConnector_ClientProxy.zig:283)
quarkus_1    |  at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.createSubscriberBuilder(ConfiguredChannelFactory.java:156)
quarkus_1    |  at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.lambda$register$5(ConfiguredChannelFactory.java:124)
quarkus_1    |  at java.util.HashMap.forEach(HashMap.java:1289)
quarkus_1    |  at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.register(ConfiguredChannelFactory.java:124)
quarkus_1    |  at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.initialize(ConfiguredChannelFactory.java:118)
quarkus_1    |  at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory_ClientProxy.initialize(ConfiguredChannelFactory_ClientProxy.zig:195)
quarkus_1    |  at java.util.Iterator.forEachRemaining(Iterator.java:116)
quarkus_1    |  at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
quarkus_1    |  at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
quarkus_1    |  at io.smallrye.reactive.messaging.extension.MediatorManager.initializeAndRun(MediatorManager.java:132)
quarkus_1    |  at io.smallrye.reactive.messaging.extension.MediatorManager_ClientProxy.initializeAndRun(MediatorManager_ClientProxy.zig:100)
quarkus_1    |  at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle.onApplicationStart(SmallRyeReactiveMessagingLifecycle.java:20)
quarkus_1    |  at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle_Observer_onApplicationStart_4e8937813d9e8faff65c3c07f88fa96615b70e70.notify(SmallRyeReactiveMessagingLifecycle_Observer_onApplicationStart_4e8937813d9e8faff65c3c07f88fa96615b70e70.zig:51)
quarkus_1    |  at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:224)
quarkus_1    |  at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:65)
quarkus_1    |  at io.quarkus.arc.runtime.LifecycleEventRunner.fireStartupEvent(LifecycleEventRunner.java:23)
quarkus_1    |  at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:108)
quarkus_1    |  at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent56.deploy_0(LifecycleEventsBuildStep$startupEvent56.zig:77)
quarkus_1    |  at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent56.deploy(LifecycleEventsBuildStep$startupEvent56.zig:36)
quarkus_1    |  at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:161)
quarkus_1    |  at io.quarkus.runtime.Application.start(Application.java:94)
quarkus_1    |  at io.quarkus.runtime.Application.run(Application.java:218)
quarkus_1    |  at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:41)
quarkus_1    | Caused by: org.apache.kafka.common.KafkaException: org.apache.kafka.common.KafkaException: Could not find a public no-argument constructor for org.apache.kafka.common.security.authenticator.SaslClientCallbackHandler
quarkus_1    |  at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:160)
quarkus_1    |  at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:146)
quarkus_1    |  at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:67)
quarkus_1    |  at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:99)
quarkus_1    |  at org.apache.kafka.clients.producer.KafkaProducer.newSender(KafkaProducer.java:439)
quarkus_1    |  at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:420)
quarkus_1    |  ... 29 more
quarkus_1    | Caused by: org.apache.kafka.common.KafkaException: Could not find a public no-argument constructor for org.apache.kafka.common.security.authenticator.SaslClientCallbackHandler
quarkus_1    |  at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:314)
quarkus_1    |  at org.apache.kafka.common.network.SaslChannelBuilder.createClientCallbackHandler(SaslChannelBuilder.java:289)
quarkus_1    |  at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:127)
quarkus_1    |  ... 34 more
quarkus_1    | Caused by: java.lang.NoSuchMethodException: org.apache.kafka.common.security.authenticator.SaslClientCallbackHandler.<init>
quarkus_1    |  at java.lang.Class.getConstructor0(DynamicHub.java:3082)
quarkus_1    |  at java.lang.Class.getDeclaredConstructor(DynamicHub.java:2178)
quarkus_1    |  at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:312)
quarkus_1    |  ... 36 more
quarkus_1    |
quarkus_1    | javax.enterprise.inject.spi.DeploymentException: org.apache.kafka.common.KafkaException: Failed to construct kafka producer
quarkus_1    |  at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle.onApplicationStart(SmallRyeReactiveMessagingLifecycle.java:22)
quarkus_1    |  at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle_Observer_onApplicationStart_4e8937813d9e8faff65c3c07f88fa96615b70e70.notify(SmallRyeReactiveMessagingLifecycle_Observer_onApplicationStart_4e8937813d9e8faff65c3c07f88fa96615b70e70.zig:51)
quarkus_1    |  at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:224)
quarkus_1    |  at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:65)
quarkus_1    |  at io.quarkus.arc.runtime.LifecycleEventRunner.fireStartupEvent(LifecycleEventRunner.java:23)
quarkus_1    |  at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:108)
quarkus_1    |  at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent56.deploy_0(LifecycleEventsBuildStep$startupEvent56.zig:77)
quarkus_1    |  at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent56.deploy(LifecycleEventsBuildStep$startupEvent56.zig:36)
quarkus_1    |  at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:161)
quarkus_1    |  at io.quarkus.runtime.Application.start(Application.java:94)
quarkus_1    |  at io.quarkus.runtime.Application.run(Application.java:218)
quarkus_1    |  at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:41)
quarkus_1    | Caused by: org.apache.kafka.common.KafkaException: Failed to construct kafka producer
quarkus_1    |  at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:431)
quarkus_1    |  at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:271)
quarkus_1    |  at io.vertx.kafka.client.producer.impl.KafkaWriteStreamImpl.create(KafkaWriteStreamImpl.java:52)
quarkus_1    |  at io.vertx.kafka.client.producer.KafkaWriteStream.create(KafkaWriteStream.java:92)
quarkus_1    |  at io.smallrye.reactive.messaging.kafka.KafkaSink.<init>(KafkaSink.java:50)
quarkus_1    |  at io.smallrye.reactive.messaging.kafka.KafkaConnector.getSubscriberBuilder(KafkaConnector.java:73)
quarkus_1    |  at io.smallrye.reactive.messaging.kafka.KafkaConnector_ClientProxy.getSubscriberBuilder(KafkaConnector_ClientProxy.zig:283)
quarkus_1    |  at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.createSubscriberBuilder(ConfiguredChannelFactory.java:156)
quarkus_1    |  at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.lambda$register$5(ConfiguredChannelFactory.java:124)
quarkus_1    |  at java.util.HashMap.forEach(HashMap.java:1289)
quarkus_1    |  at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.register(ConfiguredChannelFactory.java:124)
quarkus_1    |  at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.initialize(ConfiguredChannelFactory.java:118)
quarkus_1    |  at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory_ClientProxy.initialize(ConfiguredChannelFactory_ClientProxy.zig:195)
quarkus_1    |  at java.util.Iterator.forEachRemaining(Iterator.java:116)
quarkus_1    |  at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
quarkus_1    |  at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
quarkus_1    |  at io.smallrye.reactive.messaging.extension.MediatorManager.initializeAndRun(MediatorManager.java:132)
quarkus_1    |  at io.smallrye.reactive.messaging.extension.MediatorManager_ClientProxy.initializeAndRun(MediatorManager_ClientProxy.zig:100)
quarkus_1    |  at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle.onApplicationStart(SmallRyeReactiveMessagingLifecycle.java:20)
quarkus_1    |  ... 11 more
quarkus_1    | Caused by: org.apache.kafka.common.KafkaException: org.apache.kafka.common.KafkaException: Could not find a public no-argument constructor for org.apache.kafka.common.security.authenticator.SaslClientCallbackHandler
quarkus_1    |  at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:160)
quarkus_1    |  at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:146)
quarkus_1    |  at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:67)
quarkus_1    |  at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:99)
quarkus_1    |  at org.apache.kafka.clients.producer.KafkaProducer.newSender(KafkaProducer.java:439)
quarkus_1    |  at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:420)
quarkus_1    |  ... 29 more
quarkus_1    | Caused by: org.apache.kafka.common.KafkaException: Could not find a public no-argument constructor for org.apache.kafka.common.security.authenticator.SaslClientCallbackHandler
quarkus_1    |  at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:314)
quarkus_1    |  at org.apache.kafka.common.network.SaslChannelBuilder.createClientCallbackHandler(SaslChannelBuilder.java:289)
quarkus_1    |  at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:127)
quarkus_1    |  ... 34 more
quarkus_1    | Caused by: java.lang.NoSuchMethodException: org.apache.kafka.common.security.authenticator.SaslClientCallbackHandler.<init>
quarkus_1    |  at java.lang.Class.getConstructor0(DynamicHub.java:3082)
quarkus_1    |  at java.lang.Class.getDeclaredConstructor(DynamicHub.java:2178)
quarkus_1    |  at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:312)
quarkus_1    |  ... 36 more
quarkus_1    | Exception in thread "main" java.lang.RuntimeException: Failed to start quarkus
quarkus_1    |  at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:185)
quarkus_1    |  at io.quarkus.runtime.Application.start(Application.java:94)
quarkus_1    |  at io.quarkus.runtime.Application.run(Application.java:218)
quarkus_1    |  at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:41)
quarkus_1    | Caused by: javax.enterprise.inject.spi.DeploymentException: org.apache.kafka.common.KafkaException: Failed to construct kafka producer
quarkus_1    |  at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle.onApplicationStart(SmallRyeReactiveMessagingLifecycle.java:22)
quarkus_1    |  at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle_Observer_onApplicationStart_4e8937813d9e8faff65c3c07f88fa96615b70e70.notify(SmallRyeReactiveMessagingLifecycle_Observer_onApplicationStart_4e8937813d9e8faff65c3c07f88fa96615b70e70.zig:51)
quarkus_1    | 2019-11-20 14:09:37,855 INFO  [io.sma.rea.mes.ext.MediatorManager] (main) Cancel subscriptions
quarkus_1    |  at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:224)
quarkus_1    |  at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:65)
quarkus_1    |  at io.quarkus.arc.runtime.LifecycleEventRunner.fireStartupEvent(LifecycleEventRunner.java:23)
quarkus_1    |  at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:108)
quarkus_1    |  at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent56.deploy_0(LifecycleEventsBuildStep$startupEvent56.zig:77)
quarkus_1    |  at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent56.deploy(LifecycleEventsBuildStep$startupEvent56.zig:36)
quarkus_1    |  at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:161)
quarkus_1    |  ... 3 more
quarkus_1    | Caused by: org.apache.kafka.common.KafkaException: Failed to construct kafka producer
quarkus_1    |  at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:431)
quarkus_1    |  at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:271)
quarkus_1    |  at io.vertx.kafka.client.producer.impl.KafkaWriteStreamImpl.create(KafkaWriteStreamImpl.java:52)
quarkus_1    |  at io.vertx.kafka.client.producer.KafkaWriteStream.create(KafkaWriteStream.java:92)
quarkus_1    |  at io.smallrye.reactive.messaging.kafka.KafkaSink.<init>(KafkaSink.java:50)
quarkus_1    |  at io.smallrye.reactive.messaging.kafka.KafkaConnector.getSubscriberBuilder(KafkaConnector.java:73)
quarkus_1    |  at io.smallrye.reactive.messaging.kafka.KafkaConnector_ClientProxy.getSubscriberBuilder(KafkaConnector_ClientProxy.zig:283)
quarkus_1    |  at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.createSubscriberBuilder(ConfiguredChannelFactory.java:156)
quarkus_1    |  at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.lambda$register$5(ConfiguredChannelFactory.java:124)
quarkus_1    |  at java.util.HashMap.forEach(HashMap.java:1289)
quarkus_1    |  at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.register(ConfiguredChannelFactory.java:124)
quarkus_1    |  at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory.initialize(ConfiguredChannelFactory.java:118)
quarkus_1    |  at io.smallrye.reactive.messaging.impl.ConfiguredChannelFactory_ClientProxy.initialize(ConfiguredChannelFactory_ClientProxy.zig:195)
quarkus_1    |  at java.util.Iterator.forEachRemaining(Iterator.java:116)
quarkus_1    |  at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
quarkus_1    |  at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
quarkus_1    |  at io.smallrye.reactive.messaging.extension.MediatorManager.initializeAndRun(MediatorManager.java:132)
quarkus_1    |  at io.smallrye.reactive.messaging.extension.MediatorManager_ClientProxy.initializeAndRun(MediatorManager_ClientProxy.zig:100)
quarkus_1    |  at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle.onApplicationStart(SmallRyeReactiveMessagingLifecycle.java:20)
quarkus_1    |  ... 11 more
quarkus_1    | Caused by: org.apache.kafka.common.KafkaException: org.apache.kafka.common.KafkaException: Could not find a public no-argument constructor for org.apache.kafka.common.security.authenticator.SaslClientCallbackHandler
quarkus_1    |  at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:160)
quarkus_1    |  at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:146)
quarkus_1    |  at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:67)
quarkus_1    |  at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:99)
quarkus_1    |  at org.apache.kafka.clients.producer.KafkaProducer.newSender(KafkaProducer.java:439)
quarkus_1    |  at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:420)
quarkus_1    |  ... 29 more
quarkus_1    | Caused by: org.apache.kafka.common.KafkaException: Could not find a public no-argument constructor for org.apache.kafka.common.security.authenticator.SaslClientCallbackHandler
quarkus_1    |  at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:314)
quarkus_1    |  at org.apache.kafka.common.network.SaslChannelBuilder.createClientCallbackHandler(SaslChannelBuilder.java:289)
quarkus_1    |  at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:127)
quarkus_1    |  ... 34 more
quarkus_1    | Caused by: java.lang.NoSuchMethodException: org.apache.kafka.common.security.authenticator.SaslClientCallbackHandler.<init>
quarkus_1    |  at java.lang.Class.getConstructor0(DynamicHub.java:3082)
quarkus_1    |  at java.lang.Class.getDeclaredConstructor(DynamicHub.java:2178)
quarkus_1    |  at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:312)
quarkus_1    |  ... 36 more
quarkus-kafka-5254-ssl-sasl_quarkus_1 exited with code 1
```

Am I doing something wrong ?

**Comment by anamarija** [comment]
I managed to reproduce it...yeeey! So this only happens when the application is run as a docker-native image. When its run as a java native runner everything works. 
Do you want me to investigate further why this happens or should I fix it and enable the reflection through some property.

**Comment by gsmet** [comment]
This is really weird.

The main difference between Docker builds and standard builds is this: https://quarkus.io/guides/native-and-ssl#working-with-containers .

I'm wondering if properly including SSL in the container would fix the issue.

I don't really see how just adding reflection could work. Or maybe... the Kafka client is trying to initialize some SSL support and it can't due to the SunEC library missing and then it defaults to another implementation and that's when we need the additional reflection.

**Comment by anamarija** [comment]
I think the SSL handshake was completed. This is a problem with the SASL login which is done after  . I tried to add the extra reflections which were needed 
´´´
reflectiveClass.produce(new ReflectiveClassBuildItem(false, false, SaslClientCallbackHandler.class, DefaultLogin.class, DefaultLoginCallbackHandler.class));
´´´

but it now fails 

´´´
Caused by: java.util.MissingResourceException: Resource bundle not found sun.security.util.Resources. Register the resource bundle using the option -H:IncludeResourceBundles=sun.security.util.Resources.
	at com.oracle.svm.core.jdk.LocalizationSupport.getCached(LocalizationSupport.java:103)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:49)
	at sun.security.util.ResourcesMgr$1.run(ResourcesMgr.java:47)
	at sun.security.util.ResourcesMgr$1.run(ResourcesMgr.java:44)
	at java.security.AccessController.doPrivileged(AccessController.java:69)
	at sun.security.util.ResourcesMgr.getString(ResourcesMgr.java:43)
	at javax.security.auth.login.LoginContext.invoke(LoginContext.java:793)
	at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195)
	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682)
	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680)
	at java.security.AccessController.doPrivileged(AccessController.java:104)
	at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680)
	at javax.security.auth.login.LoginContext.login(LoginContext.java:587)
	at org.apache.kafka.common.security.authenticator.AbstractLogin.login(AbstractLogin.java:60)
	at org.apache.kafka.common.security.authenticator.LoginManager.<init>(LoginManager.java:61)
	at org.apache.kafka.common.security.authenticator.LoginManager.acquireLoginManager(LoginManager.java:104)
	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:149)
	... 34 more
´´´
Something is missing in the graalvm native image builder. This will take some extra investigating on what is missing.

**Comment by cescoffier** [comment]
@anamarija 

Looking at https://github.com/frohoff/jdk8u-dev-jdk/blob/master/src/share/classes/javax/security/auth/login/LoginContext.java#L711.

The stack you have is because it got a NoClassDefFoundError` because it cannot load the _module_ (class). Thus,  it tried to internationalize the message and fails because the i18n file (Resource) is not available.

We would need to know which module it is trying to load.

**Comment by anamarija** [comment]
Well looking at https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/common/network/SaslChannelBuilder.java#L147
the login module is resolved from the provided configuration  
```
mp.messaging.outgoing.match-result.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="${user}" password="${password}";
```

**Comment by cescoffier** [comment]
Did you try adding `org.apache.kafka.common.security.plain.PlainLoginModule` in the reflection list ?

**Comment by irenakezic** [comment]
After adding a few classes in the reflection list as suggested above the problem remains. It seems to me that this native method could be problematic java.security.AccessController.getStackAccessControlContext() as it seems that password is missing in context when running a native image. Any suggestions on how to debug this further?

**Comment by irenakezic** [comment]
My last comment was not clear enough so I would like to add the following:
1. I reproduce the issue when running a native image in a container or on my localhost so it does not seem to be docker image related.
2. I used GraalVM 19.2.1 
3. This is the error I get after updating the reflections with the classes above:
> Caused by: org.apache.kafka.common.errors.SaslAuthenticationException: Failed to configure SaslClientAuthenticator
> Caused by: javax.security.sasl.SaslException: Cannot get userid/password [Caused by javax.security.auth.callback.UnsupportedCallbackException: Could not login: the client is being asked for a password, but the Kafka client code does not currently support obtaining a password from the user.]
> 	at com.sun.security.sasl.ClientFactoryImpl.getUserInfo(ClientFactoryImpl.java:157)
> 	at com.sun.security.sasl.ClientFactoryImpl.createSaslClient(ClientFactoryImpl.java:94)
> 	at javax.security.sasl.Sasl.createSaslClient(Sasl.java:384)
> 	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.lambda$createSaslClient$0(SaslClientAuthenticator.java:180)
> 	at java.security.AccessController.doPrivileged(AccessController.java:104)
> 	at javax.security.auth.Subject.doAs(Subject.java:422)
> 	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.createSaslClient(SaslClientAuthenticator.java:176)
> 	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.<init>(SaslClientAuthenticator.java:168)
> 	at org.apache.kafka.common.network.SaslChannelBuilder.buildClientAuthenticator(SaslChannelBuilder.java:254)
> 	at org.apache.kafka.common.network.SaslChannelBuilder.lambda$buildChannel$1(SaslChannelBuilder.java:202)
> 	at org.apache.kafka.common.network.KafkaChannel.<init>(KafkaChannel.java:140)
> 	at org.apache.kafka.common.network.SaslChannelBuilder.buildChannel(SaslChannelBuilder.java:210)
> 	at org.apache.kafka.common.network.Selector.buildAndAttachKafkaChannel(Selector.java:336)
> 	at org.apache.kafka.common.network.Selector.registerChannel(Selector.java:327)
> 	at org.apache.kafka.common.network.Selector.connect(Selector.java:259)
> 	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:922)
> 	at org.apache.kafka.clients.NetworkClient.access$700(NetworkClient.java:67)
> 	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1092)
> 	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:983)
> 	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:533)
> 	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:312)
> 	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:235)
> 	at java.lang.Thread.run(Thread.java:748)
> 	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:460)
> 	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)

**Comment by alfsch** [comment]
Hello together, any progress in this topic? BR, Alfred

**Comment by cescoffier** [comment]
Related to #8168. 

SASL itself is working, the issue is Jaas

**Comment by cescoffier** [comment]
Fixed by https://github.com/quarkusio/quarkus/issues/8168.

**Comment by sedaition** [comment]
Beginning in 1.5.0 I have this issue for all my kafka related apps. Any version prior to that works fine. Are we sure this issue is resolved and that there were no backwards breaking config changes? Stack trace:
`Caused by: io.quarkus.builder.BuildException: 
Build failure: Build failed due to errors
        [error]: Build step io.quarkus.kafka.client.deployment.KafkaProcessor#withSasl threw an exception: java.lang.NoClassDefFoundError: org/apache/kafka/common/security/authenticator/AbstractLogin$DefaultLoginCallbackHandler
        at io.quarkus.kafka.client.deployment.KafkaProcessor.withSasl(KafkaProcessor.java:140)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:932)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at java.base/java.lang.Thread.run(Thread.java:830)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Caused by: java.lang.ClassNotFoundException: org.apache.kafka.common.security.authenticator.AbstractLogin$DefaultLoginCallbackHandler
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:371)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:323)
        ... 13 more

Caused by: java.lang.NoClassDefFoundError: org/apache/kafka/common/security/authenticator/AbstractLogin$DefaultLoginCallbackHandler
Caused by: java.lang.ClassNotFoundException: org.apache.kafka.common.security.authenticator.AbstractLogin$DefaultLoginCallbackHandler
`

**Comment by sedaition** [comment]
@cescoffier
