### ISSUE TITLE
Reactive Message Error Receiving Message

### ISSUE THREAD

**Issue by garrettahines1** [quarkusio/quarkus#5449]
**Describe the bug**
I'm on Quarkus 0.28.1. I am using smallrye-amqp to listen to messages over artemis mq. From a node js service I am sending a text message using the STOMP protocol. Get the following error when receiving the message in my quarkus application. 

```
ERROR [com.ServiceRequestResultListener#receiveRequest] [{}] (vert.x-eventloop-thread-0) The method com.ServiceRequestResultListener#receiveRequest has thrown an exception: java.lang.ClassCastException: class [B cannot be cast to class java.lang.String ([B and java.lang.String are in module java.base of loader 'bootstrap')
        at com.ServiceRequestResultListener_SmallryeMessagingInvoker_receiveRequest_f873ae93a96fc221154ff1ca86863df8150ec1c7.invoke(ServiceRequestResultListener_SmallryeMessagingInvoker_receiveRequest_f873ae93a96fc221154ff1ca86863df8150ec1c7.zig:46)
        at io.smallrye.reactive.messaging.AbstractMediator.invoke(AbstractMediator.java:61)
        at io.smallrye.reactive.messaging.SubscriberMediator.lambda$processMethodReturningVoid$0(SubscriberMediator.java:128)
        at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:63)
        at io.smallrye.context.propagators.rxjava2.ContextPropagatorOnFlowableCreateAction$ContextCapturerFlowable.lambda$onNext$2(ContextPropagatorOnFlowableCreateAction.java:50)
        at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:215)
        at io.smallrye.context.propagators.rxjava2.ContextPropagatorOnFlowableCreateAction$ContextCapturerFlowable.onNext(ContextPropagatorOnFlowableCreateAction.java:50)
        at io.reactivex.internal.util.HalfSerializer.onNext(HalfSerializer.java:45)
        at io.reactivex.internal.subscribers.StrictSubscriber.onNext(StrictSubscriber.java:97)
        at io.smallrye.context.propagators.rxjava2.ContextPropagatorOnFlowableCreateAction$ContextCapturerFlowable.lambda$onNext$2(ContextPropagatorOnFlowableCreateAction.java:50)
        at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:215)
        at io.smallrye.context.propagators.rxjava2.ContextPropagatorOnFlowableCreateAction$ContextCapturerFlowable.onNext(ContextPropagatorOnFlowableCreateAction.java:50)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drainLoop(FlowableFlatMap.java:501)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.drain(FlowableFlatMap.java:366)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$InnerSubscriber.onNext(FlowableFlatMap.java:665)
        at io.smallrye.context.propagators.rxjava2.ContextPropagatorOnFlowableCreateAction$ContextCapturerFlowable.lambda$onNext$2(ContextPropagatorOnFlowableCreateAction.java:50)
        at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:215)
        at io.smallrye.context.propagators.rxjava2.ContextPropagatorOnFlowableCreateAction$ContextCapturerFlowable.onNext(ContextPropagatorOnFlowableCreateAction.java:50)
        at io.reactivex.internal.subscriptions.DeferredScalarSubscription.complete(DeferredScalarSubscription.java:117)
        at io.reactivex.processors.AsyncProcessor.subscribeActual(AsyncProcessor.java:242)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at io.reactivex.Flowable.subscribe(Flowable.java:14865)
        at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:163)
        at io.smallrye.context.propagators.rxjava2.ContextPropagatorOnFlowableCreateAction$ContextCapturerFlowable.lambda$onNext$2(ContextPropagatorOnFlowableCreateAction.java:50)
        at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:215)
        at io.smallrye.context.propagators.rxjava2.ContextPropagatorOnFlowableCreateAction$ContextCapturerFlowable.onNext(ContextPropagatorOnFlowableCreateAction.java:50)
        at io.reactivex.internal.util.HalfSerializer.onNext(HalfSerializer.java:45)
        at io.reactivex.internal.subscribers.StrictSubscriber.onNext(StrictSubscriber.java:97)
```

Here is my method:

```
@Incoming("request")
@Acknowledgment(Acknowledgment.Strategy.PRE_PROCESSING)
public void receiveRequest(final String requestJson) {
    System.out.println(requestJson);
}
```

**Expected behavior**
Accept message.

**Actual behavior**
Throws error

**To Reproduce**
1. Start up qurkus service using smallrye-amqp
2. Send text message to artemismq broker using STOMP protocol 

**Configuration**
```properties
mp.messaging.incoming.<stream-name>.connector=smallrye-amqp
mp.messaging.incoming.<stream-name>.durable=true
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: 11.0.2
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 0.28.1

**Comment by geoand** [comment]
Can you please try version `1.0.0.CR1` and see if you still have the issue?

**Comment by cescoffier** [comment]
I believe it was fixed in 1.0.0.CR1.

**Comment by garrettahines1** [comment]
@cescoffier tried this in 1.0.0.Final and still getting the error. If I change the requestJson to be a byte[] instead of String it works.

**Comment by cescoffier** [comment]
I believe it's a bug in the AMQP connector, can you open an issue in https://github.com/smallrye/smallrye-reactive-messaging/issues

**Comment by garrettahines1** [comment]
https://github.com/smallrye/smallrye-reactive-messaging/issues/336

**Comment by cescoffier** [comment]
Left-over. Was fixed a long time ago.
