### ISSUE TITLE
Infinispan Client is ignoring configuration environment variables

### ISSUE THREAD

**Issue by ricardozanini** [quarkusio/quarkus#5708]
**Describe the bug**
Unless specified in `application.properties` file, [configurations for Infinispan Client](https://quarkus.io/guides/infinispan-client#quarkus-infinispan-client_configuration) are being ignored when they are only available via environment variables.

For example, if I have an empty `application.properties` file and set `QUARKUS_INFINISPAN_CLIENT_SERVER_LIST` environment variable, the client fails to read it and do not connect:

```
2019-11-22 16:28:39,544 INFO  [org.inf.cli.hot.RemoteCacheManager] (main) ISPN004021: Infinispan version: 10.0.0.CR1
2019-11-22 16:28:39,589 ERROR [org.inf.cli.hot.imp.ope.RetryOnFailureOperation] (HotRod-client-async-pool-1-1) ISPN004007: Exception encountered. Retry 10 out of 10: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /127.0.0.1:11222
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
```
(tries to connect to localhost, the default value)

If I set the property `quarkus.infinispan-client.server-list` in the properties file to an empty value, then the environment variable is read and the client successfully connects to the server.

**Expected behavior**

That the Infinispan client extension reads the environment variable without having to explicit set it into an `application.properties` file.

**Actual behavior**

The desired property is not being read from environment variable if it's not presented in the properties file.

**To Reproduce**
1. Clone [this project](https://github.com/ricardozanini/kogito-examples/tree/remove-props/onboarding-example/onboarding):

```
$ git clone --single-branch --branch remove-props https://github.com/ricardozanini/kogito-examples
$ cd kogito-examples/onboarding-example/onboarding
```
2. Set the environment variable to something like `export QUARKUS_INFINISPAN_CLIENT_SERVER_LIST=http://im-not-here:11222`
3. Build it with `mvn clean package -Ppersistence -DskipTests`
4. Run it: `java -jar target/onboarding-8.0.0-SNAPSHOT-runner.jar`
5. Check the logs and you'll see the message described above (failing to connect to **localhost**)

**Configuration**
Blank properties

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux skywalker 5.3.11-200.fc30.x86_64 #1 SMP Tue Nov 12 19:25:25 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

 - Output of `java -version`: 
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-20191008104205.buildslave.jdk8u-src-tar--b07)
OpenJDK 64-Bit GraalVM CE 19.2.1 (build 25.232-b07-jvmci-19.2-b03, mixed mode)

 - Quarkus version or git rev: 0.27.0

**Additional context**
Would be nice to have such feature working, so we could configure Quarkus application in containers much easier.

Might be related: https://github.com/quarkusio/quarkus/issues/1887

**Comment by gsmet** [comment]
@dmlloyd is it related to all the config fixes that just went in?

**Comment by dmlloyd** [comment]
Yes, this is something that was fixed with #5387.

**Comment by ricardozanini** [comment]
Thanks @dmlloyd 
I assume this went for 1.0.0?

**Comment by dmlloyd** [comment]
Correct, 1.1.0.

**Comment by geoand** [comment]
Is this still an issue?

**Comment by ricardozanini** [comment]
@geoand lol this is old, I think it was fixed.

**Comment by geoand** [comment]
Thanks!

**Comment by israel-ramos** [comment]
@dmlloyd  @gsmet 
This issue persists.
The ENV vars is ignored.
For instance: `QUARKUS_INFINISPAN_CLIENT__NAMED_INFINISPAN_CLIENTS__HOSTS`
The same configs on application.properties works.
Version: `quarkusPlatformVersion=3.11.0.CR1`

**Comment by dmlloyd** [comment]
Are you sure you're using the correct config key? What is the equivalent key in `application.properties` that you are trying to set?

/cc @karesti

**Comment by karesti** [comment]
Hey, ```QUARKUS_INFINISPAN_CLIENT__NAMED_INFINISPAN_CLIENTS__HOSTS``` it's not a valid key

**Comment by israel-ramos** [comment]
Hi @karesti 
![image](https://github.com/quarkusio/quarkus/assets/5123320/66b1e01e-25b8-4cca-9384-82e4c9fca800)

Source: https://quarkus.io/guides/infinispan-client-reference

So, I believe the docs are out of date.
Here, we use Quarkus for all our services. As I know, by conventions (Quarkus community), all the configs supported at application.properties could be translated to equivalent ENV var, uppercase, single underscore for dots and double underscore for  `"` (named configs).

We run all services our services built to native images (on Kubernetes). So we prefer, as most as possible, to use ENV vars and keep the `application.properties` empty.


BTW, as a work around I am using as following way for a while.
At `application.properties`:

```
quarkus.infinispan-client.tagfull.hosts=${QUARKUS_INFINISPAN_CLIENT__TAGFULL__HOSTS:}
quarkus.infinispan-client.tagfull.username=${QUARKUS_INFINISPAN_CLIENT__TAGFULL__USERNAME:}
quarkus.infinispan-client.tagfull.password=${QUARKUS_INFINISPAN_CLIENT__TAGFULL__PASSWORD:}
quarkus.infinispan-client.use-schema-registration=${QUARKUS_INFINISPAN_CLIENT__TAGFULL__USE_SCHEMA_REGISTRATION:true}
```

**Comment by karesti** [comment]
@israel-ramos Sorry for what might be confusing docs, however the docs are correct. The named connections are dependant of your configuration. In this case you named it "tagfull". If you have a single connection, you can avoid naming it for simplicity. https://quarkus.io/guides/infinispan-client-reference#default-and-named-connections

The documentation then lists all the properties. The "named-infinispan-clients" should be replaced by the name you used. If you check any other database that supports naming connections, you will see that all the docs follow that.
However, renaming "named-infinispan-clients" to "infinispan-client-name" might be helpful to avoid confusion. What do you think ?

**Comment by israel-ramos** [comment]
@karesti 

I have double checked, and none of the following works:

```
_## DOES NOT WORK_
QUARKUS_INFINISPAN_CLIENT_TAGFULL_HOSTS=127.0.0.1:11222
QUARKUS_INFINISPAN_CLIENT_TAGFULL_USERNAME=user
QUARKUS_INFINISPAN_CLIENT_TAGFULL_PASSWORD=****
QUARKUS_INFINISPAN_CLIENT_TAGFULL_USE_SCHEMA_REGISTRATION=true

_## DOES NOT WORK_
QUARKUS_INFINISPAN_CLIENT__TAGFULL__HOSTS=127.0.0.1:11222
QUARKUS_INFINISPAN_CLIENT__TAGFULL__USERNAME=user
QUARKUS_INFINISPAN_CLIENT__TAGFULL__PASSWORD=****
QUARKUS_INFINISPAN_CLIENT__TAGFULL__USE_SCHEMA_REGISTRATION=true

_## DOES NOT WORK_
QUARKUS_INFINISPAN_CLIENT_HOSTS=127.0.0.1:11222
QUARKUS_INFINISPAN_CLIENT_USERNAME=user
QUARKUS_INFINISPAN_CLIENT_PASSWORD=pass
QUARKUS_INFINISPAN_CLIENT_USE_SCHEMA_REGISTRATION=true
```

PS.: For the last one, not named, I have also removed the annotation `@InfinispanClientName("tagfull")`

**Comment by israel-ramos** [comment]
@karesti 
I mean:

`jakarta.enterprise.inject.CreationException: Error creating synthetic bean [2V6HFAxu7Ly4lVcHuosbTNsgBtM]: java.lang.IllegalStateException: Unable to produce RemoteCache. RemoteCacheManager is null.`

**Comment by israel-ramos** [comment]
@karesti 

Just a update.
So far I was using disabled the dev services for infinispan `QUARKUS_INFINISPAN_CLIENT_DEVSERVICES_ENABLED=false`
Because I am using local infinispan cluster (running on local k8s cluster).
So, just for double check, I just tried to re-enable the dev services, and whe removing all the env vars, it works.

Do you believe the "dev services" stuff could be impacting the way the configs are being loaded?

PS.: Running here with `./gradlew quarkusDev`

**Comment by karesti** [comment]
@israel-ramos so, you are running infinispan in a local k8s cluster, and your application is dev mode, is that alright ?

**Comment by israel-ramos** [comment]
@karesti yes, it is. That's the way we setup our local dev env, using a local k8s. 

For a few special kind of tests/debug tasks, during development, we depend on other apps running on that cluster to comunicate with the same infinispan within the cluster. The app being worked (development) is running on IDE, outside the cluster. That's why it is running using quarkusDev and connecting to infinispan inside the k8s. Also there are other resources, not only other apps, in the same cluster which we depend on like service mesh, gateway classes, http routes, database, etc...

That's the reason.

But anyway, many thanks. We will keep using the workaround at the `application.properties` doing the config bridge.

**Comment by geoand** [comment]
> maybe you can help clarify if this behaviour is normal in any other extension using a database, for example

Which behavior are we talking about?

**Comment by karesti** [comment]
The env variables and dev mode

**Comment by israel-ramos** [comment]
@geoand This one:

Using:
```
@Inject
@Remote("health-check")
RemoteCache<String, String> healthCache;
```
In this way, the `application.properties` as following, **IT IS WORKING**, and the remote cache instance is being injected normally:
```
# IT WORKS
quarkus.infinispan-client.hosts=127.0.0.1:11222
quarkus.infinispan-client.username=user
quarkus.infinispan-client.password=****
quarkus.infinispan-client.use-schema-registration=true
```

But in this way, **DOES NOT WORK**. The remote cache instance **IS NOT** being injected.

```
# DOES NOT WORK
quarkus.infinispan-client.devservices.enabled=false
quarkus.infinispan-client.hosts=127.0.0.1:11222
quarkus.infinispan-client.username=user
quarkus.infinispan-client.password=****
quarkus.infinispan-client.use-schema-registration=true
```

**Comment by geoand** [comment]
I just tried:

```
QUARKUS_INFINISPAN_CLIENT_HOSTS=localhost:11222 mvn quarkus:dev
```

and it worked as expected (with the cavear that the logging is misleading which is why I opened #40936).
