### ISSUE TITLE
@Inject PanacheRepository into @QuarkusTest causes "This method is normally automatically overridden in subclasses: did you forget to annotate your entity with @Entity?"

### ISSUE THREAD

**Issue by zeljkot** [quarkusio/quarkus#6349]
**Describe the bug**

If the class implementing PanacheRepository is injected into @QuarkusTest, the test will throw infamous "This method is normally automatically overridden in subclasses: did you forget to annotate your entity with @Entity?"

**Expected behavior**

PanacheRepository implementor is injected and can be used to manipulate entities.

**Actual behavior**

Throws
```
Caused by: java.lang.IllegalStateException: This method is normally automatically overridden in subclasses: did you forget to annotate your entity with @Entity?
        at io.quarkus.hibernate.orm.panache.runtime.JpaOperations.implementationInjectionMissing(JpaOperations.java:408)
```

**To Reproduce**

1. @Inject PanacheRepository into @QuarkusTest
2. mvn clean test

**Configuration**

```properties
quarkus.datasource.driver = org.h2.Driver
quarkus.datasource.url=jdbc:h2:mem:test"
quarkus.datasource.username=sa
quarkus.datasource.password=sa

quarkus.hibernate-orm.database.generation=drop-and-create
```

**Screenshots**

(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**

 - Output of `uname -a` or `ver`: Microsoft Windows [Version 10.0.19041.1]
 - Output of `java -version`: 
```
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)
```
 - GraalVM version (if different from Java): not tested

 - Quarkus version or git rev: 1.1.0.Final

**Additional context**

Maven project: [rest.zip](https://github.com/quarkusio/quarkus/files/4005886/rest.zip)

**Comment by geoand** [comment]
I think this is a duplicate of #1724 but I'll let @FroMage confirm

**Comment by zeljkot** [comment]
It could be, but in my case workaround with @PostConstruct does not work. This is a very basic test case so I am a bit worried about usability of the Quarkus platform, especially if the problem is known since March.

**Comment by geoand** [comment]
The issue is known and is being worked on as we speak.
The issue is complicated by how junit 5 deals with classloaders, but a solution will be land soon enough.

**Comment by zeljkot** [comment]
It would be amazing if you crack this, as Arquillian or other complicated solutions will not be needed anymore.

**Comment by geoand** [comment]
@stuartwdouglas is working in it IIRC

**Comment by gintsgints** [comment]
I have got same error message just by declaring test class variable with entity.

**Comment by jonathanvila** [comment]
This was driving me crazy .... now I see I'm not alone.
Any progress on this @geoand ?

**Comment by geoand** [comment]
This should now be fixed in master. Can you give it a try?

**Comment by jonathanvila** [comment]
I've tried with 1.1.1.Final and happens the same @geoand

**Comment by gsmet** [comment]
@jonathanvila @geoand asked to try with master, not 1.1.1.Final. Even in 1.2, this issue isn't fixed.

Try with the latest snapshots `999-SNAPSHOT` published here: https://oss.sonatype.org/content/repositories/snapshots/io/quarkus/ .

Thanks.

**Comment by jonathanvila** [comment]
Yep, I know he said master.

What I would like is to "fix" this as a "regular" user..... and with a
stable release. So from your words I see this needs to wait until be
released.

So, I will move to a workaround and remain at 1.1.1

**Comment by jonathanvila** [comment]
No workaround possible :( I tried the indirect injection with wrappers, but is not possible apparently due to the kind of test.

**Comment by jonathanvila** [comment]
@gsmet Tried with sonatype repo and I have errors on downloading artifacts : 

```
[ERROR] Plugin io.quarkus:quarkus-maven-plugin:999-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact io.quarkus:quarkus-maven-plugin:jar:999-SNAPSHOT in quarkus (https://oss.sonatype.org/content/repositories/snapshots/io/quarkus/) -> [Help 1]
org.apache.maven.plugin.PluginResolutionException: Plugin io.quarkus:quarkus-maven-plugin:999-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact io.quarkus:quarkus-maven-plugin:jar:999-SNAPSHOT in quarkus (https://oss.sonatype.org/content/repositories/snapshots/io/quarkus/)
```
Now I will try to clone quarkus and build it locally

**Comment by jonathanvila** [comment]
@gsmet @geoand 
Tried with master with no luck :( 

This is the repository & branch : https://github.com/jonathanvila/spring-petclinic-rest/tree/quarkus

This is the command to test : mvn clean test -Dtest=ClinicServiceTests

**Comment by geoand** [comment]
@jonathanvila I tried it and got:

```
Expecting actual not to be null
```

I didn't really look at the code but are you sure it's due to this issue? I didn't see anything in the output indicating it

**Comment by jonathanvila** [comment]
Yes

This is the test class : 

```
@QuarkusTest
@QuarkusTestResource(H2DatabaseTestResource.class)
public class ClinicServiceTests {

    @Inject
    ClinicService clinicService;

    @Inject
    JpaPetTypeRepository petTypeRepository;

    @Inject
    JpaVetRepository vetRepository;

    @Test
    public void shouldFindPetTypeById(){
        assertThat(this.clinicService).isNotNull();
        assertThat(((ClinicServiceImpl) this.clinicService).petTypeRepository).isNotNull(); // This fails
        assertThat(((ClinicServiceImpl) this.clinicService).petTypeRepository.listAll().size()).isGreaterThan(0);
    	PetType petType = this.clinicService.findPetTypeById(1);
    	assertThat(petType.getName()).isEqualTo("cat");
    }
```

I added 3 asserts before the real test code in order to see the value for the injections , and the service injected is not null, but the repository injected in it appears to be null

**Comment by Jupdi** [comment]
We got the same Issue in two independent implementations.

**Comment by jmkgreen** [comment]
I'm guessing this has nothing to do with Panache specifically and everything to do with injecting of resources? I have a test injecting a service that doesn't work (same error). Works fine within IntelliJ, but through Maven it blows up.

**Comment by zeljkot** [comment]
Panache is OK and error is fixed in 1.3.0.Alpha1
