### ISSUE TITLE
Kubernetes: wrong .jar file name in JAVA_APP_JAR env var (for OpenShift)

### ISSUE THREAD

**Issue by Ladicek** [quarkusio/quarkus#6827]
**Describe the bug**

The `JAVA_APP_JAR` environment variable, which the OpenShift Java images use to know which JAR they should run, is generated wrongly.

Dekorate generates this env var here: https://github.com/dekorateio/dekorate/blob/master/annotations/openshift-annotations/src/main/java/io/dekorate/openshift/handler/OpenshiftHandler.java#L200

From that code, it is apparent that Dekorate tries to use its knowledge about the build to figure out the correct file name.

However, if I define `quarkus.application.name`, this value is used as the file name, which is wrong, as `quarkus.application.name` can be something different than, e.g., Maven's `${project.build.finalName}`.

**Expected behavior**

The actual JAR file name is always used, even if `quarkus.application.name` is defined.

**Actual behavior**

The value of `quarkus.application.name` is used, even if it doesn't match the file name.

**To Reproduce**

```properties
quarkus.application.name=fooooo-baaaaaar
kubernetes.deployment.target=openshift
```

See `target/kubernetes/openshift.yml`:

```yaml
apiVersion: "apps.openshift.io/v1"
kind: "DeploymentConfig"
metadata:
  ...
  name: "fooooo-baaaaaar"
spec:
  ...
  template:
    ...
    spec:
      containers:
      - env:
        ...
        - name: "JAVA_APP_JAR"
          value: "/deployments/fooooo-baaaaaar-1.0.0-SNAPSHOT-runner.jar"
        image: ""
      ...
```

**Comment by Ladicek** [comment]
CC @iocanel

**Comment by iocanel** [comment]
@Ladicek: This is a known issue and it should be fixed on master.

**Comment by Ladicek** [comment]
I'm pretty sure I'm testing with Quarkus `master`. I'll try again.

**Comment by iocanel** [comment]
> I'm pretty sure I'm testing with Quarkus `master`. I'll try again.

Damn! I thought I deleted my comment in time!
So, I fixed a similar issue recently, but upon closer inspection this seems different.

**Comment by Ladicek** [comment]
:-)

I've just tested with Quarkus `999-SNAPSHOT` built from `76fcdc4b8e6c113c53bb55f965a116afdee5290a`, and the problem remains.
