### ISSUE TITLE
Kotlin quarkus Dev recompiling with JVM target 1.6

### ISSUE THREAD

**Issue by zulq** [quarkusio/quarkus#7038]
When running in Dev mode with kotlin, JVM 1.6 target is being used instead of the Intellij settings after code changes and thus causing the following error.

**Calls to static methods in Java interfaces are prohibited in JVM target 1.6. Recompile with '-jvm-target 1.8'**

After restarting it works initially until code is changed again.

**Comment by gsmet** [comment]
This has been fixed in 1.3.0.Alpha1.

Agreed it's an Alpha but probably better than something not working :).

**Comment by geoand** [comment]
@gsmet beat me to it 😎. Please give 1.3.0.Alpha1 a try to see if the problem disappears for you

**Comment by zulq** [comment]
Tried to update but dependencies failed to resolve for 1.3.0.Alpha1 after I updated the gradle properites file.

**Comment by geoand** [comment]
It is in Maven Central: https://mvnrepository.com/artifact/io.quarkus/quarkus-bom/1.3.0.Alpha1

**Comment by zulq** [comment]
Yes, I did confirm that before updating but still not resolving.

**Comment by geoand** [comment]
I have tried it myself and the dependencies were resolved. Also other users have reported success.
What is the exact error you are getting?

**Comment by zulq** [comment]
Could not resolve: io.quarkus:quarkus-resteasy-qute and for all the other packages.

**Comment by geoand** [comment]
I propose you clean you clean your gradle cache and/or your `.m2` directory

**Comment by zulq** [comment]
Did all that and still, however getting the following:
-Declare repository providing the artifact, see doc....

**Comment by zulq** [comment]
However if add the package version explicitly as part of the implementation it works so am suspecting the platform/quarkus plugin

**Comment by geoand** [comment]
@zulq are we sure the gradle parts were properly released?

**Comment by zulq** [comment]
Getting the following after adding the package versions explicitly:
`   > Could not find io.quarkus:quarkus-universe-bom:1.3.0.Alpha1.`

**Comment by geoand** [comment]
Oh OK, that's easy then :)

We haven't released universe bom. You can change the artifactId to `quarkus-bom` and things should be fine

**Comment by zulq** [comment]
Did that and deps resolved but now getting:
`Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact io.quarkus:quarkus-spring-data-jpa-deployment:jar:1.3.0.Alpha1`

Tried to resolve this by adding `1.2.0.Final to quarkus-spring-data-jpa` but no luck.

**Comment by geoand** [comment]
@aloubyansky I am seeing the following:

* Create a new project using: `mvn io.quarkus:quarkus-maven-plugin:1.3.0.Alpha1:create -DprojectGroupId=org.acme -DprojectArtifactId=getting-started -DclassName="org.acme.quickstart.GreetingResource" -Dpath="/hello" -DbuildTool=gradle
`

* Update the versions and bom
* Execute quarkusDev using: ` ./gradlew quarkusDev`

And the exception is:

```
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: io.quarkus.bootstrap.resolver.AppModelResolverException: Failed to resolve artifacts
        at io.quarkus.dev.DevModeMain.main(DevModeMain.java:51)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: io.quarkus.bootstrap.resolver.AppModelResolverException: Failed to resolve artifacts
        at io.quarkus.dev.DevModeMain.start(DevModeMain.java:108)
        at io.quarkus.dev.DevModeMain.main(DevModeMain.java:46)
        Suppressed: java.lang.NullPointerException
                at io.quarkus.dev.DevModeMain.close(DevModeMain.java:115)
                at io.quarkus.dev.DevModeMain.main(DevModeMain.java:49)
Caused by: java.lang.RuntimeException: io.quarkus.bootstrap.resolver.AppModelResolverException: Failed to resolve artifacts
        at io.quarkus.bootstrap.BootstrapAppModelFactory.doClasspathDiscovery(BootstrapAppModelFactory.java:347)
        at io.quarkus.bootstrap.BootstrapAppModelFactory.resolveAppModel(BootstrapAppModelFactory.java:249)
        at io.quarkus.bootstrap.app.QuarkusBootstrap.bootstrap(QuarkusBootstrap.java:134)
        at io.quarkus.dev.DevModeMain.start(DevModeMain.java:103)
        ... 1 more
Caused by: io.quarkus.bootstrap.resolver.AppModelResolverException: Failed to resolve artifacts
        at io.quarkus.bootstrap.resolver.maven.MavenArtifactResolver.resolve(MavenArtifactResolver.java:214)
        at io.quarkus.bootstrap.resolver.BootstrapAppModelResolver.doResolveModel(BootstrapAppModelResolver.java:235)
        at io.quarkus.bootstrap.resolver.BootstrapAppModelResolver.resolveManagedModel(BootstrapAppModelResolver.java:149)
        at io.quarkus.bootstrap.BootstrapAppModelFactory.doClasspathDiscovery(BootstrapAppModelFactory.java:344)
        ... 4 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: The following artifacts could not be resolved: io.quarkus:quarkus-netty-deployment:jar:1.3.0.Alpha1, io.quarkus:quarkus-resteasy-server-common-deployment:jar:1.3.0.Alpha1, io.quarkus:quarkus-vertx-core-deployment:jar:1.3.0.Alpha1, io.quarkus:quarkus-resteasy-deployment:jar:1.3.0.Alpha1: Could not find artifact io.quarkus:quarkus-netty-deployment:jar:1.3.0.Alpha1
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:422)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:224)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifacts(DefaultRepositorySystem.java:268)
        at io.quarkus.bootstrap.resolver.maven.MavenArtifactResolver.resolve(MavenArtifactResolver.java:212)
        ... 7 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact io.quarkus:quarkus-netty-deployment:jar:1.3.0.Alpha1
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:412)
        ... 10 more
```

Are we doing something wrong or is this an issue?

**Comment by aloubyansky** [comment]
Yes, that's a wrong resolver.

**Comment by geoand** [comment]
The issue mentioned above should be fixed by #7071

**Comment by gsmet** [comment]
@geoand so can we close this issue?

**Comment by geoand** [comment]
Yes certainly

**Comment by lfmunoz** [comment]
Using 1.3.0.Final I am facing this same problem. Maybe because I am using gradle? Anyone have a work around?

**Comment by geoand** [comment]
You need to set the jvmTarget configuration value of the Kotlin Maven plugin

**Comment by lfmunoz** [comment]
@geoand   I used the quick start project generator. It does that for you? I went ahead and uploaded my project here it is:

https://github.com/lfmunoz/quarkus-bridge

1. Do a git clone
2. ./gradlew quarkusDev
3. localhost:8080 works
4. Make some change in the code,
In particular eco.analytics.monitor.KeyValueConfigurator  is a web endpoint for http://localhost:8080/api/view  

simply add a and space and save reload webpage I see error 

/home/luis/github/TMP_DELETE_ME/quarkus-bridge/src/main/kotlin/eco/analytics/monitor/KeyValueConfigurator.kt:56:15
Reason: Cannot inline bytecode built with JVM target 1.8 into bytecode that is being built with JVM target 1.6. Please specify proper '-jvm-target' option

**Comment by geoand** [comment]
The project generation has been fixed to include 1.8 as the target and should be available in 1.3.1.Final which goes out tomorrow (if all goes well)

**Comment by lfmunoz** [comment]
@geoand with 1.3.1.Final I still get same error.   Do you know why am I getting this error and what is the fix? I don't understand what you said above. Clearly in my project I have (https://github.com/lfmunoz/quarkus-bridge)

```
compileKotlin {
    kotlinOptions.jvmTarget = JavaVersion.VERSION_1_8
    kotlinOptions.javaParameters = true
}
```

The project generator has been adding that since before 1.3.0 so don't know what difference 1.3.1.Final would have done.

According to this ticket this issue should have been fixed in 1.3.0?
 

```
/home/luis/github/TMP_DELETE_ME/quarkus-bridge/src/main/kotlin/eco/analytics/monitor/KeyValueConfigurator.kt:81:16
Reason: Cannot inline bytecode built with JVM target 1.8 into bytecode that is being built with JVM target 1.6. Please specify proper '-jvm-target' option
	at io.quarkus.kotlin.deployment.KotlinCompilationProvider.compile(KotlinCompilationProvider.java:82)
	at io.quarkus.dev.ClassLoaderCompiler.compile(ClassLoaderCompiler.java:174)
	at io.quarkus.dev.RuntimeUpdatesProcessor.checkForChangedClasses(RuntimeUpdatesProcessor.java:194)
	at io.quarkus.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:125)
	at io.quarkus.vertx.http.runtime.devmode.VertxHotReplacementSetup$1.handle(VertxHotReplacementSetup.java:50)
	at io.quarkus.vertx.http.runtime.devmode.VertxHotReplacementSetup$1.handle(VertxHotReplacementSetup.java:42)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by geoand** [comment]
@lfmunoz it has been fixed, but only for Maven unfortunately... I opened https://github.com/quarkusio/quarkus/pull/8262 which should fix it for Gradle as well.
