### ISSUE TITLE
Error running @ParameterizedTest in Quarkus 1.3.0.Final

### ISSUE THREAD

**Issue by masini** [quarkusio/quarkus#7916]
**Describe the bug**
Simple method in a `@QuarkusTest` which is also a `@ParameterizedTest` doesn't work.

To reproduce:

```
@QuarkusTest
public class ExampleResourceTest {

    public enum MyEnum {
        VALUE1,
        VALUE2
    }

    @ParameterizedTest(name = "Enum Value for test {0}")
    @EnumSource(value = MyEnum.class)
    public void testHelloEndpoint(MyEnum input) {
    }

}
```

if you try to run it you got:

`java.lang.RuntimeException: Could not find method public void net.lucamasini.testcase.ExampleResourceTest.testHelloEndpoint(net.lucamasini.testcase.ExampleResourceTest$MyEnum) on test class`

one for every enum value.

**Expected behavior**
The runtime container should find the enumerated method

**Actual behavior**
Cannot find the public method

**To Reproduce**
1. Create a project from Quarkus.io
2. Add the test case at the top of this issue
3. Run it

**Configuration**
None

**Comment by gastaldi** [comment]
It looks like it was fixed in https://github.com/quarkusio/quarkus/pull/7881, can you give it a try with the latest master?

**Comment by geoand** [comment]
It seems like  #7881 doesn't fix this issue. I'll take a look

**Comment by geoand** [comment]
I am pretty sure I know what the problem is, but I need to do a few more tests first

**Comment by geoand** [comment]
I have a hack in #7920. I absolutely don't like it, but I don't see any other way around...
