### ISSUE TITLE
Error while creating the native imgae on mac os

### ISSUE THREAD

**Issue by shahparthiv** [quarkusio/quarkus#8386]
**I am running the below command**

`./mvnw package -Pnative -Dquarkus.native.container-build=true`

**I am getting following error**

```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.3.1.Final:build (default) on project my-artifactId: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: java.lang.RuntimeException: Failed to build native image
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:353)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:938)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:273)
[ERROR] 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2027)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1551)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1442)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
[ERROR] Caused by: java.lang.RuntimeException: Image generation failed. Exit code: 125
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.imageGenerationFailed(NativeImageBuildStep.java:369)
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:339)
[ERROR] 	... 12 more

```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Darwin Parthiv.local 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64`
 - Output of `java -version`: 
```
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02)
OpenJDK 64-Bit Server VM GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02, mixed mode, sharing)
```
 - Quarkus version or git rev: `1.3.1`
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): `Apache Maven 3.6.3`

**Comment by geoand** [comment]
Is there any more information in the output?

Perhaps if you add `-X`?

**Comment by shahparthiv** [comment]
I have ran the command using `-X`.
Please check the attached log file. 
[logs.log](https://github.com/quarkusio/quarkus/files/4433003/logs.log)

**Comment by geoand** [comment]
Hm... I see `[ERROR] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Unable to get GraalVM version from the native-image binary.` in the logs.

Can you please try and execute the following command:

```
docker run --rm quay.io/quarkus/ubi-quarkus-native-image:19.3.1-java11 --version
```

?

**Comment by shahparthiv** [comment]
hey I ran the given command and output is:  `GraalVM Version 19.3.1 CE`

In ma bashrc I have set the path as below:
`export GRAALVM_HOME=/Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.0.0/Contents/Home`

and in path `$GRAALVM_HOME/bin`

please let me know If I configure something wrong.

**Comment by shahparthiv** [comment]
@geoand, @Sanne,   As the attached issue is merged.
I need to just run the command or I need to upgrade something?

**Comment by shahparthiv** [comment]
any update?

**Comment by Sanne** [comment]
sorry the merged issue #8429 is unrelated. I also don't have a mac myself, I'll let others on the team investigate this issue. @geoand is this on your plate?

**Comment by geoand** [comment]
I have never even used a Mac, so it will be difficult for me take it :)

**Comment by Sanne** [comment]
> I have never even used a Mac, so it will be difficult for me take it :)

lol me neither. Linux since 20 years!  Ok let's ask to our other teammates then.

**Comment by geoand** [comment]
@shahparthiv I don't supose anything changed with version `1.4.0.CR1` of Quarkus (you've have to use `quarkus-bom` instead of `quarkus-platform` to test it)

**Comment by maxandersen** [comment]
do you have a reproducer proejct ? then I can try reproduce on my mac.

**Comment by ebullient** [comment]
Native image generation works ok for me on 1.3.2-Final on MacOS.

What consistently fails is trying to build that image with `-Dquarkus.native.container-build=true` (which is what is also attempted above). For me, the build hangs for a LONG TIME, and then reports OutOfMemory, and dies.

Happy to run a screenshare so you guys can poke around..

**Comment by geoand** [comment]
@ebullient mind adding `-Dquarkus.native.native-image-xmx=5g` and trying again?

**Comment by ebullient** [comment]
Relaying here (@geoand and I will keep tossing things back and forth in Zulip), adding the above attribute lands me with the pretty error message the OP reported. ;)

**Comment by ebullient** [comment]
Ok. The pretty error message isn't coming out because the Image generation step/process is exiting with RC=1 (rather than the pretty 137 that is emitted somewhere):
```
Caused by: java.lang.RuntimeException: Image generation failed. Exit code: 1
    at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.imageGenerationFailed (NativeImageBuildStep.java:369)
    at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build (NativeImageBuildStep.java:339)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at io.quarkus.deployment.ExtensionLoader$2.execute (ExtensionLoader.java:938)
    at io.quarkus.builder.BuildContext.run (BuildContext.java:273)
    at org.jboss.threads.ContextClassLoaderSavingRunnable.run (ContextClassLoaderSavingRunnable.java:35)
    at org.jboss.threads.EnhancedQueueExecutor.safeRun (EnhancedQueueExecutor.java:2027)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask (EnhancedQueueExecutor.java:1551)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run (EnhancedQueueExecutor.java:1442)
    at java.lang.Thread.run (Thread.java:834)
    at org.jboss.threads.JBossThread.run (JBossThread.java:479)
```

What I still can't understand is _why_ it is totally running out of memory. I have tried all kinds of numbers other than 5g that are bigger, and none of them seem to change anything. I would be scared for my app if creating native binaries didn't work just fine for macos and linux when not building using the container.

**Comment by geoand** [comment]
@ebullient I am not sure which scenario your observation applies to.

**Comment by ebullient** [comment]
I can compile a native image on mac OS without an issue.
If I want to build a containerized native image, that requires using a build container.
Setting `-Dquarkus.native.native-image-xmx=5g` gives me a slightly faster fail than before, but it still fails. It doesn't seem like changing that specific number helps. I don't think infinite RAM is required, because my mac doesn't tip over when building the image w/o docker.

So, do we know what is chewing memory? Is that value the right value to try increasing, or is there something else that could also be required?

**Comment by geoand** [comment]
On Mac (and Windows) when using docker, one also has to set the max memory the VM (which is used implicitly) can have.
So you also might have to increase that value.

On Linux there is no such VM and docker can access all memory.

**Comment by ebullient** [comment]
I understand that. What I don't understand is how I am supposed to increase that value, as any combination of numbers I tried (which all seemed reasonable) had no effect.

**Comment by geoand** [comment]
The docker VM should have as much memory as possible, that's for sure.

As for the JVM that runs the native image build, that's trickier since there are a lot of ergonomics in play... Might I suggest using Xmx of a couple gigabyte less than the VM memory.

**Comment by AmareshKulkarni** [comment]
I ran into a similar issue. I had to restart Docker on my Mac to get things back to normal. Apparently, the quay.io/quarkus/ubi-quarkus-native-image was hung or was not in the appropriate state for the native build to proceed.

**Comment by BigFatDog** [comment]
> I understand that. What I don't understand is how I am supposed to increase that value, as any combination of numbers I tried (which all seemed reasonable) had no effect.

I had the same issue and found the solution.
Docker memory usage HAS to be configured in 2 places:
* open "Preferences -> Advanced" in your Docker Desktop and adjust max memory. Mine is 8G
* add jvm memory arg in pom.xml:
```
<properties>
    ......
    <quarkus.native.native-image-xmx>8192m</quarkus.native.native-image-xmx>
  </properties>
``` 

In fact the jvm args could be configured in other ways, too.

**Comment by cockatoowtf** [comment]
> > I understand that. What I don't understand is how I am supposed to increase that value, as any combination of numbers I tried (which all seemed reasonable) had no effect.
> 
> I had the same issue and found the solution.
> Docker memory usage HAS to be configured in 2 places:
> 
> * open "Preferences -> Advanced" in your Docker Desktop and adjust max memory. Mine is 8G
> * add jvm memory arg in pom.xml:
> 
> ```
> <properties>
>     ......
>     <quarkus.native.native-image-xmx>8192m</quarkus.native.native-image-xmx>
>   </properties>
> ```
> 
> In fact the jvm args could be configured in other ways, too.

I can confirm this is the solution = Adjust the memory setting too in your Docker Desktop. I didn't see this suggestion in anywhere for months. Thanks god!
Without that, even you set your xmx  to 10g it just wont work.

As for the jvm xmx, I'm doing it in command as such
`mvn clean install -Pnative -Dnative-image.docker-build=true -Dquarkus.native.native-image-xmx=4g`

**Comment by ewoks** [comment]
I actually faced same issue `Image generation failed. Exit code: 125` and `Unable to get GraalVM version from the native-image binary.` on RHEL 8.3 with podman v2.0.5. Just increasing xmx doesn't help.
There is one more error logged as INFO after GraalVM version issue stating: "Error: requested user's UID 119066 is too large for the rootless user namespace", so I guess this is another flavor of the issue. 

`[ERROR] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Unable to get GraalVM version from the native-image binary.
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] podman run -v /home/<user>/repos/quarkus-getting-started/target/quarkus-getting-started-1.0.0-SNAPSHOT-native-image-source-jar:/project:z --env LANG=C --user 119066:119066 --userns=keep-id --rm registry.access.redhat.com/quarkus/mandrel-20-rhel8 -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=1 -J-Duser.language=en -J-Dfile.encoding=UTF-8 --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -H:+AllowFoldMethods -jar quarkus-getting-started-1.0.0-SNAPSHOT-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http --no-server -H:-UseServiceLoaderFeature -H:+StackTrace quarkus-getting-started-1.0.0-SNAPSHOT-runner
Error: requested user's UID 119066 is too large for the rootless user namespace`

**Comment by ewoks** [comment]
I'm surprised that memory is the real issue here and it got resolved by increasing xmx. Expected error in case of memory limitation would explicitly state:
`Image generation failed. Exit code was 137 which indicates an out of memory error. Consider increasing the Xmx value for native image generation by setting the "quarkus.native.native-image-xmx" property`
but original issue description states `Exit code: 125` which implied different problem.

**Comment by mutasemhidmi** [comment]
I increased the memory but it's still not working, and building gets stuck 
this is the command I am using ./mvnw package -Pnative -Dquarkus.native.container-build=true -Dquarkus.native.native-image-xmx=16g

**Comment by rachidbm** [comment]
@mutasemhidmi make sure to follow [the instructions from BigFatDog](https://github.com/quarkusio/quarkus/issues/8386#issuecomment-753322720) a few comments above...

I had the same issue, but my Docker Desaktop only had 2gb configured. When I changed its preferences to 8gb I could successfully build the native image with: 

```
./gradlew build -Dquarkus.package.type=native -Dquarkus.native.container-build=true -Dquarkus.native.native-image-xmx=8g
```

**Comment by mutasemhidmi** [comment]
@rachidbm I did that already. Please note thwt I have a MacBook m1 pro so I think this is the problem because the type of the quarkus image that is being used is amd64 and not arm64

**Comment by rachidbm** [comment]
I see @mutasemhidmi. I thought I read in some other Github issue that ARM is not supported. That you have to build your native Quarkus image yourself as well in that case. I can't find back where I read this, but this helps your search...

**Comment by mutasemhidmi** [comment]
@rachidbm yes I will build it myself

**Comment by tarasmurzenkovv** [comment]
Another possible issue would be that the Docker or Docker daemon is not running

**Comment by geoand** [comment]
Closing as this is almost certainly not a Quarkus specific issue
