### ISSUE TITLE
Rest Client does not propagate errors correctly in Async mode (Uni, RxJava)

### ISSUE THREAD

**Issue by csotiriou** [quarkusio/quarkus#8543]
**Describe the bug**
It seems that when using the asynchronous REST Client operators (~~either CompletionStage,~~ rxJava 2.x operators, or the Mutiny operators), when the REST client encounters an error like 404, it is not able to call any exception mappers correctly, thus making it impossible to handle any HTTP errors from the rest client.

This was reported before, and either the fix applied was not working correctly, or there is a regression.

**To Reproduce**
1. Open and run the attached project
2. Call http://localhost:8080/country/sync
3. The 404 error is propagated to the result.
4. Now call http://localhost:8080/country/async
5. Note that the error is a generic 500. The logs mention "Handled Internally". There is no way to figure our what went wrong in the async mode.

** Expected Outcome **
The async REST call should properly propagate the 404 error, just like the synchronous call does.

**Environment (please complete the following information):**
Quarkus 1.3.2.Final, OS X 10.15, Java 11 OpenJDK.

**Additional context**
(Add any other context about the problem here.)
Previously reported in https://github.com/quarkusio/quarkus/issues/3655  - the issue seems to be closed after a fix was applied, but the issue persists.

[error.zip](https://github.com/quarkusio/quarkus/files/4466579/error.zip)

**Comment by FroMage** [comment]
This is slightly different, because it actually works with `CompletionStage`, but not with `Uni`.

**Comment by FroMage** [comment]
So yeah, this was fixed in `AsyncInterceptorRxInvoker` which extends `CompletionStageRxInvokerImpl` and is installed by `AsyncInterceptorRxInvokerProvider`.

Now, we have a `UniInvokerProvider` which returns a `UniRxInvokerImpl` based off the `CompletionStageRxInvoker` which it gets from the `ClientInvocationBuilder`, which is not the right subtype, so it also doesn't apply interceptors. I believe this is wrong.

This appears to be a bug split between Mutiny (@cescoffier), RESTEasy client (@asoldano) and MP REST client (@kenfinnigan).

**Comment by FroMage** [comment]
Probably `MpClientInvocationBuilder` needs to override:

```java
   @Override
   public CompletionStageRxInvoker rx()
   {
      return new CompletionStageRxInvokerImpl(this, invocation.getClient().asyncInvocationExecutor());
   }
```

To return its own `AsyncInterceptorRxInvoker` type instead, which is what `rx(CompletionStage.class)` would have returned.

**Comment by kenfinnigan** [comment]
@phillip-kruger FYI

**Comment by csotiriou** [comment]
@FroMage you are right, my bad. `CompletionStage` works fine, but it seems that RxJava and Mutiny operators don't. I changed the title and made the necessary edits.

**Comment by phillip-kruger** [comment]
Created https://issues.redhat.com/browse/RESTEASY-2558

**Comment by phillip-kruger** [comment]
From https://issues.redhat.com/browse/RESTEASY-2558:

Quarkus needs to provide a CompletionCallback to AbstractAsynchronousResponse
so it has something to hand the exception to. See lines 166-169 in
AbstractAsynchronousResponse.completionCallbacks

Looks like your addition needs to be made after line 105 in
io.quarkus.resteasy.runtime.standalone.VertxRequestHandler

`vertxRequest.getAsyncContext().getAsyncResponse().register(CompletionCallback)`

The line number (105) refer to v 1.3.2 and not current master. This is in RESTEasy extension.

**Comment by FroMage** [comment]
Uh… was my fix not sufficient, then?

**Comment by FroMage** [comment]
I'll comment on the issue.

**Comment by phillip-kruger** [comment]
@FroMage Not sure about your fix, but I can still create the issue using the error.zip attached above and master (SNAPSHOT-999)

**Comment by shireenmagdy** [comment]
Is there any updates on this issue?
@csotiriou

**Comment by csotiriou** [comment]
@shireenmagdy The issue still persists in Quarkus 1.8.3. We decided to put a ClientRequestFilter to catch the error and propagate it gracefully ourselves, until this is fixed.

**Comment by guilhermeogliari** [comment]
Any solution for this issue?
I have this problem in version 1.12.1.FINAL
@csotiriou

**Comment by cescoffier** [comment]
@FroMage @michalszynkiewicz do you know if has been fixed?

**Comment by FroMage** [comment]
Well it was supposed to have been fixed ages ago…

**Comment by csotiriou** [comment]
@guilhermeogliari @FroMage This is still not fixed. 

What we have resorted to doing is to putting a REST client filter that catches all errors and rethrows a runtime exception of our making. @dusik66 's method also works fine.

**Comment by michalszynkiewicz** [comment]
Looking at the fix versions in https://issues.redhat.com/browse/RESTEASY-2558 it didn't make it into 4.5.x branch, and Quarkus is still on 4.5.9

**Comment by michalszynkiewicz** [comment]
Or am I missing something?

**Comment by FroMage** [comment]
Oh, I had missed that detail. How come we never updated? Any reason or just we forgot?

**Comment by spbolton** [comment]
I got stuck on this recently and traced through to the issue.   I did create a workaround by overriding the UniProvider and set the correct AsyncInterceptorRxInvoker.  Looks like the fix may be now backported to 4.5.10 . 

```
@Provider
@Priority(1)
public class FixupUniInvokerProvider implements RxInvokerProvider<UniRxInvoker> {

  @Override
  public boolean isProviderFor(Class<?> clazz) {
    return UniRxInvoker.class.equals(clazz);
  }

  @Override
  public UniRxInvoker getRxInvoker(SyncInvoker syncInvoker, ExecutorService executorService) {
    if (syncInvoker instanceof ClientInvocationBuilder) {
      return new UniRxInvokerImpl(new AsyncInterceptorRxInvoker(syncInvoker, executorService));
    } else {
      throw new ProcessingException("Expected a ClientInvocationBuilder");
    }
  }
}

```

**Comment by FroMage** [comment]
Thanks. Given that there's a workaround, and it should be fixed in Quarkus 2.0, I'm going to close this issue. Please reopen it if you can't make the workaround work, and you absolutely must need it in Quarkus 1.13.x.
