### ISSUE TITLE
[CI] - Kogito extension + Quarkus master

### ISSUE THREAD

**Issue by mariofusco** [quarkusio/quarkus#8694]
This issue will be open and closed dependent on the state of https://github.com/kiegroup/kogito-runtimes building against Quarkus master snapshot.

If you have interest in being notified of this subscribe to the issue.

**Comment by mariofusco** [comment]
Build fixed:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/86399026

**Comment by mariofusco** [comment]
Unfortunately, the build failed:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/94935385

**Comment by mariofusco** [comment]
Build fixed:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/95840973

**Comment by mariofusco** [comment]
Unfortunately, the build failed:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/102155243

**Comment by geoand** [comment]
@mariofusco the break was a problem on our side. #9231 should take care of the problem

**Comment by mariofusco** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/103225007

**Comment by geoand** [comment]
@mariofusco I am seeing this:

```
2020-05-13T05:18:49.9015607Z [ERROR] [ERROR] Some problems were encountered while processing the POMs:
2020-05-13T05:18:49.9018861Z [ERROR] 'dependencies.dependency.version' for org.testcontainers:junit-jupiter:jar is missing. @ line 98, column 17
```

We recently removed `org.testcontainers:junit-jupiter` from our BOM, so I think you need to add it to yours

**Comment by mariofusco** [comment]
@geoand PR sent to kogito https://github.com/kiegroup/kogito-runtimes/pull/505 thanks for having reported this.

**Comment by mariofusco** [comment]
Build fixed:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/104293569

**Comment by mariofusco** [comment]
Unfortunately, the build failed:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/108905143

**Comment by mariofusco** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/114407264

**Comment by geoand** [comment]
Seems like there was a connection timeout during dependency download.

@mariofusco would you perhaps consider doing something like https://github.com/quarkusio/quarkus-platform/pull/69 in order to avoid such failures in the future?

**Comment by mariofusco** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/115369763

**Comment by geoand** [comment]
@mariofusco can you take a look at my comment above? The build seems to have failed again due to dependency transfer issues

**Comment by mariofusco** [comment]
@geoand I can add those maven timeouts as you suggested but I'm afraid the problem is not (only) there. Now I tried to build locally our extension against latest quarkus master and I have a few tests failing. I'll investigate the problem and keep you updated.

**Comment by geoand** [comment]
Thanks @mariofusco

**Comment by mariofusco** [comment]
@geoand this pull request should fix both problems https://github.com/kiegroup/kogito-runtimes/pull/531 I'll keep you updated. Thanks for having reported it.

**Comment by geoand** [comment]
Coolio!

**Comment by mariofusco** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/116463552

**Comment by mariofusco** [comment]
@geoand I merged that PR https://github.com/kiegroup/kogito-runtimes/commit/bbb83a58a8926bedd2c4f2366034f1de6b8abf4d Can you relaunch CI to check that everything is ok?

**Comment by geoand** [comment]
@mariofusco job restarted :)

**Comment by mariofusco** [comment]
Build fixed:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/116581947

**Comment by geoand** [comment]
Thanks for addressing the issue @mariofusco!

**Comment by mariofusco** [comment]
Unfortunately, the build failed:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/125594721

**Comment by geoand** [comment]
@mariofusco @evacchi something failed, but I can't really tell what. Can you have a look please?

Thanks

**Comment by mariofusco** [comment]
@geoand I gave a look at the log, but didn't find anything helpful. I think it's a CI failure, but really have no clue. For now I relaunched it and will keep an eye on it.

**Comment by geoand** [comment]
OK, cool

**Comment by mariofusco** [comment]
@geoand @evacchi it is confirmed it was a CI failure, I reran it and now it's green.

**Comment by geoand** [comment]
Great to know, thanks!

**Comment by mariofusco** [comment]
Build fixed:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/128200788

**Comment by mariofusco** [comment]
Unfortunately, the build failed:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/148281869

**Comment by mariofusco** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/151097271

**Comment by geoand** [comment]
@mariofusco @evacchi it seems like the `kogito-quarkus-integration-test` is failing

**Comment by mariofusco** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/152313827

**Comment by mariofusco** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/153641548

**Comment by mariofusco** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/154932775

**Comment by geoand** [comment]
@mariofusco @evacchi the build is still failing, can you please take a look?

**Comment by mariofusco** [comment]
@geoand I ran our hot reload tests against latest quarkus snapshot and they all fail with the following message. Any hint on what could be going wrong?

```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.006 s <<< FAILURE! - in io.quarkus.it.kogito.drools.HotReloadTest
[ERROR] io.quarkus.it.kogito.drools.HotReloadTest  Time elapsed: 0.004 s  <<< ERROR!
java.lang.ExceptionInInitializerError
        at io.quarkus.it.kogito.drools.HotReloadTest.<clinit>(HotReloadTest.java:39)
Caused by: java.lang.ClassCastException: class java.util.logging.LogManager$RootLogger cannot be cast to class org.jboss.logmanager.Logger (java.util.logging.LogManager$RootLogger is in module java.logging of loader 'bootstrap'; org.jboss.logmanager.Logger is in unnamed module of loader 'app')
        at io.quarkus.it.kogito.drools.HotReloadTest.<clinit>(HotReloadTest.java:39)
```

**Comment by geoand** [comment]
I don't, but I'm about to look into it

**Comment by mariofusco** [comment]
@geoand I'm pretty sure that the problem has been caused by this https://github.com/quarkusio/quarkus/commit/7a64dcd4d36afc8d59a0c4fe75a68152eddfdca8#

Do you agree? Should we import some specific logging impl?

**Comment by geoand** [comment]
@mariofusco here you go: https://github.com/kiegroup/kogito-runtimes/pull/600

**Comment by geoand** [comment]
> @geoand I'm pretty sure that the problem has been caused by this [7a64dcd](https://github.com/quarkusio/quarkus/commit/7a64dcd4d36afc8d59a0c4fe75a68152eddfdca8)
> 
> Do you agree? Should we import some specific logging impl?

Yes, exactly

**Comment by mariofusco** [comment]
> @mariofusco here you go: [kiegroup/kogito-runtimes#600](https://github.com/kiegroup/kogito-runtimes/pull/600)

yep, I confirm this fixed the problem, thanks a lot :)

**Comment by geoand** [comment]
You are welcome! And sorry we broke things on your side :(

**Comment by evacchi** [comment]
it would be helpful if it were possible to throw a self-explanatory message in case of bad config like: "You appear to have mis-configured your logger: please read https://quarkus.io/guides/logging#how-to-configure-logging-for-quarkustest". Thanks for helping @geoand !

**Comment by geoand** [comment]
@evacchi Yeah, that would indeed be useful!

**Comment by mariofusco** [comment]
Build fixed:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/156187511

**Comment by mariofusco** [comment]
Unfortunately, the build failed:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/158887548

**Comment by mariofusco** [comment]
Build fixed:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/160185036

**Comment by mariofusco** [comment]
Unfortunately, the build failed:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/189548156

**Comment by geoand** [comment]
@karesti @wburns @mariofusco @evacchi there seems to be some problem in the Kogito - Infinispan integration.

```
2020-07-31T05:30:11.7455489Z [ERROR] Failed to execute goal on project infinispan-persistence-addon: Could not resolve dependencies for project org.kie.kogito:infinispan-persistence-addon:jar:8.0.0-SNAPSHOT: The following artifacts could not be resolved: org.infinispan:infinispan-directory-provider:jar:11.0.1.Final, org.infinispan:infinispan-lucene-directory:jar:11.0.1.Final: Could not find artifact org.infinispan:infinispan-directory-provider:jar:11.0.1.Final in jboss-public-repository-group (https://repository.jboss.org/nexus/content/groups/public/) -> [Help 1]
```

Can you take a look please?

cc @gsmet

**Comment by gsmet** [comment]
AFAICS, the artifact is gone in 11.0.1.Final: https://search.maven.org/artifact/org.infinispan/infinispan-directory-provider

No idea if it's normal or not.

**Comment by mariofusco** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/192830412

**Comment by mariofusco** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/194281089

**Comment by mariofusco** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/195747629

**Comment by mariofusco** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/198706631

**Comment by mariofusco** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/202014158

**Comment by mariofusco** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/203523425

**Comment by mariofusco** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/205045718

**Comment by mariofusco** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/206568770

**Comment by evacchi** [comment]
```
2020-08-13T05:43:22.1479051Z [INFO] Kogito :: Quarkus Extension :: Integration Tests (Legacy API) FAILURE [04:07 min]
```

I propose we disable those tests for now @mariofusco

**Comment by mariofusco** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/208093288

**Comment by mariofusco** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/211532530

**Comment by mariofusco** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/213089418

**Comment by mariofusco** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/214673467

**Comment by mariofusco** [comment]
Fixed on Drools by https://github.com/kiegroup/drools/commit/c401f20b7ec3bea2b9860d00d8f02db60f4a0850

I'm keeping the ticket opened since We will need to bump into Kogito a version of Drools containing this commit to fix the lagacy API test.

**Comment by mariofusco** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/216255301

**Comment by mariofusco** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/217865400

**Comment by mariofusco** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/221480253

**Comment by mariofusco** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/223121733

**Comment by geoand** [comment]
@mariofusco @evacchi this is failing with:

```
2020-08-25T05:23:51.4956945Z [ERROR] [ERROR] Some problems were encountered while processing the POMs:
2020-08-25T05:23:51.4990189Z [FATAL] Non-resolvable parent POM for org.kie.kogito:kogito-runtimes-jenkins-tests:1.0.0-SNAPSHOT: Could not transfer artifact org.kie.kogito:kogito-build-parent:pom:1.0.0-SNAPSHOT from/to jenkins-releases (https://repo.jenkins-ci.org/releases): Transfer failed for https://repo.jenkins-ci.org/releases/org/kie/kogito/kogito-build-parent/1.0.0-SNAPSHOT/kogito-build-parent-1.0.0-SNAPSHOT.pom 409 Conflict and 'parent.relativePath' points at wrong local POM @ line 5, column 13
```

**Comment by mariofusco** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/224792007

**Comment by mariofusco** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/226466755

**Comment by mariofusco** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/228139688

**Comment by mariofusco** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/232074163

**Comment by geoand** [comment]
@mariofusco @evacchi there seems to be a legit CI failure:

```
20-08-31T05:33:04.9326262Z [INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] docker run -v /home/runner/work/kogito-runtimes/kogito-runtimes/current-repo/kogito-quarkus-extension/integration-test/target/kogito-quarkus-integration-test-1.0.0-SNAPSHOT-native-image-source-jar:/project:z --env LANG=C --user 1001:116 --rm quay.io/quarkus/ubi-quarkus-native-image:20.2.0-java11 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=1 -J-Duser.language=en -J-Dfile.encoding=UTF-8 --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -jar kogito-quarkus-integration-test-1.0.0-SNAPSHOT-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http --no-server -H:-UseServiceLoaderFeature -H:+StackTrace kogito-quarkus-integration-test-1.0.0-SNAPSHOT-runner
2020-08-31T05:33:23.6465138Z [kogito-quarkus-integration-test-1.0.0-SNAPSHOT-runner:24]    classlist:  17,529.36 ms,  1.69 GB
2020-08-31T05:33:25.5814302Z [kogito-quarkus-integration-test-1.0.0-SNAPSHOT-runner:24]        (cap):   1,020.11 ms,  1.69 GB
2020-08-31T05:33:27.1399608Z [kogito-quarkus-integration-test-1.0.0-SNAPSHOT-runner:24]        setup:   3,479.26 ms,  1.69 GB
2020-08-31T05:34:05.1969484Z 05:34:05,195 INFO  [org.jbo.threads] JBoss Threads version 3.1.1.Final
2020-08-31T05:35:03.8081487Z [kogito-quarkus-integration-test-1.0.0-SNAPSHOT-runner:24]     (clinit):     787.05 ms,  2.83 GB
2020-08-31T05:35:04.1545466Z [kogito-quarkus-integration-test-1.0.0-SNAPSHOT-runner:24]   (typeflow):  49,291.14 ms,  2.83 GB
2020-08-31T05:35:04.1546576Z [kogito-quarkus-integration-test-1.0.0-SNAPSHOT-runner:24]    (objects):  43,402.65 ms,  2.83 GB
2020-08-31T05:35:04.1547286Z [kogito-quarkus-integration-test-1.0.0-SNAPSHOT-runner:24]   (features):   1,232.35 ms,  2.83 GB
2020-08-31T05:35:04.3830088Z [kogito-quarkus-integration-test-1.0.0-SNAPSHOT-runner:24]     analysis:  96,970.48 ms,  2.83 GB
2020-08-31T05:35:04.3869575Z Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.ClassLoader.defineClass1(ClassLoader, String, byte[], int, int, ProtectionDomain, String) is reachable
2020-08-31T05:35:04.3870390Z To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
2020-08-31T05:35:04.3870564Z Detailed message:
2020-08-31T05:35:04.3870685Z Trace: 
2020-08-31T05:35:04.3870830Z 	at parsing java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
2020-08-31T05:35:04.3870995Z Call path from entry point to java.lang.ClassLoader.defineClass(String, byte[], int, int, ProtectionDomain): 
2020-08-31T05:35:04.3871157Z 	at java.lang.ClassLoader.defineClass(ClassLoader.java:1015)
2020-08-31T05:35:04.3871302Z 	at java.lang.ClassLoader.defineClass(ClassLoader.java:878)
2020-08-31T05:35:04.3871464Z 	at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer$ContextClassLoader.defineClass(ASMAccessorOptimizer.java:2256)
2020-08-31T05:35:04.3871629Z 	at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer.loadClass(ASMAccessorOptimizer.java:2265)
2020-08-31T05:35:04.3880495Z 	at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer._initializeAccessor(ASMAccessorOptimizer.java:752)
2020-08-31T05:35:04.3880782Z 	at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer.optimizeCollection(ASMAccessorOptimizer.java:3060)
2020-08-31T05:35:04.3881081Z 	at org.mvel2.ast.InlineCollectionNode.<init>(InlineCollectionNode.java:70)
2020-08-31T05:35:04.3887092Z 	at org.mvel2.compiler.AbstractParser.nextToken(AbstractParser.java:402)
2020-08-31T05:35:04.3887274Z 	at org.mvel2.MVELInterpretedRuntime.parseAndExecuteInterpreted(MVELInterpretedRuntime.java:92)
2020-08-31T05:35:04.3887451Z 	at org.mvel2.MVELInterpretedRuntime.parse(MVELInterpretedRuntime.java:58)
2020-08-31T05:35:04.3887605Z 	at org.mvel2.MVEL.eval(MVEL.java:136)
2020-08-31T05:35:04.3887766Z 	at org.kie.soup.project.datamodel.commons.util.RawMVELEvaluator.eval(RawMVELEvaluator.java:38)
2020-08-31T05:35:04.3888117Z 	at org.jbpm.workflow.instance.impl.WorkflowProcessInstanceImpl.resolveVariable(WorkflowProcessInstanceImpl.java:687)
2020-08-31T05:35:04.3888305Z 	at org.jbpm.workflow.instance.impl.WorkflowProcessInstanceImpl.resolveVariable(WorkflowProcessInstanceImpl.java:672)
2020-08-31T05:35:04.3888482Z 	at org.jbpm.workflow.instance.impl.WorkflowProcessInstanceImpl$$Lambda$912/0x00000007c2963840.apply(Unknown Source)
2020-08-31T05:35:04.3888798Z 	at sun.security.ec.XECParameters$1.get(XECParameters.java:183)
2020-08-31T05:35:04.3888965Z 	at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:190)
2020-08-31T05:35:04.3889143Z 	at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:143)
2020-08-31T05:35:04.3889314Z 	at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:331)
2020-08-31T05:35:04.3889506Z 	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)
```

**Comment by evacchi** [comment]
@mariofusco related to latest ASM-related / MVEL / unfork changes?

**Comment by mariofusco** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/233769885

**Comment by mariofusco** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/235494319

**Comment by geoand** [comment]
@evacchi once you have a fix for Kogito and the artifacts are released, please also update the Quarkus platform as well.

Thanks!

**Comment by evacchi** [comment]
@geoand yup!

**Comment by mariofusco** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/237204441

**Comment by geoand** [comment]
@evacchi we have new error:

```
2020-09-03T05:48:45.6280902Z [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.182 s <<< FAILURE! - in org.kie.kogito.integrationtests.quarkus.NativeJavaFNctxIT
2020-09-03T05:48:45.6282571Z [ERROR] org.kie.kogito.integrationtests.quarkus.NativeJavaFNctxIT  Time elapsed: 0.181 s  <<< ERROR!
2020-09-03T05:48:45.6283990Z java.lang.RuntimeException: Unable to instantiate the test resource org.kie.kogito.testcontainers.quarkus.InfinispanQuarkusTestResource$Conditional
2020-09-03T05:48:45.6287653Z Caused by: java.lang.reflect.InvocationTargetException
2020-09-03T05:48:45.6288177Z Caused by: java.lang.NullPointerException: dockerImageName is marked non-null but is null
```

**Comment by evacchi** [comment]
@geoand probably some quay.io/dockerhub timeout/limit ? cc @cristianonicolai

**Comment by mariofusco** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/238894233

**Comment by gsmet** [comment]
@evacchi @mariofusco still the same issue:
```
2020-09-04T05:49:27.6897441Z [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.183 s <<< FAILURE! - in org.kie.kogito.integrationtests.quarkus.NativeJavaFNctxIT
2020-09-04T05:49:27.6901332Z [ERROR] org.kie.kogito.integrationtests.quarkus.NativeJavaFNctxIT  Time elapsed: 0.183 s  <<< ERROR!
2020-09-04T05:49:27.6905056Z java.lang.RuntimeException: Unable to instantiate the test resource org.kie.kogito.testcontainers.quarkus.InfinispanQuarkusTestResource$Conditional
2020-09-04T05:49:27.6907063Z Caused by: java.lang.reflect.InvocationTargetException
2020-09-04T05:49:27.6910098Z Caused by: java.lang.NullPointerException: dockerImageName is marked non-null but is null
```

I don't think it's a timeout. Maybe the image you used has been removed or something similar?

**Comment by evacchi** [comment]
@gsmet I think it's more about this:
https://github.com/kiegroup/kogito-runtimes/blob/2dcdb8e8b99a7ee0247c4c9cb0a7064d36e3f817/kogito-test-utils/src/main/java/org/kie/kogito/testcontainers/quarkus/InfinispanQuarkusTestResource.java

not working in native mode for some reason -- the JVM version has run (few lines above) otherwise the native image would be skipped.

**Comment by gsmet** [comment]
The test resource is not supposed to be executed in native but around the native execution.

**Comment by mariofusco** [comment]
Build fixed:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/242462655

**Comment by mariofusco** [comment]
Unfortunately, the build failed:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/253226605

**Comment by geoand** [comment]
@evacchi @mariofusco seems like there is some GraalVM related issue:

```
2020-09-14T05:52:49.5511999Z Error: Detected a ZipFile object in the image heap. A ZipFile object contains pointers to unmanaged C memory and file descriptors, and these resources are no longer available at image run time.  To see how this object got instantiated use -H:+TraceClassInitialization. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image run time by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
2020-09-14T05:52:49.5518251Z Trace: Object was reached by 
2020-09-14T05:52:49.5521323Z 	reading field java.util.zip.ZipFile$ZipFileInflaterInputStream.this$0 of
2020-09-14T05:52:49.5569467Z 		constant java.util.zip.ZipFile$ZipFileInflaterInputStream@2a71e794 reached by 
2020-09-14T05:52:49.5570389Z 	reading field java.io.FilterInputStream.in of
2020-09-14T05:52:49.5572026Z 		constant sun.net.www.protocol.jar.JarURLConnection$JarURLInputStream@7ef04906 reached by 
2020-09-14T05:52:49.5573098Z 	reading field java.io.Reader.lock of
2020-09-14T05:52:49.5573695Z 		constant java.io.InputStreamReader@722ae47d reached by 
2020-09-14T05:52:49.5574658Z 	reading field org.drools.core.io.impl.ReaderResource.reader of
2020-09-14T05:52:49.5575786Z 		constant org.drools.core.io.impl.ReaderResource@7f51969a reached by 
2020-09-14T05:52:49.5576873Z 	reading field org.kie.dmn.core.impl.DMNModelImpl.resource of
2020-09-14T05:52:49.5578007Z 		constant org.kie.dmn.core.impl.DMNModelImpl@603de4ac reached by 
2020-09-14T05:52:49.5578606Z 	indexing into array
2020-09-14T05:52:49.5579254Z 		constant java.lang.Object[]@3922e1dc reached by 
2020-09-14T05:52:49.5580290Z 	reading field java.util.ArrayList.elementData of
2020-09-14T05:52:49.5583268Z 		constant java.util.ArrayList@1b935082 reached by 
2020-09-14T05:52:49.5584037Z 	reading field java.util.Collections$UnmodifiableCollection.c of
2020-09-14T05:52:49.5585008Z 		constant java.util.Collections$UnmodifiableRandomAccessList@122a629f reached by 
2020-09-14T05:52:49.5586418Z 	reading field org.kie.dmn.core.internal.utils.DMNRuntimeBuilder$DMNRuntimeKBStatic.models of
2020-09-14T05:52:49.5588121Z 		constant org.kie.dmn.core.internal.utils.DMNRuntimeBuilder$DMNRuntimeKBStatic@5187cc0d reached by 
2020-09-14T05:52:49.5589577Z 	reading field org.kie.dmn.core.impl.DMNRuntimeImpl.runtimeKB of
2020-09-14T05:52:49.5590693Z 		constant org.kie.dmn.core.impl.DMNRuntimeImpl@2e9f467b reached by 
2020-09-14T05:52:49.5592242Z 	scanning method org.kie.kogito.app.DecisionModels.getDecisionModel(DecisionModels.java:16)
2020-09-14T05:52:49.5593901Z Call path from entry point to org.kie.kogito.app.DecisionModels.getDecisionModel(String, String): 
2020-09-14T05:52:49.5595500Z 	at org.kie.kogito.app.DecisionModels.getDecisionModel(DecisionModels.java:16)
```

**Comment by evacchi** [comment]
so it looks like returning a Resource from a jar holds onto some reference that native-image dislikes. Maybe it is safer to unpack it to disk? @mariofusco

**Comment by evacchi** [comment]
@geoand https://github.com/kiegroup/kogito-runtimes/pull/761

**Comment by mariofusco** [comment]
Build fixed:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/255057288

**Comment by mariofusco** [comment]
Unfortunately, the build failed:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/271829001

**Comment by geoand** [comment]
@evacchi there seems to be an issue with native image now:

```
2020-09-25T05:51:28.1978264Z [INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on GraalVM Version 20.2.0 (Java Version 11.0.8)
2020-09-25T05:51:28.9033568Z [INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] docker run -v /home/runner/work/kogito-runtimes/kogito-runtimes/current-repo/integration-tests/integration-tests-quarkus-rules/target/integration-tests-quarkus-rules-1.0.0-SNAPSHOT-native-image-source-jar:/project:z --env LANG=C --user 1001:116 --rm quay.io/quarkus/ubi-quarkus-native-image:20.2.0-java11 -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=1 -J-Duser.language=en -J-Dfile.encoding=UTF-8 --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -jar integration-tests-quarkus-rules-1.0.0-SNAPSHOT-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http --no-server -H:-UseServiceLoaderFeature -H:+StackTrace integration-tests-quarkus-rules-1.0.0-SNAPSHOT-runner
2020-09-25T05:51:58.3273215Z [integration-tests-quarkus-rules-1.0.0-SNAPSHOT-runner:25]    classlist:  27,823.73 ms,  1.70 GB
2020-09-25T05:52:00.8047066Z [integration-tests-quarkus-rules-1.0.0-SNAPSHOT-runner:25]        (cap):   1,324.25 ms,  1.70 GB
2020-09-25T05:52:02.6700737Z [integration-tests-quarkus-rules-1.0.0-SNAPSHOT-runner:25]        setup:   4,320.00 ms,  1.70 GB
2020-09-25T05:52:42.5876233Z 05:52:42,576 INFO  [org.jbo.threads] JBoss Threads version 3.1.1.Final
2020-09-25T05:53:37.1581212Z [integration-tests-quarkus-rules-1.0.0-SNAPSHOT-runner:25]     (clinit):     726.74 ms,  2.84 GB
2020-09-25T05:53:37.4871534Z [integration-tests-quarkus-rules-1.0.0-SNAPSHOT-runner:25]   (typeflow):  44,895.27 ms,  2.84 GB
2020-09-25T05:53:37.4896457Z [integration-tests-quarkus-rules-1.0.0-SNAPSHOT-runner:25]    (objects):  45,208.32 ms,  2.84 GB
2020-09-25T05:53:37.4928882Z [integration-tests-quarkus-rules-1.0.0-SNAPSHOT-runner:25]   (features):   1,351.58 ms,  2.84 GB
2020-09-25T05:53:37.6408931Z [integration-tests-quarkus-rules-1.0.0-SNAPSHOT-runner:25]     analysis:  94,612.96 ms,  2.84 GB
2020-09-25T05:53:37.6454648Z Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: io.cloudevents.json.Json. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
2020-09-25T05:53:37.6457503Z Detailed message:
2020-09-25T05:53:37.6457873Z Trace: 
2020-09-25T05:53:37.6460129Z 	at parsing io.smallrye.reactive.messaging.http.converters.CloudEventSerializer.convert(CloudEventSerializer.java:13)
2020-09-25T05:53:37.6464700Z Call path from entry point to io.smallrye.reactive.messaging.http.converters.CloudEventSerializer.convert(CloudEventMessage): 
2020-09-25T05:53:37.6469842Z 	at io.smallrye.reactive.messaging.http.converters.CloudEventSerializer.convert(CloudEventSerializer.java:13)
2020-09-25T05:53:37.6473645Z 	at io.smallrye.reactive.messaging.http.converters.CloudEventSerializer.convert(CloudEventSerializer.java:8)
2020-09-25T05:53:37.6476887Z 	at io.smallrye.reactive.messaging.http.HttpSink.send(HttpSink.java:52)
2020-09-25T05:53:37.6489574Z 	at io.smallrye.reactive.messaging.http.HttpSink.lambda$new$2(HttpSink.java:42)
2020-09-25T05:53:37.6506966Z 	at io.smallrye.reactive.messaging.http.HttpSink$$Lambda$1795/0x00000007c33f0c40.apply(Unknown Source)
2020-09-25T05:53:37.6510963Z 	at sun.security.ec.XECParameters$1.get(XECParameters.java:183)
2020-09-25T05:53:37.6516611Z 	at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:190)
2020-09-25T05:53:37.6533334Z 	at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:143)
2020-09-25T05:53:37.6535362Z 	at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:331)
2020-09-25T05:53:37.6538908Z 	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)
2020-09-25T05:53:37.6540438Z 
2020-09-25T05:53:37.6546930Z com.oracle.svm.core.util.UserError$UserException: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: io.cloudevents.json.Json. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
2020-09-25T05:53:37.6550075Z Detailed message:
2020-09-25T05:53:37.6550362Z Trace: 
2020-09-25T05:53:37.6573321Z 	at parsing io.smallrye.reactive.messaging.http.converters.CloudEventSerializer.convert(CloudEventSerializer.java:13)
2020-09-25T05:53:37.6576724Z Call path from entry point to io.smallrye.reactive.messaging.http.converters.CloudEventSerializer.convert(CloudEventMessage): 
2020-09-25T05:53:37.6580076Z 	at io.smallrye.reactive.messaging.http.converters.CloudEventSerializer.convert(CloudEventSerializer.java:13)
2020-09-25T05:53:37.6583743Z 	at io.smallrye.reactive.messaging.http.converters.CloudEventSerializer.convert(CloudEventSerializer.java:8)
2020-09-25T05:53:37.6586180Z 	at io.smallrye.reactive.messaging.http.HttpSink.send(HttpSink.java:52)
2020-09-25T05:53:37.6587782Z 	at io.smallrye.reactive.messaging.http.HttpSink.lambda$new$2(HttpSink.java:42)
2020-09-25T05:53:37.6589671Z 	at io.smallrye.reactive.messaging.http.HttpSink$$Lambda$1795/0x00000007c33f0c40.apply(Unknown Source)
2020-09-25T05:53:37.6592080Z 	at sun.security.ec.XECParameters$1.get(XECParameters.java:183)
2020-09-25T05:53:37.6594760Z 	at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:190)
2020-09-25T05:53:37.6597366Z 	at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:143)
2020-09-25T05:53:37.6599329Z 	at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:331)
2020-09-25T05:53:37.6600934Z 	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)
2020-09-25T05:53:37.6602214Z 
2020-09-25T05:53:37.6602839Z 	at com.oracle.svm.core.util.UserError.abort(UserError.java:79)
2020-09-25T05:53:37.6604938Z 	at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:217)
2020-09-25T05:53:37.6606980Z 	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:765)
2020-09-25T05:53:37.6609108Z 	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:555)
2020-09-25T05:53:37.6610801Z 	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:468)
2020-09-25T05:53:37.6612577Z 	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
2020-09-25T05:53:37.6614112Z 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
2020-09-25T05:53:37.6615432Z 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
2020-09-25T05:53:37.6617202Z 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
2020-09-25T05:53:37.6618740Z 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
2020-09-25T05:53:37.6620384Z 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
2020-09-25T05:53:37.6625567Z Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: io.cloudevents.json.Json. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
2020-09-25T05:53:37.6631513Z Detailed message:
2020-09-25T05:53:37.6632255Z Trace: 
2020-09-25T05:53:37.6633970Z 	at parsing io.smallrye.reactive.messaging.http.converters.CloudEventSerializer.convert(CloudEventSerializer.java:13)
2020-09-25T05:53:37.6640188Z Call path from entry point to io.smallrye.reactive.messaging.http.converters.CloudEventSerializer.convert(CloudEventMessage): 
2020-09-25T05:53:37.6643803Z 	at io.smallrye.reactive.messaging.http.converters.CloudEventSerializer.convert(CloudEventSerializer.java:13)
2020-09-25T05:53:37.6646882Z 	at io.smallrye.reactive.messaging.http.converters.CloudEventSerializer.convert(CloudEventSerializer.java:8)
2020-09-25T05:53:37.6649372Z 	at io.smallrye.reactive.messaging.http.HttpSink.send(HttpSink.java:52)
2020-09-25T05:53:37.6651115Z 	at io.smallrye.reactive.messaging.http.HttpSink.lambda$new$2(HttpSink.java:42)
2020-09-25T05:53:37.6652663Z 	at io.smallrye.reactive.messaging.http.HttpSink$$Lambda$1795/0x00000007c33f0c40.apply(Unknown Source)
2020-09-25T05:53:37.6653832Z 	at sun.security.ec.XECParameters$1.get(XECParameters.java:183)
2020-09-25T05:53:37.6656539Z 	at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:190)
2020-09-25T05:53:37.6660739Z 	at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:143)
2020-09-25T05:53:37.6662662Z 	at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:331)
2020-09-25T05:53:37.6664331Z 	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)
2020-09-25T05:53:37.6665344Z 
2020-09-25T05:53:37.6666926Z 	at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:126)
2020-09-25T05:53:37.6669818Z 	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:762)
2020-09-25T05:53:37.6671209Z 	... 8 more
2020-09-25T05:53:37.6674047Z Caused by: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: io.cloudevents.json.Json. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
2020-09-25T05:53:37.6677736Z 	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.reportUnresolvedElement(SharedGraphBuilderPhase.java:265)
2020-09-25T05:53:37.6680596Z 	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedType(SharedGraphBuilderPhase.java:220)
2020-09-25T05:53:37.6683422Z 	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedMethod(SharedGraphBuilderPhase.java:246)
2020-09-25T05:53:37.6686308Z 	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedInvoke(SharedGraphBuilderPhase.java:209)
2020-09-25T05:53:37.6688864Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1650)
2020-09-25T05:53:37.6691213Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1625)
2020-09-25T05:53:37.6693426Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5340)
2020-09-25T05:53:37.6695861Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3413)
2020-09-25T05:53:37.6699110Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3220)
2020-09-25T05:53:37.6701165Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1090)
2020-09-25T05:53:37.6703347Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:984)
2020-09-25T05:53:37.6705365Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
2020-09-25T05:53:37.6707425Z 	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase.run(SharedGraphBuilderPhase.java:74)
2020-09-25T05:53:37.6709114Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
2020-09-25T05:53:37.6710501Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:214)
2020-09-25T05:53:37.6711935Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
2020-09-25T05:53:37.6713269Z 	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
2020-09-25T05:53:37.6715012Z 	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:223)
2020-09-25T05:53:37.6717179Z 	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:357)
2020-09-25T05:53:37.6719232Z 	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:313)
2020-09-25T05:53:37.6721032Z 	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:302)
2020-09-25T05:53:37.6722910Z 	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:103)
2020-09-25T05:53:37.6725141Z 	at com.oracle.graal.pointsto.DefaultAnalysisPolicy$DefaultVirtualInvokeTypeFlow.onObservedUpdate(DefaultAnalysisPolicy.java:227)
2020-09-25T05:53:37.6727277Z 	at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:470)
2020-09-25T05:53:37.6728731Z 	at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:542)
2020-09-25T05:53:37.6729778Z 	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:552)
2020-09-25T05:53:37.6731284Z 	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
2020-09-25T05:53:37.6733102Z 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
2020-09-25T05:53:37.6733901Z 	... 5 more
```

**Comment by evacchi** [comment]
@ruromero @ricardozanini as I remembered, the new CE SDK has issues with native image. We may need to register something for reflection or remove/rewrite some method using GraalVM's substitutions. Seek help with @mariofusco who knows more details -- basically in the Kogito extension there are already usages of both the techniques (the KogtioAssetProcessor class in the `deployment` module registers stuff for reflection and the `runtime` module contains substitutions)

**Comment by ruromero** [comment]
@evacchi the projects that really need to marshall/unmarshall CloudEvents (i.e. depend on cloudevents java-sdk, 2.0.0-milestone2)  require to have the CloudEventsProvider registered. This won't happen in milestone3 as per https://github.com/cloudevents/sdk-java/pull/233
In this case, the cloudevents-api was indirectly added by the quarkus-smallrye-reactive-messaging-kafka and smallrye-reactive-messaging-http dependencies. I don't think they're really needed in the project as I have removed them and the build passes.
I have created this PR to remove them: https://github.com/kiegroup/kogito-runtimes/pull/786

**Comment by mariofusco** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/276018215

**Comment by ruromero** [comment]
@mariofusco but the PR has not yet been merged

**Comment by ruromero** [comment]
@mariofusco it is now merged, would the CI build start automatically?

**Comment by geoand** [comment]
I'll restart it

**Comment by geoand** [comment]
Actually I can't restart it since I don't have right in your repo. Please go to: https://github.com/kiegroup/kogito-runtimes/actions/runs/276018215 and perform the restart

**Comment by ricardozanini** [comment]
I tried to run it, but it seems that it was skipped. @mariofusco any clues?

**Comment by geoand** [comment]
Ah right, I remember why. It need to be triggered by the ecosystem-ci run. I'll do that

**Comment by mariofusco** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/276553135

**Comment by cristianonicolai** [comment]
Please retrigger the build, it should be fixed by https://github.com/kiegroup/kogito-runtimes/pull/790

**Comment by mariofusco** [comment]
The build is still failing:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/277909283

**Comment by cristianonicolai** [comment]
Seems it needs https://github.com/kiegroup/kogito-runtimes/pull/792 to be in

**Comment by cristianonicolai** [comment]
Fix merged.

**Comment by ruromero** [comment]
Please retrigger the build, PR https://github.com/kiegroup/kogito-runtimes/pull/792 is merged

**Comment by geoand** [comment]
Done

**Comment by mariofusco** [comment]
Build fixed:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/278797970

**Comment by mariofusco** [comment]
Unfortunately, the build failed:
* Link to latest CI run: https://github.com/kiegroup/kogito-runtimes/actions/runs/288748525

**Comment by geoand** [comment]
Superceded by https://github.com/quarkusio/quarkus/issues/12486
