### ISSUE TITLE
Quarkus should be able to run tests in different folders than the "preset" ones

### ISSUE THREAD

**Issue by oscarfh** [quarkusio/quarkus#8950]
**Description**
This issue comes from: [here](https://stackoverflow.com/questions/61299474/how-do-i-configure-quarkus-to-run-tests-in-folders-other-than-test-and-native-te)
I want to separate my unit tests from my integration tests for multiple reasons. To do that, I can add a set sourceSet (in gradle) or similar in maven, but when running the tests, I get this message:

> Caused by: java.lang.RuntimeException: The test class class YourTest is not located in any of the directories [classes/scala/native-test, classes/java/test, classes/scala/test, classes/java/native-test, /test-classes, bin/test, classes/kotlin/test, classes/kotlin/native-test]

It should be possible to run tests outside these folder.

**Implementation ideas**
I don't have any. But if you provide me some guidance, I would love to create the PR for that.

**Comment by oscarfh** [comment]
I was thinking about replacing the logic  in `io.quarkus.test.common.PathTestHelper#isTestClass` with a logic that looks for `QuarkusTest` annotation or similar.
If I cannot replace it, maybe adding it as an `OR` conditional? Either it is in the given folder or it is annotated with `QuarkusTest`? Let me know what you think, I would love to contribute that.

**Comment by debae** [comment]
Looks like this is a duplicate of https://github.com/quarkusio/quarkus/issues/8737

**Comment by oscarfh** [comment]
@debae Hi, no, because I run it using gradle, not Intellij.
#8737 is a known problem when running the test using intellij. While my ticket is about accepting that tests might be in other paths than the ones hardcoded in `io.quarkus.test.common.PathTestHelper`

**Comment by ebramirez** [comment]
I get the same error and I'm not using IntelliJ, so it looks like the same problem.

**Comment by oscarfh** [comment]
[This line](https://github.com/quarkusio/quarkus/blob/f772aa1de07c067b44b4a52cbac3a1ab1a252515/test-framework/common/src/main/java/io/quarkus/test/common/PathTestHelper.java#L73) explicitly fails if the class is not in the hardcoded folders.

**Comment by aloubyansky** [comment]
Should be fixed with https://github.com/quarkusio/quarkus/pull/10459

**Comment by augustobmoura** [comment]
I don't think it's fixed, the code is still checking for the "correct" directory, why I can't put my tests in a arbitrary dir is beyond me

The check at https://github.com/quarkusio/quarkus/blob/c5da033c2029b21b95804f9fc962b737df3d0e91/test-framework/common/src/main/java/io/quarkus/test/common/PathTestHelper.java#L77 doesn't make any sense

I want to be able to just put my tests in any directory that I want, be it `integrationTests` or `integrationTestsForModuleFooThatShouldPass110PercentAtMay`

**Comment by Alexander-Krause-Glau** [comment]
This is closed, but there is still no solution to that right? I know there is the `@QuarkusIntegrationTest` annotation, but I don't want to integration test only via network. I have custom integration tests that use the `@QuarkusTest` annotation and Testcontainer and require Injection.

**Comment by aloubyansky** [comment]
@Alexander-Krause-Glau could you describe your issue in more detail? Is it a Gradle project? Do you have a little reproducer or instructions to create one? Thanks.

**Comment by Alexander-Krause-Glau** [comment]
Thanks for the reply. I think we are talking about narrow integration tests. Have a look at https://github.com/ExplorViz/landscape-service/blob/master/src/integrationTest/java/net/explorviz/landscape/peristence/cassandra/ReactiveSpanStructureRepositoryTest.java 

This is a Gradle Project and in Eclipse when I run this test as JUnit test I get 

`
java.lang.RuntimeException: The test class net.explorviz.landscape.peristence.cassandra.ReactiveSpanStructureRepositoryTest is not located in any of the directories classes/scala/native-integration-test, classes/scala/test, classes/scala/native-integrationTest, /test-classes, out/test, classes/kotlin/test, classes/java/native-integrationTest, classes/kotlin/native-integrationTest, classes/scala/integrationTest, classes/java/integration-test, classes/java/integrationTest, classes/kotlin/native-integration-test, classes/scala/native-test, quarkus-app-classes-test, classes/kotlin/integration-test, classes/java/test, classes/java/native-test, bin/test, classes/java/native-integration-test, classes/kotlin/integrationTest, classes/kotlin/native-test, classes/scala/integration-test
`

Depite currently failing tests, you can still use the custom Gradle Task `integrationTest` to execute them.

**Comment by Alexander-Krause-Glau** [comment]
> @Alexander-Krause-Glau could you enable debug and see if you get a line starting with `test dir mapping -` logged?

Here is the output from the Gradle Task. The `Eclipse -> Right Click -> Run as JUnit Test` approach (obviously) shows the same behavior as mentioned above:

```
> Task :integrationTest
test dir mapping - build/classes/java/integrationTest:build/classes/java/main
```

Btw. I get the same log output if I use `quarkus.log.level=INFO` or even  `quarkus.log.level=ERROR`.

**Comment by aloubyansky** [comment]
Thanks. Yes, I see it changed to debug only in 2.15.0.CR1.

**Comment by Alexander-Krause-Glau** [comment]
@aloubyansky Import as Gradle Project in Eclipse, not as Eclipse Project. Dunno if you already did.

**Comment by aloubyansky** [comment]
Yes, that's what I did. Are you on zulip @Alexander-Krause-Glau?

**Comment by aloubyansky** [comment]
@Alexander-Krause-Glau https://github.com/quarkusio/quarkus/pull/29808 should fix it for you.
